### ISSUE TITLE
labelmargin() in Fl_Widgets.

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1039]
**Is your feature request related to a problem? Please describe.**
Currently, when images are displayed next to label, they are placed, particularly on Linux, right next, at the border of the image.  

**I am using FLTK**
 - 1.4.

**Describe the solution you'd like**
It would be good if a labelmargin() function was added to Fl_Widget to control the margins of the labels/images.

**Describe alternatives you've considered**
Subclassing the widget and trying to draw images and labels as I want, but the fl_draw functions are way too convoluted and quite undocumented.
Adding spaces in my labels in my subclassed widget (currently my solution).

**Comment by MatthiasWM** [comment]
Would that need to be per widget or is a global variable enough? Yes, the source code of label drawing has grown and evolved over time for every new feature we needed ;-)

**Comment by ggarra13** [comment]
Ideally per widget, of course.

**Comment by erco77** [comment]
Regarding the "particularly linux" -- image placement behavior should really be /consistent/ across all platforms -- do you find it is not? If there's a variance somehow, that should be investigated, as it'd be a pain if there's differences across platforms.

Regarding the feature itself: adding top/bot/lt/rt margins would enlarge the size of Fl_Widget by 4 64bit ints. In FLTK there's a strong goal to keep the size of Fl_Widget _as small as possible_; just adding a single int can greatly enlarge the memory footprint of apps that use 100k or more instances of widgets.

If seriously considered for adding, maybe use 4 chars for the top/bot/lt/rt instead of 4 ints; +/-127 should be enough for margins; anything larger should probably be done with the below technique.

When I want margins (for things like icons), building margins into the image seems perfectly workable; a transparent alpha channel for the borders works well in XPMs, PNGs, and probably SVGs. Better than messing with the low level Fl_Widget's size.

**Comment by ggarra13** [comment]
@MatthiasWM Thank you Matthias in advance.

**Comment by erco77** [comment]
> ends in a byte variable/alignment/32bit

I'm not sure about that; unless there's a variable that follows the byte that needs to be paragraph aligned, I don't think the compiler needs to pad the struct/class. Consider:

```
$ cat foo.cxx
#include <stdio.h>
class Foo { char c; };

int main() {
  Foo foo;
  printf("sizeof(foo): %ld\n", sizeof(foo));
  return 0;
}

$ g++ foo.cxx -o foo

$ ./foo
sizeof(foo): 1
```

**Comment by MatthiasWM** [comment]
Fl_Label is usually part of Fl_Widget, and in that class it's followed by `unsigned int flags_`. I am not sure for Intel machines, but on ARM32, Fl_Label would be padded so that flags_ is on a 4 byte boundary. I know that x86 can access unalingned data. Not sure how modern compilers do it.

Just checked my ARM64 Mac with Clang: sizeof(Fl_Widget) is 120 bytes. I can add up to 7 more bytes after Fl_Label::type_ until the size jumps to 128 bytes. I have no Intel machine this moment.

**Comment by MatthiasWM** [comment]
This should not change anything if not set to a value other than 0. @ggarra13 please try it out and let me know if this works fo you. You can test this interactively in `test/label`

**Comment by ggarra13** [comment]
@MatthiasWM Seems to work as advertised.  Sorry it took long to test.
