### ISSUE TITLE
FL_KEYDOWN events not delivered to out-of-focus widgets

### ISSUE THREAD

**Issue by dkogan** [fltk/fltk#1044]
Hello. I'm observing a bug in fltk 1.3 (Debian libfltk1.3t64:amd64=1.3.8-6.1). Fairly certain this bug isn't new and that it's present in the fltk 1.4 sources as well. A trivial pyfltk program to reproduce the problem:

```python
#!/usr/bin/python3

import sys
from fltk import *

class Fl_Button_Derived(Fl_Button):

    def __init__(self,
                 *args,
                 **kwargs):
        return super().__init__(*args, **kwargs)

    def handle(self, event):
        if Fl.event_key() == fltk.FL_Delete:
            widget_focused = Fl.focus()
            if event == FL_KEYDOWN:
                print(f"FL_KEYDOWN: delete with focused = '{widget_focused.label()}'")
            if event == FL_KEYUP:
                print(f"FL_KEYUP:   delete with focused = '{widget_focused.label()}'")
                return 1

        return super().handle(event)



window  = Fl_Window(800, 600,
                    "window")
button1 = Fl_Button_Derived(0,0, 800, 300,
                            "Event-receiver button")
button2 = Fl_Button(0,300, 800, 300,
                    "Other button")

window.end()
window.show()

Fl.run()

sys.exit(0)
```

On Debian, `apt install python3-fltk` to make this runnable. It should be clear. If you really need a c++ reproducer, I can make one, but that shouldn't be needed.

Here I make a window with two buttons: one normal `Fl_Button` and the other using a derived class. The derived button simply prints out when it gets key-up or key-down events with the user pressing Delete, and which widget is focused at the time. I would expect neither button to want any of these events, so the derived button should see both, the up and down events, regardless of which widget is focused. Instead I see this when I press Delete, focus the other button, and press Delete again:

```
FL_KEYDOWN: delete with focused = 'Event-receiver button'
FL_KEYUP:   delete with focused = 'Event-receiver button'
FL_KEYUP:   delete with focused = 'Other button'
```

I.e. when the derived button isn't focused, it doesn't see the other button's FL_KEYDOWN event.

I believe the cause is this bit of code: https://github.com/fltk/fltk/blob/f151ecb87b8ecfca4bfcd352ff7590edf425666a/src/Fl_Group.cxx#L173

Here we check for navigation keys. And if the pressed key isn't a navigation we return 0. Instead we should evaluate the `default:` code to distribute the unwanted event to the other widgets that might want it. That's what happens with the FL_KEYUP event, which isn't hijacked by the bit of code above.

Thanks

**Comment by ManoloFLTK** [comment]
What you see is a consequence of a special feature of FL_KEYUP events documented at:
https://www.fltk.org/doc-1.3/events.html#events_fl_keydown :
> FL_KEYUP events are sent to the widget that currently has focus.

That feature is the same in 1.3 and 1.4.

I'm not sure that's a bug.

**Comment by MatthiasWM** [comment]
Not that there is no `return 1` after `print(f"FL_KEYDOWN: ...` which is why you see the key-up event twice.

**Comment by Albrecht-S** [comment]
Hmm, there seems to be some confusion, particularly (but not only) because the title _"FL_KEYUP events not delivered to out-of-focus widgets"_ appears to be wrong.
@dkogan You wrote:
> ... when the derived button isn't focused, it doesn't see the other button's FL_KEYDOWN event.

This is also demonstrated by the output of the demo program given above. Hence the title should supposedly be "_**FL_KEYDOWN** events not delivered to out-of-focus widgets_". I don't want to change it w/o confirmation, hence I'm leaving it for now as-is.

Short answer (to the implied question of the changed title): yes, this is true and intentional, it's not a bug. Long answer follows below.

**Comment by Albrecht-S** [comment]
**_Long answer:_** FLTK's event delivery is tricky, and derived classes need to
- return 1 or 0 whether they handle a particular event or not
- call the handle() method of the parent class in all but very special cases, for instance if you **really** want disable (short-circuit) the `handle()` method of the parent class for some events
- "know" about some of FLTK's internals WRT event delivery.

> A trivial pyfltk program to reproduce the problem: [...]
> If you really need a c++ reproducer, I can make one, but that shouldn't be needed.

We need a C++ reproducer in most cases to ensure that the described behavior is really caused by the FLTK library itself and not by the wrapper library (here `pyFLTK`). Hence, if you really want to report a bug, please provide a C++ reproducer. FLTK developers are also more familiar with C++ code than pyFLTK code.

After all it's important that the demo program itself (whether it's C++ or a wrapper library) is correct WRT the documented FLTK functionality. As @MatthiasWM pointed out, there's at least one issue with your program that is not correct (potentially missing return statement), but there's another one: the `handle()` method of the parent class is not always called which can have unexpected effects.

Before I post an updated demo program that does IMHO what the OP intended, here is the output of this program:
```
FL_KEYDOWN  on 'Event-receiver' with focused = 'Event-receiver'
FL_SHORTCUT on 'Other button  ' with focused = 'Event-receiver'
FL_KEYUP    on 'Event-receiver' with focused = 'Event-receiver'
FL_KEYUP    on 'Event-receiver' with focused = 'Event-receiver'
FL_KEYUP    on 'Other button  ' with focused = 'Event-receiver'

FL_KEYDOWN  on 'Other button  ' with focused = 'Other button  '
FL_SHORTCUT on 'Other button  ' with focused = 'Other button  '
FL_KEYUP    on 'Other button  ' with focused = 'Other button  '
FL_KEYUP    on 'Other button  ' with focused = 'Other button  '
FL_KEYUP    on 'Event-receiver' with focused = 'Other button  '
```

As you can see the `FL_KEYDOWN` event is converted to `FL_SHORTCUT` before it is received by 'Other button'. This is done as specified in the documentation:
- [`FL_KEYBOARD`:] If you return zero then FLTK assumes you ignored the key and will then attempt to send it **_to a parent widget_**. If none of them want it, it will change the event into a `FL_SHORTCUT` event.
- [`FL_SHORTCUT`:] ... then FLTK tries sending this event to every widget it can, until one of them returns non-zero. FL_SHORTCUT is first sent to the `Fl::belowmouse(`) widget, then its parents and siblings, and _eventually to every widget in the window_, trying to find an object that returns non-zero.

That said, the delivery of `FL_KEYUP` events **can** send the same event twice to a particular widget because it is first sent to the `Fl::focus()` event and then to all parents, where parents distribute this event to all children, including the `Fl::focus()` widget again. This is also visible in the output (above) of my modified demo program (below):

```python
#!/usr/bin/python3

import sys
from fltk import *

class Fl_Button_Derived(Fl_Button):

    def __init__(self,
                 *args,
                 **kwargs):
        return super().__init__(*args, **kwargs)

    def handle(self, event):
        ret = super().handle(event) # ALWAYS call the parent's handle()
        if Fl.event_key() == fltk.FL_Delete:
            widget_focused = Fl.focus()
            event_label = self.label()
            if event == FL_KEYDOWN:
                print(f"")
                print(f"FL_KEYDOWN  on '{event_label}' with focused = '{widget_focused.label()}'")
                # ret = 1 # commented out for testing purposes
            if event == FL_SHORTCUT:
                print(f"FL_SHORTCUT on '{event_label}' with focused = '{widget_focused.label()}'")
                ret = 1
            if event == FL_KEYUP:
                print(f"FL_KEYUP    on '{event_label}' with focused = '{widget_focused.label()}'")
                ret = 0  # TEST: ignore FL_KEYUP event to see it propagate

        return ret

window  = Fl_Window(800, 600,
                    "window")
button1 = Fl_Button_Derived(0,0, 800, 300,
                            "Event-receiver")
button2 = Fl_Button_Derived(0,300, 800, 300,
                            "Other button  ")

window.end()
window.show()

Fl.run()

sys.exit(0)
```

**_Disclaimer:_** I'm not a python programmer and don't know pyFLTK enough to ensure that my demo program is correct but I hope it's "good enough" for this purpose.

See even more in a follow-up comment.

**Comment by Albrecht-S** [comment]
FWIW, here's another point: looking at the code of `Fl_Button::handle(int event)` it seems that this widget **_always_** returns 1 on `FL_KEYDOWN` events, no matter if it really uses it to trigger an action (call the callback) or not. I'm not sure if this is really true (the code is not trivial to read and understand) but if it is this **may** be considered questionable but it's probably not changeable because of backwards compatibility.

`Fl_Button` always returns 0 on `FL_KEYUP` events which is as expected.

**Comment by ManoloFLTK** [comment]
> looking at the code of Fl_Button::handle(int event) it seems that this widget always returns 1 on FL_KEYDOWN events

I've modified the `button` test program to make it use a class that does the same as class Fl_Button but just prints its `handle` method's return value. I see that value 0 (not 1) is returned on FL_KEYDOWN events. Same thing with or without attached callback function. Tested on macOS and X11.

**Comment by dkogan** [comment]
Thanks for the comments. FYI https://www.fltk.org is down right now, so the links don't work.

As you noted, I messed-up several things in the bug report, creating needless confusion. Sorry about that; I should have proofread better.

In the script in the bug report: the "return 1" was unintentional: I wanted the derived `handle()` to just fall-through in all cases. Also I should have spelled-out the problem sequence more clearly. To test I would:

- run the attached program
- Press Delete with one button focused
- Press Tab to focus the other button
- Press Delete with the other button focused

So each focused button would see a press/release cycle of the Delete key. The complaint wasn't the two FL_KEYUP events (that's correct: Delete WAS pressed and released twice). The complaint was the one missing FL_KEYDOWN event. I re-title the bug report.

Your corrected program above describes what's happening. It sounds confusing, but I suppose changing this might break other people's code, so we leave it alone.

What I REALLY want to do is to have a derived widget react to FL_KEYDOWN regardless of what's focused. To do that I now see that I need to respond to FL_KEYDOWN or FL_SHORTCUT. This seems to work, and it the right way to do this. Yes?

I'm closing this report, since there doesn't seem much to do here. Thank you very much.

**Comment by Albrecht-S** [comment]
Note: I added label "wontfix" which means here: there is nothing to be fixed.

**Comment by Albrecht-S** [comment]
FTR, @ManoloFLTK wrote:
> I've modified the button test program to make it use a class that does the same as class Fl_Button but just prints its handle method's return value. I see that value 0 (not 1) is returned on FL_KEYDOWN events.

I also double-checked this and I noticed that Fl_Button returns 1 if space (`' '`) is pressed but 0 otherwise, hence my statement above (that it always returns 1) was wrong. Manolo, can you confirm this with your modified test program (hitting `space`)?

**Comment by Albrecht-S** [comment]
FTR, @ManoloFLTK wrote:
> I've modified the button test program to make it use a class that does the same as class Fl_Button but just prints its handle method's return value. I see that value 0 (not 1) is returned on FL_KEYDOWN events.

I also double-checked this and I noticed that Fl_Button returns 1 if space (`' '`) is pressed but 0 otherwise, hence my statement above (that it always returns 1) was wrong. Manolo, can you confirm this with your modified test program (hitting `space`)?

**Comment by ManoloFLTK** [comment]
> can you confirm this with your modified test program (hitting space)?

I confirm this. Hitting space has the Fl_Button widget return 1 and triggers the widget's callback. Other keys have the button return 0.

**Comment by dkogan** [comment]
Hi. I've a very related question, that hopefully is ok to ask here. I have an fltk application with lots of widgets; one widget is a horizontal slider. If a user presses FL_Right I'd like the slider to advance, whether it's focused or not. None of the other widgets want the FL_Right event, but it's interpreted by the navigation code. So pressing Fl_Right repeatedly eventually changes focus to the slider, and then it advances. Should I disable the navigation logic somehow? Thanks

**Comment by Albrecht-S** [comment]
> I've a very related question, that hopefully is ok to ask here. ...

@dkogan No, sorry, this is not the right place. Please open a new "Discussion" in the "Q&A" section for your question. Although your question may seem related we can't answer it here. We need separate issues or - in this case - a new thread in GitHub Discussions for each question. It would also be helpful if you could post a simple (minimal) reproducer (i.e. not with "lots of widgets" but only with as many widgets as necessary to show your issue).

Please follow this link: https://github.com/fltk/fltk/discussions/categories/q-a
