### ISSUE TITLE
[CMAKE] Cannot change msvc runtime library on Windows Clang

### ISSUE THREAD

**Issue by supsm** [fltk/fltk#1058]
**Describe the bug**
If clang is used as the compiler on windows, the FLTK_MSVC_RUNTIME_DLL option will not be available.

**To Reproduce**
Note: these steps use clang and ninja but it's probably not strictly necessary
1. Install LLVM for windows
2. Install ninja build
3. Configure FLTK with `-G Ninja` and `-DFLTK_MSVC_RUNTIME_DLL=FALSE` **outside of msvc command prompt** (make sure it says Clang with GNU-like command-line and not MSVC-like command-line)

**Expected behavior**
The msvc runtime should be set to /MTd

**Screenshots**
```
CMake Warning:
  Manually-specified variables were not used by the project:

    FLTK_MSVC_RUNTIME_DLL
```

**FLTK Version**
 - Version: 1.4.0 (634ce80, latest as of writing)
 - Cloned from Github

**FLTK Configure / Build Options**
`cmake -S . -B build -G "Ninja" -DFLTK_MSVC_RUNTIME_DLL=FALSE`

**Operating System / Platform:**
 - OS: Windows 11

**Additional context**
The problem is simply that clang.exe (as opposed to clang-cl) on windows does not set `MSVC` to true in CMake (this makes sense since the command-line syntax is different).  
The fix is to simply remove the if statement on [lines 90 and 97 of `CMake/options.cmake`](https://github.com/fltk/fltk/blob/634ce805e5de4663fc9efdb288ed5b726af96005/CMake/options.cmake#L90-L97) (but keep the contents) such that the `FLTK_MSVC_RUNTIME_DLL` option appears on all platforms. [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) says that "The value is ignored on compilers not targeting the MSVC ABI", so it should not cause any issues.  
Maybe the option description could be changed to "use MSVC Runtime-DLL (/MDx) when using MSVC linker" or something similar to prevent confusion on other platforms.

**Comment by Albrecht-S** [comment]
@supsm Thanks for the report. I see what you want to achieve but I don't like your proposed solution for the following reason:

You wrote:
> [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) says that "The value is ignored on compilers not targeting the MSVC ABI", so it should not cause any issues.

I'm not concerned about the CMake variable (yes, it will be ignored by CMake) but I wouldn't like to add an option on platforms that don't need nor use this option to avoid confusion of users.

I can't test this myself because I don't have `LLVM/clang` installed on my Windows system and I won't install it because my test system is disk space constrained. I suggest to use a better condition to add the relevant code, i.e. **replace** `if(MSVC)` with another condition rather than removing it completely. What about:
```
  if(WIN32 AND NOT MINGW AND NOT MSYS)
```
?

Can you provide a condition that works for you? It should at least contain `if(WIN32 ...)` if we can't use `if(MSVC ...)`.

Last but not least, for my better understanding: what exactly do you mean with "**_outside of msvc command prompt_**", i.e. which shell are you using to do this? A standard "DOS shell" (command prompt window), a Powershell window, or any of MinGW or MSYS shells (usually `bash`)? Or anything else?

**Comment by supsm** [comment]
> I'm not concerned about the CMake variable (yes, it will be ignored by CMake) but I wouldn't like to add an option on platforms that don't need nor use this option to avoid confusion of users.  

That is understandable. The `if(WIN32 AND NOT MINGW AND NOT MSYS)` condition you provided does work for windows 
clang, and it doesn't seem like there is any better option.

> Last but not least, for my better understanding: what exactly do you mean with "outside of msvc command prompt", i.e. which shell are you using to do this? A standard "DOS shell" (command prompt window), a Powershell window, or any of MinGW or MSYS shells (usually bash)? Or anything else?  

The standard command prompt and powershell both work for this (interestingly, Git Bash also worked despite it being labeled MINGW64). I think as long as `clang.exe`/`clang++.exe` is visible on the PATH but `cl.exe` isn't, it should work.

**Comment by Albrecht-S** [comment]
@supsm Thanks for your confirmation. Commit b595db30d46f9ace877540c073a7a3e7e423aaa7 fixes the issue.
