### ISSUE TITLE
Wayland crash on mapping windows at startup

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#1072]
**Describe the bug**
When mapping a mid-sized window on Wayland, I get a crash.  It does not seem to happen with small or big (fullscreen) windows.  On release builds, it happens all the time time with mid-sized windows (ie 1325x825 getting mapped on a 1920x1080 monitor).  On debug builds, the crash happens sometimes and sometimes it does not.

**To Reproduce**

The issue might be related to a group of a Fl_Flex getting hidden during a timeout sometimes *before* and sometimes *after* Wayland maps its first window.

**Expected behavior**
No crash.

**Screenshots**

**FLTK Version**
1.4.0 master
1.4.0 634ce805e5de4663fc9efdb288ed5b726af96005

**Operating System / Platform:**
Ubuntu 24.04 

**Linux/Unix Runtime, if applicable:**
 - Wayland

**Additional context**

Attached stack trace:
[start_crash.txt](https://github.com/user-attachments/files/16990191/start_crash.txt)

**Comment by ManoloFLTK** [comment]
Please, try replacing line #1912 in file `src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx` from
      `Fl_Wayland_Graphics_Driver::buffer_commit(parent_xid);`
to
      `if (parent_xid->buffer) Fl_Wayland_Graphics_Driver::buffer_commit(parent_xid);`
and report whether the crash still occcurs.

**Comment by ggarra13** [comment]
That fixed it!

**Comment by Albrecht-S** [comment]
@ggarra13 I notice that Manolo replied with a patch suggestion, and that it fixed your issue. Great!

However I also noticed something in your log:
```
Plugin "GTK3 plugin" uses conflicting symbol "png_free".
No plugins found, falling back on no decorations
```

The point is `uses conflicting symbol "png_free"`. This can really become an issue, unrelated to your current crash. This tells us (AFAICT) that your own build of libpng conflicts with the system libpng which would be implicitly linked (loaded) at runtime by the GTK plugin or some other shared libs your program may use. I **_strongly suggest not to ignore this warning_** because it can cause all sorts of fails and crashed. In short terms: that's exactly the reason why our bundled libs use "symbol prefixing" which avoids such conflicts. More details would be OT here though.

**Comment by ggarra13** [comment]
> The point is `uses conflicting symbol "png_free"`. This can really become an issue, unrelated to your current crash.

It only happens on debug builds, as the library is called libpngd.so.x.x.  On release builds, the png_free function does not conflict.

**Comment by ManoloFLTK** [comment]
The change is committed. Please, close issue if you agree it's fixed.
