### ISSUE TITLE
[Bug] Windows: Ctrl+= shortcut no longer recognized

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#1086]
**Describe the bug**

Commit 3fbd4f9 broke Ctrl+= application shortcuts.

**To Reproduce**

Here is a patch for test/menubar.cxx to witness the bug:

```diff
diff --git a/test/menubar.cxx b/test/menubar.cxx
index a0424732d..d854944e6 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -105,7 +105,7 @@ Fl_Menu_Item menutable[] = {
     {"Clear",       0,           0, 0, FL_MENU_DIVIDER},
     {"Invisible",   FL_ALT+'e',  0, 0, FL_MENU_INVISIBLE},
     {"Preferences", 0,           0},
-    {"Size",        0,           0},
+    {"Size",        FL_CTRL+'=', 0},
     {0},
   {"&Checkbox",FL_F+3,0,0,FL_SUBMENU},
     {"&Alpha",  FL_F+2, 0, (void *)1, FL_MENU_TOGGLE},
@@ -224,6 +224,7 @@ void about_cb(Fl_Widget*, void*) {
 }
 
 int main(int argc, char **argv) {
+  Fl::keyboard_screen_scaling(0);
   //Fl::set_color(Fl_Color(15),0,0,128);
   for (int i=0; i<99; i++) {
     char buf[100];
```

1. Apply the above patch to test/menubar.cxx
2. Compile and run like normal
3. Press Ctrl and '='
4. See that the menu shortcut is not triggered

**Expected behavior**

The shortcut should be recognized and the terminal should print "Size - Ctrl+=".

Comment out `{VK_OEM_PLUS,  '+'},` from 3fbd4f9 and see that the shortcut works as expected.

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5c6ec56

**FLTK Configure / Build Options**
 - VS CMake, default options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11
 - Processor if relevant: Intel

**Additional context**

This was tested on a US ANSI keyboard.

**Comment by Albrecht-S** [comment]
@dannye Thanks for this detailed report and the suggested fix.

I set priority to 4 (High) because the previous commit introduced a regression.

Note: Windows keyboard handling in 1.3.x (and thus in 1.4.x as well) is not correct for many international keyboards. Commit 3fbd4f944f0a6e16630974e56e1e896eb7bbf6f7 was an attempt to support the usual scaling shortcuts on Windows but the additional virtual key value `VK_OEM_PLUS` unintentionally overrode another table entry (`0xbb`).

A better - and hopefully correct - implementation is planned for 1.5.0.
