### ISSUE TITLE
Fl_Sys_Menu_Bar::update does not update menu items correctly

### ISSUE THREAD

**Issue by carmiker** [fltk/fltk#1094]
**Describe the bug**
Fl_Sys_Menu_Bar::update does not update menu items correctly.

**To Reproduce**
Apply the attached diff, then build the tests.

- Run the "menubar" test
- Observe that the menu items in the "Inactive" dropdown are not active
- Use the "Activate" menu item in the "Empty" dropdown
- Observe that the menu items in the "Inactive" dropdown remain inactive

**Expected behavior**
- After using the "Activate" menu item in the "Empty" dropdown, the items in the "Inactive" dropdown should be activated

**FLTK Version**
c0e07d3452a65cc0f0ea7f56ec149ffd7e6e934f

**Operating System / Platform:**
 - OS Version: macOS 12.7.6, Intel

**Additional context**
- Uncommenting the following line makes the bug non-observable:
```
Fl_Sys_Menu_Bar::window_menu_style(Fl_Sys_Menu_Bar::no_window_menu);
```
- All other options (tabbing_mode_none, tabbing_mode_automatic, tabbing_mode_preferred) result in the behaviour described in the bug report.
- Activating the menu items before the main window is shown will result in them being activated. A commented call to `mbar_activate` can be uncommented to demonstrate this.

Diff:
```
diff --git a/test/menubar.cxx b/test/menubar.cxx
index a5ccfc234..40e5984db 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -63,6 +63,8 @@ void test_cb(Fl_Widget* w, void*) {

 void quit_cb(Fl_Widget*, void*) {exit(0);}

+void mbar_activate(Fl_Widget *w, void *data);
+
 Fl_Menu_Item hugemenu[100];

 Fl_Menu_Item menutable[] = {
@@ -170,7 +172,9 @@ Fl_Menu_Item menutable[] = {
     {"Hangul character Cieuc", 0x003148},
     {0},
   {"E&mpty",0,0,0,FL_SUBMENU},
+    {"Activate", 0, mbar_activate, 0, 0},
     {0},
+
   {"&Inactive", 0,      0, 0, FL_MENU_INACTIVE|FL_SUBMENU},
     {"A very long menu item"},
     {"A very long menu item"},
@@ -204,6 +208,14 @@ Fl_Menu_Item menu_location[] = {

 Fl_Sys_Menu_Bar* smenubar;

+void mbar_activate(Fl_Widget *w, void *data) {
+    printf("Activate inactive menu items (%d)\n", menutable[0].size());
+    for (int i = 0; i < menutable[0].size(); ++i) {
+        menutable[i].activate();
+    }
+    smenubar->update();
+}
+
 void menu_location_cb(Fl_Widget* w, void* data)
 {
   Fl_Menu_Bar *menubar = (Fl_Menu_Bar*)data;
@@ -302,6 +314,7 @@ int main(int argc, char **argv) {
   };
   Fl_Mac_App_Menu::custom_application_menu_items(custom);
   //Fl_Sys_Menu_Bar::window_menu_style(Fl_Sys_Menu_Bar::no_window_menu);
+  //mbar_activate(nullptr, nullptr);
 #endif
   window.show(argc, argv);
   return Fl::run();
```

**Comment by ManoloFLTK** [comment]
@carmiker  This "problem" results from a wrong implicit assumption made in how you wrote function `mbar_activate()`. This function uses the `menutable`array because this array was initially used to populate the system menubar. The error is that a menubar's array of menu items is a changing object. Each time an item is added or removed, the menubar's array is susceptible to change. A program that accesses a menubar's array of items should **always** use the `Fl_Menu::menu()` member function to obtain the valid item array. Because by default the system menubar is extended by a Windows menu, the system menubar's array of items does change to accomodate for the new "Windows" item. Ultimately the array of items that function `mbar_activate()` modifies was initially the system menubar's item array but is no longer that when the function runs. All of this also explains your observation that if you uncomment `Fl_Sys_Menu_Bar::window_menu_style(Fl_Sys_Menu_Bar::no_window_menu);` the bug disappears. That's because the system menubar's item array is not changed to make room for a Windows menu for lack of such menu.

The fix for this issue is to write `mbar_activate()` as follows:
```
void mbar_activate(Fl_Widget *w, void *data) {
  Fl_Menu_Item *table = (Fl_Menu_Item*)smenubar->menu();
    printf("Activate inactive menu items (%d)\n", table[0].size());
    for (int i = 0; i < table[0].size(); ++i) {
        table[i].activate();
    }
    smenubar->update();
}
```
