### ISSUE TITLE
Fl_Screen_Driver::system_driver not deleted

### ISSUE THREAD

**Issue by KaruroChori** [fltk/fltk#1095]
**Describe the bug**
`Fl_Screen_Driver::system_driver` is allocated but never deleted for X11 (Fl_X11_Screen_Driver::close_display) unlike wayland (Fl_Wayland_Screen_Driver::close_display).
Other globals might be affected as well, but they are not reflected in a basically headless example.

**To Reproduce**
Any empty main function linked to fltk.
Running the executable in valgrind shows the issue:
```
==164234== HEAP SUMMARY:
==164234==     in use at exit: 8 bytes in 1 blocks
==164234==   total heap usage: 1,551 allocs, 1,550 frees, 197,909 bytes allocated
==164234== 
==164234== 8 bytes in 1 blocks are still reachable in loss record 1 of 1
==164234==    at 0x4843F83: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==164234==    by 0x5011371: Fl_System_Driver::newSystemDriver() (../subprojects/libfltk/src/drivers/X11/fl_X11_platform_init.cxx:62)
==164234==    by 0x4F498D5: Fl::system_driver() (../subprojects/libfltk/src/Fl.cxx:105)
==164234==    by 0x4F493B8: __cxx_global_var_init (../subprojects/libfltk/src/Fl.cxx:2388)
==164234==    by 0x4F49478: _GLOBAL__sub_I_Fl.cxx (../subprojects/libfltk/src/Fl.cxx:0)
==164234==    by 0x400429D: call_init (dl-init.c:74)
==164234==    by 0x400429D: call_init (dl-init.c:26)
==164234==    by 0x400438B: _dl_init (dl-init.c:121)
==164234==    by 0x401BB2F: ??? (in /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2)
==164234==    by 0x1: ???
==164234==    by 0x1FFF0001EE: ???
==164234==    by 0x1FFF0001F9: ???
==164234== 
==164234== LEAK SUMMARY:
==164234==    definitely lost: 0 bytes in 0 blocks
==164234==    indirectly lost: 0 bytes in 0 blocks
==164234==      possibly lost: 0 bytes in 0 blocks
==164234==    still reachable: 8 bytes in 1 blocks
==164234==         suppressed: 0 bytes in 0 blocks
```

**Expected behavior**
The driver should be destroyed at some point, even if it is a global variable.

**Screenshots**

**FLTK Version**
master

**FLTK Configure / Build Options**
not relevant, the logic to delete that pointer is just missing in code from what I can tell.

**Operating System / Platform:**
not relevant, the logic to delete that pointer is just missing in code (debian testing channel)

**Linux/Unix Runtime, if applicable:**
X11

**Comment by Albrecht-S** [comment]
@KaruroChori  Thank you for this report. However, this is not an issue we care about:

> The driver should be destroyed at some point, even if it is a global variable.

There are lots of other global variables and some memory allocated on the heap that is (are) not deleted (or free'd) before the program exits. All such memory is returned to the system when the program exits.

There are two "real" issues we care about:
1. Memory is allocated multiple times and not free'd during runtime. This constitutes a memory leak.
2. An object is created and allocates a specific resource. Such resources (e.g. open, writable files) must be free'd in a destructor or similar to return the resources to the system. Note that files are only a (bad) example because files are closed on exit as well.

That said, this issue will not be worked on because there's nothing to do.
