### ISSUE TITLE
error: typedef redefinition (MacOS 15.1/Homebrew)

### ISSUE THREAD

**Issue by dasergatskov** [fltk/fltk#1125]
compiling octave with fltk 1.3.9 on MacOS 15.1 (Homebrew) I see:
```
In file included from ../libinterp/dldfcn/__init_fltk__.cc:74:
In file included from /opt/homebrew/Cellar/fltk/1.3.9/include/FL/fl_draw.H:27:
In file included from /opt/homebrew/Cellar/fltk/1.3.9/include/FL/x.H:30:
/opt/homebrew/Cellar/fltk/1.3.9/include/FL/mac.H:32:25: error: typedef redefinition with different types ('class FLWindow *' vs 'XID' (aka 'unsigned long'))
   32 | typedef class FLWindow *Window; // pointer to the FLWindow objective-c class
      |                         ^
/opt/homebrew/include/X11/X.h:96:13: note: previous definition is here
   96 | typedef XID Window;
      |             ^
```
```
% clang++ -v
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Dmitri.
--

**Comment by ManoloFLTK** [comment]
When compiling FLTK for macOS, you include `FL/x.H` which contains this
```
#  elif defined(__APPLE__)
#    include "mac.H"
#  else
#    if defined(_ABIN32) || defined(_ABI64) // fix for broken SGI Irix X .h files
#      pragma set woff 3322
#    endif
#    include <X11/Xlib.h>
#    include <X11/Xutil.h>
```
Therefore, macOS-style definitions inside file `FL/mac.H` are used, and X11-style definitions are not used.
If, before doing that, you have included `X11/X.h`, it indicates you intend to use X11 rather than macOS
as windowing system. That's a conflict which is apparent in type `Window` being given 2 distinct definitions.

Overall, my advice is to clarify why `X11/X.h` is included in the first place. That creates an incompatibility with FLTK under macOS which does not use X11 as windowing system.

**Comment by ManoloFLTK** [comment]
@dasergatskov Please note that, starting from FLTK 1.4 0 released today, FLTK supports 2 windowing systems under macOS, the usual one (I would call it Cocoa) and X11 provided that XQuartz is present on the running machine and at build time. Then any FLTK app, octave included, can be built either as a Cocoa app or as an X11 app and run on macOS. It remains essential to choose between one of these 2 windowing sytems and not to mix components expecting distinct systems.
