### ISSUE TITLE
FL_REGION_STACK_SIZE could be increased

### ISSUE THREAD

**Issue by parisseb** [fltk/fltk#1139]
Current value defined in FL/Fl_Graphics_Driver.H is 10.  I propose to raise this to say 64, because 10 is too small for applications having several levels of embedded Fl_Group * (or inheriting classes) inside Fl_Group *, each doing 1 or 2 fl_push_clip regions on the stack. 
For example inside my Xcas app, if I open an interactive geometry level, I can have
main Fl_Window -> main tab -> history_fold -> scroll -> history_pack -> geometry -> history_pack -> scroll -> tile ->  scroll -> input field
This should not impact that much memory footprint since sizeof(Fl_Region) is not that big...

**Comment by Albrecht-S** [comment]
@parisseb Thank you for this report.

I agree that 10 is too small and this shows one of the problems where fixed size arrays are used in FLTK. There are two things to do:
1. increase the array size in FLTK 1.4.1 (Git `master`) as suggested  [1]
2. use `std::vector` or another appropriate construct in FLTK 1.5 to allocate the stack dynamically

I set priority `High` - this needs to be fixed ASAP (in 1.4.1) because clipping is an essential feature.

What I found out so far:
- the constant `FL_REGION_STACK_SIZE` is used for both the "normal" and for "gl region" stack size
- when Cairo drawing is enabled on Linux with Wayland (hybrid) or X11 there's no such restriction because Cairo clipping is used (at least that's what I found by reading the code and by testing)
- other than that the problem is in common code (not platform specific)

Solution:
1. I will increase `FL_REGION_STACK_SIZE` for FLTK 1.4 to `64` as suggested (after further checks)
2. I will open a new issue for FLTK 1.5
-------
[1] we could allocate the stack dynamically and reallocate it if necessary but I prefer solution (2.) in FLTK 1.5.

**Comment by Albrecht-S** [comment]
FTR: Point 2 done, see #1140: "Fix static array allocation"

**Comment by Albrecht-S** [comment]
Point 1 done in commit 801125b9a4abfe259eca1437f4a3a36aba9f5052.

Thanks again for the report, closing this issue now.

**Comment by parisseb** [comment]
Thanks for the quick fix. Dynamic alloc would indeed be better, but perhaps some warnings could be raised if the size is bigger than some fixed value in order to catch unmatched push/pop clip.

**Comment by Albrecht-S** [comment]
> Thanks for the quick fix.

You are welcome.

> Dynamic alloc would indeed be better, but perhaps some warnings could be raised if the size is bigger than some fixed value in order to catch unmatched push/pop clip.

Yes, that could be an option in 1.5 where we can supposedly use `std::vector<..>`. We can still set a limit that shouldn't be exceeded but it would be difficult to determine a useful value.

Maybe better: we could "auto-clean" the clip stack when we leave `Fl::flush()` or at any other suitable point, maybe after drawing each top-level window. At that time the clip stack **_should_** be empty and we can issue a warning if it is **_not empty_**. The other applicable warning "clip stack underflow" exists anyway and could be kept as-is.

**Comment by Albrecht-S** [comment]
@parisseb and others:

FYI: Unfortunately it turned out that commit 801125b9a4abfe259eca1437f4a3a36aba9f5052 ("Increase clipping stack size") would break the ABI because it increases the size of `Fl_Graphics_Driver`.

If you need this increased clipping stack size, please build your (local) FLTK library with ABI 10401 (1.4.1):
- ./configure --with-abiversion=10401 or
- cmake -D FLTK_ABI_VERSION:STRING=10401 ...

It seems possible to implement a different patch for FLTK 1.4.2 or later that doesn't break the ABI but this can't be done now while I'm releasing FLTK 1.4.1 - I'll let you know if I found a better and compatible implementation.

I'm sorry for this apparent step backwards -- **_for beta testers of default builds from Git only_** -- but this is absolutely necessary for ABI compatibility. It's not a regression in comparison with the official release 1.4.0 (or 1.3.x).

**Comment by Albrecht-S** [comment]
FTR: the above mentioned commit 0e6b20d957c682cd9bc7712e2869384c4801b985 has also been pushed to branch `master`.
