### ISSUE TITLE
Error compiling under macos14, missing `cp936ext_wctomb`

### ISSUE THREAD

**Issue by KaruroChori** [fltk/fltk#1148]
**Describe the bug**
Compiling with clang-19 fails at this stage:
```
 In file included from ../subprojects/libfltk/src/xutf8/utf8Wrap.c:32:
../subprojects/libfltk/src/xutf8/ucs2fontmap.c:289:9: error: use of undeclared identifier 'cp936ext_wctomb'
  289 |     if (cp936ext_wctomb(NULL, (unsigned char*)s, ucs, 2) > 0) {
      |         ^
```
Checking in the implementation, most of the relevant file where that function is define is pruned by a condition checking for the environment to be either WINDOWS or MACOS. As such the function itself is not present.

Strangely, the actual build on this repository does not fail and its shows slightly different configuration options.

**To Reproduce**
Please, check the gihub action log from here https://github.com/KaruroChori/vs-fltk/actions/runs/12101115525/job/33740566747
The same task running on debian works as expected (as that section of code is not cut off)

**FLTK Version**
Latest synchronized with master

**FLTK Configure / Build Options**
```
 | -- Configuration Summary for FLTK 1.4.0 generated by CMake 3.31.1 --

| -- The following OPTIONAL packages have been found:

| * ZLIB
| * PNG
| * JPEG

| -- The following OPTIONAL packages have not been found:

| * Doxygen

| -- Static libraries    will be built in: /Users/runner/work/vs-fltk/vs-fltk/build/subprojects/libfltk/__CMake_build/lib
| -- Shared libraries    will be built in: /Users/runner/work/vs-fltk/vs-fltk/build/subprojects/libfltk/__CMake_build/lib
| -- The forms library   will be built in: /Users/runner/work/vs-fltk/vs-fltk/build/subprojects/libfltk/__CMake_build/lib
| -- The OpenGL library  will be built in: /Users/runner/work/vs-fltk/vs-fltk/build/subprojects/libfltk/__CMake_build/lib
| -- fluid               will not be built (set FLTK_BUILD_FLUID=ON to build)
| -- fltk-options        will be built in: /Users/runner/work/vs-fltk/vs-fltk/build/subprojects/libfltk/__CMake_build/bin
| -- Test programs       will not be built (set FLTK_BUILD_TEST=ON to build)
| -- Example programs    will not be built (set FLTK_BUILD_EXAMPLES=ON to build)
| --
| -- Build configuration      Release
| -- Installation prefix      /opt/homebrew

| -- Bundled Libraries        JPEG     = System: /opt/homebrew/lib/libjpeg.dylib
| --                          PNG      = System: /opt/homebrew/lib/libpng.dylib
| --                          ZLIB     = System: /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/libz.tbd

| -- Use Wayland              No (X11 is used)
| -- All drawing uses Cairo   No
| -- Use Pango                No
| -- Use Xft                  No
| -- Fl_Cairo_Window support  No
| -- Use std::                No
```
**Operating System / Platform:**
The macos14 image used in github actions

ref: https://github.com/KaruroChori/vs-fltk/issues/30

**Comment by ManoloFLTK** [comment]
@KaruroChori Please, explain what you are trying to achieve. The cmake command visible in the github action mentioned above includes option `-DFLTK_BACKEND_X11=True`. That is supported by FLTK, but it is not the most common way to build FLTK for the macOS platform. This option makes client applications of libfltk use the X11 system to create windows and their GUI in general. That is not what a standard macOS application does where windows and the GUI use Cocoa. Do you really want to use X11 rather than Cocoa?
If no, you should remove option `-DFLTK_BACKEND_X11=True` from the cmake command.
If yes, you should install XQuartz (see `https://www.xquartz.org/`) that is required by FLTK to work as an X11 client.

**Comment by ManoloFLTK** [comment]
Please, notice also that FLTK 1.4 is available as a homebrew formula (see https://formulae.brew.sh/formula/fltk#default) ready for use. In this case, FLTK is built using Cocoa to make windows and the GUI, not X11.

**Comment by KaruroChori** [comment]
> Please, notice also that FLTK 1.4 is available as a homebrew formula (see https://formulae.brew.sh/formula/fltk#default) ready for use. In this case, FLTK is built using Cocoa to make windows and the GUI, not X11.

In general, I would **really** prefer to remove `fltk` as a build dependency, and use whatever is provided by the distro or brew, as long as it is distributed as a dynamic library.

I was more or less forced to handle it directly, as I started working on that project before 1.4 was released as stable.   
And most distributions don't ship it still.  
However, I encountered several issues due to the non-standard  `fltk-config` in place of `pkg-config` and I have concerns on how this would behave in the context of cross-compiled builds.

> Do you really want to use X11 rather than Cocoa?
Yes, it was on purpose, but I did not realize macos does no longer ship with a x11 server by default.  
Installing `xquartz` solved this issue, and `fltk` seems to compile just fine.  

Removing the flag to use cocoa somehow fails, but I think it is something wrong with the `cmake` when used through meson.

**Comment by Albrecht-S** [comment]
> I encountered several issues due to the non-standard fltk-config in place of pkg-config and I have concerns on how this would behave in the context of cross-compiled builds.

> Removing the flag to use cocoa in its place somehow fails, but I think there is something wrong with the cmake when used through meson.

@KaruroChori First of all, if you use (or your meson build uses) CMake to build FLTK then you should **NOT** use `fltk-config` at all. `fltk-config` is a script that has been used (and can still be used) to build small programs as prototypes (`fltk-config --compile`) and since FLTK 1.4  you can also use multiple source files and link libraries.

The other options of `fltk-config` can be used to request the compiler and flags (**_similar_** to what `pkg-config` does) but this is NOT intended (nor is it recommended) to be used within CMake and it is not a replacement for `pkg-config`.

CMake should always use something like
```
  find_package(FLTK 1.4 CONFIG REQUIRED)
```
as described in `README.CMake.txt` (please see this file for details).

This should provide you with everything you need to build your project w/o using fltk-config.

If you have more questions please open a GitHub Discussion in the `Q\&A` section.

Please close this issue if you agree that the original question has been resolved.

**Comment by Albrecht-S** [comment]
Thanks for confirmation and for closing the issue.
