### ISSUE TITLE
Fluid in 1.4.0 generates different output in MINGW vs gcc on Fedora Linux

### ISSUE THREAD

**Issue by hobbes1069** [fltk/fltk#1154]
**Describe the bug**
```
[ 85%] Building CXX object test/CMakeFiles/tree.dir/tree.cxx.obj
cd /builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test && /usr/bin/i686-w64-mingw32-g++ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -Dtree_EXPORTS @CMakeFiles/tree.dir/includes_CXX.rsp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -MD -MT test/CMakeFiles/tree.dir/tree.cxx.obj -MF CMakeFiles/tree.dir/tree.cxx.obj.d -o CMakeFiles/tree.dir/tree.cxx.obj -c /builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx
make[2]: Leaving directory '/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32'
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx: In function 'void Button_CB(Fl_Widget*, void*)':
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:41:3: error: 'tty' was not declared in this scope
   41 |   tty->printf("'%s' button pushed (height=%d)\n", w->label(), height);
      |   ^~~
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx: In function 'void cb_tree(Fl_Tree*, void*)':
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:338:3: error: 'tty' was not declared in this scope
  338 |   tty->printf("TREE CALLBACK: label='%s' userdata=%ld reason=%s, changed=%d",
      |   ^~~
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:352:3: error: 'tty' was not declared in this scope
  352 |   tty->printf("TREE CALLBACK: reason=%s, changed=%d, item=(no item -- probably multiple items were changed at once)\n",
      |   ^~~
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx: In function 'void cb_testcallbackflag_button(Fl_Button*, void*)':
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:758:1: error: 'tty' was not declared in this scope
  758 | tty->printf("--- Checking docallback off\n");
      | ^~~
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx: In function 'void cb_testrootshowself_button(Fl_Button*, void*)':
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:824:1: error: 'tty' was not declared in this scope
  824 | tty->printf("--- Show Tree\n");
      | ^~~
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx: In function 'void cb_showselected_button(Fl_Button*, void*)':
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:1040:3: error: 'tty' was not declared in this scope
 1040 |   tty->printf("--- SELECTED ITEMS\n");
      |   ^~~
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx: In function 'void cb_nextselected_button(Fl_Button*, void*)':
/builddir/build/BUILD/fltk-1.4.0-build/fltk-1.4.0/build_win32/test/tree.cxx:1111:3: error: 'tty' was not declared in this scope
 1111 |   tty->printf("--- TEST next_selected():\n");
      |   ^~~
make[2]: *** [test/CMakeFiles/tree.dir/build.make:91: test/CMakeFiles/tree.dir/tree.cxx.obj] Error 1
```

**To Reproduce**
Test build on Fedora linux which builds native and MinGW packages in a single build.

**Expected behavior**
Fluid should produce the same output (or at least not drop `Fl_Terminal *tty=(Fl_Terminal *)0;` in the mingw build.

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Installed as package from: N/A

**FLTK Configure / Build Options**
Linux build:
```
/usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DFLTK_CONFIG_PATH:PATH=/usr/lib64/cmake/fltk -DOpenGL_GL_PREFERENCE=GLVND -DFLTK_BUILD_PDF_DOCS:BOOL=OFF -DFLTK_BUILD_SHARED_LIBS:BOOL=ON
```

MinGW build:
```
/usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw32.cmake -DBUILD_SHARED_LIBS:BOOL=ON -DSYSCONF_INSTALL_DIR:PATH=/usr/i686-w64-mingw32/sys-root/mingw/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/i686-w64-mingw32/sys-root/mingw/share -DCMAKE_INSTALL_PREFIX:PATH=/usr/i686-w64-mingw32/sys-root/mingw -DINCLUDE_INSTALL_DIR:PATH=/usr/i686-w64-mingw32/sys-root/mingw/include -DCMAKE_VERBOSE_MAKEFILE=ON -DFLTK_BUILD_SHARED_LIBS:BOOL=ON ..
```

**Operating System / Platform:**
 - OS: Fedora Rawhide

**Comment by MatthiasWM** [comment]
Since you are cross compiling on a Linux machine to WIN32, you are not using the FLUID version that comes with the checked out archive (since that is cross compiled as well), but instead the build system is picking up some other version of FLUID, probably a preinstalled FLUID 1.3.x . Fl_Terminal is new in 1.4, so FLUID 1.3 will not generate code for it. You should have seen a warning during your build phase.

**Comment by MatthiasWM** [comment]
Please let me know if that is the case and making sure a newer version of FLUID is used fixes the build. Thanks.

**Comment by MatthiasWM** [comment]
You could probably do this by setting the PATH in the shell. Something like this maybe:
```
cmake -B build/native .
cmake --build build/native --target fluid
export PATH=`pwd`/build/native/bin/:$PATH
cmake -B build/mingw ...flags_for_mingw... .
cmake --build build/mingw
```

**Comment by MatthiasWM** [comment]
Ok, my previous idea will probably not work because CMake searches for FLUID, and if 1.3 is installed on your system, it will use the full path to access it.

Excluding FLUID `-DFLTK_BUILD_FLUID=off` does not work. CMake will still find your old FLUID and use that.

So the easiest is probably to uninstall fltk 1.3 and install fltk 1.4 which will the provide the correct version of FLUID.

Or you could disable building test `-DFLTK_BUILD_TEST=off` . FLTK and FLUID do not require FLUID to be built. Their .fl files are prebuilt.

If you know CMake well, maybe you could add an `FLTK_EXTERNAL_FLUID` option that takes a full path to a working FLUID executable, overriding the CMake search result, and post that as a Pull Request ;-)

**Comment by Albrecht-S** [comment]
1. If a pre-built native 1.4 fluid executable exists when the cross-build is executed with CMake, then presetting the CMake variable `FLTK_FLUID_EXECUTABLE` to the path of the 1.4 fluid might work (I didn't test it).

@hobbes1069 Please try setting the variable on the CMake commandline like this:
```
cmake -DFLTK_FLUID_EXECUTABLE=/path/to/native-1.4/fluid
```
... and report if this helps.

2. After writing the first part I noticed that the build (reported by the OP) uses a toolchain file for cross-compiling as it should. This would be a good place to preset `FLTK_FLUID_EXECUTABLE` in this case.

Any feedback if one or both methods work would be appreciated. TIA.

**Comment by Albrecht-S** [comment]
PS: if none of the two solutions suggested by me above works I can look for a better solution.

Looking at @MatthiasWM's suggestion I **believe** that changing the PATH in a way that the native 1.4 fluid is found before the system one (1.3) should help as well. I can't see though why it didn't work for Matthias. Maybe because the shell caches the `fluid` command... (?)

**Comment by Albrecht-S** [comment]
@MatthiasWM wrote:
> If you know CMake well, maybe you could add an FLTK_EXTERNAL_FLUID option that takes a full path to a working FLUID executable, overriding the CMake search result, and post that as a Pull Request ;-)

See my comment above, the CMake cache variable `FLTK_FLUID_EXECUTABLE` should hopefully work in this case.

**_Addition (maybe the better working solution):_**

@hobbes1069 I took a quick look at the code and it looks as if the undocumented variable `FLTK_FLUID_HOST` would be the one to preset when cross-compiling. Please make sure that you run cmake with a new build folder (or empty CMake cache) to be sure it works as expected.

In my cross-build I have these variables set in the CMake cache and this works well:
```
fltk/master/build/mingw$ grep FLTK_FLUID CMakeCache.txt 
FLTK_FLUID_EXECUTABLE:STRING=fltk::fluid-cmd
FLTK_FLUID_HOST:FILEPATH=/usr/local/fltk/1.4-debug/bin/fluid  <<< this would be the key <<<
```

The only difference is that this was found automatically by my (very special) **PATH** settings which lets me assume that modifying the PATH as suggested by @MatthiasWM should also work.

**Comment by MatthiasWM** [comment]
Ah, I did not know about FLTK_FLUID_HOST . Thanks for finding that.

**Comment by Albrecht-S** [comment]
Yeah, it's an undocumented feature. Maybe we should document it...

**Comment by hobbes1069** [comment]
Thanks guys! Weekend is almost over but I'll try this out as soon as I can. 

FYI, my CMake is a bit rusty these days but when I developed the CMake config for Codec2 I used `if(CMAKE_CROSSCOMPILING)` or something like that do automatically detect this situation.

https://github.com/drowe67/codec2/blob/main/src/CMakeLists.txt#L65

**Comment by Albrecht-S** [comment]
> when I developed the CMake config for Codec2 I used if(CMAKE_CROSSCOMPILING) or something like that do automatically detect this situation.

@hobbes1069 Thanks for this hint, we are indeed using this in several places. Therefore we are consequently looking on a `fluid` executable on the build host (typically in the PATH) but in your case this finds the incompatible 1.3 fluid that is installed on the system and in the path. That's why it fails.

FWIW: we discussed a similar issue with the Debian maintainer of FLTK. In the next Debian Stable release "Trixie" there will be - at least initially - only one `fluid` package and this will have the **_1.4 version of fluid_** which can be used (with some warnings) for building FLTK 1.3 applications. As usual the new 1.4 fluid is mostly backwards compatible but the 1.3 fluid version can obviously not be used to "compile" 1.4 project files.

**Comment by hobbes1069** [comment]
Using `FLTK_FLUID_HOST` and pointing at the flud in the build directory for Linux worked!

**Comment by Albrecht-S** [comment]
> Now we should document this. ...

Done in commit 5af62bc565b3493c9cef2bd7e3cf3bb82a4d3209. Closing this issue now.
