### ISSUE TITLE
customize corner radius for rounded box/frame

### ISSUE THREAD

**Issue by bart9h** [fltk/fltk#130]
The (maximum) corner radius is hardcoded on src/fl_rounded_box.cxx line 27: `#define RS 15`.

I need to use 10 as the radius.

Can we make this variable, and add a function to customize this value?

If you tell me what the function name and location should be, I could implement this and make a pull request.

**Comment by Albrecht-S** [comment]
Thanks for reporting / asking this. It's an interesting question.

I'm not sure though how to implement such a feature. The current `RS` value is clearly a global parameter concerning all rounded **box types**, i.e. it's not per widget. If we changed just the global constant to a variable this would concern all widgets and their rounded boxes. I can imagine that someone would rather have the value per widget so some widgets would be able to have a larger corner radius and other (more constrained?) widgets could have a smaller corner radius, but I don't know.

What exactly is the reason why you want to reduce the max. corner radius?

**Comment by erco77** [comment]
We could do what we did with Fl::scrollbar_size() / scrollbar_size(); a global that can be overridden with a local per-widget local setting.

**Comment by bart9h** [comment]
> What exactly is the reason why you want to reduce the max. corner radius?

Just aesthetics.

I plan to customize the appearance of most of the widgets.
Some will need a custom draw() methods, but for others just tweaking the parameters could be enough.

**Comment by Albrecht-S** [comment]
Sorry, a closer look at the code showed that it wouldn't be sensible to make this per-widget settable. Even if we had a variable per widget (which would cost 1 or more bytes per widget, BTW) it wouldn't be straight-forward to implement it. The problem is that the box drawing code does not have a widget context. The only way I see to implement such a feature with per widget settings would be to set a global variable every time the box drawing code is called and (maybe) to reset it after the call. I would not suggest to do this.

But I think we could do it with a static method in the `Fl::` class as @erco77 mentioned. And while we're at it I propose to make the macro `BW` (box shadow width) also a global variable which could be used to draw other box types as well, for instance in function fl_oval_shadow_box() which uses a literal `3` for the shadow width. There are very likely more such "shadow with" instances in the code.

My (first) proposal:
- int Fl::box_shadow_width()
- void Fl::box_shadow_width(int)
- int Fl::max_box_border_radius() -- or Fl::box_border_radius_max() ?
- void Fl::max_box_border_radius(int) -- or (see above) ?

`max_box_border_radius()` is a very long method name but I didn't find a better one. Are there other suggestions?

Note: implementation with these simple static methods would be pretty simple. Proper documentation would likely be the most work to do.

**Comment by bart9h** [comment]
I like `max_box_border_radius()`.
It's descriptive, and not too lengthy.

**Comment by erco77** [comment]
+1 for `Fl::box_border_radius_max()`, the reason:
- If there are several `box_border_xxx()` related methods, In an alphabetical index they'd all be listed together
- I'm assuming we might have several of these, one for each constant a user might want to change

If it started with `max_box_border_xxx()` then it would just be near other methods that started with `max_xxx()`, perhaps that'd be less useful.

**Comment by Albrecht-S** [comment]
I agree with Greg's reasoning (that's why I proposed the 2nd name in the first place). We have now:
- Fl::box_shadow_width()
- Fl::box_border_radius_max()
with both getters and setters, as usual.

Thoughts regarding implementation:
- The definition of the variables should **not** be in file `src/fl_rounded_box.cxx` because this file should only be linked in (statically) if there's really a need for it, i.e. if one of these rounded boxtypes is used. I believe `src/fl_boxtype.cxx` would be a good place, but any sensible place where other static `Fl::` class members are defined would be fine as well (IMHO).
- The new variables should be applied wherever we're now using constants, macros and literals for the same aspects of box drawing code.
- Hopefully there are no significant differences in current code, for instance box shadow width == 4 in other box drawing functions.

Any takers?

**Comment by Albrecht-S** [comment]
Working on a solution...

**Comment by Albrecht-S** [comment]
Added methods as mentioned above, updated box types docs (image).

Thanks for all contributions.
