### ISSUE TITLE
Window still visible after hide().

### ISSUE THREAD

**Issue by bart9h** [fltk/fltk#134]
```
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
int main()
{
    Fl_Window *window = new Fl_Window(320,200);
    window->show();
    Fl::run();
    window->hide();
    puts("Window should be closed by now.");
    getchar();
}
```

The message shows right after pressing ESC to close the window.
But the window only actually disappears after I hit ENTER.

Probably not a bug, but something I'm doing wrong?

This happens with both the sable 1.3.5 version and the master branch.

**Comment by erco77** [comment]
On 2020-09-07 12:49, Rodolfo Borges wrote:
> |#include <FL/Fl.H> #include <FL/Fl_Window.H> int main() { Fl_Window *window = new Fl_Window(320,200); window->show(); Fl::run(); window->hide(); puts("Window should be closed by now."); getchar(); } |
>
> The message shows right after pressing ESC to close the window.
> But the window only actually disappears after I hit ENTER.
>
> Probably not a bug, but something I'm doing wrong?
>
> This happens with both the sable 1.3.5 version and the master branch.
>
    Try calling Fl::flush(); after hide(), to ensure the graphics hardware is flushed out.

    Assuming that works, you can probably comment out the window->hide() because
    it's probably redundant; hitting ESC in a window hide()s it already, which causes
    Fl::run() to return since no more windows are open.

    The need for Fl::flush() is necessary, because many operations in FLTK are just
    scheduled to happen (e.g. show() and hide()) but aren't actually reflected in graphics
    hardware until the next iteration of the application loop which actually updates the screen
    all at once.

**Comment by bart9h** [comment]
`Fl::flush()` worked.

Thanks a lot!

(Maybe add that to the `Fl_Window::hide()` documentation?
