### ISSUE TITLE
FL_Window_Type.cxx crashes

### ISSUE THREAD

**Issue by mjm2017** [fltk/fltk#14]
we need to change the code to the following 

// Convert A::B::C::D to D (i.e. keep only innermost name)
// This is useful for classes that contain a namespace component
static const char *trimclassname(const char *n) {
  const char *nn;
  if(n!='\0')
  while((nn = strstr(n, "::"))) {
    n = nn + 2;
  }
  return(n);
}

**Comment by Albrecht-S** [comment]
Thanks for the report, I can see what you mean. The crash would occur if `n` is null at entry of the function. Maybe this should never happen and the cause is somewhere else. If this is true then your fix wouldn't fix the cause but only cure symptoms.

That's why I'm asking: Can you provide a short but complete fluid (.fl) file that shows the crash?

Other than that I think the modification you suggest should read

- `if (n != 0)` ... or
- `if (n != NULL)` ... or simply
- `if (n)` ...

since we compare a pointer but that's kinda nitpicking. Just my 2 ct.

Since this is a fluid issue maybe @MatthiasWM can tell us more.

**Comment by Albrecht-S** [comment]
FTR: the commit mentioned above is **not related** to this issue.
