### ISSUE TITLE
fl_filename_absolute mishandles double-backslash on Windows

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#141]
Windows 10 / FLTK 1.4 / Built locally with Microsoft Visual Studio 2019

I've been having problems with fl_filename_absolute on Windows. Here is a sample:

```
    // verify our working directory is "e:/temp"
    char buff[100];
    char* cwd = fl_getcwd(buff, sizeof(buff));
    assert(!strcmp(cwd, "E:\\temp"));

    // this one works
    fl_filename_absolute(buff, sizeof(buff), "./log.txt");
    assert(!strcmp(buff, "E:/temp/log.txt"));

    // this one fails [result is "E:/temp/..\\log.txt"
    fl_filename_absolute(buff, sizeof(buff), ".\\log.txt");
    assert(!strcmp(buff, "E:/temp/log.txt"));    
```

Stepping into the fl_filename_absolute() call, I find that any invocation of `isdirsep` inside Fl_WinAPI_System_Driver.cxx is using the version of `isdirsep` in filename_absolute.cxx. The latter does not accept the double-backslash.

My fix was to declare each instance of `isdirsep` to be `static`. Then `Fl_WinAPI_System_Driver::filename_absolute` would use the correct version of `isdirsep`.

As of this writing, I have not yet tested the change on Linux.

**Comment by fire-eggs** [comment]
I have just confirmed that my change also fixes another problem I've been having:
```
    fl_filename_absolute(buff, sizeof(buff), "E:\\temp\\log\\log.txt");
    assert(!strcmp(buff, "E:\\temp\\log\\log.txt"));
```
Before my fix, the results would be: "E:/temp/E:\\temp\\log\\log.txt".

**Comment by Albrecht-S** [comment]
> My fix was to declare each instance of isdirsep to be static. Then Fl_WinAPI_System_Driver::filename_absolute would use the correct version of isdirsep.

Thanks for the report and the proposed fix. Can you please post your patch here as a `git diff` (or `diff -u`) file? TIA

**Comment by fire-eggs** [comment]
Please find below the two git diff files. I hope I've done it right - let me know if there are any questions/concerns.

I took the liberty of including the changes for both this issue (#141) and my next issue (#142). Added comments to clarify.

[Fl_WinAPI_System_Driver.txt](https://github.com/fltk/fltk/files/5248510/Fl_WinAPI_System_Driver.txt)
[filename_absolute.txt](https://github.com/fltk/fltk/files/5248511/filename_absolute.txt)

**Comment by fire-eggs** [comment]
Here's my test program.

(rename .txt to .cxx)
[AbsPath.txt](https://github.com/fltk/fltk/files/5248553/AbsPath.txt)

**Comment by erco77** [comment]
Hmm, I could swear I ran into this stuff once before in a bug report, and did a deep dive into the parsing of pathnames down deep into the linux system calls, and I think I went into the windows stuff too. Lemme sniff around, it might be in an unresolved STR or some such.. it wasn't that long ago.

**Comment by erco77** [comment]
Ah, here it is.. possibly related work here:
https://www.fltk.org/str.php?L3441

In this case I was working on the OPPOSITE function, fl_filename_relative(), which had similar issues.
Built a pretty good test suite at the time too, similar to your tests OP.
The basis of my work went down the linux realpath(3) rabbit hole. Looks like I /only/ addressed unix, and saw Windows as a whole other can of worms because of UNCs and drive maps (X:). I know I put a bit of work into that too, but not sure if I kept it.

**Comment by erco77** [comment]
Of interest, the realpath(1) function would do what this issue wants.
If you do something like (bash script here):

    cwd=`pwd`/"../your/relative/path"
    abspath=`realpath -m $cwd`

..the result is the proper "cleaned up" absolute path, with unncessary "." and ".."s removed.

In unix we have realpath(3), and under the Windows API there's the GetFullPathNameA() function.
So between those and some of the code I proposed in STR 3441, there might be a way to clean all this up.
Might be a lotta work, or might be a little. Either way a lot of testing is needed, cause there's a lot of side cases; in unix symlinks and multiple slashes, in windows uncs, drive maps, fronts vs backs, symlinks (MKLINK /?),  junctions, and lord knows what else.

Beware of dragons in the OS functions; in the case of linux, realpath(3) doesn't work with fictional pathnames, but realpath(1) can with the -m flag, so there's some smarts in there to avoid realpath(3), doing some pathname parsing itself.

**Comment by Albrecht-S** [comment]
> ... under the Windows API there's the GetFullPathNameA() function.

@erco77 Just commenting on this tiny part: please keep in mind that we need to use `GetFullPathNameW()`, i.e. the "wide character" version with path names converted from UTF-8 to "Windows wide chars" and vice versa. This applies to all other file handling functions as well.

@fire-eggs Thanks for the patches and the demo program.
> ... git diff files. I hope I've done it right ...

I believe the patches can be applied (didn't test though). Hint: if you edit directly in the Git working directory you can just run `git diff` or (if you want to restrict the diff to only certain files) `git diff -- <list of files or subdirs>`.

**Comment by fire-eggs** [comment]
My full test program also exercises the function using a network share, but I thought including it would complicate things.

An additional thought, since this topic has opened up further ... Any feeling about having `fl_absolute_filename` consistently return Unix-style path separators on Windows? Right now, the function may return a mix of path separators (depending on the input path).

**Comment by erco77** [comment]
Regarding returning unix style paths, either make it an option flag, or offer a separate method to change from one to the other. Some users might need the backslash version, as some windows browsers can't deal with frontslash paths.

**Comment by fire-eggs** [comment]
> Some users might need the backslash version, as some windows browsers can't deal with frontslash paths.

Then there's another bug, as the existing version consistently returns the current working directory portion of the output using Unix-style separators.

**Comment by erco77** [comment]
Not a bug, since the docs don't say one way or the other what style it returns.
However, I think the caller might want to choose.

My thinking is we could provide a flag that forces it one way or the other, and document that. Perhaps for backwards compatibility (where the style of paths in affects what is returned), it can be a three state flag, with the default being the current behavior, and the other two states being backs or fronts.

Trouble with that though is then ALL fltk functions dealing with paths should provide such an option, which might be bad/confusing.

So supplying a function that converts an input path to fronts or backs might be good. Though that's kind of trivial these days with the std::string stuff to just replace /'s with \\\\'s and vice versa.

In which case we could document the current behavior (possible mix of slash types), or force unix style. Not sure what the right call is in that case. Should probably choose one and document what it returns.

**Comment by Albrecht-S** [comment]
First thought: if it ain't broken, don't fix it. Did anybody complain? Well, that's only a first thought...

@erco77 wrote:
> Not a bug, since the docs don't say one way or the other what style it returns.

I agree.

>However, I think the caller might want to choose.

Why? Serious. I think there are two points:
1. Many of the Windows API functions allow both front and back slashes. If not, please correct me.
2. If this would have been an issue in the past we'd have seen more "complaints" by users.

I'm always for fixing bugs, and if it's possible, make code and behavior consistent. But if we don't know what the _correct behavior_ is, what can we do?

I think we should try to avoid inconsistencies (and bugs for sure) as far as possible but leave everything else as-is unless it's really easy to fix. I don't think that adding a user option to decide what behavior they want is not "really easy", particularly if this would have to be added to "ALL fltk functions dealing with paths" as you wrote above.

OTOH, if there's a volunteer and the API is simple and hopefully backwards compatible and (what else) ... I wouldn't object but I also wouldn't (be able to) contribute much.

**Comment by Albrecht-S** [comment]
Addition:
> So supplying a function that converts an input path to fronts or backs might be good.

That's simple, see for instance test/demo.cxx: fix_path() (only one direction). And if it's so simple users can do it themselves, don't they? But ...
:+1: if this helps to avoid a lot of work (with new bug potential) in FLTK and an additional option (API) to make it work.

**Comment by erco77** [comment]
> >     However, I think the caller might want to choose.
> Why? Serious. 

Sure; there's two main places in windows where front slashes don't work:

    In most DOS commands
    In Windows native file browsers

I actually run into this enough, that in my commercial application I provide the user with two 'Copy' options for popup menus on input and text widgets to provide copy/paste:

    Copy as front slashes
    Copy as back slashes

..This allows the user to take a highlighted path from execution logs, and copy/paste them into DOS windows as arguments to e.g. DIR and COPY commands and Windows file browsers. DOS tools only can handle backslashes because they use fronts as command line separators; e.g. COPY/XCOPY, MORE, TYPE, DIR, etc etc.

While the WIN32 API allows both, higher level software (DOS, native folder browsers) overloads fronts for other things, creating a conflict, and those situations might be relevant to an app's needs.

Arguably we should provide a way for fronts <-> backs for these and possibly other reasons, as users might not have std::string available (those embedded platforms that don't support STL/templates), and just because there's more than one possibility of return.

At very least we probably should /probably/ be consistent about what we return and document it, as returning  a mix of slashes would I think be unexpected.

**Comment by fire-eggs** [comment]
>If this would have been an issue in the past we'd have seen more "complaints" by users.

Digging into history, I see the slashes behavior is the same as FLTK 1.0. So yeah, if no-one has raised the question all this time, I'd say it's probably a non-issue IMO.

The original issue here (#141) was introduced in 1.4 during the "drivers" split. My next issue (#142) would technically belong in the "no one has complained up until now so it probably shouldn't be changed" category.

re: Unix style slashes not working with Native Windows File choosers

Interesting, I'll have to try that!

**Comment by erco77** [comment]
It's so trivial to replace fronts <-> backs that no one bothers to report it, but it probably gets through beta testing unnoticed, eventually a customer notices a problem, the programmer provides a way to normalize the paths and releases a fix.

Being undocumented, it's a pitfall waiting to happen. If we at least document it, it could save the programmer a fix cycle. 

Documenting might be as simple as "Under Microsoft Windows, slashes in the path returned may have fronts or backs or a mix of both, depending on circumstances", or we can force the slashes as fronts or backs (not sure which is best) and documenting that. We should probably be clear one way or the other.

**Comment by MatthiasWM** [comment]
I have pushed the changes for the default driver and the windows driver as they seem to make sense to me. I added a few remarks and also fixed the overflow. This was tested on MacOS and compiles on Windows.
