### ISSUE TITLE
fl_font(...) performance issue

### ISSUE THREAD

**Issue by w1hkj** [fltk/fltk#147]
I have need for a font browser that can selectively show all, fixed, or proportional fonts. To test for fixed vice proportional I am using the boolean (fl_width('.') == fl_width('W'), which requires that fl_font(font_nbr, font_size) be executed before the fl_width call.  My fresh Debian 20.x with LibreOffice and Gimp has >2500 fonts on the system.

This test program demonstrates the problem.:
// ================================
// font test program
// ================================

#include <iostream>
#include <string>
#include <time.h>
#include <sys/time.h>

#include <FL/Fl.H>
#include <FL/fl_draw.H>

int numfonts;

void find_fonts(int find_fixed, bool print)
{
	std::string fntname_old;
	std::string fntname;
	for (int i = 0; i < numfonts; i++) {
		fntname = Fl::get_font_name((Fl_Font)i);
		if (fntname_old == fntname) {
			if (print)
				std::cout << "DUPLICATE:    " << fntname << std::endl;
		} else {
			if (find_fixed > 0) {
				if (find_fixed == 2) {
					fl_font(i, 14);
					if (fl_width('.') == fl_width('W'))
						if (print)
							std::cout << "fixed:        " << fntname << std::endl;
					else
						if (print)
							std::cout << "proportional: " << fntname << std::endl;
				} else {
						if (print)
							std::cout << "font name:    " << fntname << std::endl;
				}
			} else {
				if (print)
					std::cout << "font name:    " << fntname << std::endl;
			}
		}
		fntname_old = fntname;
	}
}

int main (int argc, char *argv[]) {
	struct tm ztm, ltm;
	time_t t_temp;
	struct timeval now_val;
	char ztbuf[100];

	int print = 0;

	if (argc == 2 && std::string(argv[1]) == "-p") print = 1;

	numfonts = Fl::set_fonts(0);

	gettimeofday(&now_val, NULL);
	t_temp = (time_t)now_val.tv_sec;
	gmtime_r(&t_temp, &ztm);
	strftime(ztbuf, sizeof(ztbuf), "%H:%M:%S", &ztm);

	std::cout << numfonts << " fonts recognized" << std::endl;
	std::cout << "Start pass 0: " << ztbuf << std::endl;
	find_fonts(0, print);
	gettimeofday(&now_val, NULL);
	t_temp = (time_t)now_val.tv_sec;
	gmtime_r(&t_temp, &ztm);
	strftime(ztbuf, sizeof(ztbuf), "%H:%M:%S", &ztm);

	std::cout << "End Pass   0: " << ztbuf << std::endl;
	if (print) std::cout << std::endl;

	std::cout << "Start pass 1: " << ztbuf << std::endl;
	find_fonts(1, print);
	gettimeofday(&now_val, NULL);
	t_temp = (time_t)now_val.tv_sec;
	gmtime_r(&t_temp, &ztm);
	strftime(ztbuf, sizeof(ztbuf), "%H:%M:%S", &ztm);
	std::cout << "End Pass   1: " << ztbuf << std::endl;

	std::cout << "Start pass 2: " << ztbuf << std::endl;
	if (print) std::cout << std::endl;

	find_fonts(2, print);
	gettimeofday(&now_val, NULL);
	t_temp = (time_t)now_val.tv_sec;
	gmtime_r(&t_temp, &ztm);
	strftime(ztbuf, sizeof(ztbuf), "%H:%M:%S", &ztm);
	std::cout << "End Pass   2: " << ztbuf << std::endl;

	return 0;
}

Build with $ fltk-config --compile find_fonts.cxx
Running find_fonts produces:
$ ./find_fonts
2650 fonts recognized
Start pass 0: 19:11:56
End Pass   0: 19:11:56
Start pass 1: 19:11:56
End Pass   1: 19:11:56
Start pass 2: 19:11:56
End Pass   2: 19:12:19

Simply adding the fl_font(...) adds 23 seconds to the process.  This on a high end i5 processor.

Execute as "find_fonts -p" to print the font names and whether fixed or proportional.  The program also tags adjacent duplicate fonts.  That is probably a font data base issue.

fltk was built with libxft.

Any help would be appreciated.

Thank you.  David

**Comment by erco77** [comment]
I'm probably not gonna know this one, but it looks to me like you're loading each one of the 2650 fonts and doing stuff with them, e.g.
```
for (int i = 0; i < numfonts; i++) {           // all 2650 fonts
    fntname = Fl::get_font_name((Fl_Font)i);   // find the font
    ..
    fl_font(i, 14);                      // set it
    if (fl_width('.') == fl_width('W'))  // request a measurement of two glyphs
```
I guess I'm not surprised it takes a long time to cache that many truetype fonts into memory (all of them!), and access them the first time, as I imagine subsequent accesses (once they've all been loaded into memory) will be instantaneous, but it does take time (and memory!) to cache the _first time_ the application loads them. I imagine the memory use of this application (before it exits) is quite large, or perhaps it's loaded by a font daemon, I'm not sure. Try using top(1) and sort by memory use to see if the app or a font daemon is being stressed for memory while the app remains running (add a sleep(300) before exiting the program to keep it running so the caches don't dump on exit).

I imagine you wouldn't see this in gimp because in order to do the equivalent operation you'd have to pick each font manually and measure the relatively small amount of time between each font load, but added up would likely be equivalent.

In LibreOffice you might see the same thing if you create e.g. a word document that has a few characters from each of the 2600 fonts, then after a reboot, load that document and see how long it takes; I imagine load time would be similar.

**Comment by erco77** [comment]
If you're curious where the time is being eaten up, try turning on the profiler (see 'man -k profile') to track which function calls are using up all the CPU.. surely it's the low level font system calls, and that's just life with truetype fonts that contain not only ASCII glyphs, but UTF8 in all different languages as well..

This is probably not so much an 'issue' as a point of discussion better handled on the fltk.general group.

**Comment by w1hkj** [comment]
Font discovery is very fast.  That is what takes place on Run 0 and 1.  It is the execution of fl_font(nbr, size) that eats up the CPU.  You can see the same thing occur if you create a browser with each line either:

(1) snprintf(tempstr, sizeof(tempstr), "@F%d@S14%s", font_nbr, Fl::get_font_name(font_nbr));

or

(2) snprintf(tempstr, sizeof(tempstr), "@S14%s", Fl::get_font_name(font_nbr));

Fl_Browser lst_Font(....);

lst_Font.add(tempstr);

Case (1) takes about 23 seconds to populate all 2560 fonts.

Case (2) takes less than a second to populate all 2560 fonts.

David

**Comment by erco77** [comment]
Ya, I'm pretty sure font discovery would be fast because it's just loading the database of font names, which is probably just a walk through the /usr/share/X11 fonts directory to gather names, or perhaps there's a font daemon has that list pre-loaded.

fl_font() is surely the operation that involves actually loading the font, and pre-rendering all the glyphs at the size you request, as I think that has to be done in advance (turning all the TTF vectors/curves into pre-rendering pixels, if I understand how the font system works.. just guessing)

So a call to fl_font(somefont, 14) would I think tell the font system to load and pre-render that entire font's glyphs at the font size you specify, which would render out each glyph's vectors and curves into a pixel cache (just guessing), so that from then on, any rendering of that font will happen quickly. So that one fl_font() call is going to cause all that; high cpu and probably high memory too.

I guess I'm not sure if you're asking if that process can be optimized by FLTK? I'm not sure it can, as that load/pre-rendering process would all be handled by the font subsystem, and the only way around it would be, I think, to "schedule" pre-rendering of fonts on demand, rather than all at once, which would probably cause lots of hiccups each time a new glyph is rendered for the first time, causing sluggishness spread out over the app's execution time, rather than all up front. Or something like that.

**Comment by w1hkj** [comment]
Font discovery is very fast.  That is what takes place on Run 0 and 1.  It is the execution of fl_font(nbr, size) that eats up the CPU.  You can see the same thing occur if you create a browser with each line either:

(1) snprintf(tempstr, sizeof(tempstr), "@F%d@S14%s", font_nbr, Fl::get_font_name(font_nbr));

or

(2) snprintf(tempstr, sizeof(tempstr), "@S14%s", Fl::get_font_name(font_nbr));

Fl_Browser lst_Font(....);

lst_Font.add(tempstr);

Case (1) takes about 23 seconds to populate all 2560 fonts.

Case (2) takes less than a second to populate all 2560 fonts.

David

**Comment by w1hkj** [comment]
Resolved by moving the fixed/proportional test to a separate thread with Fl::awake(...) calls to function making UI changes to fl_font and the character width testing.
