### ISSUE TITLE
Please provide public fl_X11_open_display(Display* d) function

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#149]
In commit b8ab77e39c01b9019edaeaa09d5d08c7b21f75ab (by Albert Schlosser, Mon Feb 3 15:58:13 2020 +0100), the fl_open_display(Display*) function was eliminated.

I actually have a use case for it in VTK-FLTK bridge code (see github project vtkFLTK-V8.x-F1.4). Note certain VTK 8.x code calls a function SetDisplayId(Display* d), which in the bridge code for X11, called the (now eliminated) fl_open_display(d).

Note I am NOT requesting reinstatement of fl_open_display(Display*), rather addition of fl_X11_open_display(Display*) which would have the same functionality.

I have investigated FLTK 1.4's Fl_x.cxx and it uses static data items and functions like open_display_i(Display*) in particular, which as far as I can tell makes it nigh impossible (for me) to "extend" things cleanly from the outside of FLTK internals by adding my own externally-defined version of fl_X11_open_display().

Thanks!

**Comment by Albrecht-S** [comment]
Can you explain why you called this function and what you want to achieve? Please understand that I can't analyze the code of such a project like VTK-FLTK.

I imagine you want to set a particular display to be opened rather than the one FLTK would open automatically with fl_open_display() which is IIRC the one usually defined by the DISPLAY environment variable. Is this correct?

If this is true, what exact functionality should that new `fl_X11_open_display(Display*)` have? I believe it should give you the opportunity to call it before FLTK would call fl_open_display() in its initialization process, or something like that. Since this is all (almost) undocumented behavior, wouldn't it be better to introduce a method to **set** the (X11) display you want to be used and be done? FLTK would then open this display when it opens the display later anyway. Or something like that...

Or do you explicitly require to open the display when you call this method?

Trying to understand what you want/need to find the best solution...

**Comment by Albrecht-S** [comment]
Note: fixed typo s/oepn/open/.

**Comment by pdhahn** [comment]
It is not a matter of setting the DISPLAY environment variable before FLTK calls XOpenDisplay(). There is a call to XOpenDisplay() _in external library code beyond my control_. This call precedes my call in my BRIDGE code to fl_open_display(Display*). But since the referenced change to FLTK 1.4, fl_open_display() no longer accepts the Display pointer as an argument.

I looked at the "Operating System Issues/Changing the Display, Screen..." documentation. I considered setting the global `fl_display` variable directly with the display pointer returned by XOpenDisplay(). But the doco says "Don't attempt to change it!". Moreover, after looking at the code currently in 1.4's Fl_x.cxx, it looks like a lot of things FLTK does after its own internal call to XOpenDisplay() in open_display_platform() and open_display_i() would not get done if I simply set `fl_display`.

The issue for me is that external library code (VTK, a well known toolkit) has a method called SetDisplayId(Display* d), which _VTK calls after it has already done an XOpenDisplay() itself_. It passes the Display pointer from the latter into the former. The BRIDGE code however, overrides the SetDisplayId() method in a subclass of the VTK class. In that override, it is calling fl_open_display(Display* d) to pass the pointer into FLTK, so FLTK could do its thing with it.

Looking at the implementation of fl_open_display(Display*) in FLTK 1.3.5 (assuming that it approximates what the removed 1.4 version looked like), it appears that the code in it was refactored mostly into 1.4's open_display_i(Display*) function in Fl_x.cxx. The 1.4 fl_open_display(void) function now effectively calls open_display_platform() in Fl_x.cxx, which calls XOpenDisplay() (assuming fl_display is NULL) and then passes the display pointer to open_display_i() to initialize various FLTK internal variables, etc. etc.

So there is no way I see right now to pas in my own display pointer and have FLTK internals crunch it properly. That is the basis for my request.

**Comment by Albrecht-S** [comment]
Thanks for you long explanation. I think I got it, and my intention is to bring everything down to a short description of what you want to achieve or need. So, to summarize:

You want to pass an `X11 Display` structure `Display *d` which has already been established by external code calling `XOpenDisplay()` into FLTK in a way that FLTK uses this `Display` instead of calling `XOpenDisplay()` itself. However, FLTK should do all the stuff it would do anyway using the passed Display as if it had called `XOpenDisplay()` itself. OK.

The refactoring as it has been done in FLTK 1.4 has been done to separate platform specific code from cross platform code. I don't remember exactly why that particular commit you mentioned was done, but it seems that this had to do with this separation. The overloaded method would only be valid when compiling for an X11 platform.

That said, I'll look into it and see if/how this can be done. I'll let you know what I found out...

**Comment by pdhahn** [comment]
Yes, your summary accurately describes my request. Thanks!

**Comment by ManoloFLTK** [comment]
@pdhahn The commit mentioned above should do what you asked for, …3 years later…, in the form of a new public, documented, X11-specific function: `fl_x11_use_display(Display *)`. Please, close issue if you confirm.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks for taking this issue.

**Comment by pdhahn** [comment]
Thanks. Yes it has been a while. I think I wound up modifying the code on the VTK side of the bridge to get things to work back then.

I will close this for now with a view towards testing it with my bridge code after updating the latter to use the latest version of VTK (when time permits).

Perhaps in connection with the delay in this and some other issues, I wound up writing more FLTK widget code than I had originally planned in order to bypass using VTK pretty much altogether. Specifically, in the area of charts/plots. Even on the 3d side, I wound up porting qwtplot3d from Qt to FLTK, which again pretty much meant eliminating VTK from the scene (ha ha).
