### ISSUE TITLE
Incorrect rendering on Alpine Linux

### ISSUE THREAD

**Issue by slashdevslashurandom** [fltk/fltk#156]
OS: Alpine Linux 3.12 x86_64
FLTK Version: 1.3.5

It seems like the `fl_rect()` function, used to draw rectangles, misses the bottom right corner, at least when used on Alpine Linux. It can be seen on the screenshot below in the black area (where a white rectangle is drawn), and similar graphical bugs are visible on the buttons and other widgets (there's a gap in the bottom right corner of all buttons).

![image](https://user-images.githubusercontent.com/53902042/98665647-0489c300-235d-11eb-876f-1c211deebe77.png)

**Comment by ManoloFLTK** [comment]
On the X11 platform, fl_rect is nothing but a call to Xlib's XDrawRectangle function.
No such missing pixel is visible with Ubuntu :

![image](https://user-images.githubusercontent.com/41016272/98684736-d14c3180-2366-11eb-91af-464c5afe854c.png)

Can it be an issue of the Alpine Linux X server?

**Comment by erco77** [comment]
I can replicate the OP's issue on my old Sci Linux 7.7 system with e.g. fltk unit test rectangles in the first screenshot below, 'xmag' showing closeups of the two rectangle bot/right corners.

I expect it's an X11 problem, as I can replicate the issue with pure X code too (attached simple-rect.c code + screenshot of that app), taking FLTK completely out of the equation.

This machine also has had problems drawing "dotted lines" for the FLTK focus boxes as well, a problem long ago reported and dismissed as the X bug that it is.

Trouble is, it's an X bug that's hung around for several OS releases : /
For instance I think my Sci Linux 6.3 system had the problem too, IIRC. If so that'd be two major releases.

![xrect-problem](https://user-images.githubusercontent.com/6484779/98696251-68de5f80-2328-11eb-8235-1a46f2b9fd47.png)
![simple-rect-cu](https://user-images.githubusercontent.com/6484779/98698745-400b9980-232b-11eb-90ce-7d0468106fa8.png)
[simple-rect.zip](https://github.com/fltk/fltk/files/5518569/simple-rect.zip)

**Comment by erco77** [comment]
FWIW, here's the 'dotted line' focus box problem that's been long standing.
It's another, possibly related X11 bug.
I can't right away find the original bug report for this, but it's many years old I think.
![dotted-line-noise](https://user-images.githubusercontent.com/6484779/98700401-fde35780-232c-11eb-87c6-ca1b209370f9.png)

**Comment by slashdevslashurandom** [comment]
Weird... Alpine Linux ships with modern versions of X11 and other libraries, there's no reason for an old X11 bug to resurface :-(

**Comment by erco77** [comment]
It's probably not X11 itself, but a specific graphics hardware driver that has the bug.
What kind of graphics hardware are you on?

I'm on a Mac Mini with i915 kernel drivers for video and, I'm not really sure what Xorg is using, my Xorg.0.log file shows very generic drivers I think:

```
$ grep '[Dd]river' /var/log/Xorg.0.log | grep -v '[Ii]nput'
[   107.525] 	X.Org Video Driver: 24.0
[   107.542] (==) Matched modesetting as autoconfigured driver 0
[   107.542] (==) Matched fbdev as autoconfigured driver 1
[   107.542] (==) Matched vesa as autoconfigured driver 2
[   107.542] (==) Assigned the driver to the xf86ConfigLayout
[   107.542] (II) Loading /usr/lib64/xorg/modules/drivers/modesetting_drv.so
[   107.542] 	Module class: X.Org Video Driver
[   107.542] 	ABI class: X.Org Video Driver, version 24.0
[   107.542] (II) Loading /usr/lib64/xorg/modules/drivers/fbdev_drv.so
[   107.542] 	Module class: X.Org Video Driver
[   107.542] 	ABI class: X.Org Video Driver, version 24.0
[   107.542] (II) Loading /usr/lib64/xorg/modules/drivers/vesa_drv.so
[   107.542] 	Module class: X.Org Video Driver
[   107.542] 	ABI class: X.Org Video Driver, version 24.0
[   107.542] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   107.542] (II) FBDEV: driver for framebuffer: fbdev
[   107.542] (II) VESA: driver for VESA chipsets: vesa
[   107.605] 	ABI class: X.Org Video Driver, version 24.0
[   110.274] (II) modeset(0): [DRI2]   DRI driver: i965
[   110.274] (II) modeset(0): [DRI2]   VDPAU driver: i965

```

**Comment by Albrecht-S** [comment]
FTR: I also took a stab on it, and here is my take on it: [rect.cxx.txt](https://github.com/fltk/fltk/files/5520147/rect.cxx.txt).

@slashdevslashurandom: You wrote that you used FLTK 1.3.5, but some of the drawing issues may have been resolved in FLTK 1.4 already, particularly the box drawing code (buttons in your screenshot) which is (and was in 1.3.5 as well) a totally different drawing function (all horizontal and vertical lines are drawn independently, not by `XDrawRectangle()`). OTOH, as @ManoloFLTK wrote, fl_rect() uses `XDrawRectangle()` directly - however in FLTK 1.4 only for integral scaling factors. `fl_rect()` uses distinct lines for non-integral scaling factors.

@erco77: I could also replicate the issue with test/unittests but as a consequence of the above it went away when zooming with non-integral scaling factors. To rule out FLTK I also wrote a demo program that uses both `XDrawRectangle()` directly (in red color) besides FLTK's `fl_rect()` (black) for better comparison. The surprising thing is that there's no issue with any of the rectangles the program draws with scaling factor 1.0 on my system (Linux Mint 20.0, based on Ubuntu 20.04 LTS) - I'm really puzzled what's going on here. I added the scaling factor to the output window (rbox) but I have no idea what to do further to isolate the cause. Anyway, if anybody can shed some more light on this, please feel free to use my test program...

FWIW: The attached image shows both test/unittests and my demo program side by side, both with scaling factor 1.0 (100%).
![rect](https://user-images.githubusercontent.com/26235500/98735162-3cb3f480-23a3-11eb-9967-51f80433fea7.png)
You can see (or not see ;-) ) the missing pixels easily if you zoom the image appropriately.

PS: For convenience I added a `copy` button to copy the result to the clipboard, but this should be used with care. It uses `Fl_Copy_Surface` to draw the widget which may or may not be **exactly** the same as direct drawing on the screen.

**Comment by Albrecht-S** [comment]
A little break can sometimes be helpful... Now it's clear that setting `fl_line_style()` influences the outcome. I commented the statement
```
    // fl_line_style(FL_SOLID, 1);
```
at line no. 42 of my previously posted demo program out and the result is the missing pixel in both cases which explains a lot. Note that my demo calls
```
XDrawRectangle(fl_display, fl_window, fl_gc, x2, y2, w2-1, h2-1);
```
with the **same** `GC` (`fl_gc`) that FLTK uses and modifies by setting the line style or not. IIRC the default is line thickness `0` which **should** result in slightly better (or faster?) drawing results. Here it seems to be the opposite, i.e. worse results.

This may need some further tests, but it's a step forward. The questions remains though, what we should do about it...

**Comment by Albrecht-S** [comment]
Missing screenshot: 
![rect2](https://user-images.githubusercontent.com/26235500/98738236-afbf6a00-23a7-11eb-9b67-301460276554.png)

**Comment by Albrecht-S** [comment]
@erco77 and others: After finding the cause (see above) I tried Greg's simple-rect test program and I could confirm the findings (missing bottom/right pixel). Adding the equivalent statement to set the line width (and maybe more, I just copied it from FLTK sources and adjusted it for the demo) the rect's are correct. Here are my changes:
```
    G_mygc = XCreateGC(G_mydisplay, G_mywindow, 0, 0);
    XSetBackground(G_mydisplay, G_mygc, mybackground);
    XSetForeground(G_mydisplay, G_mygc, myforeground);

    // *ADDED* Set line attributes, particularly thickness = 1
    XSetLineAttributes(G_mydisplay, G_mygc, 1, LineSolid, CapButt, JoinMiter);
```
The last line `XSetLineAttributes(..)` is the key.

But again, finding the cause and applying the correct fix are two different things...

**Comment by erco77** [comment]
If I remember correctly from the previous bug report on this stuff, the 'fix' was to set the line width from the default (which IIRC is a single pixel width), but the non-default value could slow down default drawing speed, so it was recommended to not make changes that slowed down drawing to fix an X bug.
That was where it left off I think. I'm on the fence myself, as I run into this bug a lot on linux, enough that we should either work around in FLTK or suggest an X11 driver fix (e.g identify the buggy driver, and suggest an alternative)

**Comment by erco77** [comment]
OK, what I'm remembering was not reported as a bug, but as a conversation in fltkcoredev back in April/May 2018:

    Subject: RFC:  broken fl_line_style(FL_DOT) under Linux

Here's a link to the [fltk.coredev thread](https://groups.google.com/g/fltkcoredev/c/K8Pc0O-dCs0/m/CZ5rMRhmCQAJ) with various details to replicate and such.

**Comment by erco77** [comment]
The performance issue for the "fix" was pretty significant. Both Duncan and Oliver saw some really horrible performance when non-default values were used for the line style. Perhaps there's other ways to fix this (line caps?)
Albrecht, we should see if your XSetLineAttributes() mod is an improvement over the fixes we were trying in that older thread that caused bad performance issues with some drivers.
Perusing that old thread, there was an old X11 performance testing tool I'd come across called "x11perf" that exercised various drawing abilities of X11. There was also a [simple FLTK program](https://18223918759786972862.googlegroups.com/attach/6d49515fa2005/perf.cxx?part=0.1&view=1&vt=ANaJVrFBSG5u73elNoiEunKYFd3GyMlmvP8PFpNxHZPIbKOpNmxGjLH1Kep0UO_YY98jdUlbaC37lt8YmEIMim-XGkpK-nQ5jmus6oOnVtAqWpkt_1eGEFM) used for testing performance inside FLTK too.

**Comment by Albrecht-S** [comment]
> Albrecht, we should see if your XSetLineAttributes() mod is an improvement over the fixes we were trying in that older thread that caused bad performance issues with some drivers.

@erco77: That workaround (not really a fix) I wrote above is exactly the same as discussed in the thread you posted, although in a different context: the default line_width == 0 is obviously **fast, but buggy** with (a) dotted lines (that thread) and (b) rectangles (the topic here). BTW, I can also confirm the dotted line issue on my system.

**Comment by erco77** [comment]
Just curious; for all that can replicate, is there anything common about the graphics driver being used?

On my system i915 kernel driver, and with xorg, I'm not really sure which is the X11 driver being used to actually draw shapes. I guess I could pull the Xlib source, drill down through the XDrawRectangle() code and see if I can follow it down through the drivers to see where the problem is. I've never done down in there though, so I'm not sure if I'll be able to follow that trail or not.

**Comment by ManoloFLTK** [comment]
Here, with macOS XQuartz, rectangles are correctly drawn, with or without the
fl_line_style(FL_SOLID, 1) call.

Using https://tronche.com/gui/x/xlib/  (the Xlib Programming Manual in HTML format)
one can read what a conforming X server should produce:
- The XDrawRectangle() function draws the outlines of the specified rectangle as if a five-point PolyLine protocol request were specified for the rectangle: [x,y] [x+width,y] [x+width,y+height] [x,y+height] [x,y].
- The XDrawLines() function (which runs the PolyLine protocol) uses the components of the specified GC to draw npoints-1 lines …  The lines join correctly at all intermediate points, and if the first and last points coincide, the first and last lines also join correctly.
- Thin lines (zero line-width) are one-pixel-wide lines drawn using an unspecified, device-dependent algorithm. 
In general, drawing a thin line will be faster than drawing a wide line of width one. However, because of their different drawing algorithms, thin lines may not mix well aesthetically with wide lines. If it is desirable to obtain precise and uniform results across all displays, a client should always use a line-width of one rather than a line-width of zero. 

Therefore, the missing pixel in the XDrawRectangle output is clearly a bug in the X driver or server.
But, should the last item be understood as a suggestion to set width 1 as default line width
for maximal portability of FLTK?

**Comment by slashdevslashurandom** [comment]
So I've done some more testing.

If I change the X11 video driver on my machine from `modesetting` to `intel`, then everything renders fine. The rectangles and buttons have their corners in order. (Though an unrelated bug with OpenGL stuff appears that has nothing to do with FLTK.)

`lspci` says the video card is "Intel Corporation UHD Graphics 630 (Desktop 9 Series)". (It's a freshly installed work machine, so I don't know a lot about it.)

**Comment by Albrecht-S** [comment]
> Just curious; for all that can replicate, is there anything common about the graphics driver being used?

As written before, my system is Linux Mint 20.0, based on Ubuntu 20.04 LTS.
`lspci` says: `VGA compatible controller: Intel Corporation UHD Graphics 620 (Whiskey Lake)`.
Xorg.0.log says:
```
X.Org X Server 1.20.8
X Protocol Version 11, Revision 0
[     5.454] Build Operating System: Linux 4.15.0-115-generic x86_64 Ubuntu
...
[     5.471] (==) Matched modesetting as autoconfigured driver 0
[     5.471] (==) Matched fbdev as autoconfigured driver 1
[     5.471] (==) Matched vesa as autoconfigured driver 2
[     5.471] (==) Assigned the driver to the xf86ConfigLayout
[     5.471] (II) LoadModule: "modesetting"
[     5.471] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[     5.472] (II) Module modesetting: vendor="X.Org Foundation"
[     5.472]    compiled for 1.20.8, module version = 1.20.8
[     5.472]    Module class: X.Org Video Driver
[     5.472]    ABI class: X.Org Video Driver, version 24.1
[     5.472] (II) LoadModule: "fbdev"
...
```
uname says: `5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020`
and the next kernel 5.4.0-53 is about to be installed.

So it seems I have the "modesetting X.Org driver" installed which is the original "X.Org Foundation" driver and seems to exhibit the issues we're talking about. The Linux Mint `Driver Manager` does not offer any other drivers for my system: "Your computer does not need any additional drivers". I don't know if I can install another "Intel" driver for my system and how I would do that.

**Comment by slashdevslashurandom** [comment]
In my case, I just had to install the "xf86-video-intel" package, but it'll probably have a somewhat different name in Mint's repositories.

**Comment by Albrecht-S** [comment]
@ManoloFLTK wrote:
> Therefore, the missing pixel in the XDrawRectangle output is clearly a bug in the X driver or server.
But, should the last item be understood as a suggestion to set width 1 as default line width for maximal portability of FLTK?

Some thoughts:
1. I agree (90%) that the missing pixel in XDrawRectangle() could be considered a bug. Setting line width to 1 or 0 **should not matter** in this case. OTOH the docs state that line width 0 can lead to inconsistent drawing (the remaining 10%).
2. The "dotted line issue" could be considered "inconsistent drawing" and hence not a bug as such. It's documented that such things can happen.
3. Regarding "_set width 1 as default line width for maximal portability of FLTK_": I tend to agree, but the obvious performance degradation found in the thread mentioned by Greg lets me hesitate to agree entirely.

Further thoughts: Although the drawing performance can be massively degraded we should consider different application types. Some applications may need a clear user interface and are not drawing lots of things very often. If it's a mostly "static" UI nobody would notice "slow" drawing and people would potentially prefer correct drawing over fast drawing. OTOH, if the user interface is more interactive (moving things around etc.) users might notice the degraded drawing performance. The last type of applications would be games and such where drawing speed is essential.

That said, I think we might want to let the user (developer) choose what they want [1], if possible. Since the issues and the related performance degradation are hardware/driver dependent (and may be fixed in future xorg versions) we should implement a function that could be called at application startup or even during runtime by the app developer to enable or disable "thin or wide lines" (default line width = 0 or 1) at runtime. If the app developer decided to add a user option to tune that setting, even the end user could switch it on or off for optimal adaption to the hardware/driver installed on the end user's system.

Another option we have for FLTK is to enable wide lines explicitly for such critical things we know of like dotted lines for the focus box and `fl_rect()` and switch back to the state before that drawing function afterwards. Last but not least we could combine the user's selection with this option.

[1] This choice seems similar to Fl_Double_Window vs. Fl_Window. In my commercial apps we chose Fl_Double_Window to avoid flicker vs. potential faster drawing with Fl_Window.

**Comment by erco77** [comment]
@manolo thanks for the pointer to the x11 docs; i ran into [something similar](https://www.x.org/releases/current/doc/xorg-server/Xserver-spec.html) trying to figure out what "mi" stood for (machine independent). Regarding the line width from 0 to 1, i think we found in that[ 2018 fltk.coredev thread](https://groups.google.com/g/fltkcoredev/c/K8Pc0O-dCs0/m/CZ5rMRhmCQAJ) that really negatively affected drawing speed/performance, so it's probably best we don't just trivially change the default of 0.. there's a lot of good info in that thread.

@slashdevslashurandom thanks for changing the driver from `modesetting` to `intel`. Sounds like that might be the thing to look into next for the actual problem. I'll try to look into that tomorrow. My goal would be to report an actual bug if possible to the xorg folks.

@Albrecht-S perhaps try what the op recommends (if you dare to mess with your graphics drivers) by installing the intel drivers tp replace the "modesetting" default. 'modesetting' is an odd name for a driver, but I guess it's a default, and does seem to be common to all who've encountered these issues, even from the 2018 thread iirc. Seems like that could be the culprit to investigate an actual solution/xorg bug report.

**Comment by Albrecht-S** [comment]
@slashdevslashurandom, @erco77 Thanks for the suggestions and the "xf86-video-intel" package name. I assume this is a package name to be installed by `apt` or `apt-get`. This package name does not exist on my Mint system and I looked around for similar names including `intel`, `xfree`, `xorg`, `xserver` etc. but I could not find anything related.

@erco77: Looking forward to your results (and potential advice) trying to switch drivers. If you could really report a but to the xorg folks that would be awesome. TIA

**Comment by Albrecht-S** [comment]
> 'modesetting' is an odd name for a driver

I believe it's related to "kernel mode setting", a feature added to the kernel to remove display settings from the display drivers or something like that. I guess that's why this driver is called "modesetting", but this can also be totally wrong. Even if that's true it's still an odd name.

**Comment by erco77** [comment]
@slashdevslashurandom: before you go, can you attach your new vs. old X log file as a .zip file here?

Since you solved it without changing hardware, I'd like to see what other drivers changed by comparing your old vs new logs, in case it's not just the modesetting driver, but possibly other drivers that changed too.

The X server logs are usually in /var/log/ and have the capital letter "X" in them.

My system uses Xorg's server, new vs. old logs are named /var/log/Xorg.*.log, where "*" are numbers, low numbers being most recent.

**Comment by erco77** [comment]
@Albrecht-S - I believe the approach to hand tweaking the autoconfiguring X server is to create files in /etc/X11/xorg.conf.d using padded numbered filenames like "##-whatever.conf", where ## is e.g. 10, 20, 30, etc. I take it Xorg will run these in alphanumeric order (similar to the old init.d boot script stuff). To force certain kernel modules to load involves using e.g. the Modules command IIRC (will have to re-read up on the xorg.conf file format, but that's what it used to be. There's also special ordering of commands in 'stanzas' for keyboard, mouse, video, etc) I haven't started experimenting yet.

Intel used to provide X11 configure scripts that would detect the graphics hardware and use the correct modules, modifying your xorg.conf file. But they stopped because the autoconfig stuff seemed to be stable, and they now recommend consulting the distribution installation instructions instead of providing those older configuration tools.

**Comment by Albrecht-S** [comment]
@erco77 Thanks for your X11 config hints. There's no `/etc/X11/xorg.conf.d` on my Mint system, but there is `/usr/share/X11/xorg.conf.d`. I didn't find any graphics driver related stuff in this directory though. I'm not going to pursue this driver stuff for my own system though, I'd rather try to find a way to work around the issue with the existing drivers. Unfortunately I've been busy with other stuff today, I'll try to continue my research tomorrow.

**Comment by erco77** [comment]
@Albrecht-S You won't likely find much of anything Intel related in the xorg.conf.d because X usually autoconfigures everything on the fly.

If there's any intel stuff for the X server, the place to look I think would be in the directory hierarchy:

    /usr/lib64/xorg/modules/

Regarding the xorg.conf.d, I take it what happens is when you create files there, they'll override the X autoconfig settings, so for instance to experiment you'd create e.g. "50-Albrecht-Tests.conf" in that directory and add modules/mode settings and whatever else there, forcing it to use specific drivers you name.

How you determine those names I'm not exactly sure, as there's special drivers/settings for 3D, acceleration and whatnot. Used to be you'd look at what Video devices are detected from the boot log/dmesg/lspci/glxinfo/xrandr/hwinfo/etc and then load the kernel modules with modprobe (or configure them on boot), and separately tweak the xorg.conf to load the X specific modules.

On my system the `hwinfo` command helped clearly identify the correct kernel driver for my VGA controller, which I'm pretty sure is correct:
```
  14: PCI 02.0: 0300 VGA compatible controller (VGA)
    [..]
    Hardware Class: graphics card
    Model: "Intel Haswell-ULT Integrated Graphics Controller"
    Vendor: pci 0x8086 "Intel Corporation"
    Device: pci 0x0a2e "Haswell-ULT Integrated Graphics Controller"
    SubVendor: pci 0x106b "Apple Inc."
    SubDevice: pci 0x0141 
    Revision: 0x09
    Driver: "i915"
    Driver Modules: "i915"
    Memory Range: 0xa0000000-0xa03fffff (rw,non-prefetchable)
    [..]
  Driver Info #0:
    Driver Status: i915 is active                        <-- i915 driver
    Driver Activation Cmd: "modprobe i915"    <-- recommended modprobe command to install driver
    Config Status: cfg=new, avail=yes, need=no, active=unknown
     [..]
```
What I don't know is which xorg driver is appropriate, or perhaps better appropriate than what xorg loads by default, which I believe is currently:
```
$ grep \\.so$ /var/log/Xorg.0.log
[   299.463] (II) Loading /usr/lib64/xorg/modules/extensions/libglx.so
[   299.464] (II) Loading /usr/lib64/xorg/modules/drivers/modesetting_drv.so
[   299.465] (II) Loading /usr/lib64/xorg/modules/drivers/fbdev_drv.so
[   299.465] (II) Loading /usr/lib64/xorg/modules/drivers/vesa_drv.so
[   299.528] (II) Loading /usr/lib64/xorg/modules/libfbdevhw.so
[   299.528] (II) Loading /usr/lib64/xorg/modules/libglamoregl.so
[   300.432] (II) Loading /usr/lib64/xorg/modules/libfb.so
[   300.924] (II) Loading /usr/lib64/xorg/modules/input/evdev_drv.so
```
I don't think any of that is intel specific. Looking in that directory hierarchy, I do see an "intel_drv.so" and a "radeon_drv.so" that might be relevant to me, as radeon shows up in my `hwinfo` and `lsmod` reports. How those fit into my xorg.conf I'm not sure, need to research that. For sure I have the latest video intel drivers installed (based on `yum search intel`, and installing the drivers it shows)

**Comment by Albrecht-S** [comment]
Just to add some data points from my system:
**hwinfo:**
```
35: PCI 02.0: 0300 VGA compatible controller (VGA)
  [..]
  Hardware Class: graphics card
  Device Name: "Onboard - Video"
  Model: "Intel UHD Graphics 620 (Whiskey Lake)"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x3ea0 "UHD Graphics 620 (Whiskey Lake)"
  SubVendor: pci 0x1025 "Acer Incorporated [ALI]"
  SubDevice: pci 0x1305 
  Driver: "i915"
  Driver Modules: "i915"
  [..]
  Module Alias: "pci:v00008086d00003EA0sv00001025sd00001305bc03sc00i00"
  Driver Info #0:
    Driver Status: i915 is active
    Driver Activation Cmd: "modprobe i915"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
```
**Other commands:**
```
# grep \\.so$ /var/log/Xorg.0.log
[     5.465] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[     5.471] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[     5.472] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[     5.473] (II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[     5.496] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[     5.497] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[     5.623] (II) Loading /usr/lib/xorg/modules/libfb.so
[     5.756] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so

# ls -1 /usr/lib/xorg/modules/drivers/
amdgpu_drv.so
ati_drv.so
fbdev_drv.so
intel_drv.so
modesetting_drv.so
nouveau_drv.so
qxl_drv.so
radeon_drv.so
vesa_drv.so
vmware_drv.so
```
So it seems clear that `modesetting_drv.so` is actually in use and `intel_drv.so` is available. But how can I find out if that particular `intel_drv.so` would work for my system? I'm not keen on "killing" my system by installing the wrong graphics driver...

**Comment by erco77** [comment]
I'll be curious to see OP's X logs, before and after, as requested above, to see what new drivers got things working for him.

> I'm not keen on "killing" my system by installing the wrong graphics driver...

If the machine is critical, then yeah, I wouldn't experiment.

I keep two workstations active, both mac minis; one is always my 'old' machine, and the other my "current" machine with the "latest OS". If anything freaks with the new machine, I can safely fall back to the old one until it's fixed. Allows me to experiment with my window manager (hot rodded flwm) which I've been using forever.

**Comment by slashdevslashurandom** [comment]
Here are my Xorg.0.log files from the two attempts

[Xorg.log.intel.txt, the one where fltk displays normally](https://github.com/fltk/fltk/files/5529508/Xorg.log.intel.txt)
[Xorg.log.modeset.txt, the buggy one](https://github.com/fltk/fltk/files/5529511/Xorg.log.modeset.txt)

**Comment by erco77** [comment]
@slashdevslashurandom That's great, much thanks.

So comparing the list of .so's loaded:
![xdiff-so](https://user-images.githubusercontent.com/6484779/98957867-84777080-24b6-11eb-9814-0c1c554dc4ff.png)
Looks like the 'bad' (left) loaded "glamoregl" and "fb" drivers, but not intel.
Looks like the 'good' (right) loaded the intel_drv and didn't bother with "glamoregl" and "fb" drivers.

Comparing the two xorg log files, the bits noteworthy to me are these:
![xdiff-xorg-log](https://user-images.githubusercontent.com/6484779/98958345-08315d00-24b7-11eb-87dc-f924dcfa4790.png)

In the "bad" log, autoconfigure recognized intel drivers were needed, but couldn't find any, due to this error:

    `Failed to load module "intel" (module does not exist)"`

So apparently the modesetting driver kicked in (all those lines starting with "modeset") and initialized everything itself via the kernel driver, and loading the fb and glamor modules.

In the "good" log it /did/ find "intel_drv.so" and loaded it, causing it to handle initializing all the mode settings (all those lines starting with "intel(0)") and skipped loading the "glamoregl" and "fb" drivers, I assume because the intel drivers handled it.

This should give me some hints as to what I can do to replicate, as just installing the intel drivers for me didn't cause X's autoconfig to automatically detect and load them, though I think maybe it should, since my graphics hardware is all intel. So perhaps I can force it to load the intel drivers early in the X init, to see if that gives it a hint.

**Comment by erco77** [comment]
Working with a recommendation from Albrecht, I was able to confirm solving the missing pixel AND the dotted focus box problem by creating a new file called `/etc/X11/xorg.conf.d/00-erco.conf` and just put these four lines into it:
```
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
EndSection
```
This forces the X window manager to use load and use the `intel_drv.so` driver in `/usr/lib64/xorg/modules/drivers/intel_drv.so` (which it wasn't using by default autoconfigure), and like the OP's logs show, this causes X's autoconfig no longer bother loading the drivers `modesetting, fb, glamoregl`.

**Comment by erco77** [comment]
Would like to suggest this as a possible fix.
```
--- a/src/Fl_Graphics_Driver.cxx
+++ b/src/Fl_Graphics_Driver.cxx
@@ -71,9 +71,9 @@ void Fl_Graphics_Driver::text_extents(const char*t, int nChars, int& dx, int& dy
 /** see fl_focus_rect() */
 void Fl_Graphics_Driver::focus_rect(int x, int y, int w, int h)
 {
-  line_style(FL_DOT);
+  line_style(FL_DOT, 1);
   rect(x, y, w, h);
-  line_style(FL_SOLID);
+  line_style(FL_SOLID, 0);
 }
```

**Comment by Albrecht-S** [comment]
@erco77 Good idea, but IMHO wrong place. This is graphics driver stuff and as such your proposal would affect both the macOS and X11 (Xlib) drivers (Windows already has its own virtual method `Fl_GDI_Graphics_Driver::focus_rect(int x, int y, int w, int h)` in `src/drivers/GDI/Fl_GDI_Graphics_Driver_rect.cxx` around line 60).

We should "fix" this issue in the Xlib driver which doesn't have its own implementation yet rather than in the default (base class) driver. Hence the better solution would likely be to add somewhere in `src/drivers/Xlib/Fl_Xlib_Graphics_Driver_rect.cxx` (or another file?):
```
/** see fl_focus_rect() */
void Fl_Xlib_Graphics_Driver::focus_rect(int x, int y, int w, int h)
{
  line_style(FL_DOT, 1);
  rect(x, y, w, h);
  line_style(FL_SOLID, 0);
}
```

Note: untested but seems plausible (would likely need a declaration in Fl_Xlib_Graphics_Driver.H as well).

If we look at the Windows implementation we can see that this is also a platform specific workaround - the comment says:
```
  // Windows 95/98/ME do not implement the dotted line style, so draw
  // every other pixel around the focus area...
```

So why not do something similar for Xlib (even if it's not necessary with **all** X11 implementations).

**Comment by Albrecht-S** [comment]
I'm uploading a diff with another proposal that should only affect the Xlib driver and seems to work in a few tests. See [focus_rect_xlib.diff.txt](https://github.com/fltk/fltk/files/5745668/focus_rect_xlib.diff.txt). Needs more tests though (it's just a proof of concept right now).

Note: this patch fixes only the focus box issue (irregular dots), not the rectangle drawing itself.

**Comment by Albrecht-S** [comment]
See also: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1221
