### ISSUE TITLE
Meson build system

### ISSUE THREAD

**Issue by vit1251** [fltk/fltk#16]
Hello, how about using meson build system?

**Comment by Albrecht-S** [comment]
Our main build system is CMake since FLTK 1.4.0 (not yet released). We're still in the transition to make everything work with CMake while still supporting autoconf/configure/make systems.

I have no idea why we should consider yet another build system. Can you give some advantages of meson (other than personal preferences)? Personally I believe that the fact that meson uses Python3 is not an advantage but a drawback (particularly under Windows) but that's more a gut feeling - I don't have python installed under Windows.

FWIW: meson is obviously [maintained on GitHub](https://github.com/mesonbuild/meson) and is similar to CMake in that it generates build systems rather than building itself (like make).
Homepage: http://mesonbuild.com/

**Comment by Albrecht-S** [comment]
One more note: I looked at the meson docs and found this: 

> At the time of writing the Ninja backend is more mature than the VS backend so you might want to use it for serious work.
http://mesonbuild.com/Using-with-Visual-Studio.html

We definitely need to provide a way users can build with Visual Studio (for serious work).

Also, the backend selection seems to be somewhat behind CMake: `backend {ninja, vs,
vs2010, vs2015, vs2017, xcode}`. 
http://mesonbuild.com/Builtin-options.html#universal-options
Hmm, no 'make' build system? Personally I know and like (and prefer) ninja, but...

Other than that, I also found some **interesting** aspects but I'm still looking into it...

**Comment by Albrecht-S** [comment]
I don't think that meson fits our requirements and it would be an additional burden we can't accept for our small team. Maybe later (in several years or so), but certainly not right now or in the near future.

I'll close this issue in a few days unless there are some really appealing comments why we should consider meson (in comparison with CMake of course).

Thanks for the suggestion anyway, very much appreciated.

**Comment by vit1251** [comment]
@Albrecht-S thanks for your deep research. I review meson and find a very well feature like subprojects it have a biggest potencial to embedding source code (like FLTK) as subproject in source distribution solution (or version depending). But I use meson only under Linux platform and as you already noted I meet problems when try use meson under Windows 10 when compile with Visual Studio.

**Comment by Albrecht-S** [comment]
Welcome, and thanks for your further comment. I tried meson with a tiny own project and it seemed to work (also using Linux), but all I can see from its development seems to indicate that it's a very young and agile project, but maybe not yet mature. Let's see what the future will show.

Closing this issue. Will not fix (yet), maybe later.
