### ISSUE TITLE
Can't build checkers.cxx on Windows 10 with cmake and gnu c/c++

### ISSUE THREAD

**Issue by ceanwang** [fltk/fltk#161]
Hi,

When 'make', I got this message:

`[ 75%] Generating checkers_pieces.cxx, checkers_pieces.h
'..' is not recognized as an internal or external command,
operable program or batch file.
make[2]: *** [test/CMakeFiles/checkers.dir/build.make:63: test/checkers_pieces.cxx] Error 1`

Windows doesn't support running an exe file (Here is fluid.exe) with relative path, so this line in test\Makefile is not working under Windows.
`checkers_pieces.cxx:	checkers_pieces.fl ../fluid/fluid$(EXEEXT)
`

The content of test/CMakeFiles/checkers.dir/build.make:63 is:
`	cd D:/00master/fltk/build_win10/test && ../bin/fluid.exe -c D:/00master/fltk/test/checkers_pieces.fl`
It means first change to D:/00master/fltk/build_win10/test folder, then run ../bin/fluid.exe, but this is not working under Windows. After change ../bin/fluid.exe into D:/00master/fltk/build_win10/bin/fluid.exe, then it worked.

Is there a way copy that fluid.exe into the build/test folder first, then make the tests?

Regards,

Cean

**Comment by Albrecht-S** [comment]
Hi Cean, thank you for your report. I'm not sure if this is really a FLTK issue or a build system or setup problem. Please help to find out by providing more information about your build system and the way you were setting it up (running CMake?).

Please provide the system/platform, the build system (MinGW, MSYS2, CMake + their versions), compiler (gcc, clang), compiler version.

I assume you were using CMake to set up the build. It's important to know which CMake "Generator" and what kind/version of MinGW, MinGW-w64, MSYS2 you're using. Whether you were using the "MSYS Makefiles" or "MinGW Makefiles" (or even "Unix Makefiles") generator can make a big difference.

It's also important to know in which environment (shell) you're running `make`. If you're using for instance "MSYS Makefiles" you should run `make` always in a `MSYS` window, not in a standard "DOS" (aka "Command Prompt") window. According to the error message you posted I assume you're using one of the MinGW/MSYS generators and running `make` in a standard "DOS Window" which would explain the error message you posted. I tried it myself:
```
C:\Users\albrecht\git\fltk\build\vs2019>../msys/bin/fluid
'..' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ceanwang** [comment]
I am using Windows 10 + cmake 3.15.6 +  MinGW-w64 (It is gnu c/c++ 8.1.0 From https://sourceforge.net/projects/mingw-w64/ ). The "Generator"  is "Unix Makefile" and done in a standard "DOS".
After specifying the absolute path to fluid.exe, all the tests compiled and work perfectly.

**Comment by Albrecht-S** [comment]
@ceanwang Thanks for replying with your build info. What you try is not going to work. If you use the "**Unix Makefile**" generator then you **must** also use a **POSIX shell** to build, i.e. you must use one of the MinGW/MSYS "Terminals" your MinGW-w64 installation provides.

> After specifying the absolute path to fluid.exe, all the tests compiled and work perfectly.
In my case, maybe build fltk first, install fltk (put fluid.exe into WIndow's PATH) and then build tests.

Even if it worked now for you it's (a) unnecessary work and (b) error prone because the next build or the next CMake version can change things. You should either run the build in an MSYS (POSIX) shell (MinGW terminal) or use the "MinGW Makefiles" generator. I'm not sure if the latter really works in a DOS shell but I'm sure that using the **MinGW terminal** will work with **either** "`MSYS Makefiles`" **or** "`Unix Makefiles`" generator, resp.

**Comment by ceanwang** [comment]
It doesn't matter whick cmake version you use, but how you write your Cmakelists.txt file.
I am hoping the Cmakelists.txt file in the root folder or the one in the tests folder could consider this situation.
The one in tests folder could try not to run exe file with relative path for Windows. If it not achievable, then the root one may have separate targets: build fltk, install and build tests.

**Comment by Albrecht-S** [comment]
@ceanwang Sorry, but you are wrong. The FLTK `test/CMakeLists.txt` file does not use '../' in any way. The code you're seeing that uses the relative directory is generated by CMake. And since you're using the "`Unix Makefiles`" generator you're implicitly saying that you want to build with a Unix (POSIX) environment that allows `'../'` relative directory syntax.

As a proof, here's the relevant code that runs the fluid executable from `CMake/FLTK-Functions.cmake`:
```
      add_custom_command(
        OUTPUT "${basename}.cxx" "${basename}.h"
        COMMAND fluid -c ${CMAKE_CURRENT_SOURCE_DIR}/${src}
        DEPENDS ${src}
        MAIN_DEPENDENCY ${src}
      )
```
The key is the line `COMMAND fluid -c ${CMAKE_CURRENT_SOURCE_DIR}/${src}` which invokes the **CMake target** `fluid` to generate the `.cxx` and `.h` files from the `.fl` file. As you can clearly see there's no '../' in this cmake file (the code is in a macro). The execution code is definitely generated by CMake.

As I wrote before, please use a MinGW or MSYS terminal which should be available in your install. Here's a screenshot from my Windows 10 system:

![MinGW-terminal](https://user-images.githubusercontent.com/26235500/100022184-06369a80-2de3-11eb-88f6-7e66953b47c8.png)

I clicked on the icon labeled 'M2' (which stands for MSYS2) and you see the popup from which I selected `Mingw-w64 64 bit` to do the build in my environment (64 bit Windows) and this works flawlessly. You can be sure that I tested this! However, the menus may be different, depending how you installed the MinGW-w64 environment.

**Comment by ceanwang** [comment]
There is no MinGW terminal from my installation. Not using it is also my preference.

In root Cmakelists.txt, it says # build examples - these have to be built after fluid is built/imported
and in camke/FLTKConfig.cmake.in, it seems try to find where it is.
`if (CMAKE_CROSSCOMPILING)
  find_file(FLUID_PATH
    NAMES fluid fluid.exe
    PATHS ENV PATH
    NO_CMAKE_FIND_ROOT_PATH
  )
`

These tests comes with the core, I am just try to run it.

**Comment by Albrecht-S** [comment]
Sorry again, you're picking random code from the CMake files that really, really has nothing to do with the problem at hand.

If you really want to run the build from a DOS window my best guess is that you'd have to use the "MinGW Makefiles" generator which (IIRC) uses more Windows'ish syntax like backslash (`\`) as a directory separator. But to be sure I'd have to test that first, and I'm not going to do this soon...

I pointed you at two options (even if you couldn't find the MinGW/MSYS terminal) but you resist on using a combination that **DOES NOT WORK**. And this is, as I also pointed out, not FLTK's fault because the code in question is generated by CMake, using the "**Unix** Makefiles" generator as directed by you. Please try to do what I told you, otherwise I'm afraid I can't help you further.

**Comment by Albrecht-S** [comment]
OK, one more hint for now: I just ran `C:\msys64\mingw64.exe` which opens a terminal window. In that window I changed directory to the build directory which was generated using the "MinGW Makefiles" generator. In this directory I ran:
```
mingw32-make -j3
```
which built FLTK w/o errors. HTH.

I also tried to run this in a DOS window but this didn't work. I can't help you further with running the build from a DOS window.

**Comment by ceanwang** [comment]
I only interested in running from a DOS window. So far so good, fltk and part of its own test programs could be build out of box. With little tweak, the left over test programs also built. fltk did a very good job. I raise the issue in the hope it could do more. You can tell cmake to generate unix make file, you could also tell it you are on Windows in the CMakefiles.txt. I don't know where it could be achieved, so I can only randomly check where the possible is. 
I understand your suggestion, but it is not the way I want to go. If I could run a  program in a DOS shell, why should I bothered to installed another shell? The compiler I installed doesn't have a mingw64.exe program, sure I can't find it. I checked the link I posted in early reply, and found out it is different than I remembered.  It looks like I don't know how to install it now. The complier I use more is actually from here http://www.equation.com/servlet/equation.cmd?fa=fortran Also no shell provided, just a compiler.

**Comment by ceanwang** [comment]
Tried build without any change to get FLTK and fluid.exe first and copied it to a folder which is in Windows PATH. The newly built FLTK is not needed.

Then, at the beginning of CMake/export.cmake, in the NOT CMAKE_CROSSCOMPILING section, I added WIN32 check, put the original part in to else () like this:
```
else()

   if(WIN32)
       message(STATUS "WIN32 NOT CMAKE_CROSSCOMPILING")
       find_file(FLUID_PATH
          NAMES fluid.exe
          PATHS ENV PATH
          NO_CMAKE_FIND_ROOT_PATH
       )
       add_executable(fluid IMPORTED)
       set(FLTK_FLUID_EXECUTABLE ${FLUID_PATH})
       set(FLUID)       # no export
       set_target_properties(fluid
          PROPERTIES IMPORTED_LOCATION ${FLUID_PATH}
       )

   else()
       message(STATUS "NOT CMAKE_CROSSCOMPILING")
       add_subdirectory(fluid)
       set(FLTK_FLUID_EXECUTABLE fluid)
       set(FLUID fluid) # export
   endif(WIN32)
endif(CMAKE_CROSSCOMPILING)
```

It can build FLTK and its tests.

Maybe just build fluid.exe in its folder and install it, then build FLTK to avoid build twice as above steps.

**Comment by Albrecht-S** [comment]
Hi @ceanwang, I took another stab at your problem and I found a very simple way to build FLTK in a "DOS window" as you requested. I'll post instructions and a log in my next comment.

It seems like you found a way to build FLTK as you liked, but regarding your description and proposed changes above: this is not useful for FLTK and it might break other builds or it's more complicated than necessary or ...

Anyway, please see my instructions in the next reply for the **correct** (and working) way to build FLTK in a DOS window with existing CMake files. I hope this helps.

**Comment by Albrecht-S** [comment]
**_How to build FLTK in a "DOS window"_**

Basically there are only four commands required after you open a new DOS window:
1. set the PATH as required by your installed build system (if not yet done)
2. cd to the build directory
3. run cmake
4. build

In my example I'm using `cmake --build .` (note the trailing `.`) but you could also run `make` directly. Here are the commands I used:
```
set PATH=C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\msys64\mingw64\bin;C:\Windows\system32;C:\Windows;
cd C:\Users\albrecht\git\fltk\build\mingw-makefiles
cmake -G "MinGW Makefiles" ../..
cmake --build .
```

I used the "minimal" PATH necessary for my build system (the "Git" part is actually not necessary here) and you may need to adjust this for your system. This `PATH` ensures that all necessary programs can be found by CMake.

My build system is based on MSYS2/MinGW but if your compiler and other build tools are properly installed this should work for you as well. Note also that it's essential to use `-G "MinGW Makefiles"` to get the proper commands for the DOS shell.

FYI, this is the `fluid` command in my Makefile to build the `tabs` demo which requires `fluid`. As you can see it uses `'\'` directory separators to make sure it works in a DOS shell:
```
cd /d C:\Users\albrecht\git\fltk\build\mingw-makefiles\test && ..\bin\fluid.exe -c C:/Users/albrecht/git/fltk/test/tabs.fl
```
I'm attaching a full log for your reference: 
[fltk-in-dos-window.txt](https://github.com/fltk/fltk/files/5788864/fltk-in-dos-window.txt)

**Comment by ceanwang** [comment]
In your example, '/' and '\' are mixed: front part uses '\' and back part uses '/'.  DOS terminal does support both. The problem is in the middle '..\bin\fluid.exe' which is not recognized. Fluid.exe must be in Windows PATH. Can't see you put it into the PATH, but system found it, don't know why.

Use "Unix Makefile" and get  '..\bin\fluid.exe' is quite understandable, because supposed to follow Unix style. I was wondering why use "MinGW Makefile" get the same result? Cmake knows it will be run under DOS terminal. Maybe this a cmake problem.

For fltk, I think it's better to build fluid first.

**Comment by Albrecht-S** [comment]
Yes, in the example '/' and '\' are mixed, but in a way that works even in a DOS shell. Note that `..\bin\fluid.exe` **is correct** even in a DOS shell. That's why I always told you to use "MinGW Makefiles" rather than "Unix Makefiles".

**Please read your first post again and compare**:
> Windows doesn't support running an exe file (Here is fluid.exe) with relative path, so this line in test\Makefile is not working under Windows.
checkers_pieces.cxx: checkers_pieces.fl ../fluid/fluid$(EXEEXT)

This is only true if you're using forward slashes (`/`) in the command but it definitely works if you are using the Windows convention with backslashes (`\`). And again, that's why you need to use **"MinGW Makefiles"**.

The proof is that it worked in my test in a DOS window. See the log I attached to my previous message.

**Comment by ceanwang** [comment]
Didn't notice there is difference between ..\bin\fluid.exe and ../bin/fluid.exe under DOS. When I tried to use MinGW generator, the complying still stopped at checker test code, but is a different error now. Before is ../bin/fluid.exe not recognizable. Now is:
```
[ 69%] Generating checkers_pieces.cxx, checkers_pieces.h
make[2]: *** [test\CMakeFiles\checkers.dir\build.make:81: test/checkers_pieces.cxx] Error -1073741511
make[1]: *** [CMakeFiles\Makefile2:1293: test/CMakeFiles/checkers.dir/all] Error 2
make: *** [Makefile:148: all] Error 2
```
Line 81 of test\CMakeFiles\checkers.dir\build.make is:
`	cd /d D:\00master\fltk-org\build_MinGW\test && ..\bin\fluid.exe -c D:/00master/fltk-org/test/checkers_pieces.fl
`
I tried to run it in DOS terminal and has no error.

Need to figured it out.

**Comment by ceanwang** [comment]
The problem for using MinGW generator is that  I can get it compiled but the newly compiled exe can't be run in a DOS terminal. So I still have to go back to use Unix generator.
![zdlpvy](https://user-images.githubusercontent.com/4224442/104110515-8d58b700-532c-11eb-82cc-fc7d075998f1.jpg)

**Comment by Albrecht-S** [comment]
I'm glad I could help, and thanks for the final feedback.
