### ISSUE TITLE
Improve Xrender scaling quality

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#163]
The current scaling quality of images by Xrender is poor.
It could be improved considerably by using the bilinear filter Xrender supports. Bilinear resizing is the default in FLTK's image drawing routines when Xrender is not used, so using it also with Xrender would be appropriate. It's only a one-liner:

[xrender_bilinear_patch.txt](https://github.com/fltk/fltk/files/5583740/xrender_bilinear_patch.txt)

Here's a test program to compare the difference to the current Xrender scaling:
[xrender_bilinear_test.tar.gz](https://github.com/fltk/fltk/files/5583758/xrender_bilinear_test.tar.gz)
(Assumes the patch is active and it is executed from the test folder)

Example output:
![xrender_bilinear_test](https://user-images.githubusercontent.com/9895976/99976318-98b74980-2da3-11eb-97bc-94fe8796ce42.png)

**Comment by ManoloFLTK** [comment]
That seems a great suggestion.

Looking for function XRenderSetPictureFilter, I have found that note :
 "When you use a filter you'll probably want to use PictOpOver as the render op, regardless of whether the source picture has an alpha channel or not, since the edges may end up having alpha values after the filter has been applied."
at https://www.talisman.org/~erlkonig/misc/x11-composite-tutorial/

Do you think we should change that call too
   XRenderComposite(fl_display, (has_alpha ? PictOpOver : PictOpSrc), src, None, dst, srcx, srcy, 0, 0,
                   XP, YP, WP, HP);
if we use FilterBilinear ?

**Comment by wcout** [comment]
Yes, it seems the thin evidence out there suggests this...

So you mean something like that?

```diff
index 2dc9a76aa..2952977f2 100644
--- a/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
+++ b/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_image.cxx
@@ -805,6 +805,7 @@ int Fl_Xlib_Graphics_Driver::scale_and_render_pixmap(Fl_Offscreen pixmap, int de
   if (clipr)
     XRenderSetPictureClipRegion(fl_display, dst, clipr);
   unscale_clip(r);
+  bool smooth = false;
   if (scale_x != 1 || scale_y != 1) {
     XTransform mat = {{
       { XDoubleToFixed( scale_x ), XDoubleToFixed( 0 ),       XDoubleToFixed( 0 ) },
@@ -812,8 +813,10 @@ int Fl_Xlib_Graphics_Driver::scale_and_render_pixmap(Fl_Offscreen pixmap, int de
       { XDoubleToFixed( 0 ),       XDoubleToFixed( 0 ),       XDoubleToFixed( 1 ) }
     }};
     XRenderSetPictureTransform(fl_display, src, &mat);
+    smooth = Fl_Image::scaling_algorithm() != FL_RGB_SCALING_NEAREST;
+    XRenderSetPictureFilter(fl_display, src, smooth ? FilterBilinear : FilterNearest, 0, 0);
   }
-  XRenderComposite(fl_display, (has_alpha ? PictOpOver : PictOpSrc), src, None, dst, srcx, srcy, 0, 0,
+  XRenderComposite(fl_display, ((has_alpha || smooth) ? PictOpOver : PictOpSrc), src, None, dst, srcx, srcy, 0, 0,
                    XP, YP, WP, HP);
   XRenderFreePicture(fl_display, src);
   XRenderFreePicture(fl_display, dst);
```

**Comment by ManoloFLTK** [comment]
A change that calls XRenderSetPictureFilter() is now in the git repository.

Since   https://www.x.org/releases/current/doc/renderproto/renderproto.txt
does not mention that FilterBilinear requires PictOpOver, and since an experiment
with a few pictures shows that the rendering seems correct without change in the
XRenderComposite call, I have just kept trace of this note in a comment.
