### ISSUE TITLE
Provide easier instructions for modern CMake

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#164]
Hello
I noticed there was some changes in the cmake readme. For more modern cmake (later than 3.14 which was released on March 2019, and we're currently at version 3.19), the easiest way to create a cmake project is to use the FetchContent module:

```cmake
cmake_minimum_required(VERSION 3.14)
project(app)

include(FetchContent)

set(FLTK_BUILD_TEST OFF CACHE BOOL " " FORCE)
if(UNIX AND NOT APPLE) 
    set(OPTION_USE_PANGO ON CACHE BOOL " " FORCE)
endif()

FetchContent_Declare(FLTK
    GIT_REPOSITORY https://github.com/fltk/fltk
)
FetchContent_MakeAvailable(FLTK)

if(WIN32)
    set(GUI_TYPE WIN32)
elseif(APPLE)
    set(GUI_TYPE MACOSX_BUNDLE)
else()
    set(GUI_TYPE)
endif()

add_executable(main ${GUI_TYPE} main.cpp)
target_include_directories(main PRIVATE ${fltk_SOURCE_DIR} ${fltk_BINARY_DIR}) # needed for visual studio
target_link_libraries(main PRIVATE fltk) # if needed: fltk_gl fltk_images fltk_png fltk_jpeg fltk_z 

if(APPLE)
    target_link_libraries(main PRIVATE "-framework Cocoa") # need for Darwin
endif()
```
The above should work for Windows, MacOS and Linux.
FetchContent can work with git(along with git tags) and urls. The module made available via FetchContent exposes several variables beginning with the module name in lowercase (a cmake quirk).
This can be built using:
```
cmake -Bbin && cmake --build bin --parallel
```
Creating a static library using fltk will require adding more to the target_link_libraries depending on the platform.

**Comment by Albrecht-S** [comment]
Thanks for these fine instructions. I'll see if I can include these or similar instructions in the docs.

FWIW, some comments: as I wrote elsewhere you can use `WIN32` and `MACOSX_BUNDLE` on all platforms because it's a documented feature that these keywords are ignored on "other" platforms than they are intended to be for.

> target_include_directories(main PRIVATE ${fltk_SOURCE_DIR} ${fltk_BINARY_DIR}) # needed for visual studio

This is required on all platforms (not only visual studio) **if and only if** you use FLTK directly from its build directory because `FL/abi-version.h` is created (by CMake) in the build tree whereas all other header files must be included from the source tree. OTOH you need only one (the FLTK install) directory if FLTK was installed in a known target location.

For maximum safety [1] I suggest to reverse the two directories like this:

`target_include_directories(main PRIVATE ${fltk_BINARY_DIR} ${fltk_SOURCE_DIR})`

Note also that these instructions are best suited if you want to build only one application that uses FLTK, hence it is useful to download/pull/build FLTK together with this single app. In other scenarios it might be more sensible to download and build FLTK separately (and optionally install it in a well-known location) as a prerequisite to building more than one application.

Question: as you seem to know CMake's `FetchContent` module better than I do (I never found the time to study/test it): would it be possible to have more than one application using the same build directory so that downloading and building FLTK would be done only once even if you run several independent application builds? With all FetchContent directories _pointing at the same place_ like symbolic links?

Notes:
[1] If it ever happens that "someone" runs a build in the source directory (maybe with `configure/make`), then `FL/abi-version.h` would be _generated in the source directory_ with potentially different build options. The correct order of include directories (build directory first) makes sure the correct header file is found.

**Comment by MoAlyousef** [comment]
Thanks for the insights. I agree having an installed fltk will likely be better if one’s using fltk regularly for different applications. 

Normally FetchContent_MakeAvailable would also call add_subdirectory(${fltk_SOURCE_DIR} ${fltk_BUNARY_DIR}) according to the cmake docs. And it does work correctly except for the VS generator. 

I actually haven’t tried FetchContent with a local file:/// url. it could work so it’s worth investigating, that would be cool. However a fetched module is for a single CMakeLists BINARY_DIR, so to reuse it one can use multiple add_executable calls, or would have to separate into different projects.

**Comment by Albrecht-S** [comment]
> Normally FetchContent_MakeAvailable would also call add_subdirectory(${fltk_SOURCE_DIR} ${fltk_BUNARY_DIR}) according to the cmake docs. And it does work correctly except for the VS generator.

Thanks for your clarifications and help. However, I don't understand what your statement above is intended to say. What does 'add_subdirectory(..)` have to do with the `target_include_directories(..)` statement where you had the VS-specific comment? Or was there a typo in this text? Puzzled...

[ The point that you need both include directories is that you have two separate header directories in the CMake build and need to include both directories to the header search list in your project to find the header files in both FL/ directories. This has IMHO nothing to do with the way how FetchContent works - it's also necessary w/o FetchContent. ]

**Comment by MoAlyousef** [comment]
From the cmake docs, FetchContent_MakeAvailable is just syntactic sugar for:

```

FetchContent_GetProperties(googletest)
if(NOT googletest_POPULATED)
  FetchContent_Populate(googletest)
  add_subdirectory(${googletest_SOURCE_DIR} ${googletest_BINARY_DIR})
endif()

```

**Comment by Albrecht-S** [comment]
> If you try the camkelists in without the target_include_directories line it would work with ninja and make, ...

Are you really sure that would work? I doubt it - but it's too late here to test. I'll try this though unless you beat me with it... ;-)

One reason it might have worked at any time would be that you ran make in the root directory and thus created FL/abi-version.h which later made the build work "magically". That's the only reason I can imagine why you **thought** it worked with these generators. Or something like that...

**Comment by MoAlyousef** [comment]
That may be so. I’ll try it on a clean docker instance tomorrow and report back.

**Comment by Albrecht-S** [comment]
Well, I tried it myself and for me it didn't work w/o specifying both include dirs. I only tested under Linux, but with both `make` and `ninja` (both failed). Everything worked fine with the include dirs. I also removed the `GUI_TYPE` variable and set both GUI attributes in the `add_executable()` statement. The resultant (shorter) file is then (with `hello.cxx` as source file):
```
cmake_minimum_required(VERSION 3.14)
project(app)

include(FetchContent)

set(FLTK_BUILD_TEST OFF CACHE BOOL " " FORCE)
if(UNIX AND NOT APPLE) 
    set(OPTION_USE_PANGO ON CACHE BOOL " " FORCE)
endif()

FetchContent_Declare(FLTK
    GIT_REPOSITORY https://github.com/fltk/fltk
)
FetchContent_MakeAvailable(FLTK)

add_executable(main WIN32 MACOSX_BUNDLE hello.cxx)
target_include_directories(main PRIVATE ${fltk_BINARY_DIR} ${fltk_SOURCE_DIR})
target_link_libraries(main PRIVATE fltk) # if needed: fltk_gl fltk_images fltk_png fltk_jpeg fltk_z 

if(APPLE)
    target_link_libraries(main PRIVATE "-framework Cocoa") # need for Darwin
endif()
```

**Comment by MoAlyousef** [comment]
ehm I stand corrected.
Anyways I prefer your shorter version.

**Comment by Albrecht-S** [comment]
Thanks for your confirmation. As I wrote before I intend to put these instructions into the FLTK documentation about building FLTK and FLTK applications. Thanks you very much for these insights.

**Comment by Albrecht-S** [comment]
I updated README.CMake.txt to include a CMake example using FetchContent in commit eb759cb118fbf09da51938c04978e609822dbb48.

There will be more updates when FLTK uses "more modern CMake", but this commit is enough to close this issue.
