### ISSUE TITLE
fl_scroll / fl_can_do_alpha_blending no longer exported by shared library

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#186]
The FLTK 1.4.x shared image is not exporting fl_scroll [fl_scroll_area.cxx]. This is a regression from 1.3.5.

This was using the weekly release FLTK 1.4 20210205

[Full google group conversation](https://groups.google.com/u/1/g/fltkgeneral/c/T5yLtncAT-M)

The attached program [rename to cxx from txt] shows the issue. If linked against 1.4.x static library, 1.3.5 static library, or 1.3.5 shared library, it links correctly. If linked against the 1.4.x shared library, the following error:

test_vscroll.cxx:(.text+0x1dd): undefined reference to `fl_scroll(int, int, int, int, int, int, void (*)(void*, int, int, int, int), void*)'

Comparing readelf / nm output between the 1.4 static/shared libraries, fl_scroll is indeed not global in the shared library. [Full details in the google group conversation].

[test_vscroll.txt](https://github.com/fltk/fltk/files/5966933/test_vscroll.txt)

**Comment by fire-eggs** [comment]
Diffing the nm output between 1.3.5 and 1.4.x (20210205) I find one other symbol which went from global (1.3.5) to local(1.4). And that is:

fl_can_do_alpha_blending

**Comment by erco77** [comment]
Thanks -- weird, we probably need to run the ABI checker again, something we normally do before a release.

Not assigning this to myself, just trying to do a little sleuthing for whoever does.

Taking these one at a time, 'fl_can_do_alpha_blending' was changed in Mar 2016 by d4768073fa67e7; apparently it was a regular exported function that became an unexported inline during the implementation of non-rectangular windows for the Window Driver code by this diff:

```
-/* note: doxygen comment here to avoid triplication in os-speciic files */
-FL_EXPORT char fl_can_do_alpha_blending();
+inline char fl_can_do_alpha_blending() {return Fl_Display_Device::display_device()->driver()->can_do_alpha_blending();}
```
This is probably OK because inline's evaluate at compile time.

However, fl_scroll() changing its export status is strange.
AFAICT the function prototype in fl_draw.H and function signature in fl_scroll_area.cxx are both unchanged since 2002 and 1998 respectively.

**Comment by erco77** [comment]
OK, I think the problem with fl_scroll() is the absence of these lines from the top of `src/fl_scroll_area.cxx` during the port to the new driver interface:

```
#include <config.h>
#include <FL/Fl.H>
#include <FL/fl_draw.H>
```

**So OP, try applying the attached [patch](https://github.com/fltk/fltk/files/5967786/patch.txt) to 1.4.x and report back?**

Without these lines, or at very least the include for fl_draw.H, I think fl_scroll() won't be exported properly, perhaps due to this new code in `FL/Fl_Export.H`:

```
#  elif __GNUC__ >= 4
#    define FL_EXPORT __attribute__ ((visibility ("default")))    <-- THIS
```
..which affects the `FL_EXPORT` declaration in `fl_draw.H` on newer GNU compilers.

I'd like to suggest dynamic export procedures be added to the CMP in a new section, e.g. "DYNAMIC EXPORTING", outlining requirements for properly declaring variables/functions/classes for dynamic export on a per-platform basis, either in the CMP itself, or at least a pointer to the correct platform specific developer documentation so the current 'proper' technique for exporting be known to all devs. Windows of course has its `__declspec(dllexport)` details as well.

**Comment by erco77** [comment]
@ManoloFLTK might want to weigh in on this patch, as this change appears to have started with commit d292de92ef6b99.

Perhaps only the `#include` for` fl_draw.H` is needed. I just wasn't sure what our `Fl_Export.H` mechanics depends on. I imagine `config.h` may have been included previously because `fl_scroll_area.cxx` had platform specific code that needed it, and now does not.

**Comment by Albrecht-S** [comment]
Note: there is a platform abstraction in `FL/Fl_Export.H` that should always work so developers don't **need** to know the details for every day development [1]. However, the requirement to `#include <FL/Fl_Export.H>` (directly or indirectly) should be noted, otherwise FL_EXPORT may not work as expected (which seems to be the case here looking at your analysis). Good work, BTW. :+1: 

I don't think that config.h should be included. The macros `Fl_Export.H` depends upon (`FL_DLL` and `FL_LIBRARY`) must be supplied by the build system which is done in the Makefiles or CMake rules or user code.

It's documented that the **user** needs to define `FL_DLL` if they want to
1. build their code with Visual Studio and
2. link with a shared library (DLL) under Windows.

There's no such need for user code on other compiler/platform combos AFAICT.

 [1] i.e. unless someone wants to add another platform or compiler etc.

**Comment by fire-eggs** [comment]
Modifying fl_scroll_area.cxx to `#include <FL/fl_draw.H>` was sufficient to solve the issue. After doing so, `fl_scroll` was now global and the test program linked successfully.

While I was at it, I threw in a reference to `fl_can_do_alpha_blending` into the test code and there was no issue.

**Comment by Albrecht-S** [comment]
Fixed in Git.
@fire-eggs, @erco77 Thanks for the report and your support.

**Comment by erco77** [comment]
I reckon that'll close this then; I figure if Manolo has any additional comments, he can reopen.

**Comment by fire-eggs** [comment]
Glad to help!
Kevin
