### ISSUE TITLE
Fl_Shared_Image Improvements

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#188]
During the discussion of issue #185 "Shared Image reload() loses inital dimensions" I looked closer at the code of Fl_Shared_Image and came to the conclusion that this code is still "FLTK 1.3 style" and could potentially be improved by utilizing the new FLTK 1.4 `Fl_Image::scale(w, h)` feature which sets a new image drawing size w/o touching the original data size. This was at least one reason why Fl_Shared_Image existed in the first place: Fl_Shared_Image::get(name, w, h) would try to find the image and, if not found directly in the requested size, it would **copy** the original image, scaling the resultant image to the requested size (from the original image).

See also this comment: https://github.com/fltk/fltk/issues/185#issuecomment-777763402 and maybe later comments on that issue.

I'm not sure yet if it's feasible to rewrite / modify Fl_Shared_Image but it's worth an investigation. It could save some valuable program memory if images don't need to be copied anymore but the API would be kept so no code changes are necessary.

I filed this issue primarily so this idea is not forgotten.

**Comment by Albrecht-S** [comment]
**Important notice**: there's a potential inconsistency (bug?) in the current code of `Fl_Shared_Image::get()` and `Fl_Shared_Image::find()`:

The images are sorted by (name, w, h) and in pre-1.4 code `w()` and `h()` could not be changed for an existing `Fl_Shared_Image` object. In FLTK 1.4 `Fl_Image::scale(w, h)` **does** change `w()` and `h()` and thus the binary search in `Fl_Shared_Image::find()` could fail unless the images in the shared image list are reordered (sorted) after such changes.

I believe this is a potential bug in FLTK 1.4 current (independent of the enhancement mentioned above) and this should be investigated as well. I'm setting the "bug" label as well for this.

There is also the [old STR 3410](https://www.fltk.org/str.php?L3410) _"Fl_Shared_Image:find() doesn't find some existing images"_ which is related and should be fixed (and maybe backported to FLTK 1.3.6?).

**Comment by ManoloFLTK** [comment]
I believe the inconsistency noticed above to be fixed with commit a4866ff.

I propose a fix for the remaining issue, to remove the old-style aspect of class Fl_Shared_Image
in branch 1.4 (see attached shared_image_patch.txt) :

The fix modifies member function Fl_Shared_Image::get(const char *name, int W, int H).

Test program test/pixmap_browser.cxx is slightly modified to exercize the fix: a small
copy of the main image is added to the GUI. That makes two Fl_Shared_Image objects
that have identical underlying image (image_ member), identical data_w() and data_h()
but differ by their drawing size (w() and h()). The image file is read only once and the
image cache is computed only once with the full size of the image file. That cached form of the
image is used by two scale-and-draw operations when drawing the window.

Opinions?

[shared_image_patch.txt](https://github.com/fltk/fltk/files/6142221/shared_image_patch.txt)

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks for the patch, I'll look into it ...

**Comment by ManoloFLTK** [comment]
I still support [shared_image_patch.txt](https://github.com/fltk/fltk/files/6142221/shared_image_patch.txt) .

**Comment by Albrecht-S** [comment]
@ManoloFLTK I'll look into your patch later, when I have more time. My gut feeling is that we should not (or even **must not**) use scale() on Fl_Shared_Images internally to create a new image size. We should rather keep the "old" code consistently using copy() because that's what old user code would expect. One (and likely the most important) reason is that scale() might destroy the correct order of Fl_Shared_Images in the internal image table, or not, or ... maybe something else, I'm not sure. As I wrote, it's a gut feeling (say: "educated guess") only. But maybe I'm wrong, who knows. I need to check my thoughts and to verify the code.

**Comment by MatthiasWM** [comment]
Ok, so please correct me if I am wrong. The whole idea behind shared image is the ability to have one original image that is then available as *copies* in multiple scales (`Fl_Shared_Image::get(name, w, h)`, `...::copy(w, h)`). This is quite different form using `Fl_Shared_Image::scale(w, h)`, which does *not* create a copy but instead instructs the image to *draw* at a resolution than the actual data.

The first issue seems to be a simple bug in the binary search that assumes that the original image is at a certain position vs. copy-scaled ones. I am confident I can fix that.

The second issue to me is the easily confused difference between a copy-scaled image and a draw-scaled image. I think, Manolo's patch is ok here, but the reason for all this is really hard to explain, IMHO.

I have additional concerns about the rationale behind `Fl_Shared_Image::desaturate()` and `...::color_average()`, but I won't dive deeper into this here because I would like to get the fix for the first two out for 1.3.9 .

**Comment by Albrecht-S** [comment]
@MatthiasWM I doubt that Fl_Shared_Image should be modified to use the new (virtual) Fl_Image::scale() method. One simple reason is that we can have Fl_Shared_Image's in several resolutions besides the original (w, h) which would always need **copies of images**. I didn't have the time to check Manolo's patch (and to think about its consequences). I hope it would support the "multiple copies of the same image in different sizes/resolutions" problem.

Here are some points:

1. Yes, I agree that the image search missed some images and loaded new ones although they existed in the cache in 1.3.x. This was the reason for [STR 3410](https://www.fltk.org/str.php?L3410) which should be fixed independently of any other changes in FLTK 1.4. I believe my patch posted to the STR would fix the sorting and Fl_Shared_Image finding issue in 1.3.x and could be applied to 1.3.9 before release (if you can confirm that it is correct). I don't know why I was distracted from this old STR at that time and didn't finish it.

2. A similar patch would probably be required for 1.4, maybe using (data_w, data_h) instead of (w, h) if it turns out that data_w and data_h are the constants in this game. But we would still need to compare w and h to distinguish differently scaled "copies" of the images.

3. After all these changes it is important that programs written for 1.3.x with the expectation that Fl_Shared_Image creates distinct **copies** of the original image in different sizes will still work without changes. We need to keep backwards compatibility.

4. Should we deprecate Fl_Shared_Image in 1.4.0 and document that it is (only) kept for backwards compatibility with 1.3.x? Or would it be useful for 1.4 programs that read images from files and need several differently scaled "copies" to be displayed simultaneously? Fl_Help_View would be an example that could use this if the HTML contained the same image in different sizes/resolutions (this should be tested in 1.3 and 1.4).

**Comment by MatthiasWM** [comment]
So I fixed the first issue. Binary search was used incorrectly.

**Comment by MatthiasWM** [comment]
Ad 1: your patch does not work. You move the original image first for its name in the sorted list, so that a width of 0 finds it. But now you no longer find it when the original width is given. I implemented the search for the original as a dumb run through the list of images for binary compatibility. For 1.4, I am considering a second sorted list with pointers only to the originals. This would keep things fast for large searches as well.

As for copied vs. scaled images, I suggest to leave it as it is. Both concepts are not harming each other if they are not intermixed. If they are, I prefer to keep backward compatibility.

Example:
```
Fl_Shared_Image *img = Fl_Shared_Image::get("myImage.jpg");
img->scale(10, 10);
Fl_Shared_Image *img2 = Fl_Shared_Image::get("myImage.jpg", 20, 20);
```
...will load the original image at its original size in line 1. In line 2, it will create a scaled copy of the image and story it within `img->scaled_image_`, and in line 3, it will still find the original image at the original resolution and create a new shared copy at the new resolution. All as expected.

This line however
```
Fl_Shared_Image *img3 = Fl_Shared_Image::get("myImage.jpg", 10, 10);
```
will cause issues, because it returns image data at its original size, and not an image scaled to 10x10. If we just `draw` it, the virtual function will do the right thing though.

If I change this and sort the array by the true original sizes, the 4th line no longer finds the *scaled* image but instead creates a *copied* image in addition to the *scaled*, which is then rendered wrong on hires screens.

Anyway, if we can't win, we should probably at least stay compatible.

**Comment by Albrecht-S** [comment]
One note to commit f655a4d9399ae8b12368732b10d7663932bc2ee3: the docs of Fl_Shared_Image::find() state:
> In either case the refcount of the returned image is increased.

The new implementation is different:
- if we find an exact match that match is returned and the refcount is increased
- if we don't find an exact match but find the `original()` image the refcount of the original image is NOT increased.

This looks like an omission but I believe that this tentative "omission" might be **correct** because then the original image must and will be copied and the refcount of the new, copied, image is set to 1. I believe that **_this fixes a long standing bug_** where the refcount of the original image was unintentionally increased and never decreased when the copied image was released.

@MatthiasWM I used my test program posted previously to STR 3410 but I extended it a lot to display more info (just for curiosity). I'm uploading it here:

[shared_image.cxx](https://github.com/fltk/fltk/files/13587178/shared_image.cxx.txt)

I hope this helps to find potential bugs. It seems to work fine with branch-1.3 now. I'm leaving it to you to decide whether the refcount should be increased when we find the "original" image in the 2nd pass. I think not - it seems to be OK as it is now - but then the docs should be fixed.

**Comment by MatthiasWM** [comment]
@ManoloFLTK @Albrecht-S if you guys ok this fix for 1.3, I think we should do the same for 1.4, maybe with accelerated sorting.

**Comment by Albrecht-S** [comment]
@MatthiasWM Thanks for checking my patch and for explaining **why** it didn't work. I'm glad that I didn't commit it and that you found a better solution. Given my test program it **seems** to work fine but there are still some doubts regarding the refcounts (see my previous comment).

Regarding 1.4: I can't entirely follow your example above because I'm not sure which of the two pairs `(w, h)` or `(data_w, data_h)` the current implementation would use (find).

You wrote:
> Anyway, if we can't win, we should probably at least stay compatible.

Yup, **_we really need to stay compatible with 1.3_** so programs written for `Fl_Shared_Image` (using 1.3.x) still work in 1.4.0. My test program posted above is currently "scale-agnostic", i.e. it knows only FLTK 1.3 semantics. We should be able to run this using 1.3.9 and 1.4.0 with the same results. It would also be useful to check how Fl_Help_View works with the same image in different sizes.

**Comment by MatthiasWM** [comment]
> @MatthiasWM I used my test program posted previously to STR 3410 but I extended it a lot to display more info (just for curiosity). I'm uploading it here:

Cool, thanks.

> I'm leaving it to you to decide whether the refcount should be increased when we find the "original" image in the 2nd pass. 

An oversight! Incrementing the ref counter is correct because we can also directly call this function. If we create a copy, we must leave the ref counter incremented, because no copy should exist without the original around. As soon as I release the last reference to a copy, I can decrement the ref count to the original. Tested and working in the newest commit.

**Comment by Albrecht-S** [comment]
@MatthiasWM Hmm, something looks still wrong with commit 783d50e6b1ab9ed26eb7e066473725fb16e7a7f1. My test program logs:
```
[144] Fl_Shared_Image::num_images() = 5
[  0] (0x559ed28d2470) report1 (16, 16), original: 0, ref: 1
[  1] (0x559ed28d39a0) report1 (20, 16), original: 0, ref: 2
[  2] (0x559ed28d2b80) report1 (20, 20), original: 0, ref: 1
[  3] (0x559ed28d33d0) report1 (20, 24), original: 0, ref: 1
[  4] (0x559ed28d0b60) report1 (32, 32), original: 1, ref: 5
-----------------------------

[146] release_image(0x559ed28d39a0, "image20x16") (20, 16), original = 0, ref = 2

-----------------------------
[147] Fl_Shared_Image::num_images() = 5
[  0] (0x559ed28d2470) report1 (16, 16), original: 0, ref: 1
[  1] (0x559ed28d39a0) report1 (20, 16), original: 0, ref: 2
[  2] (0x559ed28d2b80) report1 (20, 20), original: 0, ref: 1
[  3] (0x559ed28d33d0) report1 (20, 24), original: 0, ref: 1
[  4] (0x559ed28d0b60) report1 (32, 32), original: 1, ref: 5
-----------------------------

[149] release_image(0x559ed28d39a0, "image20x16") (20, 16), original = 0, ref = 2

-----------------------------
[150] Fl_Shared_Image::num_images() = 5
[  0] (0x559ed28d2470) report1 (16, 16), original: 0, ref: 1
[  1] (0x559ed28d39a0) report1 (20, 16), original: 0, ref: 2
[  2] (0x559ed28d2b80) report1 (20, 20), original: 0, ref: 1
[  3] (0x559ed28d33d0) report1 (20, 24), original: 0, ref: 1
[  4] (0x559ed28d0b60) report1 (32, 32), original: 1, ref: 5
```

The same image with refcount 2 is released twice but its refcount is not decreased nor is it removed from the list. The intention was to release it twice so it is deleted from the list. Note that the logged "name" is only for users (us), the image is identified by its address.

I can't test further now, please take a look at this scenario.

**Comment by MatthiasWM** [comment]
> Looks crazy but since `find()` increases the refcount ... ;-)

That's why it is so heavily commented ;-P

> **_Edit:_** Or is something wrong with my test program?

Try adding `img->release();` to line 68 to get better results.

**Comment by Albrecht-S** [comment]
> Try adding img->release(); to line 68 to get better results.

Doh, silly mistake! Bug in the test program. Of course this statement was the entire purpose of this function but I missed to add it, instead I logged the call that never happened. Oh, oh. Sorry to have bothered you.

OK, the code seems now to work as expected. Besides fixing the image search you also got the refcounts right (which had always been wrong).

There's a tiny issue left which I found with my test program by accidentally searching for an image with w = 0 (2nd line below).
```
Fl_Shared_Image::find - did not find report1(24,48)
Fl_Shared_Image::find - found report1(0,999) = 0x55e2acc3cb60
```
As you can see in the full output of the program (after fixing line 68) the search with (w==0, h==999) returns the original image - which is formally correct but might be unexpected. I have no clear idea what to do:
- use only w==0 **AND** h==0 for finding the original image?
- document that neither w==0 nor h==0 may be used to find an image (which is not useful anyway)
- change the internal cache find mode to use w==-1 and h==-1?
- or leave it as-is and hope that nobody does this?
- or anything else, maybe use another argument or function internally to make clear that we're searching for the original() image? The usage of w==0 and h==0 seems to have been deliberate anyway and not really necessary.

Probably an explicit **_Fl_Shared_Image::find_original(const char *name)_** might be the best to avoid such unexpected results. Yes, I like this idea. Using any value (e.g. as a flag) is just calling for trouble, so why not use an explicit method name.

**Comment by MatthiasWM** [comment]
> Doh, silly mistake! 
No worries.

> As you can see in the full output of the program (after fixing line 68) the search with (w==0, h==999) returns the original image - which is formally correct but might be unexpected. I have no clear idea what to do:

...

> * or leave it as-is and hope that nobody does this?

That would be my suggestion. There is no need to search for 0 width or -1 wide images. They would both be completely useless.

> Probably an explicit **_Fl_Shared_Image::find_original(const char *name)_** might be the best to avoid such unexpected results. Yes, I like this idea. Using any value (e.g. as a flag) is just calling for trouble, so why not use an explicit method name.

We can add that in 1.3 as it is probably binary compatible. `Fl_Shared_Image::find(name)` without a size also does that (as the default parameters for width and height are 0 and 0. Personally, if magic values are used as flags, I like to give them a symbolic name, like `Fl_Shared_Image::find(name, FL_ORIGINAL_IMAGE)` or something.
