### ISSUE TITLE
Fl_Native_File_Chooser directory not working

### ISSUE THREAD

**Issue by MMartin09** [fltk/fltk#193]
I am using the Fl_Native_File_Chooser to browse for a directory. I want to open the dialog at a specified directory and tried using the `directory()` [function](https://www.fltk.org/doc-1.3/classFl__Native__File__Chooser.html#a21d2ceccc5b47bbb5e70082d75f4aeb1).
However, the dialog is not opening at the specified directory. 

I tried different things and different paths but nothing is working.

**Comment by erco77** [comment]
Need more details:

- Native file chooser uses the local native file chooser on each platform, so knowing which platform is important in this case
- Are you opening a directory chooser or a file chooser
- Which version of fltk? I think there were some fixes in 1.4.x, so check that

I believe it works this way:

- `directory()` for setting the directory of the directory chooser (e.g. `Fl_Native_File_Chooser::BROWSE_DIRECTORY`).
- `preset_filename()` is used for presetting the filename for the file chooser (e.g. `Fl_Native_File_Chooser::BROWSE_FILE`), and if a directory name is specified instead of a filename, the directory is shown

If it's a bug, it's probably platform specific, so knowing which platform is really important.
Also, see if you can replicate the problem with the `test/native-chooser` program.

**Comment by MMartin09** [comment]
I use Windows 10 and compile the project with the latest version of Visual Studio 2019. 
I open a file chooser (`Fl_Native_File_Chooser`) and use version 1.3.5 but I will have a look at version 1.4 if this solves my problem.

**Comment by MMartin09** [comment]
Okay, it seems I had some problems with the correct string formation. Now it is working fine!
