### ISSUE TITLE
Setting callback of Fl_Scroll's scrollbar freezes the scrollbar

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#198]
Hello
I noticed that setting the callback for Fl_Scroll's scrollbar causes the scrollbar to freeze (even though the callback is triggered, the scrollbar no longer scrolls). A minimal reproducible example:
```c++
#include <FL/Fl_Window.H>
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Box.H>
#include <FL/Fl.H>

void cb(Fl_Widget *, void *) {
    puts("works");
}

int main() {
    Fl_Window w(400, 300);
    Fl_Scroll s(50, 10, 340, 280);
    Fl_Box b(100, 500, 80, 40, "whatever");
    s.end();
    w.end();
    w.show();
    s.scrollbar.callback(cb, 0);
    return Fl::run();
}
```
While the behaviour with a regular Fl_Scrollbar just works:
```c++
int main() {
    Fl_Window w(400, 300);
    Fl_Scrollbar s(10, 10, 20, 280);
    w.end();
    w.show();
    s.callback(cb, 0);
    return Fl::run();
}
```

**Comment by erco77** [comment]
Pretty sure by just setting the callback without saving the original callback, you've disabled Fl_Scroll's
default behavior. If you want to keep Fl_Scroll's behavior intact, you have to save the default Fl_Scroll::callback()
before changing it, then invoke that callback from your own, where you deem it appropriate in your code to do so.

This is useful so that your callback code can control what happens in the scrollback before letting Fl_Scroll do
what it needs to do. But like with handle() methods, you have to be sure to invoke the original widget's callback
from your own code, otherwise your code will eclipse the default behavior.

**Comment by MoAlyousef** [comment]
Thanks. I hadn't thought of that. The example works.
