### ISSUE TITLE
Transfer issue tickets?

### ISSUE THREAD

**Issue by IngwiePhoenix** [fltk/fltk#2]
Hello!

For quite a while, I had tried to maintain an svn-to-git mirror of FLTK: https://github.com/IngwiePhoenix/FLTK - BUT... git-svn stopped doing what it is supposed to, and keeps throwing "Checksum missmatch" messages at me each time I try to fetch. Let alone rebase...

But, there happen to be issue and PR tickets on this repo, that I'd like to point towards:
- Wayland support https://github.com/IngwiePhoenix/FLTK/issues/4
- FLTKConfig.cmake not installed https://github.com/IngwiePhoenix/FLTK/issues/3

And this PR:
- https://github.com/IngwiePhoenix/FLTK/pull/5

I would like to close my mirror, seeing as there is an official repository now. Thank you for making FLTK - and finally an official FLTK repo... :)

**Comment by Albrecht-S** [comment]
Yes, we closed svn access and some programs seem to issue cryptic error messages.

I replied already to https://github.com/IngwiePhoenix/FLTK/issues/4 (Wayland) and suggest to close this issue (don't transfer it).

I also replied to https://github.com/IngwiePhoenix/FLTK/issues/3 (FLTKConfig.cmake). I believe this issue could also be closed (I answered the OP's question).

I believe you can close the PR https://github.com/IngwiePhoenix/FLTK/pull/5 because I committed updates in both the master branch (FLTK 1.4) and branch-1.3 (FLTK 1.3). The fix will be in FLTK 1.3.5.

Hence I believe there's nothing left to transfer and we can close this issue. Do you agree?

**Comment by IngwiePhoenix** [comment]
Fair enough. I will go ahead and actually terminate this mirror alltogether - after all, it's purpose is pretty much gone now.

Thank you for replying to the issues! Though I'd like to know when exactly you stopped SVN access?

**Comment by Albrecht-S** [comment]
We closed svn access on Dec 01, 2018 at about 21:00 CET.
