### ISSUE TITLE
cmake build ignores cmake's BUILD_SHARED_LIBS variable and always builds static libraries

### ISSUE THREAD

**Issue by yurivict** [fltk/fltk#213]
This is because ```STATIC``` keyword is specified in cmake files.

**Comment by Albrecht-S** [comment]
Thanks for the report, but that's intentional. We prefer static builds and have `OPTION_BUILD_SHARED_LIBS` to build shared libs _in addition to the static libs_.

The CMake variable `BUILD_SHARED_LIBS` is (AFAICT) designed to build either static or shared libs. Therefore it's ignored by the FLTK build system.

If this is a request to change this behavior: Sorry, this is not going to happen for the reasons stated above.
