### ISSUE TITLE
[Question] Can I use FLTK to make closed source apps?

### ISSUE THREAD

**Issue by Godnyx** [fltk/fltk#215]
I read the license tho I'm not very good with that stuff and I want to be 100% sure before doing anything that will get me in trouble. I was wondering, can someone create a closed source application with FLTK? And if yes, how should I do it and are there any restrictions? Can someone explain it in simple English?

**Comment by erco77** [comment]
Answer is Yes, you can use FLTK with closed source/proprietary code.

You can even statically link the FLTK library in with your closed source executable (something the normal LGPL doesn't allow, due one of the four LGPL2 exceptions, exception #⁠3, in the license file that comes with FLTK (historically named COPYING in fltk's source directory) which says:

    3. Static linking of applications and widgets to the
       FLTK library does not constitute a derivative work
       and does not require the author to provide source
       code for the application or widget, use the shared
       FLTK libraries, or link their applications or
       widgets against a user-supplied version of FLTK.

Regarding "how do I do it", exception #⁠4 goes into that detail, which says:

    4. You do not have to provide a copy of the FLTK license
       with programs that are linked to the FLTK library, nor
       do you have to identify the FLTK license in your
       program or documentation as required by section 6
       of the LGPL.

       However, programs must still identify their use of FLTK.
       The following example statement can be included in user
       documentation to satisfy this requirement:

           [program/widget] is based in part on the work of
           the FLTK project (https://www.fltk.org).

So for instance if your app has a "Help -> About" menu dialog, you can put the citation there,
or if it has a command line help flag (-h, -help), you can put it there, or put it in your app's written documentation.

For elaboration, please re-ask on the  [fltk.general google group](https://groups.google.com/forum/#!forum/fltkgeneral).
And please, in the future, ask questions about fltk on that group so others besides devs can see replies and contribute answers.

Github Issues are just for bug and RFE reporting, are bad for questions like these because once the issue is closed, it becomes almost invisible to the public, and others can't as easily contribute or benefit from the discussion, as often non-devs have more interesting answers in the form of anecdotes and a variety of real world situations.

That all said, this is one of the things you'd bounce off your IP (Intellectual Property) lawyer, as anyone doing closed source should really be consulting for not only license compliance, but creating closed source licenses/warranty/etc for your app.

**Comment by Godnyx** [comment]
I got that! Thanks a lot for everything, I will post any future question in there! Have a nice day!
