### ISSUE TITLE
Issues compiling for iOS

### ISSUE THREAD

**Issue by Gymxo** [fltk/fltk#221]
Because iOS contains Apple and Darwin, it also tends to pick up stuff that’s meant to compile for Mac OS only. These include frameworks such as carbon and cocoa to which are limited on iOS. I’ve tried replacing some areas that say Apple with something else so it don’t error. But still tends to get errors while compiling. Any help on this topic would be appreciated.

**Comment by Gymxo** [comment]
I believe that fltk would be a great edition to https://github.com/ProcursusTeam/Procursus/tree/as2 which is a modern bootstrap for iOS. And would like to hear feedback on this issue. :)

**Comment by Albrecht-S** [comment]
We discussed to port FLTK to iOS but came to the conclusion that it would be too much effort to do it and it would likely be impossible to get FLTK applications **officially** installed on iOS because Apple wouldn't allow it. This may be right or wrong, but that's where the discussion ended.

From a quick glance at Procursus I understand that it is meant to be used in a jailbreak environment. This may change things but we (the FLTK team) will not be able to put development efforts in such a project. If anybody could provide patches, well, this might change it...

That said, this is not a good place to ask questions about development of the FLTK library. FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.

If you want to discuss this topic further, please ask your questions in our FLTK development group [fltk.coredev](https://groups.google.com/forum/#!forum/fltkcoredev) where we're discussing additions and features of the FLTK library. Thanks.

**Comment by Gymxo** [comment]
Thanks for the feedback.

**Comment by Gymxo** [comment]
And yes usually we make patches for things

**Comment by Gymxo** [comment]
![Screen_Shot_2021-04-16_at_5 04 54_PM](https://user-images.githubusercontent.com/55960119/115087196-bc5a6800-9edb-11eb-8bd1-48a2dc04de63.png)
And I've also made patches.
The only thing I mostly had to do was disable some mac os specific things.
