### ISSUE TITLE
fltk (master) build errors

### ISSUE THREAD

**Issue by Godnyx** [fltk/fltk#222]
I'm trying to build the latest master fltk version using CMake and following the steps in the `README.CMake.txt` file but I'm having two errors. First I'll describe the steps I followed in any case:

1. I downloaded fltk using `git clone`
2. I changed (cd) to the fltk dir and created the `build` directory
3. I changed to the `build` directory and used the following "command" to generate the Makefile
  `cmake -D 'CMAKE_BUILD_TYPE=Release' 'CMAKE_INSTALL_PREFIX=../../FLTK_1.4' 'OPTION_BUILD_SHARED_LIBS=ON' 'FLTK_BUILD_EXAMPLES=ON' 'OPTION_USE_GL=OFF' ..`
4. The Makefile was generated with success so we're fine until now

When I tried to make the library, I got two error from which I was able to fix the one but I will still talk about it because It doesn't make any sense to me.

Problem 1: I got an error saying that `<GL/glu.h>` was not found. Now I know and I installed `glu-devel` and fixed that but why do I need OpenGL? I thought that it was disabled....
Problem 2: I'm getting an error about some undifined references. You can find the error info [here](https://gitlab.com/-/snippets/2108438)

In case you need more info, I'm glad to provide it ;)

**Comment by Albrecht-S** [comment]
> Problem 1: I got an error saying that <GL/glu.h> was not found. Now I know and I installed glu-devel and fixed that but why do I need OpenGL? I thought that it was disabled....

Answer 1: You need to repeat `-D` for each option you specify. I think you **should** get some warnings when you run the CMake command (from CMake) but I tested it and the extra parameters were silently ignored. :-(

Answer 2: Instead of `glu-devel` I installed on Linux Mint (based on Ubuntu) `freeglut3-dev` which may have pulled in `libglu1-mesa-dev` and this worked fine.

> Problem 2: I'm getting an error about some undefined references...

Answer 3: See above, answer 2.

**_Answer 4 (standard reply):_**
This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your questions will have a wider audience and you will likely get more and quicker replies.
Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

I'm going to close this issue now because of answer 4.

**Comment by Godnyx** [comment]
I thought this as a potential bug and that's why I posted here. Thanks a lot for your hard work and I wish you to have an amazing day!

**Comment by Albrecht-S** [comment]
Welcome.

In case you're not absolutely sure we suggest to ask in fltk.general first.
