### ISSUE TITLE
Rename Fl_X* Fl_Window::i private class member

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#223]
See discussion in thread `Fl_Window's "Fl_X *i" causes warning "C4458: declaration of 'i' hides class member" in Visual Studio` [in fltk.general](https://groups.google.com/g/fltkgeneral/c/SQ3RSqNgXbE/m/lIl2lnjdBQAJ).

The gist of this thread: FLTK uses a member name `i` for an internal (private) member which is generally a bad choice and doesn't comply with our CMP.

Although the warning in VS is (only?) visible at warning level `/W4` (as reported) it can be "fixed" (IMHO: easily) in the user code that introduces the variable `i` that _shadows_ the (private!!!) FLTK member variable. (Is VS here at fault warning about a private class member?)

But since there is an almost complete patch FLTK should be changed anyway to honor the CMP (by renaming the private class member as discussed).

**Comment by Albrecht-S** [comment]
Commit https://github.com/Albrecht-S/fltk/commit/332ed0db1f08b7f1ea3cb79925723a8b0bf921b0 is very likely the full solution but I'm waiting to apply it until we have merged the pending Wayland changes (Manolo's branch) because I expect some conflicts.

That said, test results (building and running apps) with my branch in my fork would be appreciated.

**Comment by ManoloFLTK** [comment]
@Albrecht-S If you agree, I propose to take care of this issue with the attached patch.
- member variable `i` of class `Fl_Window` is renamed `flx_`
- member function `i(Fl_Window*)` of class `Fl_X` is renamed `flx(Fl_Window*)`
- file `platform.H` contains
```
#  if defined(FLTK_USE_X11) && FLTK_USE_X11 // for backward compatibility
  … 2 unchanged, already present function declarations …
  static inline Fl_X* i(const Fl_Window* w) {return flx(w);}
#  endif
```
so that the previous member function `Fl_X::i()` remains usable under X11 only, because
it was mentionned in the X11-specific part of the doc only
- file `osissues.dox` uses the new `Fl_X::flx()` and adds this note
```
\note For compatibility with FLTK versions before 1.4, member function
\c Fl_X::flx(Fl_Window*) can also be written \c Fl_X::i(Fl_Window*).
```


[iTOflx.patch.txt](https://github.com/fltk/fltk/files/10413452/iTOflx.patch.txt)

**Comment by Albrecht-S** [comment]
I do not only agree but I appreciate it very much. Your description sounds good and the patch looks good (as far as I could check it quickly).

Please go ahead. Thanks!
