### ISSUE TITLE
Menus, drop-downs, etc. do not always display (X11/Debian/FVWM3)

### ISSUE THREAD

**Issue by wyatt8740** [fltk/fltk#231]
Hi,

I'm encountering an issue where menus and drop-down lists (combo boxes) do not always show up on my Debian Linux desktops. I am still able to navigate them using arrow keys, which leads me to believe they may be drawing off-screen or something.

I've been able to produce this behaviour with the `menubar-add` example as well as with other software (e.g., [Nestopia](https://github.com/0ldsk00l/nestopia), which recently adopted an FLTK UI).

Sometimes, I can see a ghost of the button I'm pressing appear a few pixels above the window, as seen in the screenshot attached. And sometimes (around 40% of the time), the menus *do* show up properly and function normally.

![fltkbug](https://user-images.githubusercontent.com/2400933/118856659-b84cac00-b8c6-11eb-9e0a-b6cc3e6cf461.png)

I am using [FVWM3](https://github.com/fvwmorg/fvwm3) as my window manager on all of my systems.

**Comment by Albrecht-S** [comment]
Thanks for the report. A quick guess would assume the bug is to be looked for in the WM though. But that's only a quick guess...

> I am using FVWM3 as my window manager on all of my systems.
Can you reproduce the issue with another WM?

That said, to investigate this further, which exact FLTK version are you using (downloaded tarball, snapshot, git (branch and commit)? I see that `examples/menubar-add.cxx` exists already in FLTK 1.3.

**Comment by wyatt8740** [comment]
I'm on the package for Debian Unstable at https://packages.debian.org/source/unstable/fltk1.3 - that is, 1.3.5.

I do not experience the issue in MATE. I will try MWM and dtwm (CDE) later, if that is useful. I also have mentioned the bug to Thomas Adam of FVWM3, and am corresponding with him.

**Comment by Albrecht-S** [comment]
Thanks for the feedback. Any further tests with other WM's would be appreciated. TIA

FLTK 1.3.5 is pretty old and 1.3.6 has been released recently, but I don't think that this release could have changed anything regarding the display of menus. Anyway, a test with the latest stable release would be useful before we're searching for something that has been fixed.

Since work on the 1.3 branch has been stopped, I suggest that you may build FLTK 1.4 from Git or a current snapshot to see if this changes anything. However, I don't **_expect_** significant changes regarding this issue.

For now I suggest to put this issue "on hold", which means that I (personally) won't investigate further until you can post news from Thomas Adam or other tests that show the issue with different WM's.

**Comment by Albrecht-S** [comment]
> I will try MWM and dtwm (CDE) later, if that is useful. I also have mentioned the bug to Thomas Adam of FVWM3, and am corresponding with him.

@wyatt8740 Any news about tests with other WM's and/or your correspondence with Thomas Adam (FVWM3)?

**Comment by Albrecht-S** [comment]
There has been no reaction on questions for more than a year.

This issue must be closed according to the FLTK CMP rules. If you find more info and if you are sure it is a FLTK bug, please open a new issue. Otherwise, please see the info below for how to proceed.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
