### ISSUE TITLE
In Fl_Text_Display style should apply to UTF-8 characters.

### ISSUE THREAD

**Issue by bstarynk** [fltk/fltk#233]
Using FLTK 1.3.6 (probably git commit cbee4880f45c66) with the following example, slightly adapted from examples/textdisplay-with-colors.cxx but using UTF-8 characters does not show the expected colors:

#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Text_Display.H>
int main() {
   // Style table
   Fl_Text_Display::Style_Table_Entry stable[] = {
       // FONT COLOR      FONT FACE   FONT SIZE
       // --------------- ----------- --------------
       {  FL_RED,         FL_COURIER, 18 }, // A - Red
       {  FL_DARK_YELLOW, FL_COURIER, 18 }, // B - Yellow
       {  FL_DARK_GREEN,  FL_COURIER, 18 }, // C - Green
       {  FL_BLUE,        FL_COURIER, 18 }, // D - Blue
   };
   Fl_Window *win = new Fl_Window(640, 480, "Simple Text Display With Colors");
   Fl_Text_Display *disp = new Fl_Text_Display(20, 20, 640-40, 480-40);
   Fl_Text_Buffer *tbuff = new Fl_Text_Buffer();        // text buffer
   Fl_Text_Buffer *sbuff = new Fl_Text_Buffer();        // style buffer
   disp->buffer(tbuff);
   int stable_size = sizeof(stable)/sizeof(stable[0]);  // # entries in style table (4)
   disp->highlight_data(sbuff, stable, stable_size, 'A', 0, 0);
   // Text
   tbuff->text("Red Line 1\nYel Line euro:€ 2\nGrn Line para:§ 3\nBlu Line 4\n"
               "Red Line 5\nYel Line 6\nGrn Line 7\nBlu Line 8\n");
   // Style for text
   sbuff->text("AAAAAAAAAA\nBBBBBBBBBBBBBBBBB\nCCCCCCCCCCCCCCCCC\nDDDDDDDDDD\n"
               "AAAAAAAAAA\nBBBBBBBBBB\nCCCCCCCCCC\nDDDDDDDDDD\n");
   win->resizable(*disp);
   win->show();
   return(Fl::run());
}

**Comment by bstarynk** [comment]
This is either a bug in the documentation or in the implementation

**Comment by erco77** [comment]
Probably a bug in the handling of corresponding multibyte characters to the byte oriented style array.

The utf8 representation of e.g. the euro character is surely "several bytes" but is a "single character", and the widget is probably assigning the color characters "per byte" instead of "per character".

**Comment by Albrecht-S** [comment]
I think this is not a bug, but maybe the documentation could be improved. Sure, the style buffer must be in sync with the text buffer, but the user code is expected to do this synchronization, for instance when text is deleted from or added to the text buffer. The user can add `modify-callbacks` and will get a **byte range** of deleted and added **characters**. I don't know how the `Fl_Text_Display` widget could do the synchronization other than scanning the whole buffer and _count characters_ rather than using the _known byte positions_ to affect the drawing of text.

Disclaimer: this is off the top of my head, w/o actually looking at the code, and I **assume** that the documentation hasn't been updated with UTF-8 in mind regarding this particular aspect since the transition to UTF-8 in 1.3.0 and later.

I agree that this should be clarified in the docs but I suspect that it will not be changed to make the style buffer use _character positions_ rather than _byte positions_. This should be investigated...

**Comment by Albrecht-S** [comment]
FTR: to see that the style handling **works** in action, please load text with UTF-8 (i.e. non-ASCII) characters in the `test/editor` example program, for instance this pseudo C++ code:
```
#include <FL/Fl_Text_Display.H>
int main() {
  // Style table
  Fl_Text_Display::Style_Table_Entry stable[] = {
  // ...
  if (b€c and €) { // text with '€' note: 'and' in code should be highlighted
    printf("This string with € and Umlauts %s is fine\n", "äöüßÄÖÜ");
  } else { // another (incorrect) French comment: déjà vû §
    printf("Incorrect French with German Umlauts %s. Déjà vû \n", "äöüß");
  }
  // Style for text with 
  sbuff->text("AAAAAAAAAA\n ¢ £ ¤ ¥ \nCCCCCCCC\nDDDDDDDDDD\n");
  // still parses "return" fine:
  return(Fl::run());
}
```

You can add and remove text with or without non-ASCII characters and the style update works (except for some special cases that are different, i.e. non-UTF-8 issues). A better working (although harder to use) example would be to load such text into fluid in FLTK 1.4.x (git) which does the style parsing somewhat better.

Screenshot attached:

![image](https://user-images.githubusercontent.com/26235500/118968450-3b740d80-b96c-11eb-8e8b-8d7b0b2a0cf2.png)

**Comment by erco77** [comment]
Ah, it's true that the app usually handles keeping the two buffers in sync in an automated way, and that the fixed string use of  "AAAAA\nBBBBB.."  is just for super-simple demos, and not practical for application use.

So agreed, docs could help this.

Perhaps too, a /simple/ example (i.e. NOT the test/editor example) that is "utf8 aware" showing proper use of e.g. `fl_utf8len()` to keep the two buffers in sync.
