### ISSUE TITLE
FL_Browser_ : horizontal scrollbar to top: undocumented feature or bug?

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#237]
In an Fl_Browser, the horizontal scrollbar can be moved to the top of the widget. The puzzler is this feature is driven by the `align()` value of `scrollbar`, not `hscrollbar`!

I.e. modifying `test/browser.cxx` as follows results in a horizontal scrollbar at the top:
```
  browser = new Fl_Select_Browser(0, 0, window.w(), 350, 0);
  browser->type(FL_MULTI_BROWSER);  //original
  browser->has_scrollbar(Fl_Browser_::BOTH_ALWAYS); // add this to force horizontal scrollbar
  browser->scrollbar.align(FL_ALIGN_TOP); // moves horizontal scrollbar to the top
  browser->callback(b_cb); // original
```

In Fl_Browser_.cxx are the following lines:
```
 78  if (hscrollbar.visible()) {
 79    H -= scrollsize;
 80    if (scrollbar.align() & FL_ALIGN_TOP) Y += scrollsize;
 81  }
```
If this is a supported feature, it seems to me line 80 should read:
```
 80    if (hscrollbar.align() & FL_ALIGN_TOP) Y += scrollsize;
```
although making this change may be a backwards compatibility issue.

**Comment by Albrecht-S** [comment]
> In an Fl_Browser, the horizontal scrollbar can be moved to the top of the widget. The puzzler is this feature is driven by the align() value of scrollbar, not hscrollbar!

Thanks for the report. I didn't have the time to look deeper into it, but what you wrote rang a bell somewhere in my memory...

There's a documented precedent in class [Fl_Scroll](https://www.fltk.org/doc-1.4/classFl__Scroll.html):
_"If the FL_ALIGN_LEFT bit is on, the vertical scrollbar is on the left. If the FL_ALIGN_TOP bit is on, the horizontal scrollbar is on the top. Note that **only the alignment flags in scrollbar are considered. The flags in hscrollbar however are ignored**."_

This looks like it's intentional, but if it's not documented it should probably be done (i.e. documented) like in Fl_Scroll. This is not meant as any kind of final decision. I just wanted to mention the facts.

**Comment by fire-eggs** [comment]
Ah, I see the same code in Fl_Scroll!

Once is an accident, twice is intentional! :-)

**Comment by Albrecht-S** [comment]
Yep, looks like we need some docs.

**Comment by MatthiasWM** [comment]
Documented now.
