### ISSUE TITLE
Fl::lock() doesn't call pthread's recursive mutex on Linux

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#245]
Following the discussion in the [mailing list](https://groups.google.com/g/fltkgeneral/c/M7J-m4BU5Sc), it appears calls checking whether PTHREAD_MUTEX_RECURSIVE is defined `#ifdef PTHREAD_MUTEX_RECURSIVE` in Fl_Posix_System_Driver.cxx end up being ignored on linux since the pthread header defines it as an enum value. While on Apple, BSD and mingw/Msys2, PTHREAD_MUTEX_RECURSIVE is actually defined as a define. 

The emulation code however seems to work ok (apart from giving some false positives in some analyzers). 

I'm not sure if adding `__USE_UNIX98` to the ifdef (as in the linux pthread header) would also be sufficient in this case. 
```cpp
#if defined(PTHREAD_MUTEX_RECURSIVE) || defined (__USE_UNIX98)
```

**Comment by Albrecht-S** [comment]
I think we need a compile (feature) test in `configure` and `CMake` which determines whether `PTHREAD_MUTEX_RECURSIVE` is available. The following test code shows that this works on Linux although `PTHREAD_MUTEX_RECURSIVE` is not defined as a macro:
```
/*
  FLTK feature test: do we have PTHREAD_MUTEX_RECURSIVE ?
  Compile and run:
    gcc -o main pthread_mutex_recursive.c -lpthread
    ./main; echo $?
*/
#include <pthread.h>
int main() {
  pthread_mutexattr_t attrib;
  pthread_mutexattr_settype(&attrib, PTHREAD_MUTEX_RECURSIVE);
#ifdef PTHREAD_MUTEX_RECURSIVE
  return 1;
#else
  return 2;
#endif
}

$ gcc -o main pthread_mutex_recursive.c -lpthread
$ ./main ; echo $?
2
```
Exit status is 2 (not defined) but the code compiles and runs anyway. If used in configure/CMake as a feature test, this could define a macro, e.g. HAVE_PTHREAD_MUTEX_RECURSIVE which we can use in the FLTK source code.

So far this is only a proof of concept.

FTR: the same logic (`#ifdef PTHREAD_MUTEX_RECURSIVE`) is also in `branch-1.3` and very likely in FLTK 1.1, this is not a regression.

**Comment by ManoloFLTK** [comment]
Reproduced from fltk.general :
====================
 I've found these situations
- PTHREAD_MUTEX_RECURSIVE is #define'd : macOS, NetBSD, pthreads-mingw64
- PTHREAD_MUTEX_RECURSIVE is an enum value : Linux, FreeBSD, pthreads-mingw32

But PTHREAD_MUTEX_RECURSIVE is always usable as a C constant value.

We definitely have to remove the present usage of
#ifdef PTHREAD_MUTEX_RECURSIVE

I see two ways out :
1) Only use recursive mutexes and remove all the code devoted to the support of non-recursive mutexes. That would be fine on all systems mentionned above. It would fail on systems where pthread.h exists but PTHREAD_MUTEX_RECURSIVE is neither an enum nor a preprocessor variable. Do such systems exist?

2) define an FLTK-specific preprocessor variable that would be used instead of #ifdef PTHREAD_MUTEX_RECURSIVE and that would be always set in config.h to 1,  but that could be commented out to allow building of FLTK on a hypothetical system lacking recursive mutexes. Alternatively, the configure-time test Albrecht showed could put config.h in the adequate state. Albrecht suggested above to name such prepro variable HAVE_PTHREAD_MUTEX_RECURSIVE
=================

Bill's post (https://www.fltk.org/newsgroups.php?s40813+gfltk.general+v40831+T) seems to suggest that early Windows versions of pthread.h didn't possess PTHREAD_MUTEX_RECURSIVE, so FLTK provides a way to emulate recursive mutexes. That's no longer true since Windows XP at least. So a case for solution 1) above still makes sense. Of course, the proper configure-time test Albrecht detailed is a better, fullproof solution.

**Comment by imaclmaca** [comment]
I think option 2 might be worth doing anyway, that is setting HAVE_PTHREAD_MUTEX_RECURSIVE in config.h and using that in the code, with the appropriate default value...?
If (1) above is true then maybe all systems would have it set anyway?
We can then more easily add a proper configure-time test like Albrecht suggests, in slower time?

**Comment by Albrecht-S** [comment]
@imaclmaca Yes, that's certainly a good idea. :+1:

This would also give us some time to find out if there are any platforms that don't build as expected (as long as the configure/CMake check is not yet in place).

**Comment by Albrecht-S** [comment]
I changed the macro usage (`#ifdef HAVE_PTHREAD_MUTEX_RECURSIVE` instead of `#ifdef PTHREAD_MUTEX_RECURSIVE`) and defined `HAVE_PTHREAD_MUTEX_RECURSIVE` in `configh.in` and `configh.cmake.in`. This works so far (compiles the code in question and `test/threads.cxx` works as expected). This could be a first solution as suggested by Ian. 

I'm now working on the full solution including
- CMake check
- configure check

(in this order).

**Comment by Albrecht-S** [comment]
This should be fixed in c6eccf6137fae2c2f158af6bdc393d70d832b9e9.

Feedback on different systems would be appreciated. A quick check would be to execute
- either `autoconf; ./configure`
- or `cmake` (or just run your build tool)

and test if `config.h` contains the correct definition of `HAVE_PTHREAD_MUTEX_RECURSIVE` (either defined or undefined/commented out).

Note that you must run `autoconf` to create the new `configure` script if you're not using `CMake`.

TIA

**Comment by MoAlyousef** [comment]
I pulled the fixes to cfltk and fltk-rs. Works great and no longer triggers warnings with helgrind.

**Comment by Albrecht-S** [comment]
Thanks, closing...
