### ISSUE TITLE
Fl::visible_focus(false) causes artifacts in some widgets when redrawn

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#263]
Hello

Consider the following program:
```cpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Check_Button.H>

int main() {
  Fl::visible_focus(false);
  Fl_Window w(400, 300);
  Fl_Check_Button btn(160, 200, 80, 40, "Hello");
  w.end();
  w.show();
  return Fl::run();
}
```
Clicking on the check button several times causes the following artifact:
![image](https://user-images.githubusercontent.com/37966791/126886606-bff6b59e-3524-43bb-9b95-92bd9a44e282.png)

Removing the `Fl::visible_focus(false)` and just using `btn.clear_visible_focus()` doesn't produce the same issue. 

Tested with version 1.4 built from source with CMake on both Windows 10 and Ubuntu 20.04 (WSL).

For buttons (check and round buttons), modifying the Fl_Button source seems to fix the issue:
```patch
diff --git a/src/Fl_Button.cxx b/src/Fl_Button.cxx
index 1651d08f5..6639feb73 100644
--- a/src/Fl_Button.cxx
+++ b/src/Fl_Button.cxx
@@ -87,6 +87,19 @@ int Fl_Button::handle(int event) {
     return 1;
   case FL_PUSH:
     if (Fl::visible_focus() && handle(FL_FOCUS)) Fl::focus(this);
+    else {
+      Fl_Widget *widget = parent();
+      while (1) {
+        if (!widget) break;
+        if (widget->box() == FL_NO_BOX) {
+          widget = widget->parent();
+          continue;
+        } else {
+          widget->redraw();
+          break;
+        }
+      }
+    }
     /* FALLTHROUGH */
   case FL_DRAG:
     if (Fl::event_inside(this)) {
```
However this might not be the most optimal solution.

**Comment by Albrecht-S** [comment]
Thanks for the report, this is a known issue caused by multiple drawing of antialiased text in the same place, but it's a more general problem than only in such buttons. It happens for instance if any label is drawn inside a box with no solid background. As your patch shows, this can (partially) be _worked around_ by searching up the widget hierarchy to find a box (widget) with a solid background and `damage()` that widget by calling `redraw()`. But even that will not always cover the entire label (e.g. if the label is large and/or crosses box boundaries).

> However this might not be the most optimal solution.

Unfortunately this is more than true. For one this could result in redrawing the entire window as the result of a button click which is really bad (performance wise), but another important issue is that testing for `FL_NO_BOX` is not enough. There are other boxtypes (all the `FL_*_FRAME` types) that don't have a solid background, and labels can be drawn outside the widget's own box etc.. Furthermore we don't have a box type attribute that would say: "this box type has a solid background" (or not).

That said, there's (currently) no other solution than using a boxtype with a solid background. If you add
```
  btn.box(FL_FLAT_BOX);
```
to the test program the issue goes away.

The fact that this happens or not whether you change Fl::visible_focus() is only a side effect and doesn't help solving the root cause.

**Comment by MoAlyousef** [comment]
I tried poking around a bit more, clearing the VISIBLE_FOCUS flag in the widget constructor, but that didn't help either. 
Anyway I'll close this issue since it's already known for FL_NO_BOX widgets.
