### ISSUE TITLE
Can we use the qt/kde file picker instead of gtk?

### ISSUE THREAD

**Issue by jointri** [fltk/fltk#278]
On linux, the gtk file picker is terrible and a well known meme you can't have thumbnails in the file picker. Can it be possible to use the kde or qt file picker instead of gtk?

**Comment by Albrecht-S** [comment]
FTR: see also [fltk.coredev, thread:](https://groups.google.com/g/fltkcoredev/c/2OMSrmSUhEk/m/EixBjas2AgAJ) "Please allow us to use qt/kde file picker instead of GTK."

**Comment by erco77** [comment]
If there's a way to open the KDE/Qt file chooser dialog from the command line, it might not be too hard to modify Fl_Native_File_Chooser (FNFC) to invoke that, using its API to control presetting the browsing directory, choosing file|directory browser, etc.

Actually, providing a generic way to tell FNFC thru its API to invoke _any_ command line tool to open a file browser might be useful, as apparently these tools change names almost as often as new linux distros are released (i.e. often).

I understand zenity(1) was the way to do this in GTK, but it's been surpassed (I think) by yad(1). KDE has something similar, e.g. `kdilog --getopenfilename` from what I can tell.

FNFC could invoke this command line tool in the background with fork() and pipes so as to not to block the FLTK app loop while the browser is open, and on completion, returns the user's chosen file through the API as per usual.

In this way the application can choose which browser is used, and perhaps even support different command line file choosers by probing to see what's available (e.g. looking for kdialog, yad, zenity, etc) without FLTK having to track all these different tool names.

**Comment by jwinnie** [comment]
There's now a way to pick the file chooser on Linux based on the user's desktop environment, using [xdg-desktop-portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser).

**Comment by Albrecht-S** [comment]
> There's now a way to pick the file chooser on Linux based on the user's desktop environment, using xdg-desktop-portal.

@jwinnie This has nothing to do with our topic. It is related to "_sandboxed applications_" (`flatpak`) and asks the user to allow access to files outside the flatpak sandbox.

**Comment by ManoloFLTK** [comment]
@jointri : could you, please, try replacing file src/Fl_Native_File_Chooser_GTK.cxx
in your FLTK source code by the version attached :
[Fl_Native_File_Chooser_GTK.cxx](https://github.com/fltk/fltk/files/7625922/Fl_Native_File_Chooser_GTK.cxx.txt)

After re-building the FLTK library, FLTK apps running with the KDE desktop should use the KDE file chooser when they use class Fl_Native_File_Chooser.

Does that meet what you expected?

**Comment by spitzak** [comment]
The desktop designers are insane that they won't make this a trivial operation. Way back there was "xdialog", but every single time they rename the program for no reason, change the switches, and refuse to make the same program work with multiple desktop environments. I have no idea why but it is really frustrating.
On my machine it looks like "zenity" works.

**Comment by spitzak** [comment]
PS: and please, please, please, make "what happens when user double-clicks a file" be "exec("open", filename, 0)"
The fact that there is an ancient program called "open" from Unix v7 is irrelevant, override it.

**Comment by ManoloFLTK** [comment]
@spitzak : the fix proposed above uses command `kdialog` to generate KDE-style file dialog windows for class Fl_Native_File_Chooser. Do you mean this is too unstable a procedure ?
The fix works only with the KDE desktop, because the same command produces GTK-style windows when run under Gnome.

**Comment by spitzak** [comment]
No that sounds correct. I am just annoyed that xdialog was renamed. There is no reason not to use "x..." to run the desktop-specific instance, rather than "k.." and "g...". If in fact kdialog runs the GTK one when on Gnome, that is good. I don't like the idea that the desktop has to be determined in order to figure out what program to call however.

**Comment by pdhahn** [comment]
Introduction of a Qt dependency also introduces the Qt LICENSE DEPENDENCY! This is a BIG NO_NO for people like me using FLTK for commercial purposes (i.e., static link).

**Comment by ManoloFLTK** [comment]
The FLTK library is not linked to any Qt library, neither dynamically nor statically.
It runs the "kdialog" program if the running desktop is KDE and if "kdialog" is available 
at run-time on the platform, and uses instead the GTK file dialog if "kdialog" is absent.

Does that impact the commercial use of FLTK?

**Comment by Albrecht-S** [comment]
I'd say no but [IANAL](https://en.wikipedia.org/wiki/IANAL).

I think it's something like the fact that distros like Debian don't provide "non-free" software but you can download and install it yourself on your system. It's not exactly the same but I think it's similar. Again, IANAL.

**Comment by pdhahn** [comment]
If I use Qt, I must abide by its terms to do so. It is the same with any software or software component. Even if linking is not involved. It's about usage. Naturally, a this point, I am obliged to state I am not a lawyer (IANAL). But decisions pertaining to commercial issues frequently do not involve lawyers but rather common sense; a lwayer is the last resort.

From my perspective, even if users choose to use KDE, software I deliver to them should not couple to it in such a way that incorporates its (KDE's) inherent dependencies on Qt. If my commercial software by design relies on Qt through any pathway, then I am afraid predatory lawyers (redundant terminology, I know) can make a case that I I owe money to somebody.

Anyway, I am happy to hear this is so loosely coupled in FLTK. Perhaps it would be best then if there were some explicit action needed to enable it (default is disabled) during build configuration so my applications linked to static FLTK will scan completely Qt-clean even if running on KDE.

**Comment by ManoloFLTK** [comment]
Here are a few additional relevant facts in this topic:
- kdialog is not in the non-free part of Debian; it's in the "main" section;
- kdialog is licensed GPL;
- FLTK would neither modify nor distribute kdialog code, only run it if present.

What about an FLTK build option that would be on by default and that, if set to off, 
would prevent class Fl_Native_File_Chooser from running kdialog?
A commercial app statically linked to FLTK does, I would presume, control the FLTK build step.

**Comment by pdhahn** [comment]
Yes, if there were a way to explicitly disable use of `kdialog` in the FLTK configure/build, it would satisfy my concerns.

FYI I get it that you want to improve FLTK and I (like so many others, I'm sure) thank you for all your efforts to do so. Likewise, let me thank you ahead of time for your diligence to preserve FLTK's independence and licensing integrity.

**Comment by ManoloFLTK** [comment]
The git repo offers now (4bc25f7) a CMake option to disable use of `kdialog` by
class `Fl_Native_File_Chooser`. It's called OPTION_USE_KDIALOG and is On by default.

Under configure + make, edit `config.h` after configure and before make and set
`#define USE_KDIALOG`
to 0 therein.

**Comment by pdhahn** [comment]
This is just to confirm that the new option is there in cmake as advertised, and I can set it 0 just fine. Thanks.

**Comment by jointri** [comment]
You guys are the best. I am very happy I can set FLTK to use kdialog on linux/BSD rather than be stuck with GTK. Does this mean my issue is solved and I can close it now?

**Comment by Albrecht-S** [comment]
@HugLifeTiZ You wrote:
> Actually, it is completely pertinent to this topic. When you use the xdg-desktop-portal for file selectors, even outside of a sandbox environment ...

Thanks for this info. When I looked at the link given above I could only see the connection to flatpak. I may have been wrong.

I also noticed your edit above about zenity and that you may look into making a patch. That's great, all contributions are welcome.

**However: please open another issue for additional options/changes/requests.**

This issue is closed and must stay closed, particularly since we are approaching the release of FLTK 1.4.0. If you can provide a patch, then please attach it to your new issue or make a PR so we can trace this new issue better. You can always refer to this issue to keep the context. Thank you in advance.
