### ISSUE TITLE
Cannot build dynamic library

### ISSUE THREAD

**Issue by rempas** [fltk/fltk#305]
I was able to successfully build and install FLTK but I'm not able to build it when I use the option `-DOPTION_BUILD_SHARED_LIBS=ON` to enable the shared libraries. When it tries to link the "libfltk_images.so" object, I get the following error message:
```
/usr/bin/ld: ../lib/libfltk_jpeg.a(jerror.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fltk_images_SHARED.dir/build.make:265: lib/libfltk_images.so.1.4.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:340: src/CMakeFiles/fltk_images_SHARED.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

If you need more specific info:

**OS:** `Linux Lite 5.6`

**Command used to create Makefile:** `cmake .. -DCMAKE_BUILD_TYPE=Release \
-DOPTION_BUILD_SHARED_LIBS=ON \
-DFLTK_BUILD_TEST=OFF \
-DOPTION_USE_GL=OFF \
-DOPTION_BUILD_HTML_DOCUMENTATION=OFF \
-DOPTION_BUILD_PDF_DOCUMENTATION=OFF \`

**Command used to build:** `sudo make install -j4`

**Comment by Albrecht-S** [comment]
Hi @rempas, thanks for the report. However, I can't reproduce this on my Linux system with FLTK 1.4 (git).

I see that you are building libjpeg which may be caused be missing development files of libjped on your system (this is detected by CMake). I used both the default build and one with system image libs disabled but none of them exhibited the issue.

I don't know `Linux Lite 5.6`. It looks like this being https://www.linuxliteos.com/ which provides version 5.6. Is this correct?

Before we continue, please let us know which (exact!) FLTK version you are using. Note that such issues will not be fixed in 1.3 (end of life). Did you use git (which commit) or a current snapshot (which one)?

If you are using a current FLTK 1.4 version, please confirm that the problem persists if you build FLTK in a fresh (empty) build directory. It's not clear to me whether you did this or if you changed options of a previous build w/o shared libs.

**Comment by Albrecht-S** [comment]
FTR: Here's my CMake command:
```
cmake .. -DCMAKE_BUILD_TYPE=Release \
  -DOPTION_BUILD_SHARED_LIBS=ON \
  -DFLTK_BUILD_TEST=OFF \
  -DOPTION_USE_GL=OFF \
  -DOPTION_BUILD_HTML_DOCUMENTATION=OFF \
  -DOPTION_BUILD_PDF_DOCUMENTATION=OFF \
  -DOPTION_USE_SYSTEM_LIBJPEG:BOOL=OFF \
  -DOPTION_USE_SYSTEM_LIBPNG:BOOL=OFF \
  -DOPTION_USE_SYSTEM_ZLIB:BOOL=OFF
```

**Comment by rempas** [comment]
Hi and sorry for the late answer. Yes I can confirm that there is an error with Linux Lite and that in my home PC which has Arch Linux, the library builds without any problems! Thanks a lot for your amazing work on FLTK!
