### ISSUE TITLE
FLTK 1.4 does not properly size window when using display scaling on Windows 10.

### ISSUE THREAD

**Issue by AlexMax** [fltk/fltk#309]
For clarity, when I say "scaling" I'm talking about Windows 10 Display Scaling, not FLTK app scaling, which is set to `1.0f` for the purposes of demonstration.

Here is what my sample window looks like when my desktop is at 100% scaling.  The drawable window is 320x240 pixels.

![image](https://user-images.githubusercontent.com/23563/145418670-c5e70785-0d1a-4879-8a4f-9a118c38b504.png)

Here is what my sample window looks like when my desktop is at 175% scaling.  The window _should_ be the same size, but the bottom and right are cut off.

![image](https://user-images.githubusercontent.com/23563/145418493-3e5875be-12dd-44d3-a92c-773b1e64555e.png)

- This is with FLTK 1.4 4f2febd
- FLTK 1.3 looks just fine.
- I am using a scaling-aware manifest in my program, so my pixel sizes should be1:1 to my monitor's resolution.

**Comment by Albrecht-S** [comment]
@AlexMax Thanks for the report and for mentioning:

> I am using a scaling-aware manifest in my program...

Can you please test and confirm that the FLTK demo programs and fluid work correctly with your scaling factor?

Can you please try your program w/o this manifest, just to exclude that this causes the issue? (I assume it does!)

If this changes (fixes) the issue, can you please provide a simple, complete test case like the one you showed in your report (we can maybe use test/hello.cxx), together with a minimal manifest and build instructions? Personally I'm not a Windows programmer and don't know how to create a program with a manifest and I assume other devs may not know this either.

If we can see a full example with a manifest we can test this and hopefully fix the issue. TIA

**Comment by Albrecht-S** [comment]
PS: build instructions with CMake (`CMakeLists.txt`) would be appreciated and preferred if you can do this, but otherwise please give us as detailed instructions as you can (e.g. for VS).

**Comment by AlexMax** [comment]
Applying the manifest is actually not necessary to replicate the issue.  Here are instructions that I followed to replicate the exact same issue with FLUID.

- Ensure that you are using a display scaling setting in Windows 10.  I use 175% at 1440p, but I was able to replicate the issue at 125%, it just wasn't as bad.
- Right click on the executable and click "Properties".
- Click on the "Compatibility" tab.
- Click on "Change high DPI settings".
- Click on the checkbox by "Override high DPI scaling behavior.  Scaling performed by:"
- Ensure that the dropdown says "Application".

Following those exact steps, FLUID was pixel-perfect to my monitor and also started exhibiting the same behavior.  I presume that applying the manifest forces this setting on automatically.

![explorer_oThX12yLnn](https://user-images.githubusercontent.com/23563/145487116-904fc993-2664-4cb4-9565-67e36c41b85d.png)

I will get you CMake instructions to reproduce the manifest.

**Comment by AlexMax** [comment]
@Albrecht-S Here is a repo with a slightly modified "Hello World" that applies the manifest file.

https://github.com/AlexMax/fltk-manifest

These manifests are somewhat common in modern Windows C++ development, and is almost a requirement for games.  Games tend to want direct knowledge of the player's actual monitor resolution, and Windows' default scaling behavior tends to turn games without a manifest into a blurry mess.

**Comment by Albrecht-S** [comment]
@AlexMax Thanks for the info so far. I tested the application properties setting dialog some hours ago when I saw your message on Matrix/Gitter/IRC (I'm on matrix from time to time, but we prefer our "forum" fltk.general which you can use like a mailing list. YMMV).

I know (basically) what a manifest is but I didn't know how to create one with CMake or MSVC or whatever.

WRT scaling in general: all FLTK applications on Windows ***should*** automatically switch to the correct system scaling on startup, i.e. honor the system setting, even w/o a manifest. I believe this is documented somewhere but it's too late here to look this up now.

I could set my Win10 system to 125% (max.) and I didn't see any issues with FLTK applications but I tested only a small set. Setting the HiDPI/scaling property to "application" didn't change anything AFAICT. At least I didn't see any obvious cut-offs.

While I'm now going to sleep you may want to try your application w/o the manifest. What happens if you do this? As I wrote above, FLTK tries to "do the right thing" at startup, hence your app should work fine w/o the manifest (maybe even better).

Another **test** is: define an environment variable "FLTK_SCALING_FACTOR=1.75" and run any of the test apps or fluid. I believe this should (a) override the system setting **or** (b) multiply the system scaling factor with 1.75. You can vary the factors, even smaller than 1 but not too small. Please report what you see with these tests.

**Comment by Albrecht-S** [comment]
@AlexMax I was able to build your CMake project (**thank you**) with manifest (FYI: with MinGW cross-compiler on Linux!) and I could also build the same program w/o manifest as `no-manifest.exe`.
[Note: I was curious if it worked with MinGW (yes) cross-compiled on Linux (yes!).]
I had to modify CMakeLists.txt somewhat but that was a minor change.

I copied the resulting .exe files to my Win10 VM and executed them with system scaling factor set to 125% (the maximum I can set).

The result is (see also attached png files):
1. the program with manifest behaves wrong, as reported (manifest.png)
2. the same program w/o manifest works correct (WRT window contents) (no-manifest.png)
3. the program with manifest can be scaled up/down with `ctrl/+/-/0` and reaches somehow a size that everything is contained as required but the w/h ratio might be different (not sure) (manifest-2.png)

It's now definitely too late to investigate further but I confirm there's something wrong.
As a pragmatic work-around I'd suggest to use FLTK programs w/o manifest (or change the HiDPI setting to ... ??)

But nevertheless it's interesting to test this further, maybe we can make it working (as expected) with the manifest as well.
**_manifest.png:_**
![manifest](https://user-images.githubusercontent.com/26235500/145512516-0853cc42-864a-44c6-bf05-ca77b51e1d93.png)
**_no-manifest.png:_**
![no-manifest](https://user-images.githubusercontent.com/26235500/145512531-a5c3b4dc-dede-42b1-a316-89ea085f252f.png)
**_manifest-2.png:_**
![manifest-2](https://user-images.githubusercontent.com/26235500/145512546-d9bf7798-feca-4343-8f11-03b23f8874f4.png)

**Comment by AlexMax** [comment]
Before I start, thank you so much for your investigation into this issue.

However, just so we're on the same page, please note that in the example, I deliberately cut out the bottom and right borders - so if the black border is touching the bottom and right side and you can see the bottom right rounded corner, that's good.  But if the border is getting cut off, that's bad.  I noted this in comments in the source code.

This is what I see for that program with the manifest - you can tell that the bottom and right borders are getting sliced right off.

![image](https://user-images.githubusercontent.com/23563/145515949-69481165-30f1-4b9d-9ee1-306db0952c17.png)

If I use ctrl + to zoom in things start getting.....incredibly strange.

![image](https://user-images.githubusercontent.com/23563/145516047-1f0137f0-9cd2-4910-9280-b65da1ca0120.png)

And then if I zoom out again the app decides it's had enough of me and hides.

![firefox_wo6GGmyZUf](https://user-images.githubusercontent.com/23563/145516159-fd5526af-ed5e-4aaa-9afd-380030dd9c3c.png)

Bizarre, I know. :)  In the interest of full disclosure, I am running 2560x1440p at 175% DPI on Windows 10 Version 21H1 - if your VM hasn't had Windows Updates, it might be a wise idea to upgrade the Windows version to see if anything changed or broke, because most folks running Windows are at the whims of Windows Update.

> As a pragmatic work-around I'd suggest to use FLTK programs w/o manifest (or change the HiDPI setting to ... ??)

If I could, I would.  Unfortunately, I am using FLTK as a boot window to a game that uses the SDL library, and that library currently does not understand Windows high-DPI.  Without a manifest, Windows scales the game automatically, which results in the game thinking it is in a much lower resolution than it really is - thus rendering to a low resolution and then being stretched by Windows.

For me, it would be a "win" if FLTK rendered tiny, but correctly, so I could scale up the app using the FLTK scaling factor.

**Comment by ManoloFLTK** [comment]
FLTK, for the Windows platform, makes this call when opening the display :
SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

My understanding is that it does the same as a manifest for DPI awareness, without it.

@AlexMax : Could you, please, try your program with SDL and without manifest
and report what you get ?

**Comment by Albrecht-S** [comment]
@AlexMax Yes, I've seen what you changed and that the box border should be "at" the window border. For later reference I also note that the demo program's original (FLTK) window size is 320 x 140 which lets me calculate with my scaling factor of 1.25 and a title bar height of about 30 (32) pixels:
```
( 320 x 140 ) * 1.25 = ( 400 x 175 ) + title bar height (30) = ( 400 x 205 )
Adding a 1 pixel border to each side: screenshot pixel size (expected) = (402 x 207 )
```

I can confirm that your demo program is _wrong_ **if the manifest is used** which is shown in my screenshot `manifest.png` above with size 322 x 167 which is a net window size of about 320 x 135 which looks weird (320 is OK, but 135?).

I also wrote that I built your demo program **without the manifest** whose result can be seen in `no-manifest.png` which looks correct. Screenshot size is 402 x 207 which is exactly the expected value (see above).

This makes it clear (to me) that your manifest adds a property that FLTK does not "understand" correctly.

Please don't understand me wrong, this is all only to understand the issue better. Interaction with Windows is not easy, particularly for a toolkit like FLTK that is working on the basics.

As I wrote above and as Manolo asked you as well, would you please test your program w/o the manifest and see what FLTK does with it under your 175% scaling factor, no matter how blurry or wrong the SDL output may be? This would be very helpful to understand the issue.

PS: I see in your latest images that 175% vs. 125% makes a big difference.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Can we test if the application has already been set to HiDPI scaling and not set it if true? Or something like that? Maybe our setting conflicts with the manifest setting...

**Comment by ManoloFLTK** [comment]
@Albrecht: I would like first to get the reply about what happens without manifest, because I believe it should work, SDL included.

**Comment by Albrecht-S** [comment]
> I would like first to get the reply about what happens without manifest

OK, let's see.

FWIW, here is my modified CMakeLists.txt file that works with VS 2019:
```CMake
cmake_minimum_required(VERSION 3.1)
project(manifest VERSION 1.0.0 LANGUAGES CXX)

if(NOT WIN32)
    message(FATAL_ERROR "This bug only applies to Windows.")
endif()
if(NOT MSVC)
    message(WARNING "This bug has not been tested with MinGW, though I'm certain a manifest can be applied with it.")
endif()

# set(FLTK_SKIP_OPENGL TRUE) # My compiled FTLK lacks GL, shouldn't matter.

find_package(FLTK)

message(STATUS "FLTK_INCLUDE_DIR      = ${FLTK_INCLUDE_DIR}")
message(STATUS "FLTK_INCLUDE_DIRS     = ${FLTK_INCLUDE_DIRS}")
message(STATUS "FLTK_LIBRARIES        = ${FLTK_LIBRARIES}")

configure_file(resource.rc.in "${CMAKE_CURRENT_BINARY_DIR}/resource.rc" @ONLY)

set (EXE manifest)
set (RESOURCES "${CMAKE_CURRENT_BINARY_DIR}/resource.rc")
add_executable(${EXE} WIN32 manifest.cpp "${RESOURCES}")
target_include_directories(${EXE} PRIVATE ${FLTK_INCLUDE_DIRS})
target_link_libraries(${EXE} PRIVATE ${FLTK_LIBRARIES} gdiplus)
if(MSVC)
    # We supply our own manifest, don't use the default one.
    set_target_properties(${EXE} PROPERTIES LINK_FLAGS "/MANIFEST:NO")
endif()

set (EXE no-manifest)
set (RESOURCES)
add_executable(${EXE} WIN32 manifest.cpp "${RESOURCES}")
target_include_directories(${EXE} PRIVATE ${FLTK_INCLUDE_DIRS})
target_link_libraries(${EXE} PRIVATE ${FLTK_LIBRARIES} gdiplus)
if(MSVC)
    # We don't supply a manifest, use the default one.
    # Comment the next statement out or not, it doesn't seem to matter
    set_target_properties(${EXE} PROPERTIES LINK_FLAGS "/MANIFEST:NO")
endif()
```

@ManoloFLTK I'll follow this thread but I'll leave the further dialog and investigation(s) up to you. What I would like to know is why the window sizing goes awry when both a manifest sets DPI awareness and we are doing it at program startup. I'd like to see that this is not the case because other users might also use a manifest for whatever reason. We have now a test case and IMHO it should work -- we can't tell the users generally not to use a manifest or not to set DPI awareness.

A general question arises (maybe you know and maybe it's documented): what if the user wants to set a conflicting DPI awareness setting for whatever reason. Is it possible to disable FLTK's automatism?

**Comment by ManoloFLTK** [comment]
@Albrecht-S `why the window sizing goes awry?` I don't know why, but the Windows doc clearly states both mechanisms can't be used together.

`we can't tell the users generally not to use a manifest or not to set DPI awareness`
My view was that DPI awareness would be set inside FLTK, leaving apps free to use manifests for any other purpose. The benefit is that it works with all compilers and build systems.
What do you think of this view? To adopt the manifest mechanism, we would have to clarify how to use it with MinGW.

`what if the user wants to set a conflicting DPI awareness setting for whatever reason`
I'll experiment with function `GetProcessDpiAwareness()` and make sure it can be used after a manifest has set the app's DPI awarenes.

**Comment by Albrecht-S** [comment]
> _why the window sizing goes awry?_ I don't know why, but the Windows doc clearly states both mechanisms can't be used together.

OK, if this is true, then FLTK should detect if a manifest has set any of the HiDPI modes and not set its own mode. That sounds simple, but I'm aware that it may not be that simple. However I'm confident that you can find a solution. TIA.

Let's think the other way around: if the user uses a manifest that sets DPI awarenes it's for a reason. If FLTK would detect this and "do nothing" the app may not use FLTK's enhanced features (particularly not use the initial system scaling factor) but such scaling issues as described here would not happen (hopefully).

**Comment by AlexMax** [comment]
> @albrecht: I would like first to get the reply about what happens without manifest, because I believe it should work, SDL included.

Just tried it.  FLTK worked like a champ, no surprise there.  I also tested Ctrl +/- and it didn't do any of the weird nonsense.

![odamex_tv1Tk2myKo](https://user-images.githubusercontent.com/23563/145655719-998d1d72-b377-49de-96b5-aea532b38960.png)

But my game also seemed to use pixel-perfect resolutions.  I did not expect that to happen.  I double-checked a build without FLTK to make sure my head was on straight and without FLTK the game scales up significantly..

**Comment by ManoloFLTK** [comment]
> 
> Just tried it. FLTK worked like a champ, no surprise there. I also tested Ctrl +/- and it didn't do any of the weird resizing tomfoolery.

@AlexMax : Thanks for this experiment. Could you, please, confirm that also the SDL part of your game runs OK without the manifest?

> But my game also seemed to use pixel-perfect resolutions. I did not expect that to happen - a pleasant surprise, but a surprise nonetheless.

Yes. The goal of FLTK is to provide automatically full pixel resolution to any app.

 >I double-checked a build without FLTK to make sure my head was on straight and without FLTK the game scales up, which is the bad behavior. More importantly, if I build the game with the GUI but comment out any calls into the GUI (which would indeed be possible, as command line parameters can bypass the boot screen and go directly into the game), I also get the undesirable scaled up behavior.

That's because if you don't call the GUI, you don't call the API that does the equivalent of the manifest.

> Also for what it's worth, [SetProcessDpiAwarenessContext](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext) is a relatively recent API addition for Windows, only coming along in Windows 10. [The manifest](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process) came along in Vista and is much more backwards compatible.

FLTK is aware (sic) of that. It searches USER32.DLL for SetProcessDpiAwarenessContext() and calls it if found.
If it wasn't found, FLTK searches SHCORE.DLL for SetProcessDpiAwareness() and calls it if found.
The net result is that the same binary runs on Windows XP, Windows 7, and Windows 10 while being as much
pixel perfect as possible in each situation.

@AlexMax : Do you know how can an app detect whether a manifest has been used to declare its dpi awareness?
I could use this mechanism so FLTK refrains from calling SetProcessDpiAwarenessContext() or SetProcessDpiAwareness() to become manifest-compatible.

**Comment by ManoloFLTK** [comment]
> But my game also seemed to use pixel-perfect resolutions. I did not expect that to happen - a pleasant surprise, but a surprise nonetheless. 

@AlexMax : Does that mean that the SDL part of your app is better with FLTK 1.4 and no manifest than with FLTK 1.3 and the manifest?

**Comment by ManoloFLTK** [comment]
@AlexMax : could you, please, try your app with the last FLTK version ( 0a8b184 ) ? 
It should work both with and without manifest.
Please, report here what you get. TIA.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thank you very much for this commit. @AlexMax's test program works now in my VS 2019 build perfectly with (left) and w/o manifest (right hand side):
![scaling-with-manifest](https://user-images.githubusercontent.com/26235500/145679433-979b117a-1a7a-4262-8f89-50783cef3539.png)

1. The two programs in the upper row were started when system scaling was at 125%.
2. After starting the two demo programs I changed the system scaling to 150%. Both windows scaled up proportionally.
3. The second pair of programs were started when the scaling was at 150% (the '50%' in the window title should read '150%').
4. The screenshot was taken with all four instances active at the same time.

Regarding window sizes: To me it appears to be correct that the left hand side screenshots are smaller (by the scaling factor) because the application says (by manifest) it's DPI-aware and neither FLTK nor Windows scales it up. The right hand side screenshots show that FLTK scales the application up by the system scaling factor - and this even works if the scaling factor is changed while the program is running, i.e. it reacts to screen scaling factor changes at runtime. I can't test with per-monitor screen scaling because I only have one monitor on this system.

This all looks perfectly fine to me now. Awesome!

**Comment by ManoloFLTK** [comment]
One more step in (12d699a).
A more advanced manifest is recognized by FLTK:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >

  <!-- Declare app as DPI aware, so that Windows Vista and later will not
       apply DPI virtualization. -->

  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitor</dpiAwareness>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```
With it, an app does the same as what FLTK does without manifest, that is,
the app detects each display's scale factor.
`PerMonitorV2` instead of `PerMonitor` in the `dpiAwareness` line is also possible.

The simpler manifest (no `dpiAwareness` line) remains accepted.

**Comment by AlexMax** [comment]
> @AlexMax : could you, please, try your app with the last FLTK version ( [0a8b184](https://github.com/fltk/fltk/commit/0a8b1845fe4b32740f7d4d6a9ce128ec9431990b) ) ?
> It should work both with and without manifest.
> Please, report here what you get. TIA.

I tested my app with 12d699a and the program behaved exactly how I would expect it to!

Thank you so much for you time and quick turnaround!

**Comment by Albrecht-S** [comment]
Then I believe this issue can be closed. I set labels `enhancement`, `fixed`, and `Windows`.

@ManoloFLTK, would you like to assign yourself and close?

**Comment by ManoloFLTK** [comment]
@AlexMax : is it conceivable that you test your app with the more advanced manifest posted above? Would SDL behave correctly?
