### ISSUE TITLE
RFE: access the MacOS windowid (or nswin windowNumber) for use by applescripts, screencapture

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#359]
On MacOS, the integer window id for a window is useful for tools like applescript, screencapture(1), etc.

Something along the lines of [this patch](https://github.com/fltk/fltk/files/7797552/get_win_id-patch.txt) to allow an FLTK application to easily access this MacOS-specific integer value.

I hacked that patch together just to get something working for my needs, but I imagine it would be better implemented as a platform.H method/function that takes an Fl_Window and returns this value, but I wasn't sure how to best suggest that approach.

**Comment by erco77** [comment]
I suppose for X windows, get_win_id() [or whatever we end up calling it] could return the X windows equivalent integer that programs like `xwd(1)` use (In the case of `xwd`, for its `-id` option)

**Comment by MoAlyousef** [comment]
I also think exposing a method to get the contentView on MacOS would be useful, libs like libvlc expect a contentView to do any drawing.. Currently one would have to go thru objective-c:
```
NSView *my_getContentView(void *xid) {
    NSWindow *win = (NSWindow *)xid;
    return [win contentView];
}
```

**Comment by wcout** [comment]
> I suppose for X windows, get_win_id() [or whatever we end up calling it] could return the X windows equivalent integer that programs like xwd(1) use (In the case of xwd, for its -id option)

Not really sure what you are needing, but at least for X11 there is `fl_xid(const Fl_Window *)` to get that window handle, and IMHO fl_xid() is already cross platform.

**Comment by erco77** [comment]
@wcout true, on X windows `fl_xid(win)` does return the X window id (useful for `xwd(1)`), but on MacOS fl_xid() does _not_ return the equivalent "window id" that e.g. 'screencapture -l' can make use of (for screenshots of a particular window)

So for access to the MacOS "windowid" (as screencapture(1) calls it) aka. the windowNumber (as it's referred to in the Objective C API), a separate accessor method is needed. And if supplied as a cross platform method name, what I'm suggesting in the X windows case is it simply return the same value fl_xid() does.

I'm not sure if Microsoft Windows has such a thing. On that platform the virtual method could simply return 0.

**Comment by ManoloFLTK** [comment]
Function fl_xid() returns on all platforms a Window quantity which is what the OS uses to identify
a window. macOS is somewhat special in using another quantity for some operations such as
the screencapture command. So I'm not sure a new cross-platform function is necessary; access
to the macOS windowId may be enough ?

I'd like to mention the cross-platform API (new in 1.4) :
  [Fl_RGB_Image *fl_capture_window(Fl_Window *win, int x, int y, int w, int h)](
https://fltk.gitlab.io/fltk/group__fl__drawings.html#gaf505e47f47ff011344d769e2f4b74067)
which captures all or part of any FLTK window with its full resolution on retina.

**Comment by Albrecht-S** [comment]
> So I'm not sure a new cross-platform function is necessary; access to the macOS windowId may be enough ?

@ManoloFLTK Yes and no: IMHO we should not force the user to use platform macros (`__APPLE__`) to encapsulate function calls, hence the function should be available on all platforms but return 0 on "other" platforms [1]. It should be documented precisely so users can get the macOS WindowID if they need it for some reason (including commandline usage, for instance in a pipe).

I wouldn't mind if Unix/Linux/X11 would return the same as `fl_xid()` because this could be used in the same way on the commandline as the macOS WindowID as Greg wrote above.

I also don't know of an equivalent window id for Windows. The `HWND` returned by `fl_xid()` and used internally doesn't seem to be appropriate here, so I do also suggest that Windows (and any other platform) would return 0 [1].

[1] If 0 is a legal window id on macOS or X11 we should change the default / unknown window id returned to -1 rather than 0 or use a separate return code (success or fail) and return the value in a reference argument.

I can see one problem though: what would be the **cross platform type** of the return value (window id)? Int, long, unsigned int, ... ?

**Comment by ManoloFLTK** [comment]
Added new member function `fl_uintptr_t Fl_Window::os_id()` with meaningful implementations for the X11 and macOS platforms.
