### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [fltk/fltk#368]
Hi I have some questions regarding this project.

1. Is it retained or immediate or a combination of both?
2. Does it support Android?
3. Does it support either html/css and/or web applications?

**Comment by MatthiasWM** [comment]
1. It's a combination. Users draw graphics in immediate mode by overriding the draw() functions in widgets. However the widgets themselves know how to draw themselves, and since the user would build a hierarchy of widgets, that part of the library draws in a retained mode.
 2. Yes and no. I have a working version of an Android port that has been stuck in Alpha for quite a while.
 3. We support a subset of HTML in the Help Viewer. fl_open_uri can be used to open more complex documents in an external viewer. We decided against using HTML in labels etc. as it is quite slow in comparison (FL in FLTK stands for Fast and Light)

**Comment by Raj2032** [comment]
Hey mate, thanks for your response :)

Hopefully the android version can come out sometime :)

One other question, do you use openGL or something else?

**Comment by MatthiasWM** [comment]
I use OpenGL, yes. Or do you mean for Android? The current implementation does not use OpenGL but render pixel by pixel as a proof of concept.

**Comment by Raj2032** [comment]
Ah right thanks mate :)

**Comment by erco77** [comment]
OK, closing this.

All devs: Do try to remind users that ask general use questions in github issues to, in the future, ask such questions on fltk.general instead, so all can benefit from the question/answer conversation. We are just using issues for bug reports.

I guess it's OK to go ahead and answer the question here anyway, we just don't want it to keep happening.

I believe Albrecht is working on a way to make a "how to" page show up on the github "New Issue" page to make this clear.

**Comment by Raj2032** [comment]
@erco77 Sorry I missed this question, thanks

**Comment by Raj2032** [comment]
@erco77 we could try adding the "Discussions" as well on this repo (others have done this).

**Comment by Albrecht-S** [comment]
@Raj2032 Thanks for the heads-up. We're considering to add and use GitHub Discussions but when I last looked at it it was still experimental or "beta" state. Since we have a working discussions group and don't want to split discussions we will likely switch only if we are sure that we can close our discussions group / forum [fltk.general](https://groups.google.com/g/fltkgeneral) and move entirely to GitHub Discussions.

**Comment by Raj2032** [comment]
@Albrecht-S No worries and I understand mate =D
