### ISSUE TITLE
Not enough contrast on automatic colors

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#370]
There is a problem that some colors used by FLTK are automatically generated. That in itself isn't a problem, but it unfortunately often generates colors with insufficient contrast. And applications have no decent way of overriding this.

The core of this is that `fl_contrast()` is used to generate some colors. And it doesn't have a good algorithm for determining contrast (which is very hard).

Fixing `fl_contrast()` is a massive thing, which probably requires implementing [APCA](https://github.com/Myndex/SAPC-APCA). Right now it doesn't even linearize values properly¹. So realistically more defined colors are probably needed for applications so that manually checked values can be directly added.

For us the problem has been a contrast color to `FL_SELECTION_COLOR`. If we use GNOME's default blue (53,132,228), or macOS blue (0, 122, 255) we get black as the contrast color. This an entirely insufficient contrast, as can be tested using this online tool:

https://www.myndex.com/APCA/

We can also see that both GNOME and macOS uses white as the contrast color in these cases.

For now the compromise seem to be the color (29, 113, 215) which is the lightest color we can use and still get white as the contrast color.

Adding a `FL_SELECTION_CONTRAST_COLOR` or something could be a way forward.

¹`fl_color_average()` also forgets to use linear values, so that probably needs to be fixed as well

**Comment by CendioOssman** [comment]
For a test I tried implementing WCAG 2, but it also calculates the incorrect thing here.

**Comment by CendioOssman** [comment]
Actually APCA doesn't look to be that complicated. See the JavaScript implementation here:

https://github.com/Myndex/apca-w3/blob/master/src/apca-w3.js

**Comment by MatthiasWM** [comment]
The current implementation uses the original color if the difference in luminance Is more that 38%. If it is less, the foreground is set to white if luminance is under 50%, and black if its over. Blue contributes only 11% to brightness in a linear system, and even less in a log system, so (0, 122, 255) as a background is (0*30 + 122*59 + 255*11)/256 = 39% bright and should absolutely return white as the contrast color. Gnome's blue at (53,132,228) still returns 46%, so the contrast color should absolutely be white (tested and working).

Maybe you see this in Fl_Tabs? The tabs in Fl_Tabs don't calculate colors, but use Fl_Tabs::color and Fl_Tabs::selection_color for text and background of selected tabs, and child::color and child::selection_color for unselected tabs, which end in low contrast, if default colors are used.

**Comment by CendioOssman** [comment]
We saw this issue with `Fl_Button`, which does `labelcolor(fl_contrast(c, col));`. Do you get white if you test that in your end?

**Comment by wcout** [comment]
> The current implementation uses the original color if the difference in luminance Is more that 38%

So as the difference in luminosity between black (0/0/0) and Gnome's blue (53,132,228) actually is calculated to be 46% in `fl_contrast()`, it will return the "original color" - black (0,0,0). That's what the OP sees.

BTW: You are calculating the luminosity here with ( sum ) / **256**, but the code in `fl_contrast()` does ( sum ) / **100**. Which one is right?

**Comment by Albrecht-S** [comment]
As @MatthiasWM wrote the algorithm used in `fl_contrast()` uses four (essentially three) cases. The first (two) case(s) use(s) the difference of the two calculated luminosities (basically `abs(L1-L2)`), the other two cases select either black or white. The formula is simplified and may not return _"optimal"_ values for several reasons:
1. No gamma correction
2. Assumed linearity (instead of power of 2 and sqrt as in other formulas)
3. Arbitrary threshold 99 which is equivalent to 99/256 = 38.67 % (as @MatthiasWM wrote)
4. Assumption that 127 (aka 50%) is the threshold to select between black and white.

Points 1 and 2 would obviously require more CPU power.

Point 3 is questionable. Whatever we use for 1 and 2, what should be the threshold to use the "original" background and foreground colors? Is 38% enough contrast? This is where I patched the FLTK library for an older application and changed 99 (38%) to a higher value. This improved `fl_contrast()` by switching "earlier" to black or white rather than accepting the original colors. IIRC I used a slightly increased value of 103 or 105 or something like that. In other words: the original colors would only be accepted if the difference of their calculated luminosities was greater than 41% (105/256).
 
Point 4 obviously depends on the "correct" calculation of the brightness (luminance) of the background color. The value 127 (~50%) might also be changed to prefer either black or white.

I can't tell if changing points 1 and 2 would have more benefits (better results) than drawbacks (more CPU power) but changing the threshold (point 3) could be done easily and could really improve the results of `fl_contrast()` - no matter how we decide about 1 and 2.

**_Possible solution with minimal effort:_** the highest possible contrast between foreground and background can obviously be 100% (black and white). The minimum contrast if we select either black or white would be 50% (if the background luminosity is 50%). Hence the values between 38.67 % (99, as it is now) and 50% (127) could be chosen as the threshold in point 3 above in `fl_contrast()` and would likely improve the contrast in border cases. The price we'd have to pay would be that we switch "earlier" to black or white.

**Comment by MatthiasWM** [comment]
I will in the next days:
 ☐ write a rainbow contrast test
 ☐ improve the cut-off value
 ☐ try non-linear luminance calculation
 ☐ provide an API for a user-defined contrast function

**Comment by Myndex** [comment]
Hi @MatthiasWM @CendioOssman @Albrecht-S 

If it's helpful, I have a quick Gist with a CodePen and repo, that is all about flipping texgt from black to white, and related issues: [**Let's Flip For Color**](https://gist.github.com/Myndex/e1025706436736166561d339fd667493#lets-flip-for-color)

But also, as it is mentioned in this thread, I'd like to add an APCA Status Update:

I just published APCA W3 0.1.2, which includes some key new features, such as an  integrated dynamic font lookup table that automatically indicate the appropriate font/weight, alpha blending, displayP3 support, and a "reverseAPCA" where you can specify a contrast value, and either the bg or text color, and it generates the missing color.

It is on npm, ` npm i apca-w3 `

It has one dependency, which I've also placed on npm: ` npm i colorparsley `

Also, Bridge-PCA is a drop-in replacement for WCAG 2's math. See that tool at https://www.myndex.com/BPCA/

Bridge-PCA is backwards compatible with WCAG 2, meaning it meets or exceeds WCAG 2 for compliance purposes, (including the areas where WCAG 2 rejects colors incorrectly). That said, Bridge-PCA is less flexible than the basic APCA guidelines.

Please let me know of any questions. The main repo discussion area is open with active discussions on APCA and related technologies: https://github.com/Myndex/SAPC-APCA/discussions

Also, there is this Linktree of all the main resources listed together:  https://linktr.ee/Myndex

Thank you!

Andy

**Comment by Albrecht-S** [comment]
@Myndex Andy, thank you very much for your comment and the links given. I read and tried to understand your article [Let's Flip For Color](https://gist.github.com/Myndex/e1025706436736166561d339fd667493#lets-flip-for-color) which is a very interesting and potentially helpful resource.

However, I have three questions. The **first question** is about licensing. Our FLTK project uses LGPL licensing with exceptions for static linking. Would usage (i.e. copying) of your code in our library be compatible with your license? I understand that using your (javascript) code (Bridge-PCA) in web applications is free but that doesn't apply to us as developers of a C++ library that can be used by others. Can you help us further with the license question?

The **second question** is about [our implementation of `fl_contrast()`](https://github.com/fltk/fltk/blob/4618fa9053217fb6c894cc10dd0ea23a9238a6e6/src/fl_color.cxx#L178). (BTW: I learned from your text that "luminosity" should be replaced with "luminance".) I'll try to describe the issue first: additionally to your article we need to decide first if the **given** text color _"contrasts sufficiently with the background color"_. If yes, the given text color is used unchanged. If not we need to decide between black and white.

We would have to calculate the contrast between the given text and background colors first and decide if this is _"enough contrast"_. How would we do this if the calculated values L1 and L2 are the text and background color luminance values resp. (division, subtraction, abs(L1² - L2²), anything else?), and what would be a useful threshold to determine "enough" contrast? [1]

Only if the question above would yield "not enough contrast", the second step would be what you describe in your article, i.e. use either black or white. Does this sound correct?

Note that we need a simple algorithm. I'm not sure how much CPU resources matter if we use e.g. `pow(sR/255.0,2.2)` and `pow(Ys,0.678) < 0.5` but if it improves legibility I think we could likely do better than with our current algorithm. Note also that changing text sizes in order to improve legibility is not applicable in this context (this would have to be done in user code).

That said, I also understand your ["40% Flip" rule](https://gist.github.com/Myndex/e1025706436736166561d339fd667493#the-40-flip), but (**third question**) why are you using both 40% and 36% (0.36) in your explanations? Is "40%" only meant as a simplification and 36% would be the real value to be used?

[1] Disclaimer: I'm not a color/contrast expert and even [your README file](https://github.com/Myndex/bridge-pca#bridge-pca-for-wcag_2) contains acronyms and references to other articles/specs that I don't know or understand w/o much further reading. Any help with a "simple" algorithm we can use to improve our `fl_contrast()` function would be very much appreciated.

**Comment by Albrecht-S** [comment]
FTR: I was curious and ported function `APCAcontrast(L1, L2)` to C and executed an example program with 10 different color combinations one million times, i.e. 10 million executions of `APCAcontrast(L1, L2)`. This includes 20 million luminance calculations by function `sRGBtoY()`.

Total CPU time used on my Intel i7 (on Linux) was less than 2 seconds on 1 core, i.e. 0.2 µs per contrast calculation, or 5 million contrast calculations per second. Even on a much slower CPU (factor 1:100) this would be 50,000 contrast calculations per second which would IMHO be sufficient for a GUI program.

**Comment by Myndex** [comment]
Hi @Albrecht-S 

Regarding "Flip for Color" that is a somewhat "down and dirty" explanation of when to flip from black to white. Certainly if you want to check for more nuanced contrasts, then APCA is the more complete solution.

### Some things to mention:

1) Contrast is substantially a function of "spatial frequency" as opposed to a pair of colors. That is, the weight and size of a font or graphical element is more important to consider—the choice of colors that are needed are dictated by size/weight.

2) Regarding the flip point:

> _...why are you using both 40% and 36% (0.36) in your explanations? Is "40%" only meant as a simplification and 36% would be the real value to be used?_

So, all things human perception have "wiggle room" and "ambiguity" once we are well above the threshold of the just noticeable differences (JND).

In the case of the flip point, for sRGB it is in the zone from about 34 Y to 42 Y, and in that zone varies a bit based on the hue of the background due to various issues. That zone is also the "weakest" contrast area, where neither white nor black provide really good contrast. This is why in the FlipForColor CodePen, the example font gets larger through that area.

3) There are much more complicated visual perception models — a goal of APCA is to specifically tune it for readability, and keep it as simple as possible.

> _i.e. 0.2 µs per contrast calculation, or 5 million contrast calculations per second. Even on a much slower CPU (factor 1:100) this would be 50,000 contrast calculations per second which would IMHO be sufficient for a GUI program._

Thank you for this... I suppose this means the math optimizations were worth it...? (or, that I optimized more than actually necessary, LOL)...

4) On resources and documentation

> _I'm not a color/contrast expert and even [your README file](https://github.com/Myndex/bridge-pca#bridge-pca-for-wcag_2) contains acronyms and references to other articles/specs that I don't know or understand w/o much further reading. Any help with a "simple" algorithm we can use to improve our fl_contrast() function would be very much appreciated._ 

Yea, sorry I do tend to get mired in jargon... this is a field I've been in and fascinated by for most of my *life*, and yea it is arcane, abstract, frustratingly non-intuitive, and difficult to explain simply.

The super short answer is that color, and contrast, are not real. They are only perceptions. What you see and believe to be reality is in fact a homogenized representation that your visual cortex (and other neurology) has created for your conscious viewing enjoyment. <sup>_see footnote 1_</sup> 😎 

### _Once you accept that, the rest is easy._

I have a linktree that is intended to make the learning curve easy. Start at the top, with the simplest plain language "Why APCA" at the bottom of the linktree you'll see things like the white papers, etc.

### https://linktr.ee/Myndex

And please feel free to ask questions, etc!


Thank you,

Andy


_Footnote_
1) _In the image below, both yellow dots are emitting the same exact light from your display. And neither dot is yellow, either. They are both separate red and green at the same time. Both dots are about ` #d18600 ` for sRGB. The fact that they both look different is due to how your neurology interprets them. This is not an optical illusion, it is a neurological illusion._

![Yellow Dots checkers Optical_grey_squares_orange_brown_(opaque)](https://user-images.githubusercontent.com/42009457/165189590-5183f51b-f7ee-45a2-8032-1ace2403be2c.png)

**Comment by Albrecht-S** [comment]
@Myndex Hi Andy,

thank you very much for your detailed explanations and further information. I'll dig deeper following your links and more. This will take some time and I'll ask if I have more questions. That's very likely.

As for the image with the "neurological illusion": I had seen this before somewhere, maybe on TV. Thanks for posting it here, it's very informative and I'm pretty sure it's helpful for other readers as well.

I would also like to thank you for all your work on the standards and I hope we can get an official APCA standard soon (if I'm not missing anything and it is already "official"). I read some of the comments on the legal stuff (particularly in the US) and the conflict between WCAG_2 and APCA - very interesting.

**Comment by Albrecht-S** [comment]
@MatthiasWM I assigned this issue to myself because I'm now actively developing an update.

**Comment by Albrecht-S** [comment]
FYI: I created mainly two new features:
1. I added a new internal `fl_contrast()` variant that works better WRT visual contrast perception
2. I added a function to enable users to implement and use their own "custom" `fl_contrast()` variant

The new 1.4 `fl_contrast()` function is based on the [CIELAB color model](https://en.wikipedia.org/wiki/CIELAB_color_space) and calculates the contrast value more according to human visual contrast perception, at least **much better** than the old 1.3 function. This new function linearizes the sRGB color values etc. as discussed above. This will be the **new default** `fl_contrast()` function.

The old 1.3 `fl_contrast()` function is still available but must be requested (opt-in). Although the new function is much better I left the old function because it may perform better (only integer arithmetic) than the new one that uses floating point arithmetic including `pow().` This may be useful for embedded systems or otherwise CPU constrained systems (although I personally don't think that this would make a big difference).

Users will be able to implement and register their own `fl_contrast_xxx()` function which will be called internally whenever `fl_contrast()` is called. This would be an option for users wanting an even better contrast function.

APCA will not be available in FLTK 1.4.0 because of licensing constraints (this is how interpret their license). If the APCA license will be opened for other usage than web projects and not have even more restrictions we may implement APCA in the FLTK core as another option.

**Comment by Albrecht-S** [comment]
@CendioOssman You wrote
> If we use GNOME's default blue (53,132,228), or macOS blue (0, 122, 255) we get black as the contrast color. This an entirely insufficient contrast...

I tested specifically these two colors with the new algorithm and my test program got FL_WHITE as the contrast color (and FL_BLACK with the "legacy" mode as you wrote).

I'm posting two screenshots from my test program which will be included in the FLTK repository together with the update:
1. Legacy (FLTK 1.3) mode:
![fl_contrast_legacy](https://user-images.githubusercontent.com/26235500/179744954-823fa4e3-643a-436f-9689-56496f8f0ea5.png)

2. CIELAB (FLTK 1.4) mode:
![fl_contrast_cielab](https://user-images.githubusercontent.com/26235500/179745064-39747236-9b21-4efe-aa7d-4c4b9962d98b.png)

The special test value can be seen in field '255' but you can visually compare the other fields as well. Although the algorithm is final there are some fine tuning options which are still work in progress but the images should show the major differences. Hint: load both screenshots in browser tabs and then switch tabs...

**Comment by Myndex** [comment]
Hi @Albrecht-S 

Just FYI, the current wording is particularly strict because this is both in a beta stage AND destined for standards adoption. Due to some misuse, we've had to "reign in" some things, to ensure that old or obsolete versions can be removed, and also to define the chunk that is destined toward a "free for use" model, vs value added components that are per-license only.

So, for use in a non-commercial GUI library seems that it should be okay—how are you using it? Is it just for selecting colors inside the library?

Where we have certain concerns is the algorithm itself (the base version) being used directly in certain applications that really need the more complete models.

Also, as a GUI library, you would be need to be the one "excluding", only that you have the appropriate disclaimer as needed. Write me direct at legal@myndex.com, and we'll sort it out.

Thank you for reading!

Andy

**Comment by Albrecht-S** [comment]
@Myndex Hi Andy, thank you for your prompt reply. This seems to indicate that it might be possible to use APCA in a future FLTK version. I'll send you a private mail as suggested to sort the legal aspects out.

> So, for use in a non-commercial GUI library seems that it should be okay

Great, thanks.

> how are you using it? Is it just for selecting colors inside the library?

Short answer: yes. Long answer follows in my next comment.

**Comment by Albrecht-S** [comment]
@Myndex In FLTK we use `fl_contrast(fg, bg)` as [documented here](https://www.fltk.org/doc-1.4/group__fl__attributes.html#ga54d75920c0484916cd6b2101937ec5ff) to return a color with "sufficient" contrast: either the foreground color or black or white.

The current implementation is fontsize agnostic. The future version has two more parameters:
```C++
Fl_Color fl_contrast(Fl_Color fg, Fl_Color bg, Fl_Fontsize fs = 0, int context = 0);
```
You can view the new documentation at the same location as soon as I pushed a commit but this may take a few more hours.

The context parameter is intended to differentiate text from other objects (icons for instance) but this is not yet implemented in any way.

The fontsize (fs) parameter will be used to define what contrast value is "sufficient". My current **experimental** (not public) evaluation implementation uses an inverted and interpolated version of your font lookup table to determine "sufficient" contrast per font size (at font weight 600):
```C++
  int Lc[20] = {
  // 10   11   12   13   14   15   16   17   18   19  // font size
    125, 115, 110, 105,  95,  75,  70,  65,  60,  58, // min. Lc
  // 20   21   22   23   24   25   26   27   28   29  // font size
     56,  55,  54,  52,  50,  48,  47,  46,  45,  43  // min. Lc
  };
```

These values are experimental but I believe we can't use font weight internally in any way because we don't "know" what exact font (weight) the user is applying to the calculation.

As opposed to your suggestion to use a larger font if the contrast is loo low, we require a higher "sufficient" contrast if the font is smaller. This sufficient contrast is only used in the first part of the calculation. If the contrast is sufficient the foreground color is returned, otherwise black or white depending on the background color.

I hope this was helpful. Thanks for reading.

Albrecht

**Comment by erco77** [comment]
Regarding the image comparison of "legacy" vs. "cielab",
here's also an [.mp4 video comparing the two images](https://www.seriss.com/people/erco/tmp/no-rsync/fltk-issue-370-legacy-cielab.mp4); a 5 frame cycle at 1 fps.
(Right-click on the video while it's playing to set it to "Loop", to loop indefinitely)

**Comment by Albrecht-S** [comment]
Commit 78cf29ba29aede2f0463e1747dc728787428d543 implements the new `fl_contrast()` method based on the CIELAB (L\*a\*b\*) color model which yields much better contrast results as can be seen in the screenshots above. This is now (i.e. in FLTK 1.4.0) the default contrast mode; users don't need to change their programs. The new demo program `test/contrast.cxx` can be used to experiment with the new contrast mode and compare it with the old ("LEGACY") contrast results (see also screenshots above).

Notes:
- There are no plans to implement this in FLTK 1.3.x (too many changes).
- For backwards compatibility the old (1.3.x) mode can be selected in 1.4.0 by calling `fl_contrast_mode(FL_CONTRAST_LEGACY)`.
- Users can implement their own contrast algorithms using `fl_contrast_mode(FL_CONTRAST_CUSTOM)`.
- For more information please refer to the [online documentation](https://www.fltk.org/doc-1.4/group__fl__attributes.html#ga062d91541bc9665836f715373b711f8d).
- There are currently no plans to implement the APCA algorithm (lack of a usable licence). This may change in the future, and we can implement a new function that implements APCA at any time.

All feedback would be appreciated. Thanks in advance.

**Comment by Albrecht-S** [comment]
@CendioOssman Hi Pierre, can you confirm that the new contrast algorithm fixes your issues? I'd really like to close this issue. Thanks in advance for testing and I'd really appreciate your report.

**Comment by Myndex** [comment]
Hi @Albrecht-S 

I'm sorry that the current APCA licensing is getting in the way, we are working on this issue.

In the meantime, I'd like to mention we have another contrast method, **_DeltaPhiStar_**, which is simpler than APCA, and it integrates with D65 CIELAB.

The repo and information is: 

https://github.com/Myndex/deltaphistar

**Comment by Albrecht-S** [comment]
Hi Andrew (@Myndex)

thanks for your comment and the link to the **_DeltaPhiStar_** contrast method. I'll have a look at it and see if we can use this as an option.

I had to make a decision to get closer to the release of FLTK 1.4.0 but we can now add new contrast methods easily, and users can add their own contrast functions - even APCA if they like.

If **_DeltaPhiStar_** can be used by our library I'll consider adding it. Thanks.

I'm still open for adding APCA if we can find a license that allows us to integrate it.

**_Happy new year to all!_**

**Comment by CendioOssman** [comment]
> @CendioOssman Hi Pierre, can you confirm that the new contrast algorithm fixes your issues? I'd really like to close this issue. Thanks in advance for testing and I'd really appreciate your report.

Sorry for the delay. I've finally done some testing of this.

Unfortunately, it doesn't work when I test it here. The contrast application shows that white should be used of the colours I initially mentioned, but it doesn't seem to work when I actually use those colours on a button.

I tried modifiying one of the test applications, as such:

```diff
diff --git a/test/resize.fl b/test/resize.fl
index 52a867c30..51164bc0c 100644
--- a/test/resize.fl
+++ b/test/resize.fl
@@ -35,13 +35,13 @@ w->position(w->x(),w->y()-50);}
       label grow
       callback {Fl_Window* w = o->window();
 w->size(w->w()+20, w->h()+20);}
-      xywh {30 130 110 40} labelfont 1 labelsize 18
+      xywh {30 130 110 40} color 0x3584e400 labelfont 1 labelsize 18
     }
     Fl_Button {} {
       label shrink
       callback {Fl_Window* w = o->window();
 w->size(w->w()-20, w->h()-20);}
-      xywh {30 190 110 40} labelfont 1 labelsize 18
+      xywh {30 190 110 40} color 0x007aff00 labelfont 1 labelsize 18
     }
     Fl_Box {} {
       label {This is a test of program-generated resize() of a window.  The window should move or resize once when each button is clicked.  The program and window manager should not go into fits echoing resizes back and forth!} selected
```

I also tried adding `fl_contrast_mode(FL_CONTRAST_CIELAB);`, but it didn't help.

**Comment by Albrecht-S** [comment]
@CendioOssman Thanks for testing. You wrote:
> ... it doesn't seem to work when I actually use those colours on a button. ... I tried modifiying one of the test applications [+ patch]

That's strange, but the devil is in the details (bad example, Murphy's law?). Unfortunately `Fl_Button::draw()` does **not** apply `fl_contrast()` unless
```
(labeltype() == FL_NORMAL_LABEL && value())
```

In your test case the first condition (labeltype) is true but the second is only true while you click and hold the button. However, then another background color (`selection_color()`) kicks in.

Please apply the following short patch as a **_workaround for your test case_**. This shows the desired effect for me. Why this particular button draw code distinction was chosen I do not know. This is another issue which I'm investigating independently.

Note that you can optionally set different `selection_color()`s which are used when you click and hold the button(s).

```
diff --git a/src/Fl_Button.cxx b/src/Fl_Button.cxx
index dec92d483..d97251f42 100644
--- a/src/Fl_Button.cxx
+++ b/src/Fl_Button.cxx
@@ -69,7 +69,7 @@ void Fl_Button::draw() {
   Fl_Color col = value() ? selection_color() : color();
   draw_box(value() ? (down_box()?down_box():fl_down(box())) : box(), col);
   draw_backdrop();
-  if (labeltype() == FL_NORMAL_LABEL && value()) {
+  if (labeltype() == FL_NORMAL_LABEL /* && value() */ ) {
     Fl_Color c = labelcolor();
     labelcolor(fl_contrast(c, col));
     draw_label();
```

> I also tried adding fl_contrast_mode(FL_CONTRAST_CIELAB);, but it didn't help.

This doesn't have an effect because it is the default. Please remove this for a "normal" test. You can use `fl_contrast_mode(FL_CONTRAST_LEGACY);` though to see the "original" (1.3.x) behavior.

**Comment by Albrecht-S** [comment]
> Why this particular button draw code distinction was chosen I do not know. This is another issue which I'm investigating independently.

OK, after thinking about it for a while, here's an explanation: this code assumes (or the original author assumed) that you set the button's `color()` and `labelcolor()` in a sensible way and hence doesn't use `fl_contrast()` for the "normal" button view. Only if it is clicked (selected, value() is 1), the background color is changed to the selection color which is variable (either set by the user or by the system's theme) and only then `fl_contrast()` is applied. This seems sensible so far.

However, why this also depends on the `labeltype()` is still an open question. It would perhaps be a problem if you used `FL_SHADOW_LABEL` and the `labelcolor()` is set to `FL_WHITE` by `fl_contrast().` Or maybe something similar...

**Comment by CendioOssman** [comment]
Sorry, you are right. That was not a good test case. The problem wasn't with `color()`, but rather with `selection_color()` as there is no `selection_labelcolor()`.

If I do this test instead, then everything now works well:

```diff
diff --git a/test/bitmap.cxx b/test/bitmap.cxx
index a182096d5..c87506bb9 100644
--- a/test/bitmap.cxx
+++ b/test/bitmap.cxx
@@ -58,8 +58,10 @@ int main(int argc, char **argv) {
   insideb->callback(button_cb);
   overb = new Fl_Toggle_Button(25,75,100,25,"text over");
   overb->callback(button_cb);
+  overb->selection_color(fl_rgb_color(53,132,228));
   inactb = new Fl_Toggle_Button(125,75,100,25,"inactive");
   inactb->callback(button_cb);
+  inactb->selection_color(fl_rgb_color(0,122,255));
   w->resizable(w);
   w->end();
   w->show(argc, argv);
```

Both buttons now correctly get a white text colour when pressed.

This is also the use case I was originally trying to fix for TigerVNC.

**Comment by Albrecht-S** [comment]
@CendioOssman Pierre, thank you for confirmation. Closing this issue now.

If there's need for other contrast algorithms another issue should be opened.
