### ISSUE TITLE
Not possible to raise font size

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#371]
Modern standard font size is around 11pt/13px, which is noticably larger than what FLTK is designed for. This makes FLTK applications look out of place, and is also causing problems with usability as modern text rendering is also designed with larger text in mind.

You can easily increase the font sizes in FLTK, and the sizes of widgets is under application control. Unfortunately there are a bunch of other hard coded sizes that the application cannot touch. One example is the distance between check marks and the text. Such things should scale with the text size and/or widget size.

Tested with 1.3, but I can see the same hard coded numbers in 1.4 so I assume the issue is still present.

**Comment by Albrecht-S** [comment]
Please be more specific. "One example" is not suitable to investigate and base work on.

What we'd need is
- which constants should be adjusted or varied by font or widget size
- what do you expect
- any more information we can use to change things

**Comment by erco77** [comment]
It would probably be good if we could get rid of _all_ hard coded numbers in FLTK, providing an API to change them, with the current values as defaults. Identifying them all is a chore, but perhaps just start with checkbox and go from there.

OP: in case you're working with a deadline for release on VNC, when I've run into the check mark issue, or issues like those with limitations of labels, I usually take one of two approaches:

- Add leading spaces to the label to add space (easy solution, but hacky)
- Derive a custom class, e.g. "MyCheckbox", from Fl_Group, and put the checkbox and an Fl_Box next to it to act as the more controllable label, allowing custom placement with your own API to manage

**Comment by Albrecht-S** [comment]
> This makes FLTK applications look out of place, and is also causing problems with usability as modern text rendering is also designed with larger text in mind.

What exactly does this mean, what is "modern text rendering", what are the issues?

Is it maybe because TigerVNC has problems to render text and widgets from remote systems?

**Comment by Albrecht-S** [comment]
@CendioOssman Another question: you wrote
>Modern standard font size is around 11pt/13px, which is noticably larger than what FLTK is designed for

According to the code base FLTK's standard text (font) size is 14 (px), so what does the above statement mean? I don't understand, please enlighten me.

**Comment by erco77** [comment]
@Albrecht-S I'm guessing OP is making an RFE, asking for general margin control for widget labels (I think?), and perhaps in a more general way, having as many hardcoded values in widgets as possible be adjustable via an API, esp. with respect to changing font sizes. I ran into all this early on too.

I realized looking at fltk's innards that the base widgets were not designed to include the general concepts modern UI's, like margins (top/bot/left/right), font size offsets (like the normalized 'em' values in html (e.g. font-size: 1.2em to make the font 1.2x larger), and I suppose, when fonts are enlarged, some kind of scaling of the margins (so e.g. the 5 pixel margins for a small font would be larger for a large font).

At least I think that's what he's getting at.

I think the best we can offer is an API to change any hard coded margins, as the widgets were not designed to do things like autoscaling and such.

**Comment by MatthiasWM** [comment]
I know that there are a few hardcoded values that could be changed or be a function of a related font height. We have already a way to set the width of scroll bars on a [per-application](https://www.fltk.org/doc-1.4/classFl.html#aa6d2b6e0d640b81c6ec44d0164ec0f91) base, as well [as per-widget](https://www.fltk.org/doc-1.4/classFl__Scroll.html#a40c34a9fd755968a283e247fed068dd4). You can set the line spacing for [menus](https://www.fltk.org/doc-1.4/classFl.html#a6eaabff6af047485f864dbc66cf5978d).

It would certainly be possible to add this for other fixed values as well, like margins. It would be great to have a list to find the really important settings, so we can still stay Fast and Light

We should come up with a smart system to store these settings. There is already a tendency to add the same `fontsize(), fontcolor(), labelsize()` list of parameters after every non-standard widget. Instead of random global settings and massive attribute lists, I would like to suggest the introduction of styles.

**Comment by Albrecht-S** [comment]
> I would like to suggest the introduction of styles

AFAICT from the previous attempts (FLTK 2 and 3) styles are (were) only a shortcut for setting some of the existing widget attributes in another way. This wouldn't help with the problem at hand.

But I agree that we have too many hard coded values in all widgets. Besides sizes this concerns also colors (e.g. FL_BACKGROUND2_COLOR etc.).

This could be attacked in FLTK 1.5 (my guess) because FLTK 1.4 should be released soon.

**Comment by Albrecht-S** [comment]
@erco77 "I'm guessing OP is making an RFE, asking for general margin control for widget labels".

My point is that he said "Modern standard font size is around **11pt/13px**, which is noticably larger than what FLTK is designed for" but FLTK's standard font size is **14 px** which is larger than what he wrote. This is the opposite of what he said, hence I asked him to elaborate. If FLTK's standard size is 14 you can't assume it was **designed for** smaller for smaller sizes.

**Comment by MatthiasWM** [comment]
I agree that styles are an FLTK 1.5 issue. 

It's much more though. It avoids repeating the same attributes over and over and makes FLTK's footprint much smaller.

Think of how styles are used in text editors like MSWord: if you want a headline, you just set the style to _headline_. You wouldn't want to set _size 21, Helvetica bold, align left_ over and over again for every headline that you write. And if you want to change the size of all headlines, you just change the style, instead of finding every text that happens to be Helvetica bold 21, and update each one. 

I'll be happy to delay discussion until 1.5, but I want to warn about introducing many new settings for margins and colors without keeping a possible future style system in mind.

**Comment by MatthiasWM** [comment]
> If FLTK's standard size is 14 you can't assume it was **designed for smaller sizes**.

Well yes and no. When FLTK was written, screens were cathode ray tubes and screen resolution was 1024x800. Today's resolutions are huge in comparison, and UI's are generally mach more 'lofty'. Some issues (checkbox right on the text) can be healed by adding spaces, some can't. It also depends very much on screen dpi, which is why our scaling feature is pretty awesome.

**Comment by Albrecht-S** [comment]
> When FLTK was written, ...

Well, the OP isn't comparing 1998 with today, he was talking explicitly about font sizes. But such a discussion is moot. Let's wait for what he can tell us about his intentions.

**Comment by erco77** [comment]
I feel like I should catch up with this styles enhancement -- @MatthiasWM / @Albrecht-S is there a document describing the API? Perhaps it's a WIP, but would be fun to see the base design. I take it this would help not only apps, but perhaps people doing 'skins', kinda like our schemes?

**Comment by MatthiasWM** [comment]
It's documented for [fltk2](https://www.fltk.org/doc-2.0/html/index.html) but need a review before considering it. Much has changed over the years. But before anything, lets get 1.4 out of the door first.

**Comment by MatthiasWM** [comment]
> > When FLTK was written, ...
> Well, the OP isn't comparing 1998 with today, he was talking explicitly about font sizes. 
px, em, and pt are defined at 96ppi. My screen for example hat 254ppi, so with pixel doubling, a 14 pixel font has a size of 11px on my screen. A 14 pixel font on a monitor back then was much larger than it is now. 

The checkbox is squeezed directly to the label text. On old screen, this saved space. In modern typesetting, you would simply not do that anymore. The OP suggests that the box and the text should have a margin between them that depends on the font height. 

To generalise, label alignment should have a settable horizontal and vertical margin that is a factor of the font height.

**Comment by MatthiasWM** [comment]
FLTK uses neither px nor pt. It uses FLTK units that originally related to pixels, and never bothered about the screen dpi.

There is an easy solution for you though. You can design your user interface for a typical resolution, making sure that the margins are what you expect. Sometimes, adding a space character helps. Once it is done, you can use `void Fl::screen_dpi(float &h, float &v, int n)` to get the resolution of the user's screen. Next, you use `void Fl::screen_scale(int n, float factor)` to scale the entire user interface to have the correct size for that screen. 

This scales the entire UI by fixing coordinates and sizes (not be scaling a bitmap which would blur fonts and lines). It may create artefacts though, and it also scales the bitmaps in all windows on a given screen. You can alleviate this though by adding the inverse scale to the image using `void Fl_Image::scale(width, height, ...)`.

These are all FLTK 1.4 features. Please let me know if this fixes your issues.

**Comment by CendioOssman** [comment]
Injecting some spaces might work in some cases. I'll see if I have time to test that. It won't work for things that don't include text though, or where the text is under user control (e.g. input fields).

Scaling won't solve this as (I assume) everything will scale proportionally. So the margins will still be too small. Just in more glorious resolution. :)

And yes, I know FLTK unfortunately lacks a layout engine. But I think these issued should be possible to resolve without going that far.  To reiterate, the two steps that would be nice to see are:

 * Convert all (most?) hard coded pixel values in the library to be relative to `labelsize()` instead (or whatever font size is appropriate in each case)
 * Expose all hard coded sizes to applications so they can adjust them if they want another look

**Comment by MatthiasWM** [comment]
After quite a discussion here, we decided to not have a layout engine in FLTK 1.4. I did however add three methods to Fl_Widget that allow for fine tuning of label positions in relation to their widgets.

[horizontal_label_margin()](https://fltk.gitlab.io/fltk/classFl__Widget.html#adc01f69d79b01d8c80cce8d04cee5ec6) 
[ vertical_label_margin()](https://fltk.gitlab.io/fltk/classFl__Widget.html#a45be357b07c2a6a6cb2807c233546fc8)
and
[label_image_spacing()](https://fltk.gitlab.io/fltk/classFl__Widget.html#a56595013f83bca736967a9b54aca5113)

I hope this makes things a bit more pleasing to the eye.
