### ISSUE TITLE
'GL/glx.h' file not found: macOS Monterey (12.1)

### ISSUE THREAD

**Issue by bsdooby** [fltk/fltk#386]
While trying to build the target `fltk_gl` in Xcode (project generated by CMake in a relative build dir, with `cmake .. -G Xcode`) the above error is produced. This error happens on both branches (`master` [1.4], `branch-1.3`).

**Comment by Albrecht-S** [comment]
Please ask questions about building the FLTK library in our user support forum fltk.general (see instructions below). The error you're seeing is likely to do with missing software packages but particularly on macOS there are several ways to install such additional packages (homebrew and others).

Standard reply follows:

>This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.

>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.

>Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by bsdooby** [comment]
It was always my impression that FLTK should be self-contained. Therefore, this looks like a bug to me. For sure I can install the necessary 3rd party dependencies, but then: what's the point? I will have a look at your suggestions.

**Comment by Albrecht-S** [comment]
> It was always my impression that FLTK should be self-contained.

It is not possible that a GUI library like FLTK is self-contained. FLTK needs at the very least the graphics library of the OS. Even that requires header files (usually "-dev" packages) so we can compile and link the library. Unfortunately macOS does not even provide all necessary files to build the library itself (autoconf, CMake) but you can install the "Xcode command line tools" from Apple which are NOT enough. This or at least parts of this is described in our [README.macOS.md](https://github.com/fltk/fltk/blob/master/README.macOS.md) file (for macOS, obviously) which you can read online. But this will maybe not alone help you with missing development files (sorry for the inconveniencies). There are other resources ...

... and this is why I wrote that you should please ask in fltk.general because there you will get answers from people who had the same questions and/or from developers that know better how to proceed than me.

Hint: you could maybe build FLTK w/o OpenGL support (to work around the issue you reported) by using a CMake option to disable GL support if that helps you. Details can be found in [README.CMake.txt](https://github.com/fltk/fltk/blob/master/README.CMake.txt).
```
OPTION_USE_GL - default ON
   Enables OpenGL support.
```

**Comment by bsdooby** [comment]
Hi Albrecht,

THX for your valuable/appreciated information. As we are dependent on
OpenGL, we need these file(s).
But as gl3w (the only req. for us at the moment) has a more or less
painless target OS installation,
it works magically. I need now investigate how Xcode (in my case) "finds"
these dependencies without
manual intervention. The advantage of a "close" ecosystem :/

Beste Gruesse
Peter

**Comment by Albrecht-S** [comment]
Hi Peter,
I can only tell you that I installed "Xcode commandline tools" (which are part of Xcode so you don't need to do that explicitly if you have Xcode already IIRC) and homebrew with some packages I needed. But I don't remember which ones and how exactly I did that. I was a complete noob regarding macOS at that time and I did it in a trial-and-error process because I needed macOS as a test system for FLTK development. With this constellation I can build all FLTK test and example programs.

PS: interesting name. In my "neighborhood" is a small town named "Niedernhausen" ;-)

Beste Grüße aus DE und viel Glück
Albrecht

**Comment by bsdooby** [comment]
Thank you for your information. There seems to be a need for gl3w for the
M1 chip (?): macOS Monterey on the x86_64
platform does not need it. At least this is what my preliminary tests
showed.

;) Near where I live there is a little village which is called
"Niederhäusern".

Cheers from Bern
Peter

**Comment by Albrecht-S** [comment]
> There seems to be a need for gl3w for the M1 chip (?): macOS Monterey on the x86_64 platform does not need it.

On my macOS 11 (Big Sur) on Apple M1 I didn't see `gl3w` in my `homebrew` installation with `brew list` but this may not mean anything. I'm now upgrading to Monterey...

**Comment by Albrecht-S** [comment]
No news other than what I wrote (edited) [four days ago](https://github.com/fltk/fltk/issues/386#issuecomment-1031488916). Maybe you missed my later edit of the comment because you're obviously reading the notification mails rather than using the GitHub web interface.

[ Sorry for this. I learned from this not to edit messages later with essential informations. ]

Grüße in die Schweiz.
Albrecht

**Comment by bsdooby** [comment]
Hi

Did no receive the full message (?) I just went on GitHub to see your
comment.
I can confirm that the dependency to gl3w somehow disappeared.
That is really strange. But: even better like this :)

Thx again for your investigations.

Cheers
Peter
