### ISSUE TITLE
Enter bypasses focused button for default button

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#402]
FLTK's way of handling a default button differs from other toolkits (at least GTK), which is confusing for our users. The specific detail that trips them up is what happens when the focus is on a non-default button and Enter is pressed.

On GTK, and what our users are expecting, is that the focused button gets pressed.

What happens is that the default button gets pressed instead. This also usually closes the dialog, which makes it extra unclear for users what exactly happened.

I haven't checked the code, but I notice that other widgets can prevent the default button from activating (saw this with radio buttons), so it should hopefully be possible with normal buttons as well.

**Comment by Albrecht-S** [comment]
FLTK does not support the `enter` key on normal buttons. The only key to activate (trigger) a button is the `space` key. The exception to the rule is the `Fl_Return_Button` which takes the `return` or `enter` key when no other widget takes the event.

What do you mean with "default button" in your description above?

There's AFAICT no "default button" in FLTK standard dialog windows unless there is a `Fl_Return_Button`. FLTK uses the "hotspot" positioning so the "default button" appears under the mouse and in many of the standard (aka "common") dialogs there is a `Fl_Return_Button` which reacts on the `enter` key.

> On GTK, and what our users are expecting, is that the focused button gets pressed.

That would happen if the user presses <space> rather than <enter> or <return>.

That said, this is standard FLTK behavior and I don't think that this can be changed w/o breaking many users' expectations (users that are used to the current behavior).

If you want to change this for your users you can of course write your own dialog functions, and if you want to suggest to change the behavior of FLTK you should open a thread in our developer forum [fltk.coredev](https://groups.google.com/g/fltkcoredev).

**Comment by CendioOssman** [comment]
> FLTK does not support the `enter` key on normal buttons. The only key to activate (trigger) a button is the `space` key. The exception to the rule is the `Fl_Return_Button` which takes the `return` or `enter` key when no other widget takes the event.
> 

Ah, I see. All my dialogs had a return button so I couldn't really check what happened without one. :)

So I guess the issue would rather be that `Fl_Button` doesn't respond to Enter at all.

> What do you mean with "default button" in your description above?

An `Fl_Return_Button`, yes.

> That said, this is standard FLTK behavior and I don't think that this can be changed w/o breaking many users' expectations (users that are used to the current behavior).

I can sympathise with that. Though at the same time FLTK is the small guy in most cases, so I would argue that behaviours from the major toolkits are de facto whether we like it or not.

**Comment by Albrecht-S** [comment]
> So I guess the issue would rather be that Fl_Button doesn't respond to Enter at all.

Yes, that would be the central issue, but if it did Fl_Return_Button would be (almost?) useless.

> ... I would argue that behaviours from the major toolkits are de facto whether we like it or not.

Sure, that's a valid point, I can generally agree with this. IIRC there have already been requests to accept enter in normal buttons. However there are certainly compatibility issues if we changed it...

This should definitely be discussed in [fltk.coredev](https://groups.google.com/g/fltkcoredev) because it would change an essential behavior of FLTK. Here is not the right place to discuss this.

**Comment by Albrecht-S** [comment]
Closing this now, please open a thread in [fltk.coredev](https://groups.google.com/g/fltkcoredev) as suggested above if you believe this needs discussion.
