### ISSUE TITLE
fl_xid() on wayland returns a type that can't be used with wayland functions

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#403]
Hello

I might be missing something, but it seems fl_xid, which would normally return a window handle on all platforms, when using the wayland backend, it returns a wld_window which is an internal type to FLTK, defined in `src/drivers/Wayland/Fl_Wayland_Window_Driver.H`. To get the wl_surface for example, one would have to include the Fl_Wayland_Window_Driver header to be able to get the wl_surface member:
```cpp
#include <wayland-client.h>
#include "fltk/src/drivers/Wayland/Fl_Wayland_Window_Driver.H" 

auto winid = fl_xid(win);
auto surface = winid->wl_surface;
wl_surface_attach(surface, NULL, 0, 0); // just an example
```

**Comment by Albrecht-S** [comment]
Thanks for the report. As you know the Wayland port is absolutely new and may need more documentation or even an improved implementation.

 I don't think that using the wayland surface in a user program is going to work.

That said, we need to document what fl_xid() returns in our "Operating System Issues" documentation chapter. This has not been done yet.

If there's a useful usage of these objects we would need to document how to access the internal structures but currently I don't see such a usage yet.

@MoAlyousef Can you help and explain what you intend to do with the internal wayland specific structures? Is there any real reason to access them? I'm not sure if using the wayland surface or any other wayland structures in a user program is going to work -- but maybe you know better?

**Comment by MoAlyousef** [comment]
It’s mainly for media libraries which usually take a window id (xid, hwnd, nswindow/nsview) to do their drawing, for wayland it’s the wl_surface. For example gstreamer on wayland expects a wl_surface. 
That said, I haven’t tried gstreamer with FLTK’s wayland backend yet. 
Also libvlc is planning to add a
libvlc_media_player_set_wl_surface:
https://code.videolan.org/videolan/vlc/-/issues/16106

**Comment by Albrecht-S** [comment]
OK, I see, thanks.

My take on this would be to provide an OS/platform specific method that returns a wl_surface from an Fl_Window if this is what is needed, or something like that. This would IMHO be better than exposing details about internal structures. In this case I would imagine that the user creates an Fl_Window to draw into, then gets the wl_surface via the API mentioned above, and calls the media library with that wl_surface. Is this what you mean?

Would this window/wl_surface have to be a main window, or could it also be a subwindow? What if the user resizes the main FLTK window and the subwindow and its wl_surface within it? I don't know how this would work with Wayland (regarding synchronization, resizing, drawing, etc.).

This is something @ManoloFLTK can likely help better with because he wrote the Wayland port.

**Comment by MoAlyousef** [comment]
I’m ok with providing some utility method to get the wl_surface. Also it should be possible to get a wl_surface from a subwindow. 

Regarding the last point, I’m also not sure how that would work with wayland, but I would say it’s the user’s responsibility to ensure correct sync and usage of the raw handle, just like with hwnd etc. 

It’s nothing urgent, just I have yet to experiment much with wayland. Bizarrely, the most consistent wayland environment I have is gwsl (graphical windows subsystem for linux) on windows 11. I can’t get wayland to work on a real kubuntu machine, nor correctly/reliably on an ubuntu vm.
