### ISSUE TITLE
Fl::set_font() different Xft/Pango

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#406]
Tested with a modified hello.cxx, where the font should be replaced with a custom font:

```cxx
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

int main(int argc, char **argv) {
//  static const char *custom_font = "Ubuntu Mono bold italic"; // needed for Pango
  static const char *custom_font = "PUbuntu Mono"; // needed for X11
  Fl::set_font(FL_HELVETICA_BOLD_ITALIC, custom_font);

  Fl_Window *window = new Fl_Window(340, 180);
  Fl_Box *box = new Fl_Box(20, 40, 300, 100, "Hello, World!");
  box->box(FL_UP_BOX);
  box->labelfont(FL_BOLD + FL_ITALIC);
  box->labelsize(36);
  box->labeltype(FL_SHADOW_LABEL);
  window->end();
  window->show(argc, argv);
  return Fl::run();
}
```
(Using Ubuntu 20.04, so I have the font 'Ubuntu Mono' installed)

FLTK compiled *without* Pango (i.e. using Xft) requires the font name to be passed in the format, where the first character specifies the style and does not work with the other variant.
FLTK compiled with Pango requires the font name to be passed literally.

The docs for Fl::set_font() are somewhat sparse, but I found this STR: https://www.fltk.org/str.php?L3392, where is stated in comment #6:

> The Fl::set_font() function expects an FLTK-style font name,
which means italic font names begin by I, bold by B, bold-italic by P,
and others by space. The initial space can be ommited.

Is this not valid any longer for Pango?

**Comment by Albrecht-S** [comment]
Thanks for the report. I'm not sure what the correct answer is. It seems that the font names used by Pango **are** different than those used by Xft or the older (XLFD?) font names.

IMHO this should at least be documented so users know how to deal with this. I could also imagine that parsing the font names if Pango is enabled would ignore the first letter in a kinda fallback mode, i.e. if the first attempt to find the font with the first letter fails (a leading space should always be ignored but P/I/B maybe not). However, I don't know the font name conventions well enough to make a useful proposal.

@ManoloFLTK What do you think about this issue and [STR 3392](https://www.fltk.org/str.php?L3392) which has not been solved yet. I can't tell whether the [proposed patch](https://www.fltk.org/strfiles/3392/medium.patch) is good or useful. Any ideas how to proceed for best compatibility?

**Comment by ManoloFLTK** [comment]
Function `Fl::set_font(int, const char name)` allows to assign a user-chosen font to
a given font number. Under Windows, font are arranged in families, and each (or most?) family contains a regular, an italic, a bold, and a bold-italic variant.

Under X11+Xft and X11+Pango (or Wayland), many other font variants exist, with many different names: black, condensed, light, extralight, thin, semibold, etc…

The trick used in Windows to prefix the font family name by one letter (space, I, B, P) to build a font name thus fails with Xft to represent all the fonts of a family. Another drawback of this way to give a name to a font is that the name displayed by programs test/fonts and test/utf8 which list all fonts known by the system is not the name expected by function Fl::set_font().

Font names used by Xft and those used by Pango slightly differ. Pango names are more consistent than Xft names which sometimes use abbreviations such as ExtLt and SemBd in place of ExtraLight and SemiBold. Thus, Xft names can't be used with the new Pango option anyway.

That's why FLTK 1.4 proposes to use a simpler and consistent way to name fonts for function `Fl::set_font(int, const char *name)` for its new X11+Pango and Wayland platforms: 
- stop using the undocumented 1-letter prefix trick;
- have the `Fl::set_font()` function use the same name as that produced by `Fl::get_font_name()` which is also the name displayed by programs test/fonts and test/utf8.

This will soon be stated clearly in the documentation.

**Comment by ManoloFLTK** [comment]
See e8461a6 which documents in great detail function `Fl::set_font(Fl_Font, const char *name).`

**Comment by wcout** [comment]
So in practice:
For an application, that does not know if it is compiled with Pango/Cairo/Wayland (and without wanting to use `#ifdef`'s in the code) it should be possible to query `Fl::get_font(FL_HELVETICA)` and if this returns an 'old format' name with 'space' as first character it must use the 'old format' for `Fl::set_font()` too, otherwise it must use the new format.
Would that be the way?

**Comment by ManoloFLTK** [comment]
Yes. The first character of the string returned by Fl::get_font(FL_HELVETICA) would be a space for X11+Xft and an 'S' for X11+Pango (or Wayland).
