### ISSUE TITLE
macOS: Second OpenGL context flashes with a red or black window (it is not properly initialized it seems)

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#408]
Under certain conditions, a second opengl context does not get properly initialized and shows a flashing red (or black) window that does not update.  The problem seems related to an FL_RELEASE event before the opening of the context (as calling menus show the issue).
I am attaching a simple demo program that shows the issue with a  README.txt file explaining how to compile it and reproduce.   The demo uses only fltk libraries for everything.

[exrdisplay.zip](https://github.com/fltk/fltk/files/8242238/exrdisplay.zip)

**Comment by Albrecht-S** [comment]
Copying (and editing) [my reply on fltk.cordev](https://groups.google.com/g/fltkcoredev/c/Qrap9ljL2ao/m/jAPlzDgYBQAJ):

I could reproduce the issue and went back until commit 67347dd76e996 from Sep 16 12:31:03 2020 -0700 (which is, BTW, totally unrelated) and I could still reproduce the issue (flashing window) - whatever that means (in my case it was black rather than red). At least it's not a regression introduced by a **recent** FLTK commit, i.e. not during the last ~18 months. Note: I can't test on older macOS platforms (if that would make a difference) and I didn't check/verify the application code.

I see three possible reasons of this issue:
1. A bug in the user software (i.e. in the demo program)
2. A long standing bug in FLTK (never recognized before)
3. A bug in macOS or its OpenGL implementation, maybe introduced in macOS 12 (Monterey)?

To rule out the latter it would be interesting if someone could test the demo program with an older macOS version...

**Comment by ggarra13** [comment]
From my comments on fltk.coredev on the original thread:

In my actual program, the 3d view is opened thru menus.  Changing the menus to select the 3d view opening with the keyboard instead of the left or right mouse button, solves the problem.  That probably means the menu (or the window, not sure how events are propagated) never gets a FL_RELEASE.

In the demo program, changing the FL_RELEASE of the right mouse button to an FL_PUSH (and moving down the FL_PUSH at the beginning of the handle function to the end of the it right above the Fl_Gl_Window::handle() hand-off to avoid the quick exit) solves the issue.  That avoids the drag and the FL_RELEASE.

**Comment by Albrecht-S** [comment]
@ggarra13 Your descriptions above are too unspecific to be sure what you mean. To avoid trial and error, please post a diff file, file names, line numbers, and/or the modified code here. This would help others to understand what you mean and remove all ambiguities of the description.

That said, regarding event propagation: `FL_RELEASE` events are mouse button events usually handled in your class(es). If open menu windows change the behavior of your program this can be caused by the menu being a kinda _modal window_ (and using `Fl::grab()`) to catch all mouse and keyboard events while it is open, which can in turn cause your window to miss the expected `FL_RELEASE` event.

I looked at your demo program and tried to understand what's it. However, there is way too much unrelated code for me to understand and it would take too much work (and time) for me to investigate further. Meanwhile I believe that the culprit is in your code (see above: event handling) and if you can't remove all unrelated code I personally won't be able to help further. I suggest that you remove everything that does image analysis (if this is what it does) and draw only simple geometric objects (e.g. rectangles), make the windows smaller, and concentrate on event handling. If this still shows the effects this could be tested and debugged much easier. I also suggest to add _printf()_ or other debugging statements to significant events to see better what's going on under the hood. Maybe this can reveal the real problem and you can fix it yourself.

**Comment by ggarra13** [comment]
Hi Albrecht.  Please download the latest exrdisplay.zip here on these pages.  I simplified it a lot and removed a lot of the unnecessary functions. I also placed comments on where the ImageView::handle() function can be changed to make it work.

**Comment by Albrecht-S** [comment]
@ggarra13 Thanks for the update, I'll look into it later unless someone else finds the cause. I'm right now busy with other FLTK stuff, hence further tests and inspection will be delayed.

@ManoloFLTK Just in case this issue is caused by something in FLTK related to macOS, could you please also take a look? TIA.

**Comment by ManoloFLTK** [comment]
I've built exrdisplay for macOS and see no red thing at all.

I see that 4 GL windows are created and only one image is displayed in a window.

**Comment by ggarra13** [comment]
@ManoloFLTK Be sure to follow the instructions to Left click first (to bring up the chart) and then Right click and drag (to bring up the 3d view).  There's only 3 windows created: 2 GL Windows (one with the image and one with a 3d view) and one normal fltk window (the chart).

**Comment by Albrecht-S** [comment]
FTR: I opened issue #411 about FL_ENTER, FL_MOVE, and FL_LEAVE event delivery.

**Comment by ggarra13** [comment]
@Albrecht-S @ManoloFLTK Yes, I know about the weird redraw() getting called after each event.   It was me just being lazy not wanting to put a redraw() on each location.

**Comment by Albrecht-S** [comment]
@ggarra13 redraw() schedules drawing the entire scene which means not only wating CPU time but can also contribute to flicker. This is why I mentioned it and I recommend strongly to remove this at least for entirely ignored events like FL_MOVE.

Note that I won't be able to debug this issue further. I gave up so I can concentrate on FLTK 1.4.0 release work. I'm sorry but I spent already way too much time on this and I don't see anything I could contribute.

**Comment by ggarra13** [comment]
@Albrecht-S @ManoloFLTK I am placing a new version of the demo program now using a menu so that it can be more easily tested and with the redraw() fixed per Albrecht-S comments.

[menu_exrdisplay.zip](https://github.com/fltk/fltk/files/8257428/menu_exrdisplay.zip)

**Comment by ggarra13** [comment]
I confirm this fixes the issue both in the exrdisplay short demo program as well as in my actual application.  Thank you very much.  I am closing the issue.
