### ISSUE TITLE
FLUID:  issues with gettext and menus (when created for the second time)

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#417]
Currently, static menus are created with Fl_Menu_Item, like:

```
Fl_Menu_Item ViewerUI::menu_uiWindows[] = {
 {_("Reels"), 0,  (Fl_Callback*)ViewerUI::cb_Reels, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {_("Media Info"), 0,  (Fl_Callback*)ViewerUI::cb_Media, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 };
```
Then, gettext is run on the menus, like this:

```
          { Fl_Menu_Item* o = &menu_uiWindows[0];
            o->label(gettext(o->label()));
          }
```

The problem is that this modifies the original menu entry, as it is modified thru a pointer.  Ideally we would like a o->copy_label() call but Fl_Menu_Item does not provide one. Another approach would be if the menus would get add()ed like: uiWindows->add( menu_uiWindows[0][0] ); (and the other flags).

The issue I ran into is when the menus need to be recreated, like when the UI changes language on the fly while the application is running.  The menus don't get recreated properly, as they contain the other language, no longer the original language (English).

**Comment by Albrecht-S** [comment]
As @MatthiasWM wrote in fltk.coredev the "static menus" approach is very old and error prone. Creating menus dynamically in their entirety is now the preferred and recommended method because this can guarantee not to leak memory.

Would creating the menus from scratch by Fl_Menu_Item::add() in the first place and when you recreate the menus be an option? Something like
1. recreate the menu from scratch
2. apply gettext() with the default or changed language

always, whether you create them for the first time or later?

Another option would be to create a static menu (the "template") without applying the locale settings to it, then use Fl_Menu::copy() to copy the entire menu, and finally apply gettext() or whatever. This process (copying from the template and applying the locale) could be repeated later when/if the locale is changed.

Just my 2 ct.

**Comment by ggarra13** [comment]
One question I have is whether Fl_Menu:_::add() copies the string passed to it.  The documentation for it is not too clear about it.  It says:

If the menu array was directly set with menu(x) then copy() is done to make a private array.

and then:

The label string is copied to new memory and can be freed. The other arguments (including the shortcut) are copied into the menu item unchanged.

If I read that correctly, then doing:

uiWindows->add( gettext( menu_uiWindows[0][0] ) );

should work.

**Comment by MatthiasWM** [comment]
If your entire menu is create using add() and insert() calls, FLTK will take care of duplicating labels and free those allocations when deleting the menu widget or removing menu items.

If you provide your own menu using the menu() call, FLTK has no way of knowing if you label was duplicated or not, so it will not free any labels, even if they were added later using add() or insert().

This is controlled by Fl_Menu_::alloc . If this is set to 0, FLTK will leave the Manu array handling to the user. If a menu is added to an existing menu array, FLTK will set alloc to 1, duplicate the array, and free the duplicated array, but not the labels. If you use add() without a preexisting menu, FLTK will set alloc to 2 and deallocate the menu array and the label text later.

**Comment by ggarra13** [comment]
So, fluid is wrong in using the Fl_Menu::menu() call to create the static menus.  It should add() each menu item, like:
```
for ( unsigned i = 0; i < sizeof(menu_uiWindows)/sizeof(Fl_Menu_Item); ++i )
{
  Fl_Menu_Item* item = uiWindows->add( gettext(menu_uiWindows[i][0]), menu_uiWindows[i][1], menu_uiWindows[i][2], 
                                                                        menu_uiWindows[i][3], menu_uiWindows[i][4] );
  item->labeltype_ = menu_uiWindows[i][5];
  item->labelfont_ = menu_uiWindows[i][6];
  item->labelsize_ = menu_uiWindows[i][7];
  item->labelcolor_ = menu_uiWindows[i][8];
}
```

**Comment by MatthiasWM** [comment]
Using add() instead of menu() is a completely different interface with a lot of consequences for the code, including callbacks and activating/deactivating menu items. Fluid is correct for using the menu() interface to Fl_Menu_Item arrays and the generated code will fit 99% of all cases. It's surely possible to have an option in Fluid for creating menus using add(), but then keeping a pointer to a menu item is no longer possible because it is up to FLTK then to reallocate the menu item array at will.

**Comment by MatthiasWM** [comment]
I would like to close this issue as there seems to be no satisfying solution. Most apps don't offer a way to change language on the fly, but simply use the system or user's preferred language. Apps that allow changing languages, even big commercial ones, usually ask you to restart the app after changing languages, which I find perfectly acceptable, as changing language is usually only ever done once.

I am German, and I use some apps with a German UI, but most with the English UI. In my own experience, I set it once, and I never touch that setting again.

As for Fluid to generate menus by using `add()` instead of menu item arrays, I will generate a different Issue for that and check the implications later.
