### ISSUE TITLE
Document the correct behavior of Fl_Image::copy()

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#431]
In FLTK 1.4 we have an ambiguity in method `Fl_Image::copy(W, H)` and all derived classes if the image has been scaled because we did not exactly specify what the copy should produce:

1. the original data size (`data_w, data_h`) with an image that is scaled to the new size (`W, H`)
2. the new data size (`W, H`) with unscaled (i.e. converted) image data if it is different than (`data_w, data_h`)

We need to specify and document this not only for users but also for developers of future changes and I think point (2.) is the correct implementation. This is the behavior users can expect from the behavior of FLTK 1.3 where scale() did not yet exist and the best backwards compatible approach. Note that `Fl_Image::copy()` with default arguments is a shortcut for `Fl_Image::copy(w(), h())`.

A typical use case would be to use `Fl_Image::copy(W, H)` to convert an image to another size and to access the `data()` array of this new size, for instance to write an image file or for any other direct image data modifications.

**Comment by ManoloFLTK** [comment]
At present, the [doc of class Fl_Image](https://fltk.gitlab.io/fltk/classFl__Image.html#details) states :
`The values [of w() and h()] are equal to data_w() and data_h() when the image is created.`
Since `Fl_Image::copy()` creates new image objects, that is in principle enough to make clear that behaviour 2 above is implemented. It would do no harm, though, to add a sentence in the doc of `Fl_Image::copy()` stressing what to expect of created copies.

**Comment by Albrecht-S** [comment]
I tried to improve the documentation as described in commit 114dbc9c8158b7d35eacbdde3d8179a99a035378. Some parts of the changes are only formatting, others clarify things, and some changes even fix old references to w() and h() where now data_w() and data_h() must be used.

**Comment by Albrecht-S** [comment]
PS: @ManoloFLTK I'm done with this issue. If you find that I missed something please feel free to fix it or comment here.

**Comment by ManoloFLTK** [comment]
Here are a few suggestions for additional changes in the documentation of class Fl_Image :

1) Regarding Fl_Image::copy(int, int)

* "For the copied image the following equations are true"
"copied image" can be understood to refer to both images involved.
I would suggest to replace that by "image copy" or "returned image".

* same issue below in description of the W and H parameters

* when I use Fl_Image::copy(), I nearly always have to cast its result to the specific image class of the copied (sic) image, and I know I can do it because each overriden copy() method does produce a copy of the same class as "this". I would suggest it would be useful to add a paragraph such as

"Note: the returned image can be safely cast to the same image type as that of the image being copied provided this type is one of Fl_RGB_Image,  Fl_SVG_Image, Fl_Pixmap, Fl_Bitmap, Fl_Tiled_Image, and Fl_Shared_Image."


2) In detailed description of Fl_Image class:

"Since the Fl_Image class does not support image drawing by itself, calling the draw() method results in a box with an X in it being drawn instead." 

That's confusing (I know it's old stuff) because when calling the virtual draw() method to an image, you call its override which does draw the image correctly.

Either replace "the draw() method" by "the Fl_Image::draw() method" or remove that statement that brings very little if any information.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thank you very much, these are all good points. This discussion shows how difficult it is to write good documentation - and users might still be confused or detect ambiguities...

>"copied image" can be understood to refer to both images involved.
I would suggest to replace that by "image copy" or "returned image".

That's true. What about "new image" instead? For further reference I would call the original image the "source image" if there is any doubt.

> ... it would be useful to add a paragraph such as [... about casting ...]

I agree, but should we really enumerate all image types? This would require maintenance as soon as we added another image type and, BTW, your enumeration is not complete (Fl_GIF_Image is missing). Maybe better and shorter:

_"Note: the returned image can be safely cast to the same [ Fl_Image ] subclass as that of the source image."_

In this context I would really use "returned image" rather than "new image" but I'm in doubt whether we should use "Fl_Image" or not (I tend to leave it away).

> Either replace "the draw() method" by "the Fl_Image::draw() method" or remove that statement that brings very little if any information.

I'd like to keep it and agree to use the fully qualified "`Fl_Image::draw()`" method name. The additional information given to the user is that it's not useful to call the draw() method of the base class like when drawing a box etc..

**Comment by ManoloFLTK** [comment]
> What about "new image" instead? For further reference I would call the original image the "source image" if there is any doubt.

"new image" seems excellent.

> I agree, but should we really enumerate all image types? This would require maintenance as soon as we added another image type and, BTW, your enumeration is not complete (Fl_GIF_Image is missing). 

I disagree and believe it's complete, because there's no such thing as Fl_GIF_Image::copy() (nor with Fl_JPEG_Image and several other classes). Thus, the copy of an Fl_GIF_Image object is an Fl_Pixmap, not an Fl_GIF_Image. It's exactly for this reason that I believe the exact enumeration of classes is useful, even though it creates a maintenance cost.

> I'd like to keep it and agree to use the fully qualified "Fl_Image::draw()" method name. 

Very well.

**Comment by Albrecht-S** [comment]
Thanks for your agreement to the first and last points. That's clear now.

However, I'm not happy with the other points you mentioned. I'll reopen the issue with this comment so our discussion doesn't get lost.

> ... there's no such thing as Fl_GIF_Image::copy() (nor with Fl_JPEG_Image and several other classes).

These methods _exist by inheritance_ and you can use them fully qualified in code, for instance in
```
Fl_GIF_Image *gif = new Fl_GIF_Image(...);
Fl_Image *out = gif->Fl_GIF_Image::copy();
```
The compiler wouldn't allow this if these methods didn't **exist**.

> ... the copy of an Fl_GIF_Image object is an Fl_Pixmap, not an Fl_GIF_Image.

Unfortunately this is true. I'm surprised and confused. My expectation has always been that the new image is an object of the same class as the source image. I believe this is what users would also expect. Shouldn't a copy of "something" be the same kind of "thing"?

So what is wrong? My expectation or our implementation?

I'm currently looking into the implementation to see if we can change it to make the expectation come true, i.e. return the same image class in all cases. I believe this would be better for both consistency and (user) expectations.

Besides that the objects of `Fl_Pixmap` and `Fl_GIF_Image` are exactly the same size and layout in memory because `Fl_GIF_Image` only defines new constructors. Thus, casting the new `Fl_Image` to `Fl_GIF_Image` would at least do no harm. The same is true for `Fl_JPEG_Image` and `Fl_RGB_Image` (verified) and probably all the other not mentioned image classes. Side note: I **assume** that the identical memory layout is the reason why the implementation was done this way (by inheritance) in the first place but I don't know.

But don't understand me wrong, I agree with the statement that Fl_GIF_Image::copy() returns an Fl_Pixmap object _as it is currently implemented_.

> It's exactly for this reason that I believe the exact enumeration of classes is necessary, even though it creates a maintenance cost.

Consequently we would have to document the returned image types for all the other image classes to make the documentation complete. As a user I would expect that the documentation is "complete", hence if it says that I can cast the new image to the original image type for some classes only, then what image type can I use instead for all the other classes?

One option to make this "complete" would be to document the returned image type of all individual `copy()` methods, but this is a problem if there is no explicit copy method as in `Fl_GIF_Image`. Well, a smart user might click on the `copy()` method of `Fl_GIF_Image` in the doxygen docs, find the docs of `Fl_Pixmap::copy()` and see that it returns an `Fl_Pixmap`. I believe this would open a lot questions of novice users and those not familiar with C++ inheritance.

**Comment by ManoloFLTK** [comment]
I'd say the implementation is correct in the sense that there's no Fl_PNG_Image::copy(int, int) override because it would bring nothing more than Fl_RGB_Image::copy(int, int) since class Fl_PNG_Image has only constructors.

The expectation that a copy of an object should have the same type as the source image may be wrong given the inheritance mechanism of C++. The documentation could avoid this assumption with something like :
"Note: the returned image can be safely cast to the same image type as that of the source image  provided this type is one of Fl_RGB_Image, Fl_SVG_Image, Fl_Pixmap, Fl_Bitmap, Fl_Tiled_Image, and Fl_Shared_Image. Returned objects copied from images of other, derived, image classes belong to the parent class appearing in this list. For example, the copy of an Fl_GIF_Image is an object of class Fl_PIxmap."

There's also a form of inheritance in Doxygen that makes a single member function documentation (that of Fl_Image::copy(int, int)) appear several times for each overriden copy() function. The paragraph above would therefore appear several times. Classes that don't override copy(int, int) don't show that function in their documentation but invite to visit the parent class to discover it. Thus, with the paragraph above, the documentation would be "complete" in my view.

I'm afraid that proper use of the copy(int, int) member function of FLTK image classes requires some knowledge of the inheritance mechanism of C++ even if all classes are extensively documented.

**Comment by erco77** [comment]
Just dropping about being surprised/confused about "the copy of an Fl_GIF_Image object is an Fl_Pixmap, not an Fl_GIF_Image".

That seems to make sense to me.. If Fl_GIF_Image made a copy "of the gif", would it then make a new Fl_Pixmap and keep /both/ in memory at all times, or would it convert GIF -> Pixmap on demand whenever the image needed to be redrawn?

I'm guessing it immediately converts to Fl_Pixmap and only keeps a copy of that so that it (a) doesn't have to keep two copies of the image in memory, and (b) can quickly redraw on demand without having to re-convert GIF -> Pixmap.

But I may be missing some nuances..

**Comment by Albrecht-S** [comment]
@erco Talking about the copy operation of images means the C++ object types themselves. The equivalent statement for `Fl_JPEG_Image` would be "the copy of an `Fl_JPEG_Image` object is an `Fl_RGB_Image`, not an `Fl_JPEG_Image`". Neither `Fl_GIF_Image` nor `Fl_JPEG_Image` (nor `Fl_PNG_Image` etc.) keep the image sources (as stored in the image files) in memory. They are read only once and stored as their internal image representations (for JPEG and PNG this is `Fl_RGB_Image` with its well-known array of `w()` x `h()` x `d()` image data bytes).

`Fl_GIF_Image`'s are read from disk and the data representation is internally converted to the same representation as that of `Fl_Pixmap` which is the base class of `Fl_GIF_Image`. The internal storage is a combination of ASCII and binary data which is not directly used to draw the image.

What you mean is very likely the X11 "`Pixmap`" structure that is used under X11 for caching the image. This is done internally even for `Fl_Pixmap` data which is converted from the FLTK representation to the X11 "`Pixmap`" data.

That said, the internal representation of the whole object of `Fl_Pixmap` and `Fl_GIF_Image` is exactly the same but WRT `C++` these are different object types (classes) with potentially different methods. Casting from `Fl_Image*` to `Fl_Pixmap*` after a copy operation of an `Fl_GIF_Image` is formally correct, but casting from `Fl_Image*` to `Fl_GIF_Image*` would not be correct WRT `C++` rules because the returned image class of `copy()` **is** an `Fl_Pixmap` and not an `Fl_GIF_Image` (which is a **subclass** of `Fl_Pixmap`). You can test this with `dynamic_cast<>` if you like:
```c++
  Fl_GIF_Image *gif  = new Fl_GIF_Image("image.gif");
  Fl_Image     *out  = gif->Fl_GIF_Image::copy();           // same as gif->copy()
  Fl_Pixmap    *out2 = dynamic_cast<Fl_Pixmap *>(out);      // valid (non-NULL)
  Fl_GIF_Image *out3 = dynamic_cast<Fl_GIF_Image *>(out);   // invalid (NULL)
```
... and the gist of my statement(s) above is that I (as a user) would **_expect_** that `copy()` of an `Fl_GIF_Image` would return an `Fl_GIF_Image` object so `out3` would also be a valid object pointer and not `NULL`, or generally spoken, that a copy() operation of any `Fl_Image` and its derived classes would return the same object class as the source object.

(I'm still not sure whether my expectation or the current FLTK implementation is wrong.)

**Comment by Albrecht-S** [comment]
> (I'm still not sure whether my expectation or the current FLTK implementation is wrong.)

This statement still holds but I came to the conclusion that changing the existing copy() methods would be too much work to do and not worth the effort because "it's always been this way". I updated the documentation as suggested by @ManoloFLTK regarding the copy() method and its returned image classes.

@ManoloFLTK Thanks for all your input.

Commit 804c48515d63393d12f61f8a783dc9f0586fcdba should hopefully be the final commit related to this issue.
