### ISSUE TITLE
example/cairo-draw-x.cxx compile error: CAIRO_ANTIALIAS_BEST invalid

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#436]
I am using FLTK 1.4 bleeding edge from github. I have old Cairo 1.8.8 installed on my CentOS 6 system (by my package manager). I see this error when building FLTK examples (i.e., with the cairo option enabled in the config):
```
fltk-clone/examples/cairo-draw-x.cxx: In function void my_cairo_draw_cb(Fl_Cairo_Window*, cairo_t*):
fltk/fltk-clone/examples/cairo-draw-x.cxx:31:29: error: CAIRO_ANTIALIAS_BEST was not declared in this scope
     cairo_set_antialias(cr, CAIRO_ANTIALIAS_BEST);                // use best antialiasing
```
I verified my system-installed `cairo.h` file has a definition for `cairo_antialias_t` without this enum member, but it does contain one for `CAIRO_ANTIALIAS_DEFAULT` (and some others). When I edit `cairo-draw-x.cxx` to substitute DEFAULT for BEST, all is well.

Sadly, since this is an enum, one cannot just use `#ifdef ` to check if `CAIRO_ANTIALIAS_BEST` is defined or not.

I will of course try to install a more recent version of Cairo and hope everything resolves. Assuming it does, then this is just an 'FYI' report, especially since the subject is just an example.

**Comment by Albrecht-S** [comment]
@pdhahn Thanks for the report.

I found that [CAIRO_ANTIALIAS_BEST](https://cairographics.org/manual/cairo-cairo-t.html#cairo-antialias-t) is available since Cairo version 1.12. I could have implemented a version check but I chose to document this fact and use `CAIRO_ANTIALIAS_DEFAULT` instead.

I'm closing this issue now.
