### ISSUE TITLE
Request for a new OpenGL widget class (e.g., Fl_Gl_Widget) usable within Fl_Scroll

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#437]
I would like FLTK to have a new OpenGL-based class `Fl_Gl_Widget` (or named whatever), derived from `Fl_Group`, such that multiple instances of it could be used within `Fl_Scroll` with the expected scrolling effects.

Since `Fl_Gl_Window` is of course derived from a window, then using instances of it under `Fl_Scroll` will mean "sub-windows". My understanding is that those do not scroll properly.

I am pretty sure OpenGL function calls can be used in FLTK widgets outside of `Fl_Gl_Window` (I never tried it), but having things tied together in the new class similar to how they are in the `Fl_Gl_Window` class, while oriented for successful utilization under `Fl_Scroll`, is really what I am asking for. Ideally, this 'tied together' aspect includes the great work recently done to allow easy use of FLTK widgets directly under `Fl_Gl_Window`.

I do not know if all this is technically feasible, but I wanted to get the request onto the FLTK development team's roadmap in case it is (per their expert evaluation). If it's feasible, then maybe it could be part of an FLTK 1.4.x or 1.5 release.

Thanks!

**Comment by Albrecht-S** [comment]
> I would like FLTK to have a new OpenGL-based class Fl_Gl_Widget (or named whatever), derived from Fl_Group, such that multiple instances of it could be used within Fl_Scroll with the expected scrolling effects.

@pdhahn Thanks, that sounds like an interesting feature. However, I don't believe that this kind of widget should be derived from Fl_Group which would (only) be useful if this widget should have its own nested (maybe non-GL) children. Although this kinda works now with Fl_Gl_Window's. If you need nesting inside an Fl_Scroll I'd rather use an Fl_Group inside the Fl_Scroll with the Fl_Group's children being `Fl_Gl_Widget's` (or whatever their name would be).

To enable scrolling within an Fl_Scroll this widget wouldn't need to be derived from Fl_Group, hence I believe the most appropriate we could do would be to derive such a widget from Fl_Box (Fl_Gl_Box) or directly from Fl_Widget (Fl_Gl_Widget). Another name might be Fl_Gl_Canvas.

That said, I have no opinion about adding such a widget, the comments above are just my thoughts. Other comments welcome...

**Comment by ManoloFLTK** [comment]
Mixing GL and non-GL drawings in the same (sub)window is impossible under macOS.

**Comment by MatthiasWM** [comment]
Fl_GL_WIndow is a window because it needs its own (sub)window - or canvas - handler. On the OS side, these are rectangular regions that may (or may not) be implemented completely different on the hardware side than the regular screen. With newer unified graphics cards, this starts to merge into the same thing again, but we can not know that reliably on the FLTK side of the OS.

To implement GL inside Fl_Scroll, we would have to change the GL canvas based on how much of it would be visible and where. This is not trivial. I am not sure how GL reacts if we interactively change the canvas size during a scroll operation, or even hide and show the canvas if needed. It may have to recreate a new GL context every time to work properly.

On a side note, similar things happen with Fl_Windows inside another FL_Window. On Win32 for example, sub windows have their own graphics context as well, similar to what I just described with GL contexts. So no reliable scrolling there either, no clipping between canvases, no overlaps.

**Comment by Albrecht-S** [comment]
OK, after reading @ManoloFLTK's and @MatthiasWM's comments I believe that this is not doable with the FLTK "Fast and Light" design in mind.

IMHO we should close this issue. I'll update the labels (add `wontfix`) and I'm asking the OP @pdhahn to close this issue. Sorry.

**Comment by pdhahn** [comment]
Thanks for examining the possibilities.

Closed as per advisement by @Albrecht-S.

**Comment by pdhahn** [comment]
oops really closed this time.
