### ISSUE TITLE
WIN10 bug

### ISSUE THREAD

**Issue by szukw000** [fltk/fltk#462]
My FLTK application hat 2 windows: one main window int the middle
and one readings window on the left.

As you can see, WIN10 (is the only OS that) does not correctly show
the readings in the left window. LINUX, MAC CATALINA, RASPBERRY P4
all show the readings in the left window correctly.

The missing info in the left window makes the application in WIN10
very unstable: it crashes.

winfried
![Screenshot 26 06 2022 18_36_32](https://user-images.githubusercontent.com/5041293/177974290-08d6e6b3-a2ad-451e-a900-44c138665402.png)

**Comment by Albrecht-S** [comment]
@szukw000 Winfried, I can only guess, but this seems to be an application (i.e. programming) error which we can't resolve here, unless you can provide a small, compileable example program that shows the error. Such errors can be caused by overwriting data, e.g. pointers, somewhere in the application program. It is obvious that such random memory errors would be different on different platforms. Please try to reduce your program to a small test case, and probably you'll find the cause in this process. Maybe a memory checker (valgrind on Linux) can help finding bugs (even if the error does not manifest on Linux).

I suggest that you ask your question in our user forum fltk.general, because ... please see below.

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by szukw000** [comment]
@Albrecht-S ,
I did not guess. As I could not find an FLTK library of about 3 months ago, I used

> fltk-3916fcda6d09083a983b1e8ad8190fa7e3a287a3-1.zip

to compile it with WIN10 (nmake).
And this FLTK library showed a stable left window: all readings were shown. This
should prove: it is the current library that has a bug.
winfried

**Comment by Albrecht-S** [comment]
> This should prove: it is the current library that has a bug.

Sorry, but no, this is not a proof. Using another library version changes the memory layout and whatnot. If your program writes to random memory (a pointer out of scope or something like this), then anything can happen or not. It depends on many things.

Beware: I don't exclude the possibility of a bug in the library. The only thing I'm saying here is that your build with another version of the library (which does not exhibit the error) does not **prove** that the bug is in the library.

Winfried, please do as I wrote above: please ask your question in [fltk.general](https://groups.google.com/g/fltkgeneral) and/or provide a small, compileable program that exhibits the bug. Without seeing valid (preferably: short) code that exhibits the bug nobody can help you find it. Neither in your program nor in the FLTK library, wherever it is.

And, BTW: just showing a window with a bug is not enough for anybody to see what exactly is wrong. What are "the readings" that are wrong? Can you provide a correct screenshot for comparison? That said, all follow-ups should go to [fltk.general](https://groups.google.com/g/fltkgeneral).

**Comment by szukw000** [comment]
@Albrecht-S,
after trying several times on WIN10 I first found that libpng-libpng16\pngrio.c
at line 60 in routine png_default_read_data crashed the execution. But today
png_default_read_data did not  crash the execution.
Instead the crash came within Fl::run() with a `Head Corruption`.
WIN10 really is a filthy child. 
winfried

**Comment by szukw000** [comment]
@Albrecht-S,
I meant "Heap Corruption".
winfried

**Comment by Albrecht-S** [comment]
@szukw000 Winfried, **_this issue has been closed_**. Your new report emphasizes (IMHO) that there must be something weird going on in **your** code. The only thing I can recommend is to run your program with a memory checker like asan or valgrind, or try it on another platform (e.g. Linux) and run your program through valgrind on Linux, or use one of the certainly available memory checkers on Windows (which I can't help with).

**_Note:_** you reported above that your program works well on Linux. I conclude that you can build your program on Linux and you should be able to run it with address sanitizer (asan) or valgrind. I'd bet that this will show you some clues where your program goes awry - although it **seems** to operate correctly. If you need help with this procedure, please ask in fltk.general for help (see also below) or consult one of the general user forums like stackoverflow.

If this doesn't help you, please **strip your program down to a small, complete** (i.e. compileable and linkable) **test case** that we can test. **Unless you do this** and this confirms that there is a bug in FLTK **there is no way for us (the FLTK team) to proceed and help you**.

As I wrote before, standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
