### ISSUE TITLE
fl_rescale_offscreen weird behavior on windows

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#475]
Hi
Not sure if it's because I'm not using it correctly, but this example works correctly on Linux and macOS:
```cpp
#include <FL/Fl.H>

#include <FL/Enumerations.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Double_Window.H>
#include <FL/fl_draw.H>

class Canvas : public Fl_Box {
  Fl_Offscreen offs = 0;
  int ox = 0, oy = 0;

public:
  Canvas(int x, int y, int w, int h)
      : Fl_Box(x, y, w, h), offs(fl_create_offscreen(w, h)) {
    fl_begin_offscreen(offs);
    fl_color(FL_WHITE);
    fl_rectf(0, 0, w, h);
    fl_end_offscreen();
  }
  void draw() override {
    if (offs) {
      fl_rescale_offscreen(offs);
      fl_copy_offscreen(x(), y(), w(), h(), offs, 0, 0);
    }
    Fl_Box::draw();
  }
  int handle(int e) override {
    auto ret = Fl_Box::handle(e);
    switch (e) {
    case FL_PUSH: {
      fl_begin_offscreen(offs);
      fl_color(FL_RED);
      fl_line_style(FL_SOLID, 3);
      ox = Fl::event_x();
      oy = Fl::event_y();
      fl_point(ox, oy);
      fl_end_offscreen();
      redraw();
      fl_line_style(FL_SOLID, 0);
      return true;
    }
    case FL_DRAG: {
      fl_begin_offscreen(offs);
      fl_color(FL_RED);
      fl_line_style(FL_SOLID, 3);
      int nx = Fl::event_x();
      int ny = Fl::event_y();
      fl_line(ox, oy, nx, ny);
      ox = nx;
      oy = ny;
      fl_end_offscreen();
      redraw();
      fl_line_style(FL_SOLID, 0);
      return true;
    }
    default:
      return ret;
    }
  }
};

int main() {
  auto win = new Fl_Window(800, 600);
  auto box = new Canvas(5, 5, 790, 590);
  win->end();
  win->show();
  return Fl::run();
}
```
If you remove the call to fl_rescale_offscreen, it works correctly, but the call is necessary if resizing is needed.

This produces a strange blurry artifcat while drawing:
![image](https://user-images.githubusercontent.com/37966791/182148320-a52f3bab-1823-4cfd-86ab-961cefba00a1.png)

**Comment by Albrecht-S** [comment]
Hi @MoAlyousef, thank you for the report and the demo program. I can reproduce the issue on my windows VM.

However, it looks as if this effect is caused by rounding errors **and** your usage of `fl_rescale_offscreen()` -- at least in my environment: my **system** (Windows) screen scaling factor is 125%, and this is my observation with your program:

- start program, draw by dragging: the canvas moves slowly to the right and produces artifacts (much better visible than in your screenshot)
- type `ctrl/-` once (FLTK displays "90%"): still artifacts
- type `ctrl/-` a second time ("80%"): no artifacts

Note that 1.25 * 0.80 = 1.00, i.e. 80% is equivalent to the native screen resolution and all other scaling factors are likely to suffer from rounding effects.

Note also that the printed scaling factor in the test code below is the "FLTK scaling factor" on top of the system scaling factor, i.e. it starts usually with 1 even if the system scaling factor is 1.25 (as in my case).

I assume you have a similar configuration on Windows which would explain the effect, right?

Questions (please answer independent of the solution below):
1. What is your system scaling factor on this Windows system?
2. What happens if you type `ctrl/-` once or more, does it change the behavior?

Solution: you should call `fl_rescale_offscreen()` only if the screen scaling factor changed WRT the previous draw() call. I fixed your demo program with code like this -- including test `printf()'s` which can be seen in my MinGW environment but maybe not if you compile with MSVC compilers. My proposed code changes (remove test statements):
```C++
// add this if you need fl_message() output (see below, commented out):
#include <FL/fl_ask.H>

// ... add this to the member variables:
  float scf; // scaling factor

// ... add the following lines at the end of the constructor:
    scf = Fl::screen_scale(0);
    // fl_message("scaling factor = %g\n", s);
    printf("scaling factor = %g\n", scf); fflush(stdout);

// ... change your draw() method like this:
  void draw() override {
    Fl_Box::draw();
    if (offs) {
      float s = Fl::screen_scale(0);
      if (s != scf) {
        // fl_message("scaling factor = %g\n", scf);
        // printf("New scaling factor = %g\n", s); fflush(stdout);
        fl_rescale_offscreen(offs);
        scf = s;
      }
      fl_copy_offscreen(x(), y(), w(), h(), offs, 0, 0);
    }
  }
```
This is simplified and works only on screen 0 (the first screen). My solution above is based on educated guesses (call `fl_rescale_offscreen()` only if the scaling factor was changed) and testing. It works for me with all tested screen scalling factors. I didn't look at the FLTK code though but I believe that @ManoloFLTK could tell if my assumptions are correct. Manolo?

Other than that it could be possible that the implementation of `fl_rescale_offscreen()` has a bug but that's also something Manolo would know better.

That all said, this issue doesn't look like a platform (Windows) issue, it's more like a "system scaling factor related" issue (at least if my assumptions are correct).

PS: independent of the given solution I suggest to use the new Fl_Image_Surface rather than the old fl_offscreen in new code.

**Comment by Albrecht-S** [comment]
PS: My solution lacks a proper initialization: you need to scale the screen at least once, e.g. ctrl/- and ctrl/+ to scale the canvas but I'm leaving this as an exercise to the user. ;-)

**Comment by MoAlyousef** [comment]
Thanks @Albrecht-S for looking into this. Indeed the scaling factor I'm using on my windows machine is 125%. Also pressing ctrl/- twice does indeed not show any new artifacts. Applying your solution also works.

**Comment by Albrecht-S** [comment]
Great, thanks for confirmation.

**Comment by ManoloFLTK** [comment]
Yes, fl_rescale_offscreen() should be called only when the scaling factor changes value.
I attach a version of the code based on class Fl_Image_Surface.
This version does not blur when rescaling because the canvas is kept a constant size and gets drawn to the display with whatever zoom is necessary.

```
#include <FL/Fl.H>
#include <FL/Enumerations.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Image_Surface.H>
#include <FL/fl_draw.H>

class Canvas : public Fl_Box {
  //Fl_Offscreen offs = 0;
  Fl_Image_Surface *offs = 0;
  int ox = 0, oy = 0;

public:
  Canvas(int x, int y, int w, int h)
      : Fl_Box(x, y, w, h), offs(new Fl_Image_Surface(w, h)/*fl_create_offscreen(w, h)*/) {
    //fl_begin_offscreen(offs);
    Fl_Surface_Device::push_current(offs);
    fl_color(FL_WHITE);
    fl_rectf(0, 0, w, h);
    //fl_end_offscreen();
    Fl_Surface_Device::pop_current();
  }
  void draw() override {
    if (offs) {
      //fl_rescale_offscreen(offs);
      //fl_copy_offscreen(x(), y(), w(), h(), offs, 0, 0);
      Fl_RGB_Image *img = offs->image();
      img->scale(w(), h(), 0, 1);
      img->draw(x(), y());
      delete img;
    }
    Fl_Box::draw();
  }
  int handle(int e) override {
    auto ret = Fl_Box::handle(e);
    switch (e) {
    case FL_PUSH: {
      //fl_begin_offscreen(offs);
      Fl_Surface_Device::push_current(offs);
      fl_color(FL_RED);
      fl_line_style(FL_SOLID, 3);
      ox = Fl::event_x();
      oy = Fl::event_y();
      fl_point(ox, oy);
      //fl_end_offscreen();
      Fl_Surface_Device::pop_current();
      redraw();
  //fl_line_style(FL_SOLID, 0);//incorrect here because not a drawing context
      return true;
    }
    case FL_DRAG: {
      //fl_begin_offscreen(offs);
      Fl_Surface_Device::push_current(offs);
      fl_color(FL_RED);
      fl_line_style(FL_SOLID, 3);
      int nx = Fl::event_x();
      int ny = Fl::event_y();
      fl_line(ox, oy, nx, ny);
      ox = nx;
      oy = ny;
      //fl_end_offscreen();
      Fl_Surface_Device::pop_current();
      redraw();
      //fl_line_style(FL_SOLID, 0);
      return true;
    }
    default:
      return ret;
    }
  }
};

int main() {
  auto win = new Fl_Window(800, 600);
  auto box = new Canvas(5, 5, 790, 590);
  win->end();
  win->show();
  return Fl::run();
}
```

**Comment by MoAlyousef** [comment]
Thanks for the Fl_Image_Surface example @ManoloFLTK
