### ISSUE TITLE
fltk-config --ldflags prints "-lm" twice

### ISSUE THREAD

**Issue by ifox12** [fltk/fltk#484]
I'm not sure if there's a good reason for this, but it seems like a bug to me. 
When I execute:
```
$ fltk-config --ldflags
-lfltk -lm -lX11 -lXext -lpthread -lXinerama -lXfixes -lXcursor -lXft -lXrender -lm -lfontconfig -ldl
```
This is the result - with two times the "-lm" flag.

Same for --ldstaticflags:
```
$ fltk-config --ldstaticflags
/usr/lib/libfltk.a -lm -lX11 -lXext -lpthread -lXinerama -lXfixes -lXcursor -lXft -lXrender -lm -lfontconfig -ldl
```

Version:
```
$ fltk-config --version
1.3.8
$ fltk-config --api-version
1.3
```

**Comment by Albrecht-S** [comment]
Thank you for the report. There is no good reason for this other than it may be hard to determine the correct order of and dependencies from other libs. Linking order can be significant, particularly for static linking. I can look into it if you give us more info, see below:

Please tell us where your FLTK version comes from:
- self built (if yes: with `configure/make` or `CMake`)
- from a Linux (?) distribution

Besides that, please tell us also the platform (Linux?), distribution, and version. Thanks.

Note: the distinction `configure/make` vs. `CMake` is important.
Thanks in advance for further information.

**Comment by ifox12** [comment]
I just installed package from the official manjaro repos.
As for the Version, Manjaro uses a rolling release model, and the FLTK package is exactly:

```
pacman -Q fltk
fltk 1.3.8-1
```

Which build system manjaro uses for their version I do not know.

Just tried to compile 1.3.8 myself.
With configure/make:
```
$ ./fltk-config --ldflags
-L./lib -lfltk -lXrender -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -lm -lX11
```
(no dupe)

With cmake:
```
$ ./fltk-config --ldflags
-L./lib -lfltk -lm -lX11 -lXext -lpthread -lXinerama -lXfixes -lXcursor -lXft -lXrender -lm -lfontconfig -ldl
```
(-lm twice)
Also I didn't `make install` so I think the `-L./lib` can be safely ignored either way.

**Comment by Albrecht-S** [comment]
Thanks for the info.

Regarding `make install`: yes, that would change the output, it would replace `-L./lib` with whatever is appropriate/needed.

Note that giving `-lm` twice is usually not an issue but I'll look into it anyway.

**Comment by Albrecht-S** [comment]
For the record: This issue has **very low priority** because the effect is minimal and benign. However, I just tested different build configurations with `configure` and `CMake`, respectively, and I noticed that duplicate flags and libs in the generated output are not only a `CMake` issue but can also manifest with `configure` based builds.

I'm not going to work on this further for now but I'll keep an eye on it and I'll try to fix obvious duplications when I'm working further on the build system. No guarantees though, I have no idea if this is doable. We can't just remove duplicates because we wouldn't know which one to remove in case commandline and/or link order matters.

**Comment by Albrecht-S** [comment]
Coming back to this issue: I tried several FLTK 1.4 (!) builds (configure/make + CMake in different configurations) on Linux and used both `fltk-config --ldflags` and `fltk-config --compile ...` . My test results are that CMake builds don't produce duplicate libraries in the output but configure/make builds sometimes do - particularly when building with Wayland.

Notes:
 - this issue (duplicated libraries in build commands) is benign, it doesn't do any harm
 - sometimes duplicated libs are necessary for static builds (although not for FLTK, see CMake results above)
 - this report is about FLTK 1.3.x which will not be updated anymore (except for severe bug fixes)
 - the configure/make build system will not be changed in 1.4 (other than fixing real bugs), particularly because:
 - configure/make build support will be dropped in FLTK 1.5 (please use CMake instead)
 
Therefore I'm closing this issue now.

**Comment by ifox12** [comment]
Thanks for the effort.

**Comment by Albrecht-S** [comment]
Welcome.
