### ISSUE TITLE
[Wayland] Long dropdown list "jumps" when moving cursor up-down above it

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#495]
Subj.
This can be easily reproduced on "forms" tests under Wayland. Please see the video:

https://user-images.githubusercontent.com/6562863/188481122-c60a8557-b748-42ff-a5b1-612fc24dc6ee.mp4

**Comment by Albrecht-S** [comment]
Thanks for the report. Unfortunately this behavior is the best we (i.e. mainly @ManoloFLTK) could find so far. There's a subtle difference between Wayland and X11: Wayland doesn't allow to position windows at arbitrary locations, the only choice is to position windows over and/or relative to another (most likely the main) window.

The observed behavior is not really "jumping", it's more like "fast scrolling". The difference is that under X11 the menu window is allowed to be as large as the screen and scrolling begins when the cursor is **near the screen border**. Under Wayland this doesn't work. Therefore scrolling begins when the cursor moves **near the main window border**. If you move the mouse slow enough (slower than in your video) you will be able to notice this.

Maybe we could adjust the scrolling speed or something like that so it becomes smoother but I don't know. Manolo?

I believe that's all we can do but @ManoloFLTK may chime in and tell us more about the implementation details and difficulties.

BTW, similar issues apply to popup windows whose positions we can't control sufficiently. This is also due to the Wayland "design decision" that programs may not control window positions (a "security feature").

**Comment by Albrecht-S** [comment]
Here's an alternate video from latest git (commit 13e05f4204cc636e40fd2591898c482aa0085226). As you can see the left instance of `test/menubar` is running with the `X11` backend and the right instance with the `Wayland` backend. The difference is when (where) the scrolling starts: X11 at screen boundaries, Wayland at window boundaries.

[menubar_x11_wayland.webm](https://user-images.githubusercontent.com/26235500/188906037-21ec2b65-b7a1-4d0c-b646-7906a98ce4ea.webm)

I don't see a noticeable difference in scrolling speed on my platform (Linux Mint 20 using Gnome/Wayland session).

This issue will be closed unless there are compelling reasons to keep it open and/or to change the behavior (patches would be appreciated). Please reply within 7 days or earlier.

**Comment by polter-rnd** [comment]
Thanks for the detailed description. Now I see - when I know that it will scroll at window boundary, I'm able to use it accurately. But for the average user who doesn't know this, such dropdowns as in `bin/test/forms` located near the border are quire unusable even when trying to select items slowly...

In GTK3 they somehow solve this, maybe they use some wayland protocol extensions? If I will have time, will try to investigate it.

Just another demo, Wayland (left) and X11 (right):


https://user-images.githubusercontent.com/6562863/189200628-3ac74484-b8c3-4875-a810-44fd4a3401e6.mp4

**Comment by Albrecht-S** [comment]
Thanks for your comment.
> In GTK3 they somehow solve this, maybe they use some wayland protocol extensions? If I will have time, will try to investigate it.

That would be great, any help to improve it will be appreciated. But beware: the existing menu stuff in FLTK is pretty complicated and hard to grok - and probably even harder to change. Looking forward to any investigation results and proposals. TIA.

**Comment by polter-rnd** [comment]
I'm closing this since now it's a duplicate of #613
