### ISSUE TITLE
Dirty selection render

### ISSUE THREAD

**Issue by vit1251** [fltk/fltk#500]
Example application render derty result (see below). How to fix it?

![image](https://user-images.githubusercontent.com/110534/191514982-11047a33-328f-4449-bb8a-158c044b7ff4.png)

**Comment by ManoloFLTK** [comment]
@vit1251 : could you, please, indicate what platform (Linux, Windows, macOS), and what FLTK version are you using ?

**Comment by erco77** [comment]
This looks a lot like the linux focus box drawing (issue #369) a problem that that was in 1.3.x for a long time.
It came down to a default X driver bug with the line width being zero. Default drivers had this problem, and often
it would go away with more precise graphics drivers installed. Since this came up so much, we decided
 to work around in 1.4.x by way of commit 4d88fb6f.
@vit1251 try cloning FLTK from the git repo, and it should have that workaround fix.

**Comment by vit1251** [comment]
Hmmm... I use classic 1.3.8 verision under Debian.
Since you suggest I build git version and well problem nice solution is coming... =)

![image](https://user-images.githubusercontent.com/110534/191876202-b28dd30e-29c8-4526-9c49-7e7cc890f33d.png)

**Comment by erco77** [comment]
Great, so we can close?

**Comment by Albrecht-S** [comment]
Closing this issue after 10 days w/o reply of the OP.
