### ISSUE TITLE
Cairo drawing: alpha images have different ramp compared to X11

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#510]
The alpha ramp of images drawn with Cairo is much steeper compared with images drawn under X11(Xrender) - at least with my setup:
![cairo_x11_alpha](https://user-images.githubusercontent.com/9895976/194579291-921b35e0-9060-4bd4-9f55-ca037f3e89e8.png)
In this example white means opaque, blue transparent (this is the window background).
One can see that with alpha about 90 they are drawn nearly transparent with Cairo, whereas under X11 this value is at about 20.
Is that something FLTK has under control?

Here the program I used to generate this comparison:
[cairo_alpha_image.cxx.txt](https://github.com/fltk/fltk/files/9734827/cairo_alpha_image.cxx.txt)

**Comment by Albrecht-S** [comment]
I can't answer the question whether this is under FLTK control, that's something @ManoloFLTK could probably tell us. However, here is what I see:
1. Pure vision indicates that the right (X11) image is correct since there are almost no visual differences in the lower part of the left (Cairo) image.
2. Using a color picker (Firefox: App menu - more tools - eyedropper) and simple math seems to indicate that the right (X11) image is correct. See example calculation below.

Using `a=95` should IMHO result in `255 * (95 / 255) = 95` (hex: `5F`). The left (Cairo) image returns `#2323ff` whereas the right (X11) image returns `#5f5fff` which appears to be the correct result.

The following SVG image (source) uses a blue background rgb(0,0,0) and opacity='0.372549' (95/255) for the inner square:
```svg
<svg viewBox='0 0 300 300' xmlns='http://www.w3.org/2000/svg'
     xmlns:xlink='http://www.w3.org/1999/xlink' version = '1.1'>
  <rect opacity='1.0' x='0' y='0' width='300' height='300'
    fill='rgb(0,0,255)'/>
  <rect opacity='0.372549' x='50' y='50' width='200' height='200'
    fill='rgb(255,255,255)'/>
</svg>
```
Embedded SVG image:
![rgba](https://user-images.githubusercontent.com/26235500/194700534-7a42eac1-3265-4ccf-a488-b0f798db6f16.svg)

The eyedropper tool shows `#5f5fff` which supports the results above: X11 is correct, the (FLTK) Cairo drawing version seems to be wrong.

@ManoloFLTK ?

**Comment by ManoloFLTK** [comment]
Depth-4 Fl_RGB_Image objects are drawn by libfltk using Cairo as follows :
- the image's RGBA data are used to create and fill a cairo object called "cairo image surface" with function `cairo_image_surface_create_for_data()` ([see Cairo documentation](https://cairographics.org/manual/cairo-Image-Surfaces.html#cairo-image-surface-create-for-data));
- this object is drawn to the cairo scene.

The `format` argument of function `cairo_image_surface_create_for_data()` used by libfltk is CAIRO_FORMAT_ARGB32  [documented](https://cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t) as follows:
`each pixel is a 32-bit quantity, with alpha in the upper 8 bits, then red, then green, then blue. The 32-bit quantities are stored native-endian. Pre-multiplied alpha is used. (That is, 50% transparent red is 0x80800000, not 0x80ff0000.) (Since 1.0)`
Therefore, FLTK currently premultiplies the RGB data of the Fl_RGB_Image by the pixel's alpha value and puts resulting values in the cairo object. This occurs in function `Fl_Cairo_Graphics_Driver::cache(Fl_RGB_Image *rgb)` of source file `src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx `.
If I remove this premultiplication operation from the FLTK source code, I obtain exactly the same result as that produced when drawing to X11.

Should we conclude that the Cairo documentation does not reflect what Cairo really does and ignore the statement that "Pre-multiplied alpha is used." ?

**Comment by wcout** [comment]
Hm.. viewing the SVG image  @Albrecht-S provided with the `pixmap_browser` test program of the Cairo-FLTK version, it is displayed correctly (well almost - I get 5e5eff as value of the inner box, instead 5f5fff).
So maybe there is just something wrong in the path of how the image is created in my test program?

**Comment by ManoloFLTK** [comment]
I have verified that the transparency processing in the above mentionned SVG image drawn by the pixmap_browser program is done at the step of image rasterizing. Therefore, FLTK receives an image with only fully opaque pixels, so the pre-multiplication performed by FLTK doesn't change RGB values.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Here's a **very vague theory**: is it possible that the premultiplication is applied twice in the current code path? What I see in the code is:
1. The Cairo surface `surf` is created with `cairo_image_surface_create_for_data()` with ARGB data.
2. A Cairo pattern is created with `cairo_pattern_create_for_surface(surf)`.
3. This Cairo pattern is stored as the cached image.
4. Later (I don't know when and how) this Cairo pattern is used to draw the image.

In my theory the Cairo pattern contains premultiplied alpha values. If this pattern is used to actually draw to another surface, the stored alpha value **_might_** be applied a second time.

Note that I don't know Cairo well enough to give a definite answer here, it's only a theory.

In the image above I found that the correct value for R and G is `95` (hex `5F`) with `alpha = 95`. If I apply `alpha = 95` a second time on this value I get `95 * 95 * 255 = 35` (hex `23`) which is exactly the wrong value found in the Cairo image.

> Should we conclude that the Cairo documentation does not reflect what Cairo really does and ignore the statement that "Pre-multiplied alpha is used." ?

Probably not. I read about others struggling with this fact and they mentioned that Cairo definitely uses premultiplied alpha values, hence this part appears to be correct. But ... see above.

**Comment by wcout** [comment]
@Albrecht-S I think that is it!

`cairo_mask()` seems to to just that.

Replacing it with `cairo_paint()` gives the correct result. 

```diff
diff --git a/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx b/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
index ebe7c515a..95853e629 100644
--- a/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
+++ b/src/drivers/Cairo/Fl_Cairo_Graphics_Driver.cxx
@@ -778,7 +778,7 @@ void Fl_Cairo_Graphics_Driver::draw_cached_pattern_(Fl_Image *img, cairo_pattern
   cairo_matrix_init_scale(&matrix, double(img->data_w())/Ws, double(img->data_h())/Hs);
   cairo_matrix_translate(&matrix, -Xs + offset, -Ys + offset);
   cairo_pattern_set_matrix(pat, &matrix);
-  cairo_mask(cairo_, pat);
+  cairo_paint(cairo_);
   cairo_restore(cairo_);
   surface_needs_commit();
 }

````

**Comment by Albrecht-S** [comment]
@wcout Wow, that's awesome! Thank you for your further testing and for finding a potential solution.

**Comment by wcout** [comment]
Thanks. Unfortunately this change works only for my program :( and seems to have side effects on others using images (e.g. device demo is broken with it). Perhaps some additional "things" around this fix need to be done - I am absolutely no cairo expert. Perhaps @ManoloFLTK at least gets an idea, what may be wrong.

**Comment by ManoloFLTK** [comment]
Should be good now with the last commit. It runs OK the present test program as well as pixmap_browser, unittests, tiled_image, device.

The solution is to replace cairo_mask by cairo_paint, as suggested, but only if cairo_set_source() was called before.

Thanks for the help. @wcout  : please, close the issue if you agree it's fixed.
