### ISSUE TITLE
FLTK printing and the lost Mac OS Format Dialog

### ISSUE THREAD

**Issue by olarroche** [fltk/fltk#528]
As far as I understand after playing with the `Fl_Printer` object (using the latest 1.4 weekly release), the only way to retrieve the dimensions of the printing rectangle in my app (which I use to dimension my document windows) is by going through a full printing session, enclosed by `Fl_Printer::start_job()` and `Fl_Printer::end_job()` calls, and calling `Fl_Printer::printable_rect()` and `Fl_Printer::margins()` in between. Even if I don't call `Fl_Printer::start_page()` and `Fl_Printer::end_page()`, the printer stills spits out a blank page...

Is there a way (or could you guys implement a way ;-) ) of only retrieving the dimensions, without triggering any printer activity, much in the way of the "Print Format Dialog" which was a standard feature of the good old Mac OS Carbon Print Manager ?

Thank you for your attention,
Olivier

**Comment by ManoloFLTK** [comment]
Under macOS, it's possible to select "Open in Preview" in the print dialog window and to ommit the call to `Fl_Printer::end_job()` to avoid the blank page. How to avoid the need for a print dialog since paper size can depend on the chosen printer? It's also possible to re-use previously determined printable area and margin sizes under the hypothesis that the same printer will be used.

Is this question macOS-specific? or cross-platform?

**Comment by olarroche** [comment]
Thanks for your comment. A few thoughts as a reply :
1) Not calling end_job() will leave the printer as the target of graphics calls instead of your on-screen window, will it not ? This might be a problem, but I must check this.
2) Of course we need to have some information exchange with the printer, but some of it is not really printer-specific, namely : the orientation (portrait/landscape), the paper size (which is chosen among normalized values, like A4, A3, etc...). Maybe only the margins are really printer-specific ?
3) Although the "Print format dialog" was specific to Mac OS (or was it, really ?), the functionality it provided was useful, and as such should probably be (or become) cross-platform, don't you agree ? That's what fltk aims at anyway, and I believe that's good.

Thank you again,
Olivier

**Comment by ManoloFLTK** [comment]
> Not calling end_job() will leave the printer as the target of graphics calls instead of your on-screen window, will it not ? This might be a problem, but I must check this.

The operation that directs graphics towards the printer is done inside begin_page() (a.k.a. start_page()), so the graphics target remains unchanged in the proposed scenario.

**Comment by ManoloFLTK** [comment]
> Of course we need to have some information exchange with the printer, but some of it is not really printer-specific, namely : the orientation (portrait/landscape), the paper size (which is chosen among normalized values, like A4, A3, etc...). Maybe only the margins are really printer-specific ?

The public FLTK API contains all the information for you to get paper sizes. 
- enumeration of paper formats : enum [Fl_Paged_Device::Page_Format](https://fltk.gitlab.io/fltk/classFl__Paged__Device.html#aea57eda0ffa5353c7e678a17675681d4)

- array of sizes of these formats: static const [page_format](https://fltk.gitlab.io/fltk/structFl__Paged__Device_1_1page__format.html) 	[page_formats](https://fltk.gitlab.io/fltk/classFl__Paged__Device.html#afdb0c6fcd2463aa1ce807fc6331ae6da) [[NO_PAGE_FORMATS](https://fltk.gitlab.io/fltk/Fl__Paged__Device_8H.html#ad85fd91db75c56dcf6696635c1db0aff)]

- enumeration of layouts: enum [Fl_Paged_Device::Page_Layout](https://fltk.gitlab.io/fltk/classFl__Paged__Device.html#acf20a8f5990f76f14393b4a8a9b8f812)

**Comment by ManoloFLTK** [comment]
One possibility may be to create an output configuration dialog where the user could select paper size and orientation and whose results would be stored using class Fl_Preferences. These values would be used by the page drawing code.
Later, at print time, the user would be expected to select printers and printer options compatible with these choices. Otherwise, the user could be advised to run the configuration dialog again.

> By the way, you previously told me that "under Mac OS it's possible to ... omit the call to Fl_Printer::end_job(), but is that true only for Mac OS ? I'd like my app to compile and be usable on Linux too...

That's true for macOS but not for Linux where the end_job() call remains necessary.

**Comment by Albrecht-S** [comment]
Is there any progress to be expected regarding this issue?

@ManoloFLTK, you added the "enhancement" label, but are there any code changes to be expected? If not, this issue should be closed soon. Thanks.
