### ISSUE TITLE
Reminder: image readers need to use size argument to avoid illegal memory access

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#542]

**Comment by Albrecht-S** [comment]
Note: the intention of this issue is to **_add a length argument to all image constructors that read from memory_** in the first place and then use this length in the image readers for proper read termination at "end of memory" to avoid data overrun, just like "end of file" would do.

Please refer to my comment [here](https://github.com/fltk/fltk/pull/536#issuecomment-1315195854) and check commit 7f8f7c5b851f4e15cf95c6e819bff284b7fda7ca for compatibility.

**Comment by MatthiasWM** [comment]
Personal note, API's to check:

- [ ] base classes Fl_Image, Fl_Bitmap, Fl_Pixmap, Fl_RGB_Image, Fl_Shared_Image, Fl_Tiled_Image
- [ ] Fl_XBM_Image
- [ ] Fl_GIF_Image
- [ ] Fl_XPM_Image
- [ ] Fl_BMP_Image
- [ ] Fl_JPEG_Image
- [ ] Fl_PNG_Image
- [ ] Fl_PNM_Image
- [ ] Fl_SVG_Image
- [ ] Fl_ICO_Image

**Comment by Albrecht-S** [comment]
Reopening for reference until #592 is merged.
