### ISSUE TITLE
Fl_win32.cxx RegisterDragDrop cause memory leak

### ISSUE THREAD

**Issue by xhawk18** [fltk/fltk#569]
line 2021 in Fl_win32.cxx , there's RegisterDragDrop  called there.
after removed this function call, the memroy leak goes away.

**Comment by Albrecht-S** [comment]
Thank you for the report.

Given the line number 2021 in `Fl_win32.cxx` you are using FLTK 1.3.x which will very likely not be updated anymore. The same code is in [line 2246 of Fl_win32.cxx](https://github.com/fltk/fltk/blob/a8923a0fd4424a07fff247fe1167909264f8a117/src/Fl_win32.cxx#L2246) in FLTK 1.4.0 (git).

Since calling RegisterDragDrop is done per window I agree that this causes a memory leak and this should be fixed in FLTK 1.4.0. According to Microsoft docs we should probably call [RevokeDragDrop](https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-revokedragdrop) when the window is destroyed.

Commenting out or removing this call is not an option because it is required for drag and drop operations. 

@xhawk18: How did you find the memory leak? Can you give us (me) some advice so we can test and verify a potential solution?

**Comment by xhawk18** [comment]
> @xhawk18: How did you find the memory leak? Can you give us (me) some advice so we can test and verify a potential solution?

thank you for the reply!  
please try test code below, and may found memory grows slowly.

```
#include <FL/Fl.H>
#include <FL/Fl_Window.H>

void hide(void *arg) {
    Fl_Window *win = (Fl_Window *)arg;
    Fl::remove_idle(hide, win);
    win->hide();
}

int show() {
    Fl_Window win(220, 90);
    win.show();

    Fl::add_idle(hide, &win);

    return Fl::run();
}

int main() {
    while (true) {
        show();
    }
}
```

**Comment by Albrecht-S** [comment]
I believe I found a possible solution, see attached patch [issue-569_v1.diff](https://github.com/fltk/fltk/files/10171124/issue-569_v1.diff.txt). It's maybe not the last version but I'm asking for feedback.

@xhawk18 This patch is for FLTK 1.4 (git) exclusively. Can you please try FLTK 1.4 and this patch and report if it solves the problem for you? I tried your demo program and it solves at least the memory leak. Please do not use in production software, it's still not tested thoroughly.

**Comment by xhawk18** [comment]
@Albrecht-S I test the patch, and no memory leak found now! thank you!

**Comment by Albrecht-S** [comment]
@xhawk18 Thank you for confirmation, but please keep in mind that this patch is only a proof of concept and may need modifications.

**Comment by Albrecht-S** [comment]
@MatthiasWM I created two branches in my fork. The first branch [issue-569_RegisterDragDrop](https://github.com/Albrecht-S/fltk/tree/issue-569_RegisterDragDrop) contains the fix (patch) above and is intended to be merged if you agree. This is included in PR #583.

I also added another branch [issue-569_RegisterDragDrop_Debug](https://github.com/Albrecht-S/fltk/tree/issue-569_RegisterDragDrop_Debug) which is not intended to be merged (no PR) but can be used for debugging.

@MatthiasWM You may wonder why I'm asking specifically you? Because the code in question was added by you and stands unchanged for more than 20 years!
```
commit 4603756ed1284dfc9d71a556976f4f5b898abd24
Author: Matthias Melcher <...>
Date:   Sun Feb 24 17:52:18 2002 +0000

    - added Win32 native drag'n'drop code
    ...
```

Here is a log that shows what happens in my debug branch with the patch above and many log statements:
```
$ wine bin/test/hello.exe 
FLDropTarget() [  1]                    initialized with m_cRefCount = 1
FLDropTarget::AddRef() [  1],           returning        m_cRefCount = 2
RegisterDragDrop(000000000001004e, ...) returned error code 0
hide_show_cb[   1]: hide()
Calling RevokeDragDrop(000000000001004E)
FLDropTarget::Release() [  1] executing ...
FLDropTarget::Release() [  1] done,     returning        m_cRefCount = 1
Returned from RevokeDragDrop(000000000001004E)
OK - RevokeDragDrop(000000000001004E) succeeded, return code = S_OK (0)
hide_show_cb[   1]: show()
FLDropTarget::AddRef() [  1],           returning        m_cRefCount = 2
RegisterDragDrop(000000000002004e, ...) returned error code 0
hide_show_cb[   1]: done.

hide_show_cb[   2]: hide()
Calling RevokeDragDrop(000000000002004E)
FLDropTarget::Release() [  1] executing ...
FLDropTarget::Release() [  1] done,     returning        m_cRefCount = 1
Returned from RevokeDragDrop(000000000002004E)
OK - RevokeDragDrop(000000000002004E) succeeded, return code = S_OK (0)
hide_show_cb[   2]: show()
FLDropTarget::AddRef() [  1],           returning        m_cRefCount = 2
RegisterDragDrop(000000000003004e, ...) returned error code 0
hide_show_cb[   2]: done.

hide_cb: hide()
Calling RevokeDragDrop(000000000003004E)
FLDropTarget::Release() [  1] executing ...
FLDropTarget::Release() [  1] done,     returning        m_cRefCount = 1
Returned from RevokeDragDrop(000000000003004E)
OK - RevokeDragDrop(000000000003004E) succeeded, return code = S_OK (0)
hide_cb: done.
after Fl::run(), exiting...
~FLDropTarget() [  0]                   deleted     with m_cRefCount = 1
```

This executes the modified `test/hello.exe` (cross-compiled on Linux) under `wine` but I also tested this on Windows (MinGW + Visual Studio 2019). It opens the window, runs a timer that hides and shows the window twice and then waits until it's closed. I hope the log is self-explanatory.

The important lines are the first and last lines of the log:
```
FLDropTarget() [  1]                    initialized with m_cRefCount = 1
...
~FLDropTarget() [  0]                   deleted     with m_cRefCount = 1
```

These lines show that the `FLDropTarget` instance is destroyed although it does not delete itself when its refcount reaches 0 because it's now initialized with `m_cRefCount = 1` rather than 0.

When I read the code I first thought it was OK to delete the `FLDropTarget` object when `m_cRefCount` reaches 0. I remembered to have read something about this in the MS docs. However, as soon as I call `RevokeDragDrop()` for the first time the refcount is decremented and the `FLDropTarget` deletes itself and crashes (invalid heap or something). I saw this in the VS debugger. First I removed the delete operation but then I decided that it would be sensible to initialize the object with `m_cRefCount = 1` because ... it exists (refcount 1). Then `addRef()` increments and `Release()` decrements the count as can be seen in the log. This looks plausible but I don't know why it would crash.

As a proof I called `RevokeDragDrop()` immediately after `RegisterDragDrop()` and this crashed as well in the original code. So something must have been wrong. (?)

I didn't investigate further when and why the `FLDropTarget` object is finally deleted. It happens in the destructors when the program exits.

The number in `[..]` shows the number of `FLDropTarget` instances which is never larger than one and is decremented to zero when the object is finally deleted which looks good.

Note that the last line `~FLDropTarget() [  0] deleted with m_cRefCount = 1` is **not** output when the program is built with Visual Studio because it would otherwise crash (at least in debug mode). I found out that at that point in time when the destructors are running there is no longer a console window and it crashes with an assert (`isatty() failed`). Hence I disabled this printf() when compiled by VS (wonderful MS world!), however you can set a breakpoint at that statement and look at the values. No problem if you build it with MinGW (or cross-compile under Linux with MinGW).

The other two demo programs run longer so they can be used to watch the memory consumption (leak) with the Windows task manager, see [commit log](https://github.com/Albrecht-S/fltk/commit/f6ac2cf912f37689d5730efd622279149fe52ed8).

Sorry for the long description. I hope it helps to make a decision so we can push the fix (or another one).

**Comment by MatthiasWM** [comment]
@Albrecht-S Sorry, my internet was and still is down, so it took a while to answer. I used the week for administrative jobs with the city, because they only communicate by fax... . Germany in 2022 🙄.

Anyway, yes, this code is 20 years old and was taken from a Microsoft example app, copied verbatim, and adapted until it worked. Adding `RevokeDragDrop()` surely is important because WIN32 does not do global cleanups, and some resources my be lost until reboot! 

The RefCount in this class is unnecessary. `class FLDropTarget flDropTarget` is initialised before `main()` (see the last line of the class declarations) and must never be deleted as it will be auto-deleted when the app is closed. I don't know if there is any functionality to this beyond deleting the class. MS's OLE system has always remained a mystery to me.

So, I'd keep the recounter, but remove the part that deletes the class. Initialising the RefCounter to 1 does pretty much the same thing, because having been initialised at app start makes it referenced the first time.

**Comment by Albrecht-S** [comment]
> The RefCount in this class is unnecessary. class FLDropTarget flDropTarget is initialised before main() (see the last line of the class declarations) and must never be deleted as it will be auto-deleted when the app is closed.

Doh, I should have seen that. It would have saved me a lot of debugging time, but I learned a lot while debugging Windows code.

I restored initializing the refcount with 0 and added a comment
```
  DWORD m_cRefCount; // for "statistics" only (issue #569)
```
... and removed the deletion but left the refcount as-is because I didn't want to change more than necessary.

Thanks for your help!

Committed in 8dea6505e92a93156820ea24f1256f08cf2b9e8f.

**Comment by MatthiasWM** [comment]
Thanks. Sorry for that hidden "gem". It took me a while to find it too after looking for where in the world the constructor was called.
