### ISSUE TITLE
Fl_Text_Display with line numbers and scrollbars has a minor drawing problem

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#578]
**Describe the bug**
This is an old issue (also in FLTK 1.3.8). Actually there are two things:
- Fl_Text_Display with line numbers displayed has an undrawn area that can display garbage or undefined content.
- When the horizontal scrollbar first appears a fragment of the line number remains visible.

**Steps to reproduce the behaviour:**
1. Start `test/editor`
2. Turn on line number display (`Ctrl-L` or via menu)
3. Keep pressing 'Return' to insert new lines
4. When the screen is full the horizontal scrollbar appears

Now the screen looks like that:
![editor_linedisplay_after_hscrollbar](https://user-images.githubusercontent.com/9895976/206478160-d82f3d43-6045-47e0-9838-ee456e5f90ae.png)

There is the remain of a line number below the line numbers.
(If the scrollbar is configured to be on top, then the remains are on the top of the line display).

After resizing the window or even just by pulling down a menu and back the screen regains:
![editor_linedisplay_after_hscrollbar_focus](https://user-images.githubusercontent.com/9895976/206478888-a3361502-4086-4cfb-926b-f9aa2e48b999.png)

There is now a grey rectangle under the line numbers. This is how it obviously was designed).

Initially after looking into the source of `Fl_Text_Display.cxx` I had a hard time finding out who is drawing this grey rectangle.

Long story short: Nobody! This rectangle is not drawn by Fl_Text_Display and not by its group (from which it inherits). When drawing the line numbers clipping is setup so that this rectangle is excluded from drawing.
Who puts the rectangle on screen now? It's the editor's window background!

As proof I changed `editor.cxx`, so that it has a green window background. Now the screen looks like this:
 
![editor_linedisplay_green_window_background](https://user-images.githubusercontent.com/9895976/206482399-b9938ec4-a8b4-4f5c-8c1a-7aab36cda5dd.png)

I don't think this is the expected look. 

**Expected behavior**
The rectangle if even drawn should have FLTK's `FL_BACKGROUND_COLOR`, at least it should not be left undrawn.

I have here a patch, that draws this rectangle from within Fl_Text_Display:
[textdisplay_linenumber_drawing_garbage.diff.txt](https://github.com/fltk/fltk/files/10186743/textdisplay_linenumber_drawing_garbage.diff.txt)

If you agree I could also file a PR for this.

**Comment by rageworx** [comment]
There's strange issue like filltect drawing by FL_GRAY between scrollbars , right down corner in FLTK.
In my case, different logic to draw each issued block like Fl_Text_Display own color() like this:
![image](https://user-images.githubusercontent.com/6948225/206552940-25f62c19-984d-4824-b4a6-3a501cbd1357.png)
( It's a capture of my own encrypting tool for windows and macOS )

These Fl_Text_Display widgets are set to color( FL_BLACK ) and draws each empty places by its color().
Is it kind of solution to fix your issue ?

**Comment by Albrecht-S** [comment]
@rageworx I don't understand what exactly you want to tell us. Did you patch the FLTK sources or derive your own class or did you only set color()? Would you propose to use another solution? If yes, what exactly would that be?

As I understand @wcout's proposal both "empty corners" would now be drawn with `FL_BACKGROUND_COLOR` rather than `FL_GRAY` (right bottom, between the scrollbars) and not at all (left bottom or top, which is the reason for this issue).

I believe `FL_BACKGROUND_COLOR` is the correct choice but there may be other options.

@wcout AFAICT the patch looks good, please open a PR. Then we can merge it - unless someone else finds a bug.

Thank you very much!

**Comment by rageworx** [comment]
> @rageworx I don't understand what exactly you want to tell us. Did you patch the FLTK sources or derive your own class or did you only set color()? Would you propose to use another solution? If yes, what exactly would that be?
> 
> As I understand @wcout's proposal both "empty corners" would now be drawn with `FL_BACKGROUND_COLOR` rather than `FL_GRAY` (right bottom, between the scrollbars) and not at all (left bottom or top, which is the reason for this issue).
> 
> I believe `FL_BACKGROUND_COLOR` is the correct choice but there may be other options.
> 
> @wcout AFAICT the patch looks good, please open a PR. Then we can merge it - unless someone else finds a bug.
> 
> Thank you very much!

Dear @Albrecht-S ,
Yes, you are right - "bgcolor" may better choice. :)
I was just asked @wcout to about "is it similar issue as I had question since FLTK version 1.3.x", maybe different issue rather than his bug report.
Fl_Text_Display draws FL_GRAY filledrect here even other color decided for its widget here,
- https://github.com/fltk/fltk/blob/0bb30d8f92839af826fb389fccd625c74e981a13/src/Fl_Text_Display.cxx#L3881
If I set to Fl_Text_Display draws as FL_RED, but Fl_Text_Display always draws FL_GRAY on right down small rectangle to FL_GRAY when H&V scrollbars --- Is it mean always scrollbars always FL_GRAY ?
My question was belong to here. Just all.
Regards, Raph.

**Comment by Albrecht-S** [comment]
@rageworx I merged @wcout's proposal as-is but I noticed your question regarding the color of the "unused" corners. The current fix draws them in `FL_BACKGROUND_COLOR` which is IMHO correct because this is what is (mostly) expected.

Please note that `FL_BACKGROUND_COLOR` is a dynamic color (not just GRAY) depending on the system environment. If you want to create a "dark theme" - as it looks in your screenshot - then it would be best to change the FLTK colors to make the background dark.

This is all I can say to this and if you still have questions, please ask on [fltk.general](https://groups.google.com/g/fltkgeneral) which would be the right place. Please don't use this PR for further discussion (it's closed). Thanks.
