### ISSUE TITLE
fltk timer, different behavior for Windows and macOS ?

### ISSUE THREAD

**Issue by rageworx** [fltk/fltk#580]
Dear,

I was followed FLTK timer changes since 1.3 and current version, and have a question for now, is it normal ? Or have wrong to me.
As I remember, old version don't need check has_timeout() before repeat_timeout(), but it changed almost latest of 1.3.8.
Here's some usage for macOS and Windows, with my customized FLTK ( timer source is same with here. )

- Make Image O' HDR,
   -  https://bitbucket.org/rageworx/make_img_o_hdr/src/12cb3e884d8df28ae84ba3122ca9946467880760/src/winMain.cpp#lines-671

In case of macOS, always has_timeout() return not existed, Windows(MinGW-W64) does for this code for repeating time out in class method,
```
            if ( Fl::has_timeout( WMain::TimerCB, this ) > 0 )
            {
                Fl::repeat_timeout( 0.08f, WMain::TimerCB, this );
            }
            else
            {
                Fl::add_timeout( 0.08f, WMain::TimerCB, this );
            }
```
So always macOS needed to add_timeout() to make same effect for repeat_timeout().

And end of TimerCB, there's repeat code too.
```
            Fl::repeat_timeout( 1.5f, WMain::TimerCB, this );
```
In this case, don't need to check has_timeout(), just repeat_timeout() works fine.

I've been read this issue, https://github.com/fltk/fltk/issues/517 and https://www.fltk.org/doc-1.4/migration_1_4.html#migration_1_4_add_timeout too.
But I don't understand what's the difference, 0.08f still too tight to repeat timer on macOS ?
Or need to call Fl::wait() for actual Timer callback ?
Please give me some right instruction if availed for better timer control. :)

**Comment by rageworx** [comment]
Or , as issue of @Albrecht-S 's  https://github.com/fltk/fltk/issues/524
Fl::repeat_timeout() must be called in Fl::lock() and Fl::unlock() ?

**Comment by Albrecht-S** [comment]
Hi @rageworx, there have been timeout fixes on macOS in FLTK 1.3.7, i.e. after the release of 1.3.6 in commits f091b18adfd12e4d91a5da40e379de2f8421d49d and 50e398a52c629fe9a572b9f0120bc21c1afecbc6 on Jul 25, 2021. These two commits fixed an unusual behavior and a potential crash on macOS.

The code you linked above seems to be wrong (see below why) but maybe it was useful (or even necessary) to prevent the crash that could happen up to FLTK 1.3.6.

The general rule is that you **_should_** call `Fl::repeat_timeout()` only inside a timer callback to **repeat** the same timer callback in a more accurate way rather calling `Fl::add_timeout()` to schedule the next callback. The code you linked above is too much to see what happens and when (i.e. in which context) this part of the code is called.

That said, the behavior of timeouts should be more consistent on all platforms since the release of FLTK 1.3.7.

- If you call `Fl::add_timeout()` a **new** timer is scheduled on all platforms which means that you can have more than one pending timer for the same callback. You should check if this can happen and if is what you want. On macOS in FLTK before 1.3.7 an existing timer would be rescheduled which meant that only one timer with the same callback could ever exist (IIRC). This was a bug that was fixed.

- `Fl::repeat_timeout()` **also** schedules a new timer but if you call it from within a timer callback the timer interval is corrected in a way that it is more accurate. If you call it outside a timer callback it works as if you called `Fl::add_timeout()`.

- In all cases calling `Fl::add_timeout()` or `Fl::repeat_timeout()` too often or with a too small delay can lead to a timer "overrun" that uses 100% CPU time and may cause your UI to hang.

- you should never need to call `Fl::has_timeout()` if you do what is recommended.

> 0.08f still too tight to repeat timer on macOS ?

This depends on how long your timer callback and other parts of your program need to work correctly. If you call `Fl::repeat_timeoout(0.08, ...)` **inside** the timer callback then the next schedule is corrected by the delay your currently acting timeout callback had from its scheduled time until you call `Fl::repeat_timeoout()`. The effect _should_ be that your timer is scheduled very accurately at the given interval every time. However, if your timer callback and the sum of other activity between two timer callbacks needs more than 0.08 seconds then the next timer callback will be called immediately after event and timeout processing and likely cause 100% CPU load. If this happens you may either use a longer interval or call `Fl::add_timeout()` rather than `Fl::repeat_timeout()` in the timer callback because `Fl::add_timeout()` does not use the correction mechanism that `Fl::repeat_timeout()` uses.

That said, FLTK 1.4.0 got a new timeout handling that is not only as consistent as possible on all platforms (as in 1.3.7++) but even identical because it uses the same internal code on all platforms. If you are in doubt, please use 1.4.0 (git) - unless you are doing this already (looking at your code and repos you seem to be doing this already).

**Comment by Albrecht-S** [comment]
That all said, this is not the right place to ask for advice. I tried to help anyway, but ...

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

Please close the issue and follow the advice above if you have further questions. Thanks.

**Comment by rageworx** [comment]
Oh, I though it is right place to ask right usage, but only for kind o installing issues?
Oh, Sorry for wrong place asking.
But I got answer for repeat_timeout don't need call in async thread to exposure asynchronous UI update.
Thank you again, @Albrecht-S !

**Comment by Albrecht-S** [comment]
@rageworx: you wrote:
> I got answer for repeat_timeout don't need call in async thread to exposure asynchronous UI update.
Thank you again, @Albrecht-S !

You're welcome. But I'm not sure if you misunderstood me or if I misunderstand what you wrote now.

To clarify:

1. You **_should_** always call `Fl::add_timeout()` etc. from the main FLTK thread. If you call one of these methods within a timer callback this is always correct - because it is executed in the main thread.
2. If you call one of these functions from a worker thread you **must** use `Fl::lock()` before and `Fl::unlock()` after these calls somewhere in your thread. This can reduce your thread performance.

Regarding point 2. above: I wrote in https://github.com/fltk/fltk/issues/524#issue-1422891483, point (3) that this needs to be **verified and documented**. This has not yet been done. Note point (4.) of this comment that current documentation **disallows completely** to call these methods from a worker thread. This applies to FLTK 1.3.x but if point (3) can be verified the restriction of point (4) would be removed, but (3) is still true. This will be documented when it is verified. Until then you should keep the restrictions of FLTK 1.3 in mind.

**Comment by rageworx** [comment]
Yes you meant what I understood.
thank you again!
