### ISSUE TITLE
Cast between incompatible function types warnings in Fl_Widget.H

### ISSUE THREAD

**Issue by gvnnz** [fltk/fltk#591]
I'm using FLTK as a git submodule (commit 3834a2324858891772c5341827f1d53c7d36f1cd) and I get the following warnings during compilation:

```
Fl_Widget.H: In member function ‘void Fl_Widget::callback(void (*)(Fl_Widget*))’:
fltk/FL/Fl_Widget.H:658:48: warning: cast between incompatible function types from ‘void (*)(Fl_Widget*)’ to ‘void (*)(Fl_Widget*, void*)’ [-Wcast-function-type]
  658 |   void callback(Fl_Callback0* cb) {callback_ = (Fl_Callback*)cb;}
```

```
Fl_Widget.H: In member function ‘void Fl_Widget::callback(void (*)(Fl_Widget*, long int), long int)’:
fltk/FL/Fl_Widget.H:666:17: warning: cast between incompatible function types from ‘void (*)(Fl_Widget*, long int)’ to ‘void (*)(Fl_Widget*, void*)’ [-Wcast-function-type]
  666 |     callback_ = (Fl_Callback*)cb;
      |                 ^~~~~~~~~~~~~~~~
```

Compiled with g++ version 10.2.1 20210110 (Debian 10.2.1-6).

**Comment by MatthiasWM** [comment]
Now that is one picky compiler. I will look into that, but for now, you can disable or ignore that warning (-Wcast-function-type)

**Comment by Albrecht-S** [comment]
> Now that is one picky compiler ...

... or the OP configures their build with non-default warnings which is not wrong per se but can generate "unnecessary" warnings.

Our CI builds don't show these warning, but we're using default compiler flags. We're using:
- Linux/X11: Ubuntu 20.04.5, **gcc 9.4.0** (same as I'm using)
- Linux/Wayland: Ubuntu 22.04.1, **gcc 11.3.0**
- macOS: macOS 12.6.1, **AppleClang 14.0.0.14000029**
- Windows: Microsoft Windows Server 2022, **Visual Studio 17 2022, MSVC 19.34.31935.0**

None of these builds issues this warning.

@gvnnz Please tell us how you setup your build (i.e. how you setup compiler flags/warnings etc.).

**Comment by gvnnz** [comment]
@Albrecht-S that warning is triggered by the `-Wcast-function-type` flag, which comes with `-Wextra`, a flag that I have enabled in my build.

**Comment by Albrecht-S** [comment]
> Let's hear what the other devs have to say.
> ... possible solution: we would need to introduce an additional member variable that stores the type of user_data for the callback. Then make the callback_ member a union of different callback types, and then in do_callback make sure that we call the right one.

I don't think that this works w/o opening another can of worms. This has been discussed before and it would be possible that it breaks existing user programs.

Strictly speaking we'd have to store both the callback type (`Fl_Callback`, `Fl_Callback0`, or `Fl_Callback1`) **and** the type of userdata when it was set, see `user_data()` setters and getters and `argument()`. What if they are incompatible because the user code is inconsistent? Which one is "the right one"?

Even if we called "the right one" (i.e. the right type of callback) the user could set up their callback function with an incompatible type (argument type is either `long` or `void *`). This is something where we IMHO use undefined behavior as well (at least we're in a gray zone).

We can't guarantee that user code would set up the callback function with the same mechanism they use to set the callback() and eventually - in that callback - access the userdata. Note that you can also set the userdata value independent of the callback. Which type would be "the right one"? And what if the user does it "wrong"? Think of backwards compatibility.

Also: if you define a union then you **must** access the same union member for read operations that you used to store it, otherwise the behavior is undefined. **IF** we stored the type (i.e. which union member we used to store the data) and wanted to avoid undefined behavior then we'd have to return `NULL` or `0` (zero) if the user doesn't use a compatible type of callback to access the data. This would very, very likely break existing user programs.

I don't see a way to "fix" this warning w/o the potential to break user programs **and** w/o using other undefined behavior **and** in a backwards compatible way. Don't forget that we have callbacks not only for widgets but also for menu items and maybe more.

If there's interest to pursue this topic and find a way to improve this w/o backwards compatibility issues then this should be discussed in fltk.coredev and not here. I'm always open for discussions to improve FLTK but this is the wrong place.

And I apologize for the long comment which is OT here according to what I wrote above.

**Comment by Albrecht-S** [comment]
> that warning is triggered by the -Wcast-function-type flag, which ... I have enabled in my build.

@gvnnz OK, thanks for confirmation. It's OK to enable additional warnings in your build and we appreciate reports of "uncommon" warnings (and try to fix them) but I don't think we can fix this particular warning in FLTK (see above why I believe this). I suggest to disable this warning explicitly in your FLTK (submodule) build.

Are you concerned about the warning for your own build? If yes, you can ignore/disable it, it's benign.

Did you want to report it to the FLTK team? This is a known issue, thank you for the report, but I don't think we can "fix" it.

**Comment by gvnnz** [comment]
@Albrecht-S and @MatthiasWM thanks for the interesting comments, I learned something new today. I'm not an expert when it comes to C and its best practices, I thought that kind of undefined behavior was something to avoid. I think I can just disable the warning as you @Albrecht-S suggested and close this issue. Thanks again
