### ISSUE TITLE
fltk.1.4.x: Fl_String really needs append / insert / delete to be usable

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#601]
I was tempted to use it, but in its current state it looks like it's mainly for just managing strdup()/free().

Also the static `string_count` seems scary for thread safety; I assume that's for debugging/development and wouldn't be in the final class.

The more I look at it, the more I'm thinking it should marked as a WIP.

**Comment by Albrecht-S** [comment]
I created the class for a single purpose, to return a string from some fl_ask etc. related functions. And looking at your report, I guess my development effort was somehow interrupted and I forgot about the debugging stuff.
From Fl_String.H:
```
  Fl_String is the basic string class for FLTK.

  In this version Fl_String can be used to store strings, copy strings,
  and move strings. There are no string manipulation methods yet.
```

Please feel free to:
- [ ] remove all the debugging stuff including commented-out statements like `// debug something`
- [ ] add new methods to append something or whatever you need

I can remove the debugging stuff tomorrow if you like but I wouldn't want to add new features myself.

Sorry for the confusion. Please let me know what you want to do.

**Comment by MatthiasWM** [comment]
I started to use it in FLUID. I derived my own class that avoids NULL content for empty strings. I also wouldn't;t mind if you keep `hexdump()`.

**Comment by wcout** [comment]
Probably it is all there already!?

Let me explain.
I would really be nice to have an UTF-aware string class, with insert, append, delete...

And there is already the `Fl_Text_Buffer` class that has this features:
https://fltk.gitlab.io/fltk/classFl__Text__Buffer.html

So my idea would be to transfer most of `Fl_Text_Buffer`'s methods (probably all except the highlight and and callback related ones) into the `Fl_String` class and make `Fl_String` a base class for `Fl_Text_Buffer` as a beginning.
Afterwards some more convenience methods could be added to `Fl_String`.

(If compatibility is an issue - an new class `Fl_UTF8_String` class could be derived from `Fl_String` for that).

This could then also be used to improve the `Fl_Input_` class, where it always was a nuisance to deal with the non UTF aware insert/replace.. positions.

**Comment by MatthiasWM** [comment]
That is a great idea. Everything should be UTF-8 anyway. I assume that the Gap handling must be in the base class, but I will check if that is too heavy for short string.

**Comment by Albrecht-S** [comment]
There may be some useful additions to this class, i.e. for string handling in FLTK. But having a **gap** in the internal data as it is in `Fl_Text_Buffer` is IMHO **NOT** one of these. For methods like `c_str()` we need the data consecutive in the buffer. It would be really awkward and a real performance issue if we had to copy the data for such methods as it is (or would be) required in `Fl_Text_Buffer` if we had `Fl_Text_Buffer::c_str()`. Note that we have `Fl_Text_Buffer::text()` that **copies** the buffer for users to access it (which is OK for this class but not for a base string class).

Other than that @wcout's idea could be interesting for a redesign but I don't think this is the right time to do it.

**Comment by Albrecht-S** [comment]
> I wouldn't mind if you keep hexdump()

OK, that would not be an issue, it's pretty small. But maybe it would be better in a generally usable class to make a hex dump to memory or something like that, or at least we should be able to specify the output stream or file.

**Comment by wcout** [comment]
I wouldn't expect  "gap" handling to be in the `Fl_String` class (TBH I currently don't understand properly what the gap is for and why it has be in the same allocation unit as the text).
`Fl_String` (or `Fl_UTF8_String`) should IMHO contain UTF8 aware "position" handling so as to insert/delete/substr/size etc. not with *byte* positions/offsets but (UTF-)character positions/offsets and lengths.

`Fl_Text_Buffer` could have the 'gap' string as a separate member e.g.

````cxx
Fl_Text_Buffer: public Fl_String {
...
private:
  Fl_String gap_;
}
````
But maybe I just don't understand 'the gap concept fully and talk nonsens...

**Comment by Albrecht-S** [comment]
The "gap" in `Fl_Text_Buffer` is where the last character was inserted and where consecutive input would be expected. This enables more input characters/bytes to be stored w/o shifting the rest of the buffer out of the way for each single character. As you can imagine, the "gap" is moved around and extended (if necessary) whenever a single character is inserted unless the insert position is already at the position of the gap. This means that the input buffer stores three parts: two parts of the full buffer contents plus the gap:
- first part of the buffer contents
- the gap, in varying size (size may be 0 at some time)
- second part of the buffer contents.

@wcout Regarding UTF-8 character rather than byte oriented handling: `Fl_String` is just a buffer of bytes and does not actively "support" UTF-8.

It might be "interesting" to consider a new class (`Fl_UTF8_String` as you suggest or another name) that uses Unicode character rather than byte indexing. The problem I see with such a class is that indexing might be very slow because you always need to scan the buffer unless you use a proper caching mechanism for character indices.

OTOH we might consider adding some UTF-8 "character index" features to `Fl_String` but this should IMHO only be done for special cases, for instance a method like `unsigned int Fl_String::character_at(int pos)` could return the Unicode "character" (code point) at that (Unicode character) position in the string. That's only a vague idea though, not a real concept.

**Comment by erco77** [comment]
IMHO it's fine that `Fl_String` be limited to byte-per-char string management, and `Fl_UTF8_String` would be a different, higher level class that could be derived from `Fl_String` to handle simple byte management.

For instance I could see `Fl_UTF8_String` having an internal optimization array of pointers, one for each utf8 character in the string, each pointing to the corresponding utf8 character at that index position. The array would be 'off' by default (NULL), but the first time `char_at(position)` is called, the pointer array is created (a single linear lookup hit), such that subsequent calls to `char_at()` could then just use the array, making it inexpensive to do character lookups by position from then on. Any changes to the string would update the ptr array as efficiently as possible. This would avoid repeated linear lookups, jumping quickly to a particular character quickly, and perfectly utf8 aligned.

There'd be a memory hit for such a feature, but I imagine if, in the case of a text editor for instance, when strings with this optimization are scrolled off the display (no longer being edited), the feature could be cleared, saving on memory. Since files are mostly scrolled offscreen anyway, this would prevent a memory hit for e.g. large files, and would only affect the strings in the display being actively edited.

**Comment by Albrecht-S** [comment]
> the static string_count seems scary for thread safety; I assume that's for debugging/development and wouldn't be in the final class.

@erco77 Commit 1d212b7a0394fb72e76b3e713e2aa949cea4d612 removes the static variable `string_count` and cleans the debugging code but leaves it in the class and documents it so it can be used as requested by @MatthiasWM (hexdump).

Output is still to stdout. If this should be changed we have two options:
- write to stderr instead
- change the API to make the output variable (either stdout, stderr, a file, ...?)

I'm leaving this open for further discussion.

**Comment by MatthiasWM** [comment]
I added teh argument `preserve_text` to `alloc_buf()` so that the buffer capacity can be increased without changing the content. Implementing `append` should be very easy now. FLUID adds `int empty()`, `void operator=(const char* s)`, and `operator const char* () const` which I can move form `Fd_String` to `Fl_String`.

**Comment by MatthiasWM** [comment]
See #683

**Comment by MatthiasWM** [comment]
I just merged a much improved Fl_String class into master: 9f87af8ad9a3d8112518b6bbb5b6075881a5b9a2
This class mimics a subset of std::string. It's tested thoroughly with the new Ut_Suite class in unittests.
