### ISSUE TITLE
Valgrind leak with fl_putenv changes

### ISSUE THREAD

**Issue by F7F** [fltk/fltk#64]
On Feb 10 2020 a commit with the comment "Implement fl_putenv() as cross-platform putenv()" (git 4c1b92eb52db567b4c1618222bb3007a2a2e7d9b) changed Fl_Posix_System_Driver.H and the putenv() method to:

virtual int putenv(const char *var) {return ::putenv(strdup(var));}

Valgrind is now complaining of a memory leak at that point on my system (Gentoo Linux), probably because putenv() is not taking ownership of the string returned by strdup(). FYI.

**Comment by Albrecht-S** [comment]
Yes, this is (unfortunately) intentional. The Linux (glibc) implementation `uses the given string`, which `becomes part of the environment; changing it later will change the environment` (according to the man page). Other implementations (e.g. Windows) don't have this issue.

For being entirely cross platform we sometimes need to make compromises. I decided to accept the memory leak rather than adding sophisticated environment string management in the FLTK library. I don't see an easy way (or any way at all) to implement a safe solution w/o the potential leak.

This is documented in the latest FLTK docs which are not yet officially online as of this writing, but you can view it on our [**experimental** GitLab mirror](https://fltk.gitlab.io/fltk/group__fl__unicode.html#ga7561ee8db315213580d0b164c9a71ae1).

I didn't see a better way to implement it. All suggestions for improvement would be welcome.

PS: I was thinking of an option to use a second argument or another interface to let the user keep ownership of the string (w/o using strdup()) but I'm afraid this would be problematic according to what the Linux man page states.

**Comment by F7F** [comment]
I suspected that might be the case. It's only 13 bytes, it's easy enough to add another Valgrind suppression, and I don't have any better ideas, so I'm going to close this. This is the only leak I see in FLTK versus the megabyte or so in libfontconfig and libGL, so relative to other system libraries FLTK is exceptionally clean regardless. Thanks for the quick reply!

**Comment by Albrecht-S** [comment]
You're welcome, and thanks for the feedback.
