### ISSUE TITLE
`fltk-config --compile` could handle multiple source files including `.fl` files

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#647]
**Is your feature request related to a problem? Please describe.**
`fltk-config` is really great, but it can handle just one C/C++ file when compiling.

**I am using FLTK**
1.4.0

**Describe the solution you'd like**
It would be relatively easy to add support for compile multiple files in one call. And to add one on top, it could write the code to do that as a CMake file. What a great way to jumpstart new user projects. Syntax should be:

`fltk-config --compile checkers.cxx checkers_piece.fl`

or 

`fltk-config --cmake checkers.cxx checkers_piece.fl >CMakeLists.txt`

**Describe alternatives you've considered**
So far, every new project requires copying boilerplate code from another project.

**Comment by Albrecht-S** [comment]
1. I'm +1 :+1: on extending `fltk-config` to be able to compile and link multiple source files in one command.

~Alternatively~ Additionally it would be useful if it could compile a source file without linking it, like the compiler would do with its `-c -o obj-file` commandline swtiches, like
```sh
fltk-config --compile-only example-gui.cxx      # compile only
fltk-config --compile example.cxx example-gui.o # compile and link
```

This means that `fltk-config` would need to know that a `.o` or `.obj'  extension is already compiled (it checks file extensions anyway). Or it could use only the first file to compile and require that additional files are object files (or libraries).

2. I'm not so sure that "compiling" `.fl` files in `fltk-config` is a good idea because it would make it more complex than necessary. If we have the feature(s) mentioned above the user could easily extend the example:
```sh
fluid -c example-gui.fl                         # create example-gui.{cxx|h}
fltk-config --compile-only example-gui.cxx      # compile only
fltk-config --compile example.cxx example-gui.o # compile and link
```

3. I'm -1 :-1: on creating `CMake` files **in fltk-config**.
 
I'm not against doing it in general but it should be done in another tool.

Note: KISS and the Unix philosophy: one task - one tool.

**Comment by Albrecht-S** [comment]
After thinking about it (and reading the proposals above again) I propose the following solution which resembles compile/link commands:

1. Add "`-c`" switch to `fltk-config` which has the same meaning as in compiler commands: compile but don't link one or more **source** file(s)
2. This "`-c`" switch would be used **instead of** "`--compile`"
3. "`--compile`" could be deprecated and replaced with "`--build`" because "`--compile`" is not exactly what it really does. We'd keep it for compatibility though.
4. Allow multiple input files with "`--build`" where all files can be either source files, object files, or even (static) libraries. This is possible because all input files would be processed by the compiler/linker in one command.
 
This way every invocation of `fltk-config` would execute exactly one command and wouldn't need a "loop" inside `fltk-config` to process all files with several commands.

Regarding `fluid` (`.fl`) files as input files: my first thought was "don't do that", mainly because `fluid` could be called directly and secondly because this would need a kind of loop in `fltk-config` which would make it more complicated (see above). However, **_one big advantage_** of allowing `.fl` as input files would be that `fltk-config` could make sure to use a compatible `fluid` command, i.e. the one that was generated by the same library build, and not one that is incidentally in the user's PATH.

Building an example project with multiple input files including a fluid (`.fl`) file could be done like this:
```
fltk-config -c example-gui.fl                  # create example-gui.{cxx|h}
fltk-config -c example-gui.cxx                 # compile example-gui
fltk-config --build example.cxx example-gui.o  # build = compile and link
```

A more complex "ad hoc project" consisting of multiple fluid and source files and a pre-built object library (my_lib.a) could be:
```
fltk-config -c gui-main.fl
fltk-config -c gui-other.fl
fltk-config --build main.cxx sub.cxx gui-main.cxx gui-other.cxx my_lib.a
```

**Comment by Albrecht-S** [comment]
Please see also related issue #656.

**Comment by Albrecht-S** [comment]
Here's another idea that could be used to implement issue #656 as well:

Both `fltk-config -c` and `fltk-config --build` (`fltk-config --build`) could forward everything on the commandline that is not one of the known file types (.fl, .cxx, .cpp etc.) directly to the compiler command line. This would make additional commandline flags (see #656) unnecessary.

Example project (above) with another source file and built with "-Wall" and more flags:
```
fltk-config -c gui-main.fl
fltk-config -c gui-other.fl
fltk-config -c -Wall -W -Wextra -Wsuggest-override tools.cxx
fltk-config --build -Wall -Wsuggest-override main.cxx sub.cxx gui-main.cxx gui-other.cxx tools.o my_lib.a
```

Note: instead of the new `--build` command the old `--compile` command could be used as well.

**Comment by Albrecht-S** [comment]
FYI: I'm working on a proof of concept (see [issue 656](https://github.com/fltk/fltk/issues/656#issuecomment-1399346106)).

I'll let you know of my progress, hopefully tomorrow.

**Comment by Albrecht-S** [comment]
I assigned issue #647 and #656 to myself because I'm working on a solution for both issues in one update.

The basic ideas are:
- [ ] allow more than one source file on the --compile commandline
- [ ] add --build as an alias for --compile (or vice versa)
- [ ] accept any unknown argument as a compiler flag or linker flag and forward it to the compile command
- [ ] keep the order of flags and input files in case order is relevant
- [ ] maybe: add `-c` (compile-only) flag (I'm still investigating options)
- [ ] optional: allow fluid .fl files as input, process by fluid, and replace ".fl" with ".cxx" on the build commandline

In my current model processing fluid files would be done in a first step before compilation is attempted. This shall ensure that all fluid files can be replaced by their equivalent source files in the final build command.

This is still a model but I'm pretty confident that it will work. My current WIP can already process multiple C++ source files and compiler flags.

**Comment by Albrecht-S** [comment]
Commit https://github.com/fltk/fltk/commit/877126e572c2d473cd80de7abaae6d0fadc5c142 fixes this issue (almost completely). It allows more than one source file and additional compiler and linker switches as requested by #656 but it does not allow `.fl` files to be processed by `fluid`. This may be implemented later (or not?).

I updated the help output to display the new `--compile` and `--link` options. The new syntax is:
```
fltk-config --compile MAIN [ FLAGS ] [ SOURCES ] [ --link LFLAGS LIBS ]
```
where
- `MAIN` is the main source file with all allowed source file extensions and must immediately follow `--compile` (as before)
- `FLAGS` are optional compiler flags
- `SOURCES` are optional source files, object files, or libraries. File extensions are not checked.
- `--link` separates compiler flags from linker flags and other libs (see below)
- `LFLAGS` and `LIBS` are typically other libraries and their search flags (e.g. `-L/path/to/lib -lsomelib`)

`FLAGS`, `SOURCES`, `LFLAGS`, and `LIBS` are optional and can be anything the compiler/linker understands. There are no syntactic checks; these options are simply copied to the final commandline.

The sole purpose of the `--link` option is to separate compiler flags and source files from linker flags and libraries that are added **after** the normal compiler/linker command generated by previous versions of `fltk-config`. This can be necessary if link order matters.

The final commandline is composed like this example:
```
fltk-config --compile main.cxx button.o -Wextra x1.a --link -L /usr/include/cairo/ -lcairo
g++ {fltk-flags} -o main -Wextra main.cxx button.o x1.a {fltk-libs} -L /usr/include/cairo/ -lcairo
```
where `{fltk-flags}` are the compiler flags generated by `fltk-config` as before and `{fltk-libs}` are the usual llinker flags and libs.

There's one peculiarity regarding the order of compiler flags and "source" files: order of flags and source files is taken from the commandline but all flags (`-something`) are positioned before all sources, i.e. arguments w/o leading dash (`'-'`).

Notes:
- I took the opportunity to refactor the existing code, simplify it, remove unnecessary parts, add comments, and unify indenting. This makes the diff larger than strictly necessary but it was the only way I could manage all the intended changes.
- Diff stats say that the file is 32 lines longer than before. Not too much IMHO (some lines are comments).
- I tested the changes thoroughly with `configure/make` and `CMake` and it seems to work well but it's not possible to test all combinations of build options and user commandlines.
- Testing and feedback would be very much appreciated. Thanks in advance.
- I'm leaving this issue open, awaiting feedback...

**Comment by Albrecht-S** [comment]
FTR: I believe this issue can be closed, unless someone finds any issues. Features implemented and not implemented are as follows:
- multiple source files, libraries, and compiler/linker flags can be used
- documentation [has been updated](https://www.fltk.org/doc-1.4/basics.html#basics_fltk_config)
- a new documentation section [has been added](https://www.fltk.org/doc-1.4/basics.html#basics_fltk_config2)
- compile-only option (`-c`) has intentinally not been implemented
- option `--build` as an alias for `--compile` has intentinally not been implemented
- the option to "compile" fluid (`.fl`) files has not been implemented (may be done later)

Feedback would be very much appreciated. Otherwise this issue will be closed in about three days.

**Comment by Albrecht-S** [comment]
Closing this issue now.

"Compiling" fluid (`.fl`) files will not be implemented in the context of this issue, but if there's still interest in this feature a new issue may be opened.
