### ISSUE TITLE
[1.4.x] fluid lost color for comments (regression)

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#654]
Screenshot says it all; in 1.3.x comments used to be italic / green, but the color was lost in 1.4.x, turning large fluid trees into walls of text that are kinda hard to read:

![image](https://user-images.githubusercontent.com/6484779/212763294-2e902d8b-5744-4c98-b424-036353406fb6.png)

**Comment by erco77** [comment]
Also, the bold font used for showing the first line in "Code" items (beneath function declarations) seems to emphasize un-important info, at least in my case.

Perhaps instead of bold, the first line of 'Code' can just be normal font, or some non-distracting color like a light blue or gray, so as not to be distracting; I would think the first line of code is usually not very interesting to see (unless it's a comment for the code block),  yet still clearly showing as "different" from the functions/widgets/etc.

Here's a mockup of the 1.3.x screenshot above, with a normal font with slight blue color added for the "Code" lines:
![image](https://user-images.githubusercontent.com/6484779/212765729-e761e0ca-b326-4a51-b35b-ef0d0e77dd5d.png)

**Comment by ManoloFLTK** [comment]
@Albrecht-S 
I have determined that this issue begins with commit 78cf29ba29 dated 28 dec 2022 and authored by Albrecht.

It appears that the call  `fl_contrast(FL_DARK_GREEN, color())` done at line #303 of file fluid/widget_browser.cxx returns an erroneous color, black or grey, instead of the expected green color.

The commit mentionned above introduces a heavy modification of function fl_contrast(). If the new fl_contrast() function is modified adding
```
  fl_contrast_mode_ = FL_CONTRAST_LEGACY;
```
at the beginning of function fl_contrast() (line #464 of file src/fl_contrast.cxx), fluid recovers its green comment lines. This modification has fl_contrast() work as before commit 78cf29ba29.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks for looking at this and for finding this. The mentioned change would revert the **_default contrast mode_** to the "legacy" mode which is in many cases worse than the newer default mode.

I don't have the time to check the details further right now, therefore the following statements are only first thoughts:

I see two options to "fix" this issue:
1. use a little darker green than FL_DARK_GREEN in the fluid code
2. use `fl_contrast_mode(FL_CONTRAST_LEGACY)` in fluid [as documented here](https://www.fltk.org/doc-1.4/group__fl__attributes.html#ga97d26b73ccb60281ea6ae9ab94f4e9df)

Option 1 would IMHO be the preferred option. If you look at the old image above, it appears (to me) that `FL_DARK_GREEN` has indeed too little contrast and the old (legacy) method didn't detect this. The new test/contrast demo program can be used to compare (see the instructions, and set the colors and maybe the background in fiels number 255).

Option 2 would IMHO be a regression. We should use the new contrast mode wherever possible because it's in general superior.

Besides that, there are still a few "tuning" options in the new fl_contrast() algorithm.

I'll check the details later, when time permits.

**Comment by MatthiasWM** [comment]
Somewhat darker green is surely fine. Not that I had an issue with readability.

**Comment by Albrecht-S** [comment]
I propose the following patch:
```diff
diff --git a/fluid/widget_browser.cxx b/fluid/widget_browser.cxx
index ac1e9da2e..b1d799ef0 100644
--- a/fluid/widget_browser.cxx
+++ b/fluid/widget_browser.cxx
@@ -299,8 +299,9 @@ void Widget_Browser::item_draw(void *v, int X, int Y, int, int) const {
   if (show_comments && l->comment()) {
     copy_trunc(buf, l->comment(), 80, 0);
     comment_incr = textsize()-1;
-    if (l->new_selected) fl_color(fl_contrast(FL_DARK_GREEN,FL_SELECTION_COLOR));
-    else fl_color(fl_contrast(FL_DARK_GREEN,color()));
+    Fl_Color comment_color = fl_color_average(FL_DARK_GREEN, FL_BLACK, 0.9);
+    if (l->new_selected) fl_color(fl_contrast(comment_color, FL_SELECTION_COLOR));
+    else fl_color(fl_contrast(comment_color, color()));
     fl_font(textfont()+FL_ITALIC, textsize()-2);
     fl_draw(buf, X, Y+12);
     Y += comment_incr/2;
```

This makes the green color for comments 10% darker, i.e. RGB(0,145,0) becomes RGB(0,130,0).

The contrast value of the new `fl_contrast()` algorithm of the original `FL_DARK_GREEN` is 49.96 which is borderline (should definitely be > 50 (or 55)), but the old algorithm (which is definitely wrong in many aspects) accepted it anyway as sufficient contrast. 

The contrast value of the 10% darker green is 55.49 which is OK.

I tested the patch and it works fine for me.

Background: technically spoken, the legacy (FLTK 1.3) `fl_contrast()` algorithm was definitely broken and returned bad results (see #370). In this case the broken algorithm "allowed" using `FL_DARK_GREEN` as an acceptable color. The fix is to use a better color, rather than changing the contrast algorithm.

If nobody objects I can fix it in the code, applying the patch above.

**Comment by Albrecht-S** [comment]
> Somewhat darker green is surely fine. Not that I had an issue with readability.

OT: contrast perception by humans is a complicated issue. I learned much when I worked out the new algorithm for issue 370 and studied the APCA algorithm and documentation about it. One thing I learned was that contrast perception depends on "spatial frequency", i.e. in the context of written text: the font size. Our current algorithm supports theoretically using the font size, but does not yet use it. In this case, however, the comment font is tiny, and we should therefore select a higher contrast anyway. Even if we all can read it, people with visual handicaps can have even more trouble reading the small comment font in the green color with too little contrast.

**Comment by ManoloFLTK** [comment]
> If nobody objects I can fix it in the code, applying the patch above.

No objection on my side. The patched fluid displays nice green comments.

**Comment by MatthiasWM** [comment]
No objection. Thanks for checking all this. And I actually learned something about color.

**Comment by erco77** [comment]
Patch works for me -- feel free to commit + close Albrecht

**Comment by Albrecht-S** [comment]
Done in commit 0eeb6fe33ea40a8ea85716f5f8bef4621faed042.

Sorry, I missed to mention the issue number in the commit log.
