### ISSUE TITLE
Fl::clipboard_contains() cannot query selection buffer

### ISSUE THREAD

**Issue by CendioOssman** [fltk/fltk#690]
**Describe the bug**
Unlike all other clipboard functions, `Fl::clipboard_contains()` does not have a source argument. It assumes the source is always the clipboard, not allowing any way to query the selection buffer.

**Operating System / Platform:**
Only relevant on Unix/Linux as the other platforms don't have a selection buffer.

**Comment by ManoloFLTK** [comment]
FLTK can only put text in the selection buffer. That's documented for the `Fl::copy()` member function. FLTK only pastes non-text data, which is then necessarily image data, from the clipboard. That's documented for the `Fl::paste()` member function.

Can non-FLTK apps put image data in the selection buffer under X11 ? Is that what you would like FLTK to support ?

**Comment by CendioOssman** [comment]
> Can non-FLTK apps put image data in the selection buffer under X11 ?

Yes

> Is that what you would like FLTK to support ?

Actually, no. What I am after is to see whether the selection buffer is empty or not. Sorry for the confusion.

**Comment by erco77** [comment]
I think what the OP is requesting is for `Fl::clipboard_contains()` to have a `destination` flag (optional?), similar to Fl::copy()'s argument of the same name to allow checking for contents of the selection buffer vs. clipboard.

**Comment by ManoloFLTK** [comment]
At this point, I'm not favorable to add to FLTK a function to test whether the selection buffer is empty for these reasons:
- the selection buffer exists only for the X11 platform (and not under Wayland which is now the default Linux platform);
- the clipboard is essentially never empty because it always contains the last thing copied, therefore the new function would be useless in 3 of the 4 platforms FLTK supports;

I tried to add code that does XConvertSelection() + XNextEvent() + XGetWindowProperty() to check the content of the selection buffer under X11 and also find it nearly never empty, that is, after the first time something is selected somewhere, the selection buffer remains not empty as long as the app where the selection was done runs.

The extant FLTK function Fl::clipboard_contains() is not meant to check if the clipboard is empty (not very useful as said above because it's nearly always wrong) but to check whether it contains text or image data (both can be true). 

@CendioOssman: Do you think the present documentation of this function "Returns non 0 if the clipboard contains data matching type." is not clear enough? What would be a scenario where a function to check whether the selection buffer is empty would be useful?

**Comment by ManoloFLTK** [comment]
Closing this after adding much detail to the documentation of function Fl::clipboard_contains().
