### ISSUE TITLE
Test `cairo_test.cxx` does not behave well on Windows

### ISSUE THREAD

**Issue by AnClark** [fltk/fltk#694]
**Describe the bug**
The Cairo test program `cairo_test.cxx` can render properly on Linux: three buttons shows as-is.

However, on Windows (with Msys2), only the label is shown.

**To Reproduce**

1. Configure and build FLTK via CMake. Configuration (as described in this CMake code):

```cmake
set (FLTK_BUILD_EXAMPLES OFF CACHE BOOL "")
set (FLTK_BUILD_TEST ON CACHE BOOL "")
set (FLTK_BUILD_FLTK_OPTIONS OFF CACHE BOOL "")
set (FLTK_BUILD_FLUID ON CACHE BOOL "")

set (OPTION_BUILD_HTML_DOCUMENTATION OFF CACHE BOOL "")
set (OPTION_BUILD_SHARED_LIBS OFF CACHE BOOL "")

set (OPTION_CAIRO ON CACHE BOOL "")
set (OPTION_CAIROEXT ON CACHE BOOL "")
set (OPTION_USE_GDIPLUS OFF CACHE BOOL "")
set (OPTION_USE_SVG ON CACHE BOOL "")

set (OPTION_FILESYSTEM_SUPPORT ON CACHE BOOL "")

set (OPTION_USE_SYSTEM_LIBJPEG OFF CACHE BOOL "" FORCE)
set (OPTION_USE_SYSTEM_LIBPNG OFF CACHE BOOL "" FORCE)
set (OPTION_USE_SYSTEM_ZLIB OFF CACHE BOOL "" FORCE)
```
2. Run `cairo_test.exe` in `build/bin/test`.
3. Build in the same config on Linux (Manjaro), then try & compare.

**Expected behavior**
![image](https://user-images.githubusercontent.com/12870704/223057065-14741534-3133-4947-8dbc-bbb8b1ba30eb.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/12870704/223058919-e8fdf935-3339-4554-bc2e-a6a249f25686.png)

**FLTK Version**
 - Version: 1.4.0
 - Installed as package from: Build from source
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: a52811567ebcd8c9ad96aded3c7581b9cfd78caa

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 10

**Dependencies (Msys2):**
All packages are in mingw64 variant.
- cairo: 1.17.6-3
- pixman: 0.42.2-1

**Comment by Albrecht-S** [comment]
@AnClark Thank you very much for the detailed report. I tested (with a similar configuration) and can confirm the issue if both `OPTION_CAIRO` and `OPTION_CAIROEXT` are `ON` (`OPTION_CAIROEXT` implies `OPTION_CAIRO` anyway).

Can you please try the same build only with `OPTION_CAIRO=ON` ...
```cmake
set (OPTION_CAIRO ON CACHE BOOL "")
set (OPTION_CAIROEXT OFF CACHE BOOL "")
```
and report what you get? In this case the window should show the three "buttons" but not the blue text at the top of the window, like this:

![image](https://user-images.githubusercontent.com/26235500/223235278-63656fef-0f52-4ece-b24f-4b7b8ae4861b.png)

BTW: I had a hard time to figure out how to link `cairo_test.exe` in my build configuration (this still needs some work). I copied the build commandline and modified it until I could link `cairo_test.exe` successfully. I wonder how you could link it with your setup given above. Can you please post your **_full build commands_**? This would help me fixing the issue. Thanks.

You can help further if you do the following for my information:

1. Build FLTK including `cairo_test.exe`
2. Delete `bin/test/cairo_test.exe`
3. Build `cairo_test` again, using e.g. `cmake --build . --target cairo_test --verbose`

Note the `--verbose` switch to display the full commandline. Then please copy the linker commandline that is printed by step 3. above and post it here. Thank you in advance.

**Comment by Albrecht-S** [comment]
I should have mentioned that I will investigate the issue, but please do also answer my questions above.

**Comment by AnClark** [comment]
### 1.  Retry with `OPTION_CAIROEXT` switched off.

Now it works after a rebuild:

![image](https://user-images.githubusercontent.com/12870704/223278669-51106973-9042-4046-9819-f47426e0c6f9.png)

### 2. About `cairo_test.exe` link arguments.

I build FLTK with Msys2 (mingw-w64 variant), **not** MSVC. Link success just in one time.

```
[1/1] cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe  -mwindows test/CMakeFiles/cairo_test.dir/cairo_test.cxx.obj -o bin\test\cairo_test.exe -Wl,--out-implib,bin\test\libcairo_test.dll.a -Wl,--major-image-version,0,--minor-image-version,0  lib/libfltk_cairo.a  lib/libfltk.a  -lcairo  lib/libfltk_cairo.a  -lcairo  -lgdiplus  C:/msys64/usr/lib/libdl.a  -lcomctl32  -lws2_32  -lgdiplus  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
```

**Comment by AnClark** [comment]
However, my application requires `OPTION_CAIROEXT`. They are built by FLUID, based on `Fl_Window` and required directly drawing to `Fl_Window` without migrating to `Fl_Cairo_Window`. I call `Fl::cairo_autolink_context(true);` before invoking the `show()` method.

**Comment by Albrecht-S** [comment]
Thanks for the info. I'll look further into it tomorrow.

**Comment by AnClark** [comment]
Great! Thanks for your help.

**Comment by Albrecht-S** [comment]
FYI: I made some progress in testing this issue, but unfortunately I couldn't find a solution yet. I still have some ideas what to test, but I ran out of time for now.

FTR:
- My build issues mentioned above with MinGW-w64/MSYS2 using its bundled Cairo libs [1] were caused by me using `LDFLAGS=-static` for some reason. I removed this flag and the build succeeded with and w/o `OPTION_CAIROEXT`.
- I could also build FLTK and the Cairo demo programs with VS 2019 (MSVC) using Windows Cairo headers and DLL's I had used previously. However, this needed some (not easy) tweaks of the FLTK CMake files. Maybe I can simplify this as well.
- The issue is the same in both MSYS2 and MSVC builds.

I'm taking a longer break now (taking care of other FLTK stuff), but I will continue later.

--------------------
[1] If someone is interested, I used the following package:
```
$ pacman -S mingw-w64-x86_64-cairo
...
Packages (1) mingw-w64-x86_64-cairo-1.17.6-3
...
```

**Comment by AnClark** [comment]
> The issue is the same in both MSYS2 and MSVC builds.

It appears that current FLTK Cairo implementation (with `OPTION_CAIROEXT` enabled) needs more improvement on Windows.

On Linux, both config (with or w/o `OPTION_CAIROEXT`) works.

Looking forward to further replies & ideas. I'll also put my project aside for a long time.

**Comment by Albrecht-S** [comment]
This issue has been fixed in commit 6e407cb169a3820e3d86e35230bf9b6fea2aef47 and updated in af4789077f44d0391b80432a8e0fcfbf4865a924 to fix a minor issue. Finally it was as "simple" as adding two statements that cause the Cairo drawings to be flushed to the device (screen, window) as this was done in `Fl_Cairo_Window`. Note that this is **_required_** only on the Windows platform but it does no harm on other platforms.

@AnClark You wrote:
> However, my application requires OPTION_CAIROEXT.

Is this the reason why you found the issue? Please test your application after adding similar statements (see below) to your `draw()` method after drawing with Cairo and report here if this solves the issue for your application as well:
```C++
    // flush Cairo drawings: necessary at least for Windows
    cairo_surface_t *s = cairo_get_target(cc);
    cairo_surface_flush(s);
```
Note that `cc` in this code example is the Cairo context (`cairo_t`) previously used for drawing.

I hope this fixes the issue for you as well.

May I ask you to post a small (minimized) but complete example code how you are using the Cairo interface of FLTK in your application? It would be enough to draw a rectangle or something like this. Your example could help to improve our documentation. I assume that you are subclassing `Fl_Double_Window` and overriding its `draw()` method. Is this correct, or is there anything else we could use for our documentation? If you can't post a complete example, can you describe more detailed what you are doing, maybe with code fragments? Thank you in advance for all further information.

**Comment by Albrecht-S** [comment]
FTR: I removed the `CMake` label because this is a general `'Windows + Cairo'` usage issue.

**Comment by AnClark** [comment]
> Is this the reason why you found the issue?

Sure.

I'm re-implementing a synthesizer UI from NTK to recent FLTK. At that time (many years ago) NTK has Cairo support while FLTK was not provided yet. My target is to directly port the original codebase to FLTK without `Fl_Cairo_Window`.

**Comment by AnClark** [comment]
Great! After adding the two lines at the bottom of my `draw()` method, now UI can be shown like this (in REAPER):

![image](https://user-images.githubusercontent.com/12870704/224617669-196b7ede-c00f-4911-9836-9da7dcded218.png)

This is infamousPlugins Cellular Automatic Synth by Spencer Jackson. Reimplemented by me, see: <https://github.com/AnClark/infamousPlugins>.

**Comment by Albrecht-S** [comment]
@AnClark Thank you very much for sharing how you use Cairo in FLTK windows. I need to look closer into this for distilling some information for FLTK documentation (if there's anything new). But anyway, your help is very much appreciated, real user code is always helpful.

#### Regarding the requirement to use `OPTION_CAIROEXT`
I'm not sure that you really need this. There are two options to acquire a Cairo context in FLTK. In your class Background (posted above) you are currently using ):
```
 cairo_t *cr = Fl::cairo_cc();
```
This single statement can only be used (without additional code) if configured with `OPTION_CAIROEXT`, that's true. However, I believe (I'm not 100% sure) you can use
```
 cairo_t *cr = Fl::cairo_make_current(window());
```
instead which is available with the (less intrusive) `OPTION_CAIRO`.

AFAICT you could even - after calling `Fl::cairo_make_current(Fl_Window*)` once at the beginning of your window's draw() method - continue using  `Fl::cairo_cc();` in the draw() method(s) of all subclasses within the same window because this uses the cached Cairo context stored by `Fl::cairo_make_current(window());`. As I said, I'm not sure, I'd have to test this myself. If it works you can use `OPTION_CAIRO` w/o `OPTION_CAIROEXT` but you don't need to use `Fl_Cairo_Window` - as you want.

#### Regarding plans to embed FLTK in "other" windows

> Do you have any plan for adding an API for re-embedding FLTK window to another native window?

No, there are no plans to do this. This would be hard to do cross-platform, so unless someone provides a working implementation for all four currently supported platforms (Windows, macOS, Linux/Unix (X11), and Wayland) I don't believe that anyone would (or could) do this in the near future. Your implementation appears to be Windows specific, isn't it?

Note: I ran out of time now. If I missed to answer something I'll continue later. Please feel free to ask for further information, I'll try to help if I can (as long it's on topic in this issue: using Cairo in FLTK).

**Comment by AnClark** [comment]
### About switching from `Fl::cairo_cc()` to `Fl::cairo_make_current(window())`

> However, I believe (I'm not 100% sure) you can use
> ```
> cairo_t *cr = Fl::cairo_make_current(window());
> ```
> instead which is available with the (less intrusive) OPTION_CAIRO.

If I switch to `Fl::cairo_make_current(window())` and disable `OPTION_CAIROEXT` (but not apply the instruction in `AFAICT` paragraph), should I also switch to `Fl_Cairo_Window`?

### About your instruction in `AFAICT`

Seems that you have an example in `cairo_test.cxx` already, in the `draw()` method (Line 166):

<details><summary>The `draw()` function</summary>

```c++
  void draw() {
    Fl_Window::draw(); // perform drawings with the FLTK API
#ifndef FLTK_HAVE_CAIROEXT
    Fl::cairo_make_current(this); // announce Cairo will be used in this window
#endif
    cairo_t *cc = Fl::cairo_cc(); // get the adequate Cairo context
    draw_with_cairo_(this, cc);   // draw in this window using Cairo

    // flush Cairo drawings: necessary at least for Windows
    // see also FL/Fl_Cairo_Window.H
    // FIXME: this should be simplified with an FLTK API, for instance:
    // Fl::cairo_flush(cc);

    cairo_surface_t *s = cairo_get_target(cc);
    cairo_surface_flush(s);
  }
```
</details>

> As I said, I'm not sure, I'd have to test this myself. If it works you can use OPTION_CAIRO w/o OPTION_CAIROEXT but you don't need to use Fl_Cairo_Window - as you want.

Sure it works, at least in `cairo_test.cxx`, with and w/o `OPTION_CAIROEXT`. To help testing, you can consider do this modification:

```diff
diff --git a/test/cairo_test.cxx b/test/cairo_test.cxx
index f6326f5cb..e896dbbd6 100644
--- a/test/cairo_test.cxx
+++ b/test/cairo_test.cxx
@@ -47,7 +47,7 @@
 //    Fl::cairo_make_current(Fl_Window*).
 
 
-#define USE_FL_CAIRO_WINDOW 1
+#define USE_FL_CAIRO_WINDOW 0
 
 // draw centered text
 
@@ -157,8 +157,13 @@ class cairo_using_window : public Fl_Double_Window {
   void (*draw_with_cairo_)(cairo_using_window*, cairo_t*);
 public:
   cairo_using_window(int w, int h, const char *title) : Fl_Double_Window(w, h, title) {
+#ifdef FLTK_HAVE_CAIROEXT
+    Fl_Box *box = new Fl_Box(FL_NO_BOX, 0, 0, w, 25,
+                             "use Cairo and the FLTK API in Fl_Double_Window\n(with Cairo extention)");
+#else
     Fl_Box *box = new Fl_Box(FL_NO_BOX, 0, 0, w, 25,
                              "use Cairo and the FLTK API in Fl_Double_Window");
+#endif
     box->labelfont(FL_TIMES_BOLD);
     box->labelsize(12);
     box->labelcolor(FL_BLUE);
```

### About why I prefer `OPTION_CAIROEXT` by now

The original project is based on NTK, and initially Linux-oriented. Because NTK only support Linux, I only use NTK there. To make it cross-platform, I use FLTK to provide supports on other platforms.

I need to keep compatibility with NTK, and this is why I prefer `OPTION_CAIROEXT` at first (I can directly port the original drawing code w/o significant changes).

### About embed window support

My current implementation is not usable: it can embed, but it has issues:
- Unable to operate the window
- Incompatible with Hi-DPI, for example, window clipping (just as the screenshot above)

Simply specifying a parent window during `CreateWindowEx()` is not enough. So, I need to find a better way to implement.

### Thanks

Thank you for giving instructions these days! Now my ported plugin UI is fully usable on Windows, with great powered by FLTK.

A great progress has already been made. Next I'll work with embedded window implemention. I will take a long break on this project.

**Comment by Albrecht-S** [comment]
@AnClark Thank you for your test instructions. I didn't have the time to look into it myself yesterday, but now I did (using your helpful advice), and I see now that it works as I had assumed.

You wrote:
> I need to keep compatibility with NTK, and this is why I prefer OPTION_CAIROEXT at first (I can directly port the original drawing code w/o significant changes).

Maybe I was not clear enough. My point is that you can use `OPTION_CAIRO` without `OPTION_CAIROEXT` if you only change one instruction in your window's draw() method, i.e. call in your window's draw() method once:
```
  cairo_t *cr = Fl::cairo_make_current(this);
```
and use (unchanged)
```
  cairo_t *cr = Fl::cairo_cc();
```
elsewhere in widget draw() methods (unchanged).

I would personally prefer `OPTION_CAIRO` over `OPTION_CAIROEXT` because it introduces less overhead. You would also not need to call `cairo_autolink_context(true)` anywhere in your code (if you did, you can remove it).

These tiny changes would in no way affect your Cairo drawing code, i.e. the code you are porting wouldn't be changed at all, except in this one place mentioned above where you added FLTK's Cairo setup calls anyway.

Of course this is not necessary if you are happy with using `OPTION_CAIROEXT`, I only wanted to point out that you very likely don't **need** it.

You also wrote:
> Thank you for giving instructions these days!

You're welcome. I think this issue is now resolved and we should close it. Please close it if you agree.

**Comment by Albrecht-S** [comment]
FYI: finally I can report a small simplification. Instead of adding two "cryptic" statements to flush the Cairo output I added a new FLTK method `Fl::cairo_flush(cairo_t *)` in commit 0f41797b7ab0ee010e31659f60cafd38affac8f5. You may use this if you like.

**Comment by AnClark** [comment]
OK, thanks a lot! Hope these improvements could benefit developers.

---

>

**Comment by Albrecht-S** [comment]
> Problem is that my project uses FLUID. I didn't find any explicit window draw() methods in exported code. ...
> The Double_Window ui is the main UI. It contains a Group of custom widgets (draw with Cairo).

You can either
1. subclass `Fl_Double_Window`, override its `draw()` method, and call `cairo_t *cr = Fl::cairo_make_current(this);` there before calling `Fl_Double_Window::draw()`, or
2. call `cairo_t *cr = Fl::cairo_make_current(window());` in your main group, or
3. call `cairo_t *cr = Fl::cairo_make_current(window());` in all overridden widgets.

The point is that you call `Fl::cairo_make_current()` once **before** you call `Fl::cairo_make_cc();` in any subclass. FLTK's drawing implementation is top-down, hence you can create and setup the Cairo context with `Fl::cairo_make_current();` once in the first widget that is drawn and then **use** it by calling `Fl::cairo_make_cc();` in all subsequent `draw()` methods. Calling `Fl::cairo_make_current()` in all widgets that use Cairo causes only a marginal overhead (a few `if`s) and is probably negligible.

Note the different arguments `this` in the window's `draw()` method and `window()` in widgets.

Given the structure of your code - as far as I saw it - I'd suggest method 2. or stick with `OPTION_CAIROEXT`.

**Comment by AnClark** [comment]
Thank you for your instruction. By now I'll stick with `OPTION_CAIROEXT` as it's the easiest way to handle Cairo context in my project.
