### ISSUE TITLE
Wasm

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#70]
Hello

So I've tried building fltk for wasm and it almost builds. Emscripten ships SDL so it can be chosen as a driver for fltk using ```-DUSE_SDL=ON``` when invoking cmake, however, it appears it only works for apple. The blocker is the following piece of code:
```
#define __APPLE__
#include <SDL2/SDL.h>
#undef __APPLE__
```
Which occurs in 3 files in the whole repository:
fltk/src/drivers/PicoSDL/Fl_PicoSDL_Graphics_Driver.cxx
fltk/src/drivers/PicoSDL/Fl_PicoSDL_Screen_Driver.cxx
fltk/src/drivers/PicoSDL/Fl_PicoSDL_Window_Driver.H
And since apple is defined, the SDL header looks for apple specific headers. Also the Fl_PicoSDL_Window_Driver calls certain protected members of Fl_Window, but that's another issue probably.

Another minor issue was the definition of U32 which isn't detected by emcmake, changing it to unsigned int works.

Are there any plans to make the SDL backend work on other platforms than Apple?

Thank you for all your work

**Comment by Albrecht-S** [comment]
All the `Pico* drivers` and all work on a potential SDL backend is currently only experimental code. The `Pico* drivers` are a proof of concept and only intended as building blocks for other driver (backend) development (at least AFAICT).

To answer your question: I'm not aware of any concrete plans to develop a full SDL backend on any platform - as I wrote the one given for macOS is (was) only experimental work. The `__APPLE__` **hack** was - AFAICT - due to the development on macOS and just to get "something" working.

This is not currently (and maybe not in the foreseeable future) production code. Looking at Git I can see that the last "real" work on this code was at or about Dec 2016. Please use with care.

**Comment by MoAlyousef** [comment]
I see. I'll keep an eye on it, maybe give it a go.
Thank you!

**Comment by RokeJulianLockhart** [comment]
@MoAlyousef, https://github.com/fltk/fltk/issues/41#event-15339976261
