### ISSUE TITLE
[Wayland] Fl_Copy_Surface and Fl::copy() issues

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#707]
**Describe the bug**
`Fl_Copy_Surface` doesn't work reliably with the Wayland backend right after starting the program. I found out that I need to "activate" the program window by clicking into the window and/or the title bar to make it work. When testing this further I found out that copying text with `Fl::copy()` seems to have issues as well. See description below and attached test program with comments.

**To Reproduce**
Compile and run attached test program [copy_image.cxx](https://github.com/fltk/fltk/files/11051716/copy_image.cxx.txt) with the Wayland backend and view the clipboard contents.
1. Launch test/clipboard or another tool to view the clipboard.
2. Compile and execute `copy_image.cxx` using the Wayland backend, but don't click into it and don't move the window around.
3. Watch the output of `copy_image`, it changes between `copy_rect` and `copy_text`.
4. Whenever a new image or text is copied, click on "Refresh from clipboard" in the clipboard viewer.
- as long as the `copy_image` window has not been "activated" by clicking into it the clipboard contents doesn't change
- after clicking into the `copy_image` window the copied images appear
- however, the copied text still does not appear in the clipboard viewer
- in the "text" view of the cliboard viewer you can sometimes see text starting with "BM" which looks like the header part of a bitmap.

**Expected behavior**
The Wayland backend should work in the same way as the X11 backend:
1. The images and the text are copied to the clipboard as expected
2. This works directly after starting the program w/o the need to "activate" the window
3. Interchanging text and image copies works reliably.

**Screenshots**
I hope that screenshots or a video are not necessary.

**FLTK Version**
 - Version: 1.4.0 Git, master, aebf2fec39640e2151d818e96f182af1cb3a63b3

**FLTK Configure / Build Options**
A default build with configure/make or CMake is sufficient.
Compile the demo program with `fltk-config --compile ...`

**Operating System / Platform:**
 - OS Version: Linux Mint 20 (based on Ubuntu 20.04)
 - Debian 12 (Bookworm) has the same issues
 - Gnome/Wayland user session on both systems

**Linux/Unix Runtime, if applicable:**
 - Wayland: see error description
 - X11: works flawlessly

**Additional context**
I noticed this when testing: creating an image at program startup with Fl_Copy_Surface and copying it to the clipboard before executing `Fl::run()` which failed. I noticed that test/device worked reliably though, hence I tried the timer loop to delay image creation and copying to the clipboard. Then I noticed that it worked "sometimes" and found out that I needed to "activate" the program window by clicking into it to make copying the image work. After this "activation" copying the image seemed to work reliably, but interchanging image and text still doesn't seem to work.

Hence, there seem to be two different bugs:
- incomplete Wayland initialization or something like that to make `Fl_Copy_Surface` work correctly
- interchanging text and image copies doesn't work correctly

@ManoloFLTK I'm assigning this issue to you because I don't know who else could fix this.

**Comment by Albrecht-S** [comment]
Adding this issue to the 1.4 milestone because this concerns essential functions.

**Comment by ManoloFLTK** [comment]
I'm afraid Wayland differs somewhat from X11 on the topic of clipboard support.

The reference about how to program clipboard operations for Wayland I've found is:
https://emersion.fr/blog/2020/wayland-clipboard-drag-and-drop/

Early in this web page, one finds a "Clipboard" section, and its "Source client" subsection
which reads

> The source client needs to be the currently focused application. This prevents background applications from unexpectedly changing the clipboard contents right before the users pastes it. This also allows to gracefully handle race conditions when two applications quickly send copy requests.

Thus, only the focused application can fill the clipboard. This explains why this issue notices that "as long as the copy_image window has not been "activated" by clicking into it the clipboard contents doesn't change".

Furthermore, the copied data is tagged by Wayland with a "serial number" that Wayland attributes to a "keyboard enter" event that occurs when a window gets the focus :
> The serial received during the wl_keyboard.enter must be provided to set the selection

This requirement strongly connects the "fill the clipboard" operation with the "give focus to an app" operation.

That's why I believe it won't be possible to have a Wayland FLTK client behave exactly as an X11 client for the specific operations of the present copy_image.cxx test program.

Noticeably, all "standard" clipboard operations work correctly under Wayland with the present code:
- run the editor, device, and clipboard FLTK apps
- perform text copy operations in the editor window, and click "refresh from clipboard" in the clipboard app; 
- perform image copy operations in the device app, and click "refresh from clipboard" in the clipboard app; change the copied image by changing what is selected among  "Decorated window", "Sub-Window", "Group"
- perform text copy operations in non-FLTK apps (e.g., terminal) and click "refresh from clipboard" in the clipboard app
- perform text copy operations in the editor window and paste copied text to the same window or to another window of the same app.
- perform text or image copy operations in non FLTK apps, and paste text to the editor or image to the clipboard FLTK apps
- very large text copy operations work flawlessly

Another Wayland limitation is already noticed in README.Wayland.txt:

> Although the FLTK API to read from and write to the system clipboard is fully functional,
> it's currently not possible for an app to be notified of changes to the content of
> the system clipboard, that is, Fl::add_clipboard_notify() has no effect.

I could add that Wayland can copy to clipboard only from a focused app.

Comments?

**Comment by Albrecht-S** [comment]
Wow, thanks for the detailed explanation and link to the interesting blog (I read it). This is obviously another restriction of the Wayland protocol for security reasons. Avoiding race conditions of different apps sending data to the clipboard seems to be sensible.

> I could add that Wayland can copy to clipboard only from a focused app.

Yes, please add this to the documentation. Maybe it needs more than one sentence though to describe what works and what doesn't work (and why).

But there are still some surprising things, concerning my demo program.

(1) I understand that we need to supply the serial of the keyboard enter (aka focus) event to the copy operation. However, the copy loop in the timer appears to work even after the application lost the focus: I can still receive the changing images in the clipboard app after changing the focus to the clipboard app.
- Is this a Wayland bug (since it allows us to do this)?
- Should FLTK disable (delete, invalidate) the stored serial of the keyboard enter event when the focus is lost?
- Should we reject clipboard copies after invalidation of the serial number in the previous step?

(2) I wrote above that I saw text starting with "BM" in the text view of the clipboard app. The rest of the text (as far as it was readable) were some cryptic, perhaps binary data of something that was probably an image (bitmap).
- Is this an effect of improper handling of clipboard data?
- Can this be avoided if point (1) above is "fixed" in any way?
- Maybe this is one of the race conditions mentioned in this blog article...

I'm not sure if this should still be called a bug but I'm leaving it so for now. I'd appreciate if you could add these facts to the Wayland specific docs (see above) and look into the internals (e.g. stored serial number) and maybe "fix" this so we don't even **try** to send clipboard data when the focus was lost. TIA.

**Comment by ManoloFLTK** [comment]
The commit mentionned above adds a detailed explanation of Wayland restrictions for copy to clipboard operations, and should fix remaining issues.
@Albrecht-S Do you see remaining issues?
