### ISSUE TITLE
Fl_Preferences not stored on Windows 10

### ISSUE THREAD

**Issue by eltomito** [fltk/fltk#710]
**Describe the bug**

The content of Fl_Preferences is not stored between application restarts on Windows 10.

**To Reproduce**

I'm sorry I'm not including code at the moment, I'll amend the bug report later.

1) Create Fl_Preferences
2) Store something in it.
3) Exit the program.
4) Start the program again
5) Open the same FL_Preferences
6) ...and see there's nothing in it.

**Expected behavior**

Fl_Preferences should persist between application restarts.

**FLTK Version**

Version 1.3.4
Installed from source downloaded directly from fltk.org

**Operating System / Platform:**

Windows 10

**Additional context**

I believe the reason is that fltk stores the preferences in a file that it creates in the folder that is pointed to by the AppData key in the Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders registry entry but this registry entry doesn't exist on Windows 10 anymore (see  https://answers.microsoft.com/en-us/windows/forum/all/profile-settings-shell-folders-do-not-use-this/df844603-c0d5-45d5-89b9-3f1aaf8513dd )

**Comment by Albrecht-S** [comment]
Thanks for the report, but FLTK 1.3.4 is really old. Please download a newer version (current is 1.3.8 but you can also use a 1.4.x development snapshot) and try to reproduce the issue. Finding a proper place for Fl_Preferences has changed a lot, at least in 1.4.0 (I'm not sure about 1.3.x).

FWIW, I followed your link and found another dead link to an article "The long and sad story of the Shell Folders key". However, I found an article with this title from the same author "Raymond Chen", supposedly at its new home: https://devblogs.microsoft.com/oldnewthing/20031103-00/?p=41973 .

That said, I can see that this old "don't use this" key is still used in FLTK 1.4.0 (git). This needs to be checked and maybe fixed.

**Comment by Albrecht-S** [comment]
FWIW, I investigated this issue based on the links above and found some facts, documented below with links to Microsoft (MS) docs:
1. The registry key we're using has never been officially supported by MS. It's been used in a beta version of Windows 95 and kept for backwards compatibility - but never documented.
2. We can use the **deprecated function** [SHGetFolderPathW()](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpathw) which is available since Windows XP (desktop only) or Windows 2000 (professional). "As of Windows Vista, this function is merely a wrapper for [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath)".
3. The newer function [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) is available since Windows Vista/Server 2008. We can use this if we load it dynamically and fall back to [SHGetFolderPathW()](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpathw) on older systems.
4. The required CSIDL values for [SHGetFolderPathW()](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpathw) are [documented here](https://learn.microsoft.com/en-us/windows/win32/shell/csidl) together with ...
5. The required KNOWNFOLDERID's for [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) are [documented here](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid).

That said, I don't know which CSIDL value or KNOWNFOLDERID we would want to use. Options would apparantly be:
- CSIDL_APPDATA or FOLDERID_RoamingAppData, resp.
- CSIDL_LOCAL_APPDATA or FOLDERID_LocalAppData, resp.

MS docs further mention: "Applications should [...] put their data under the locations referred to by CSIDL_APPDATA or CSIDL_LOCAL_APPDATA. Since I'm not a "Windows specialist" I'm leaving this for others to investigate further and/or implement a proper solution.

**Comment by MatthiasWM** [comment]
Thank @Albrecht-S for looking into this. I am currently travelling for two more weeks and can only check the list occasionally. The default would probably be CSIDL_APPDATA to match the original idea. We could add ROAMING as an option when creating Fl_Preferences.

**Comment by Albrecht-S** [comment]
@MatthiasWM Thanks for your input, I agree that `CSIDL_APPDATA` or `FOLDERID_RoamingAppData` would be the ID's to use (compatible with the current intention) - and these **are** the "roaming" versions as opposed to the "local" versions `CSIDL_LOCAL_APPDATA` or `FOLDERID_LocalAppData`, respectively. I wouldn't want to change this and I wouldn't add the "local" version as fallback or whatever. But I'm not a Windows "guru".

That said, I tried `fltk-options` (i.e. FLTK 1.4) on my Virtualbox VM running Windows 10 and I found that both "System" and "User" preferences worked fine. I also tested `test/preferences` with the same positive result.

After further investigation I found that the mentioned registry keys still exist in my **Windows 10** system and even in my brand-new **Windows 11** system. The latter has barely been used (just for installing Windows updates and firefox). I also copied `fltk-options` (1.4) and `test/preferences` (1.3.8) to my new **Windows 11** box and **_both worked flawlessly, storing preferences and retrieving them on the next launch_**.

Therefore I assume that the deprecated registry keys are not the issue for the OP @eltomito. We should change finding the correct directory in FLTK nevertheless and this should be done before 1.4.0 gets released.

**Comment by Albrecht-S** [comment]
@eltomito As I wrote before, please download a current (1.3.8) FLTK version and try again. If your application doesn't work, please try `test/preferences[.cxx/.exe]` and report whether you can change some of the preferences and read them back at the next start.

Further information: on my new Windows 11 system the registry keys are as follows (replace `*username*` with the real user name):
```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
  "AppData" = C:\Users\*username*\AppData\Roaming

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
  "Common AppData" = C:\ProgramData
```
These are the directories where you should look for FLTK preference files (root directory = `fltk.org`):
- The first key should be used for user preferences.
- The second key ("Common AppData") should be used for system preferences.

For user preferences there's a fallback to use "`C:\FLTK`" in FLTK 1.3.x which is deprecated and no longer used in FLTK 1.4.

_Important note:_ if you don't have write access to any of these folders on your system (for whatever reason) then preferences will not be written and changes will be silently ignored. This could happen if your protram tries to access either "`C:\FLTK`" or the system preference location, i.e. "`C:\ProgramData`". These directories may be write protected for normal Windows users.

That said, if using FLTK 1.3.8 doesn't help you further but the test program (`test/preferences`) works we really need to see your code. Please post a minimal but complete test program that does what you try to do (not a full application program). It might also help to look at test/preferences.cxx to see how preferences are created and stored correctly.

**Comment by erco77** [comment]
Can we just switch to using a .fltk in the user's %HOMEPATH% like we do with $HOME on other OS's?

I always thought Microsoft's registry concept was terribly flawed; its flat security model, ancient tools and deep hierarchies with pointlessly obscure namespace is just terrible. Names like HKEY_BLA_BLA and CurrentVersion etc all seem meaningless gibberish. It's an obscure operating system database fraught with pitfalls and is always a dreadful experience to manage for both admins and users.

At least with home directories it's possible to move from one machine to another and have your preferences follow you, and this can be easy for the user to control by e.g. symbolically linking the ~/.xyz directory to a local path if needed.

**Comment by Albrecht-S** [comment]
@erco77 I don't think that using an environment variable like `%HOMEPATH%` or `$HOME` is appropriate on Windows. This is (partially) due to different Windows "subsystems" like Git for Windows, MinGW, MSYS2, and Windows itself, i.e. running an application from the explorer, all can have different views of the "home directory". This could be intended behavior for some users, but I don't think that we should do this in FLTK.

Examples:
```
(1) Git for Windows:
$ echo $HOME
/c/Users/albrecht
$ build/debug/bin/test/preferences.exe
Preferences file will be located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences.prefs
App Preferences file is actually located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences.prefs
Preferences user data directory is located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences/

(2) MSYS2 on the same system:
$ echo $HOME
/home/albrecht
$ mount | grep 'on / '
C:/msys64 on / type ntfs (binary,noacl,auto)
$ ls -a /c/msys64/home/albrecht
.   .bash_history  .bash_profile  .config     .gnupg    ...
(note: no `fltk.org` preferences folder)
$ bin/test/preferences.exe
Preferences file will be located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences.prefs
App Preferences file is actually located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences.prefs
Preferences user data directory is located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences/

$ Visual Studio 2019 built preferences.exe, executed from within VS2019:
Preferences file will be located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences.prefs
App Preferences file is actually located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences.prefs
Preferences user data directory is located at:
C:/Users/albrecht/AppData/Roaming/fltk.org/test/preferences/
```

This shows that the current (registry key) version results in a common FLTK preferences file (I changed prefs and checked that they were correctly written to the same file) whereas the "home directory" approach would result in different directories and thus use different FLTK preferences files. That doesn't mean though that the "registry" approach is correct, see below for more.

**_My take on this is:_**
- the "standard Windows user" would expect to find the preferences files in their user (AppData) directory
- this is so now and should be kept for backwards compatibility
- using a (varying) home directory might be "interesting" for experienced users but could result in unnecessary support questions from "standard users" like "where are my prefs, why do they not change ?" etc.).
- I agree with Greg that using the registry is a bad approach, as MS themselves found out in this case ;-)
- therefore we should use the "official" MS function to retrieve the user's "AppData (Roaming)" directory, even if this official function has been changed over time and Windows versions which we need to take care of.
- the "bad thing" is that Windows tries to hide even the home directory from users (in the Windows Explorer, use "This PC") but you can find it easily in a "DOS window". I never understood what this is good for.

**_Note:_** I'm currently working on a proof of concept, using at least the older (meanwhile officially deprecated) function [SHGetFolderPathW()](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpathw) to replace the registry key usage and see how this works out. Using the newer function (loaded dynamically) and falling back to the older one would be an optional addition we might not need at all.

**Comment by wcout** [comment]
In my multiplatform applications I have used
````cxx
char home_path[FL_PATH_MAX];
#ifdef WIN32
fl_filename_expand(home_path, "$APPDATA")
#else
fl_filename_expand(home_path, "$HOME");
#endif
````
with success on all Windows versions from Windows XP onwards.
`%APPDATA%` is documented to exist in all these versions.

**Comment by Albrecht-S** [comment]
@wcout Thanks, I tried both `fl_getenv("APPDATA")` and your version with `fl_filename_expand()` and both seem to work (the former returns backslashes, the latter forward slashes).

Meanwhile my proof of concept works as well. The code is shorter than before but not yet fully tested. However, all versions seem to return the "same" result (notwithstanding backslash vs. forward slash), no matter how they are started (Git bash, MSYS2 shell, DOS window, Windows Explorer).

I'm not sure which one is best to use though. Maybe using the environment variable "`$APPDATA`" would be the easiest but still compatible approach on all supported Windows versions (as opposed to `$HOME` or `$HOMEPATH`). However, using the MS function is the officially supported Microsoft way.

I'd appreciate all comments...

**Comment by Albrecht-S** [comment]
FYI: Looking back on my code I noticed that this code (using `SHGetFolderPathW()`) serves two purposes with modification of only one constant for getting the user path and the system preference path in a Windows compatible way. Thus I decided to implement this in FLTK 1.4 rather than using environment variables.

**Comment by Albrecht-S** [comment]
FYI: I pushed commit c47dfeef61029361978e1f224350d93c8bb7694c in my fork for reference, although this might still be changed (work in progress).

Comments, test results, further suggestions appreciated!

**Comment by Albrecht-S** [comment]
@eltomito Please let us know whether you made any progress with your issue. Note that the committed fix will not be backported to 1.3.x but I'm pretty sure that the usage of the registry key is not your problem because this key still exists in recent Windows 10 and 11 systems despite the "Don't use ..." comment.

Hence your issue looks more like a programming error. Please try `test/preferences.cxx` as suggested above and/or post code as requested if you still need help. Without seeing your code we can't help. If you don't post code or let us know about your progress this issue will be closed soon (in a few days).

That said, standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.

**Comment by eltomito** [comment]
@Albrecht-S  First of all, thank you and everyone else for paying attention to this issue.

After further investigation, it seems this problem only concerns one production machine at one movie theater, so it's probably something else. I first blamed Windows 10, because most production machines used to run my software at theaters are really old and this one had just been upgraded to Win 10.

I'm sorry for causing so much fuss and hope my misguided bug report will at least help make 1.4 better.

**Comment by Albrecht-S** [comment]
@eltomito Thanks for confirmation that this was not a general problem. You helped finding out that we used an unsupported Windows "feature" and this improves FLTK 1.4 IMHO. Thanks for that.
