### ISSUE TITLE
Memory Leakage in Fl_Input_.cxx & Fl_Text_Buffer.cxx

### ISSUE THREAD

**Issue by ZJUGKC** [fltk/fltk#716]
1. Fl_Input_cxx::redo()  line 1081-1082:
    If `undo_` is empty, i.e., `undo_->undocut == 0 && undo_->undoinsert == 0`, `delete undo_`  should be executed.

1. Fl_Text_Buffer::redo() line 638-645:
    `redo_action` should be deleted after calling `apply_undo()`.

1. Fl_Text_Bufer should provide two additional methods: `bool can_undo()` and `bool can_redo()` .
    `can_undo` can be implemented by `return mCanUndo && mUndo != NULL && !mUndo->empty()`, but it must be placed in `Fl_Text_Buffer.cxx` because `Fl_Text_Undo_Action` is defined in that file.
    
    `can_redo` can be implemented by combination of `mCanUndo`, `mRedoList->pop` and `mRedoList->push`. It is so complex. If `Fl_Text_Undo_Action_List` provides `size()` method, it can be implemented easily.

   If `can_undo` and `can_redo` can be implemented as inlining functions, it will achieve the better performance.

**Comment by Albrecht-S** [comment]
@ZJUGKC Thanks for the report and for the detailed analysis.

Please provide the FLTK version (appears to be 1.4) and the **exact Git commit or snapshot version**. Otherwise code references with line numbers may not be usable later. For future reports, please use one of the issue templates ("Bug report" -> "Get started") and fill in the requested information. TIA.

I assigned this to @MatthiasWM because the `undo/redo` system has recently been (re)written by him. Matthias, I hope you don't mind...

**Comment by MatthiasWM** [comment]
Both items should be fixed. Thanks for the detailed description. 

I did add can_undo() and can_redo(). They are not inline, but a good compiler may inline them automatically when statically linking.
