### ISSUE TITLE
Buggy behaviour of dropdown menus on secondary monitor under Wayland

### ISSUE THREAD

**Issue by polter-rnd** [fltk/fltk#724]
**Describe the bug**

When running `test/forms` example under Wayland on secondary monitor, when the drop down does not fit the available space above, it is not drawn until the window is dragged below.

Important: it only reproduces on secondary monitor.

**To Reproduce**
1. Run `bin/test/forms` example under Wayland (GNOME)
2. Move the window on secondary monitor
3. Position it on top of the screen
4. Open "Boxtype" menu and select the last entry
5. Try to open menu again

**Expected behavior**
It should open as usual, but in fact it does not. When I drag the window down, it eventually is drawn.
Sometimes it segfaults when moving mouse around the area where menu should be drawn.

**Video**

https://user-images.githubusercontent.com/6562863/235150625-1d2eb446-7e5e-4dcb-9599-b937bf66863e.mp4

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 52a15632a6b8457fae2a9db61fe346c40bd46f15

**FLTK Configure / Build Options**
 - `cmake -DCMAKE_BUILD_TYPE=Debug -DOPTION_WAYLAND_ONLY=ON ..`

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Fedora 37

**Linux/Unix Runtime, if applicable:**
 - Wayland / GNOME 43

**Additional context**

Segfault call stack is the same as in issue #723 

I'm attaching another core dump here as well, just in case:

[forms3-debug.zip](https://github.com/fltk/fltk/files/11353612/forms3-debug.zip)

**Comment by ManoloFLTK** [comment]
@polter-rnd The crash you report is hopefuly fixed with the commit mentionned above. Please, report here if you confirm that.

I can reproduce the problem described here. What I see is : when a popup menu window is expected to appear **and** the current window is on a secondary display **and** the normal position of the popup would make it hit the top of the display, the expected popup does not appear.
What should happen is that Wayland's constraint mechanism should position the popup somewhat lower than asked so the popup is fully on the display.
No problem  if the popup's normal position would make it hit the display bottom: the constraint mechanism does position the popup higher.
No problem if the current window is on the main display: the constraint mechanism behaves correctly to avoid having the top or the bottom parts of the popup window invisible.

For me, that's a  bug of the Wayland compositor. I'm not sure if something can be done within the FLTK library to avoid it.

**Comment by ManoloFLTK** [comment]
@polter-rnd I believe the commit mentionned above should fix the behaviour of dropdown menus on a secondary display. Please, report here what you see.

**Comment by polter-rnd** [comment]
Hi, thank you, combo box behavior in `bin/test/forms` is now perfect!

However looks like the fix introduced strange side effects on window menus, please watch till the end:

https://user-images.githubusercontent.com/6562863/235685855-a2cee6eb-1f0e-4419-a949-4a6dc842761d.mp4

**Comment by polter-rnd** [comment]
Thanks, confirming it is fixed now
