### ISSUE TITLE
Provide --without-fluid configure option

### ISSUE THREAD

**Issue by juanitotc** [fltk/fltk#725]
**I am using FLTK**
 - Version 1.4.0 weekly snapshot

Compiling fluid takes a comparatively long time and may not be needed, therefore a --without-fluid option would be useful

**Comment by Albrecht-S** [comment]
Thanks for the request. Meanwhile CMake advanced to our preferred build system and we provide option `FLTK_BUILD_FLUID:BOOL=ON|OFF` to build fluid or not so you can use this feature already if you build FLTK with CMake.

We did not yet decide whether we add such an option to configure, but this may be done in the future if someone finds the time to do it. Patches or PR's always welcome.

**Comment by juanitotc** [comment]
Ah - thanks, I hadn't realised that cmake could be used.

**Comment by ManoloFLTK** [comment]
The commit mentioned above adds option --disable-fluid to configure which makes the building of FLTK to omit fluid.
@juanitotc Please, close issue if you agree it's fixed.

**Comment by Albrecht-S** [comment]
@ManoloFLTK This new option breaks the build if tests are also built because some of the tests require fluid. IMO we have two choices:
1. remove this option from configure since we can use CMake to build w/o fluid (easy)
2. disable tests (--disable-test) if fluid is disabled with a warning that tests can't be built w/o fluid (medium)
3. make building tests select which tests can't be built and disable these tests selectively (difficult)

See [this report in fltk.coredev](https://groups.google.com/g/fltkcoredev/c/K4z16g9p57o/m/RYdRqFyvAQAJ).

**Comment by ManoloFLTK** [comment]
@Albrecht-S  The true fix was
4. move terminal to fluid-dependent section in test/Makefile

The error was introduced when the new test app, terminal, was added.
The fix is committed at 25ffce6.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Great, sorry for the confusion, I was in a hurry and didn't check all the details.
