### ISSUE TITLE
Generating 'fltk.pdf' on Windows

### ISSUE THREAD

**Issue by gvanem** [fltk/fltk#731]
With these CMake options `-DOPTION_BUILD_PDF_DOCUMENTATION=1`,
the `documentation/CMakeLists.txt` snippet:
```cmake
  add_custom_command (
    OUTPUT  ${CMAKE_CURRENT_BINARY_DIR}/fltk.pdf
    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/make_header  << ! this
            ${CMAKE_CURRENT_BINARY_DIR}/fltk-title.tex
            ${CMAKE_CURRENT_BINARY_DIR}/fltk-book.tex
    COMMAND ${DOXYGEN_EXECUTABLE} Doxybook
    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/make_pdf   << ! and this
```
caused a failure in the `MSbuild` process: `make_header is not recognized as an internal or external command`

But w/o knowing much about CMake, I patched it like this:
```diff
--- a/documentation/CMakeLists.txt 2023-01-26 10:54:43
+++ b/documentation/CMakeLists.txt 2023-06-02 13:54:41
@@ -187,11 +187,11 @@

   add_custom_command (
     OUTPUT  ${CMAKE_CURRENT_BINARY_DIR}/fltk.pdf
-    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/make_header
+    COMMAND sh ${CMAKE_CURRENT_SOURCE_DIR}/make_header
             ${CMAKE_CURRENT_BINARY_DIR}/fltk-title.tex
             ${CMAKE_CURRENT_BINARY_DIR}/fltk-book.tex
     COMMAND ${DOXYGEN_EXECUTABLE} Doxybook
-    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/make_pdf
+    COMMAND sh ${CMAKE_CURRENT_SOURCE_DIR}/make_pdf
     COMMAND cp -f latex/refman.pdf fltk.pdf
     DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/Doxybook
             ${CMAKE_CURRENT_BINARY_DIR}/fltk-title.tex
```

and the `fltk.pdf` file (26 MByte!) produced was amazing!

Not sure how this `sh ` (a Cygwin 64-bit version in my case)
should get in there properly. I would assume CMake would detect
it is a shell script and prefix the command with with `sh ` itself.
But no.

**FLTK Version**
 - Downloaded and self-built from: `git master` today.

**FLTK Configure / Build Options:**
```
 cmake -G"Visual Studio 17 2022" -DOPTION_USE_SYSTEM_LIBJPEG=0 ^
         -DOPTION_USE_SYSTEM_LIBPNG=0  ^
         -DOPTION_USE_SYSTEM_ZLIB=0  ^
         -DOPTION_BUILD_PDF_DOCUMENTATION=1 ^
         -DOPTION_INSTALL_PDF_DOCUMENTATION=1 ^
         -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
         -DCMAKE_INSTALL_PREFIX=%~dp0\gv-install ^
         -DCMAKE_CXX_FLAGS_RELEASE="-MD -O2 -Ob2" ^
         -DCMAKE_C_FLAGS_RELEASE="-MD -O2 -Ob2" ..
```
(the above inserted in a `build.bat` file and ran from an empty `build` directory).

**Operating System / Platform:** OS:  Windows-10

**Comment by Albrecht-S** [comment]
Thanks for the detailed report and the patch suggestion. I admit that this custom command is not cross platform, I believe it requires a Posix shell to work - see `COMMAND cp -f latex/refman.pdf fltk.pdf` and the called shell scripts.

> I patched it like this: ... Not sure how this sh (a Cygwin 64-bit version in my case) should get in there properly.

I'm not sure if we can make it work with a non-Posix shell like the Windows "DOS shell" anyway. You wrote that you have "a Cygwin 64-bit version" available which is very likely the reason why the custom command (when invoked with `sh`) works at all - and obviously you need `doxygen` and `latex` as well which are not standard Windows tools.

I can take a look at it but there's no guarantee that generating the docs with doxygen will ever work in a standard Windows environment without Cygwin and/or MinGW or MSYS2. I need to check if it works with MinGW and/or MSYS2 though (but I believe it works).

Let's see what I can find...

**Comment by gvanem** [comment]
> You wrote that you have "a Cygwin 64-bit version" available which is very likely the reason why the custom command 
> (when invoked with sh) works at all 

Sure I have all that. But I did the build from a non-Posix shell (hate bash).

I thought something like:
```cmake
if (WIN32)
  set(SH "sh.exe")
else()
  set(SH "")
endif()
.....
 add_custom_command (
    OUTPUT  ${CMAKE_CURRENT_BINARY_DIR}/fltk.pdf
    COMMAND ${SH} ${CMAKE_CURRENT_SOURCE_DIR}/make_header
    .... 
```

would do it. But then again, I'm a *n00b* when it comes to Cmake.

**Comment by Albrecht-S** [comment]
> Sure I have all that. But I did the build from a non-Posix shell (hate bash).

Yes, I understood. But when you run `sh` you **_very likely execute your Cygwin shell_** [1] and the custom command is executed by that (Posix) shell, presumably `bash`. The scripts run by that shell don't use Windows commands, they are using Posix shell commands. What I wanted to say is that **_in your environment_** the minimal patch you provided works because it executes your Cygwin shell and all commands within that script are run in your Cygwin environment whereas a bare Windows environment wouldn't be able to use `cp` and many of the other commands in these scripts.

That said, your patch may be fine for your environment but unfortunately not for other Windows users in general.

> I thought something like: ... [CMake code above] ... would do it. But then again, I'm a n00b when it comes to Cmake.

Your `CMake` code doesn't look bad (thanks for providing it) but it would only solve the issue if `sh` was a valid Windows command and ran a Posix shell that could execute the `make_header` script and others.

Note: I tried to build the pdf docs under MSYS2/MinGW-w64 on my Windows test system yesterday (for comparison) but this didn't work out and I ran out of time. Something was missing from the `latex` installation. I'll continue later when I have more time to investigate this issue.

----
[1] This requires that your Cygwin environment has been added to your Windows system PATH which I do not recommend, BTW, because it may obfuscate what's going on: your Windows shell inherits some commands like `cp` from your Cygwin (bash) environment etc..

**Comment by Albrecht-S** [comment]
We're not able to make PDF generation work on a bare Windows system because we need to generate some files that are used in the PDF generation process, see make_header and make_pdf scripts and maybe more.

As written above, it **_may_** work in a `Cygwin` or `MinGW` (`MSYS2`) environment where a POSIX compliable shell and all the required tools are available.

I documented this fact in commit cfa1a3bd401cea0e2cc9a5172971c28ead7dcfff and I will close this issue soon, leaving it open now for comments. Sorry.
