### ISSUE TITLE
1.3.8 Can't build because it is missing config.sub

### ISSUE THREAD

**Issue by blackbird1999** [fltk/fltk#736]
**Describe the bug**
./configure fails because config.sub is missing

**To Reproduce**
download the 1.3.8 sources and try to compile

**Expected behavior**
it compiles

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: [e.g. 1.3.8]
 - Downloaded and self-built from: https://github.com/fltk/fltk/archive/refs/heads/branch-1.3.zip

**Operating System / Platform:**
CentOS7

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by ManoloFLTK** [comment]
I've just downloaded FLTK 1.3.8 by 2 means
1) from the download page of the main FLTK web site
https://www.fltk.org/software.php
2) from its git repo (https://github.com/fltk/fltk), doing Code -> Download ZIP

In both cases, the decompressed archive contains file config.sub and FLTK builds
OK after just typing
make

@blackbird1999  I would suggest you to use one of the 2 means mentioned above to download FLTK 1.3.8. I would also recommend you to consider version 1.4 that will be released soon and that supports HighDPI displays.

**Comment by Albrecht-S** [comment]
@blackbird1999, @ManoloFLTK It is correct that the software downloaded from the [FLTK download page](https://www.fltk.org/software.php) always contains `config.sub` and `config.guess`, even for FLTK 1.3.8.

However, downloading from GitHub (branch-1.3) as @blackbird1999 wrote, does NOT contain these two files.

(@ManoloFLTK You need to select `branch-1.3` before doing `Code -> Download ZIP` to verify this for 1.3.x)

But a simple `make` would always succeed because it creates `configure` as well as `config.sub` and `config.guess`, or `make configure` or `make clean` would create all required files.

`README.Unix.txt` recommends to run `NOCONFIGURE=1 ./autogen.sh` which is another way to create all required files to run `./configure` subsequently.

This is a special FLTK "feature" and not going to be changed in FLTK 1.3.x (git). FLTK 1.3 release tarballs and FLTK 1.4 (git) contain these files anyway.

@blackbird1999 Please use one of the suggested methods to build FLTK 1.3.8 and close the issue. Thanks.

**Comment by blackbird1999** [comment]
Ah, I see. I was following the 1.4 instructions which say to use autoconf.  Sorry. Thanks for helping!
