### ISSUE TITLE
Use of uninitialized value FL_Font_Descriptor.glok[]

### ISSUE THREAD

**Issue by zberry** [fltk/fltk#778]
In the constructor for [FL_Font_Descriptor in  fl_font_xft.cxx](https://github.com/fltk/fltk/blob/3600522ae7d2244b69552458e4d82f869a36067b/src/fl_font_xft.cxx#L329) the glok array is not initialized to 0 in as it is in [fl_font_x.cxx](https://github.com/fltk/fltk/blob/3600522ae7d2244b69552458e4d82f869a36067b/src/fl_font_x.cxx#L28C6-L28C6).

Shows up as an valgrind error later on when it gets used and may cause crashes.

```
#if HAVE_GL
  listbase = 0;
#endif // HAVE_GL

```

should be 

```
#  if HAVE_GL
  listbase = 0;
  for (int u = 0; u < 64; u++) glok[u] = 0;
#  endif
```

**Comment by Albrecht-S** [comment]
Thanks for the report. Given your links to source files this appears to be for FLTK 1.3.x. This code has been changed massively in FLTK 1.4 (git branch `master`, our current development). 

@zberry Do you also see any misbehavior or are you only reporting this valgrind issue?

I verified that in FLTK 1.4 (branch `master`):
- this initialization of the `glok[]` array is done in non-xft code (similar to `fl_font_x.cxx` as you pointed out)
- the array `glok[]` is no longer used in xft related code (as it was in FLTK 1.3 in `fl_font_xft.cxx`)

This means that this potential bug has been fixed in 1.4 and will very likely not be fixed in 1.3 because it doesn't seem to be a serious bug (no crash).

However, if valgrind finds an uninitialized variable warning, then this might indicate a problem. I didn't test 1.3.x though.

@ManoloFLTK What do you think, is this worth updating `branch-1.3` ? This branch has outstanding commits anyway and will likely get another release (1.3.9) in the near future.

**Comment by Albrecht-S** [comment]
PS: @ManoloFLTK I'm not familiar with this code. If you feel that it should be fixed, please feel free to take this issue and fix it in Git. Thanks.

**Comment by ManoloFLTK** [comment]
@zberry Thanks for this message. In fact, the array `glok` is not used by the code when FLTK uses Xft. That's visible as follows:

The only statement in FLTK where the vaiue of array `glok` is used is line 210 of file `src/gl_draw.cxx`
   ` if (!gl_fontsize->glok[r]) get_list(r);`
This statement is bracketted by
```
#if !( defined(USE_X11) || USE_XFT )
#endif
```
Therefore it's not used when Xft is active. That's the reason why the array is not initialized in file `fl_font_xft.cxx` .
Please, close issue if you agree.
