### ISSUE TITLE
fluid properties -> GUI -> Position: interactive sliding of values disabled, can only be typed

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#783]
**Describe the bug**
In fluid's properties for widgets, the Position values used to be able to be interactively adjusted by dragging inside the input field, and the numbers would increase/decrease like a slider. This made it easy to adjust a single value when interactively dragging the red outlines were impractical.

It seems like this feature has been lost somehow or dropped; it seems the position values can now only be typed.

**To Reproduce**

1. Open fluid
2. Create a **New>Code>Function/method** and a **New>Group>Window**
3. Hit F1 to open the window properties, and under the GUI tab click inside the Position input field (e.g. Width) and drag left or right.

In the new 1.4.0 current, the value doesn't change.
In the old fluid versions this interactively adjusted the values like a slider.

Of interest, the **Size Range**: values seem to still work for interactive sliding of values.

**Operating System / Platform:**
FLTK 1.4.0 current, cmake default build on Linux with X windows.

**Comment by MatthiasWM** [comment]
Yes, I did change that because the slider functionality was not obvious and uncommon for numeric inputs, plus I find it redundant because the red outlines are there, and they can be moved using arrow keys as well. Instead, the field now understand simple math and formulas, which - granted - is also not visible, but I found incredibly useful (and really needs to be documented).

For example, you want to move the widget five pixels to the right? Click on the value and append "+5<enter>". This even works when selecting multiple widgets. There are even a few variables available: want to move a widget 10 pixels in from the parent? Just enter "px+10" and "py+10" in the x and y fields. You can even stack multiple widgets vertically. In y:, enter the formula "py+10+i*25". Tadaaa.

At least there are tooltips for those four buttons.

As an idea, I could offer a tiny vertical roller just to the right of text filed? Would that make sense?

**Comment by MatthiasWM** [comment]
I really need to write the docs before I forget all the changes I made myself. And make videos.

**Comment by Albrecht-S** [comment]
> I really need to write the docs before I forget all the changes I made myself

@MatthiasWM I didn't "dare" asking you about that. The entire chapter "Programming with FLUID" would need a rework and new images (screenshots). And who could do this better than you? ;-)

**Comment by MatthiasWM** [comment]
You "should" ask because things get more and more outdated, except for the screenshots, which I updated on July 14, f8ebde4da4 .

**Comment by erco77** [comment]
I could see a popup slider from a button or some such. Or a roller might work too.. just some way to slide back and forth to change the value, as the red widget lines sometimes cannot be resized (offscreen, too close to another widget or screen edge, can't be picked without picking something else, etc)

**Comment by MatthiasWM** [comment]
I have committed a compromise in 58b13b868e9be35e2b516a72a736b8c61178467a that is hopefully good enough.

To be able to mix the behavior of the Fl_Value_Input and text input (namely being able to mark text by dragging the mouse and still be able to easily change the value) I added mousewheel support to the FLUID coordinate widget. Just scroll up and down, and you can easily and precisely position a widget.
