### ISSUE TITLE
fl_check_images has an overly restrictive JPEG header filter

### ISSUE THREAD

**Issue by fire-eggs** [fltk/fltk#81]
I believe that `fl_check_images` is overly restrictive when attempting to identify JPEG files from the header.

Namely, this section of code from `fl_images_core.cxx\fl_check_images`:
```
  if (memcmp(header, "\377\330\377", 3) == 0 &&
					// Start-of-Image
      header[3] >= 0xc0 && header[3] <= 0xef)
	   				// APPn for JPEG file
    return new Fl_JPEG_Image(name);
```

For example, the image in the attached zip file (safe-for-work; downloaded from Imgur) is a legit JPEG file, can be viewed by any viewer, yet fails the `fl_check_images` test because the fourth byte of the header is 'FE'. 
[GiY7GzK.zip](https://github.com/fltk/fltk/files/4646434/GiY7GzK.zip)

As far as I can tell from Google search and by looking at image viewer code (such as [`flpicsee`](https://sites.google.com/site/lockmoorecoding/downloads/flpicsee)), the correct identification for a JPEG file is that the first two bytes of the file are "FFD8".

To wit:
```
  if (memcmp(header, "\377\330", 2) == 0) // Start-of-Image
    return new Fl_JPEG_Image(name);
```

Kevin

**Comment by fire-eggs** [comment]
Update. [fileformats.archiveteam.org/wiki/JPEG](http://fileformats.archiveteam.org/wiki/JPEG) states under "Identification", that:
`JPEG files begin with bytes ff d8 ff.`

**Comment by erco77** [comment]
I can confirm (by way of sampling a lot of jpegs on my system) that the first 3 bytes are always `ff d8 ff` and the 4th byte seems to vary, `e0, e1, e2, db, fe`.
The docs on this page: https://www.fileformat.info/format/jpeg/egff.htm seem to indicate the 4th byte is always e0, but that doesn't appear to be the case. So I /think/ I'd be +1 for just checking only those first 3 bytes.

**Comment by Albrecht-S** [comment]
According to [ITU Recommendation T.81](https://www.w3.org/Graphics/JPEG/itu-t81.pdf), page 36, `0xff 0xfe` is a _**comment marker**_. All markers consist of one byte `0xff` followed by one byte which is **not** `0xff`. Table B.1 (p 36) in this document states that marker codes start with `X’FFC0’` and extend up to `X’FFFE’`. Marker codes `X’FF01’ through X’FFBF’` are either for "temporary private use in arithmetic coding" or reserved, which seems to indicate that these codes should not appear in bytes 3 and 4 (counting from 1) in the file.

Hence I think it would be safe and conservative to extend the detection code above to check
```
header[3] >= 0xc0 && header[3] <= 0xfe
```
instead of just
```
header[3] >= 0xc0 && header[3] <= 0xef
```
This would include the image found by the OP and all images found by Greg.

Checking only the first three bytes would be possible, but I think it would be safer to check the fourth byte as well as given above.

**Comment by Albrecht-S** [comment]
Please test and confirm that commit 91b7857 fixes the issue.

**Comment by Albrecht-S** [comment]
Fixed in 1.3 (branch-1.3) as well (d4d2136b3b28196974fa96091bebf181c3afaa63)

**Comment by fire-eggs** [comment]
Confirmed!

**Comment by Albrecht-S** [comment]
Thanks for confirmation.
