### ISSUE TITLE
fluid 1.4.x: flex move/resize issues

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#810]
**Describe the bug**
_Making this a separate issue from #809, as that's apparently a refresh issue according to matt, but this is not._

**To Reproduce**
1) In fluid a) create a window, b) create a VERTICAL oriented Flex, c) create three default buttons inside it the flex, which should all be stacked vertically
2) Select the flex widget by clicking on it in the fluid tree
3) PROBLEM # 1: Using the red resizer dots, try to shrink the flex widget on any dimension; for me this change is /ignored/, which is unexpected. (You can only enlarge the widget)
4) PROBLEM # 2: With the flex still selected, try clicking in the center to drag the widget around to change just its position. This does move the widget in the direction you move it, but also enlarges the widget, which is unexpected.
5) Similar issues occur if you try to jog the widget around with the up/down/left/right arrow keys.

The workaround for all of this is to type numbers into the properties for width and height.

There's some other issues I've seen too, where moving the widget around causes the children to move off to weird places, and changes their sizes in strange ways. Will follow up when I've figured out a replication for that. Might have to do with gap settings for the flex and/or Size/Fixed properties on the children.. not sure yet.

**Comment by MatthiasWM** [comment]
I tested this with https://github.com/fltk/fltk/commit/4b5985eb49e057aa69b8ba4e91d0ad11e1cc87ff and it seems to work well now. Don't know if there was an issue before the fix. 

As for problem 1, I don't see this (anymore). The Flex widget can be arbitrarily resized and the children will follow. However, if you select a *child* of Flex and resize it, the Flex shows the behavior that you describe. This is because children of Flex are managed by the Flex itself, and if you move or resize them, they obey, but then FLUID enlarges Flex to make all children fit, and then finally Flex rearranges the child that you just moved, making it seem like it never moved.

Problem 2 is pretty much the same. If you select the Flex, everything works here as expected. If you select a child of Flex, things may be a bit unexpected. I have one special case: if you select an inner edge of a child of a Flex, the child is changed into the "fixed" state and keeps the size that the user selected, even if the Flex is later resized or more children are added.

The problem is that self-arranging groups don't like it if the user tries to arrange the children.

**Comment by MatthiasWM** [comment]
In 8bd1bd71622df37f097b04746a98389ddb890558 I added a bit more special handling for Flex and Grid. Children that are groups should now rearrange correctly. In Grid, users can drag children into a new cell. I still have to do that for Flex. Many little bugs fixes and some new ones created.

**Comment by erco77** [comment]
Cool, thanks for checking into this; I’ll be doing more gui work tomorrow with fluid, so I’ll pull your latest and use it.

 Just so you know, my reproduce instructions were only about moving resizing the flex widget, not the children; I assume the children are under full control of flex, like a pack.

(It’s only when the children shot off to another part of the UI during movement of the flex, and I try to herd them back “inside” it, then things got nutty/unpredictable)

**Comment by MatthiasWM** [comment]
Yes, I used you report to fix a bunch of issues, some unrelated ;-)

Fluid does not have a way to move widgets *out* of a group (besides cut/paste), so what you are seeing *looks* like you moved the children out, but they are actually still children of the Flex, just not within the borders of the widget, which is unintuitive and generally undefined.

For Groups, Fluid simply enlarges the parent group, so the children remain within the bounds. For Flex, that makes not so much sense. And yes, it's very similar to what Pack does (which, IIRC, is also not very well supported by Fluid).

**Comment by erco77** [comment]
I'm on fb6c38b1 right now, and can confirm the problems I reported are fixed!
