### ISSUE TITLE
fltk 1.4.x + wayland or x11: underbars disappear in input fields and text editors

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#819]
**Describe the bug**
Underbars seem to appear and disappear randomly during editing of text based widgets.
Noticed this while using fluid's code editor, but I see it in single line input fields (Fl_Input?) as well.

**To Reproduce**
1. Open fluid, create a New -> Function and New -> Code
2. Open the code editor for the new "Code"
3. Replace any existing text with just: hello_world
4. NOTE: The underbar does not show up, e.g.
![fluid-no-underbar](https://github.com/fltk/fltk/assets/6484779/3c2d9f88-80f7-4c26-8764-1afb74c5701f)

In the below pair of screenshots, at times I noticed when the code editor opens on existing code containing underbars, most of them show up OK (BEFORE), but they /all disappear/ as soon as I start typing new text (AFTER). e.g.
![fluid-vanish-on-type](https://github.com/fltk/fltk/assets/6484779/2deb51bd-3f7a-455e-9481-b22039625cd0)

No scaling BTW, single monitor system running at 1920 res.

**Comment by erco77** [comment]
I should add I can replicate this even with FLTK_BACKEND=x11, so this might not be wayland specific.
I'll try testing on one of my other non-wayland machines and follow up.

**Comment by erco77** [comment]
Can't seem to replicate on my older Ubuntu 20.04.6 with X11.
So problem seems specific to a system using wayland, but can appear regardless of using the x11 backend stuff.

**Comment by ManoloFLTK** [comment]
> I should add I can replicate this even with FLTK_BACKEND=x11, so this might not be wayland specific.

This means the issue is in Cairo. All graphics are done by Cairo both under wayland and under FLTK_BACKEND=x11. In contrast, when building with --disable-wayland, graphics are done by Xlib.

This issue is present with Ubuntu 22.04 (gnome version 42.9) but disappears with Ubuntu 23.10 (gnome 45.0) and Debian testing (gnome 44.5).

Also, while it occurs with the tiny font fluid uses in that window, the slightly bigger font test/editor uses shows no issue. The issue also disappears with HighDPI displays and with scaling at 110% and above for LowDPI displays.

I would propose to consider this issue to be a Cairo bug known to be corrected in recent Cairo versions.

**Comment by erco77** [comment]
OK, cool -- closing this then.

**Comment by MatthiasWM** [comment]
It looks like the font is too tall for the requested height(), so the underscores are overwritten by clearing the line below. If the line below is not cleared for whatever reason, the underscores remain visible.

It would be good to choose a smaller font on the driver side. FLTK generally has this layout problem because font heights are also used as the distance between lines, which is not always a good choice. Maybe when forwarding the user request for font height to the driver, a factor of 0.8, or a reduction by a pixel, or both will fix this. It's easier than generally introducing line spacing.

**Comment by MatthiasWM** [comment]
Never mind then ;-)

**Comment by erco77** [comment]
@MatthiasWM your sugg might be a good workaround if one is needed. Wayland is still very new, so I guess there's gonna be bumps. Sounds like the workaround here is to run X11 apps instead on Ubuntu 22. Or perhaps an ubuntu 22 update will fix this with a cairo update.
