### ISSUE TITLE
fltk 1.4.x: svg markers are not handled in `Fl_SVG_Image`

### ISSUE THREAD

**Issue by OlivierSohn** [fltk/fltk#822]
**Describe the bug**

`Fl_SVG_Image` doesn't handle svg markers.

**To Reproduce**

Load the following svg in a `Fl_SVG_Image` (The marker for the arrow head is `marker id="arrow"` on the 3rd line):

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 200 200" width="200" height="200">
  <defs>
    <marker id="arrow" viewBox="0 -5 10 10" refX="5" refY="0" markerWidth="10" markerHeight="10" orient="auto">
      <path d="M0,-5L10,0L0,5" fill="#666666"></path>
    </marker>
  </defs>
  <line x1="20" y1="100" x2="100" y2="100" stroke-width="2" marker-end="url(#arrow)" stroke="#666666"></line>
</svg>
```

[nanosvg does not handle the `marker` element in `defs`](https://github.com/memononen/nanosvg/blob/cb0ae54e6b147ccdf85401ef3ef20f2c761252c0/src/nanosvg.h#L2756) which explains why we see this.

Let me know if the svg above is enough for you to repro, if not I'll create a single self-contained source file to repro.

**Expected behavior**

The markers should be taken into account.

**Screenshots**

svg rendered in a browser, where arrow head is visible:

![image](https://github.com/fltk/fltk/assets/8191319/264c7862-887c-4b79-8e94-8cd311fd5028)

same svg rendered in fltk where arrow head is missing:

![image](https://github.com/fltk/fltk/assets/8191319/e1b96fd3-9de8-4d94-92f1-7a03f600bb86)

**FLTK Version**
 - Version: fltk-1.4.x-20231103-c22a7bb6
 - Downloaded and self-built from: tarball/zip

**FLTK Configure / Build Options**
```
cmake -B bin -DOPTION_USE_SVG=ON -DOPTION_BUILD_SHARED_LIBS=ON -S .
cmake --build bin
```

**Operating System / Platform:**
 - OS: Windows 
 - OS Version: 10.0.19045 Build 19045

**Comment by Albrecht-S** [comment]
@OlivierSohn Thank you for the report, the example SVG image and the detailed analysis with the pointer to the nanosvg code.

Our intention to use nanosvg was to provide basic SVG support for drawing button backgrounds and similar things. We chose nanosvg because it is a small header-only library that we could easily bundle with our FLTK library.

You can use small SVG images for GUI elements (as long as nanosvg supports the details) but FLTK's SVG support is not intended to be used as a full SVG image viewer.

There are other notable features of SVG that are not supported in nanosvg (for instance `'text'`) but unless someone provides an upstream patch (in nanosvg) we can't support SVG markers and text elements in FLTK. Sorry.

**Comment by OlivierSohn** [comment]
I understand thanks for the explanation @Albrecht-S.

**Comment by Albrecht-S** [comment]
Thanks for your feedback. I'm closing this issue now.
