### ISSUE TITLE
small fluid dialog layout nit

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#826]
**Describe the bug**
When you are editing a fluid "Code" window and make an error, a dialog is posted:

1. The dialog buttons overlap the info icon
2. The "Cancel Dialog" button would be clearer I think if it just said "Cancel"
3. I'd think there would only be 2 choices here: Continue Editing or Ignore. Not sure how Cancel would be different than Continue Editing?
4. Continue Editing should probably be the default (I've never seen fluid be "wrong" about the errors it detects, lol)

![image](https://github.com/fltk/fltk/assets/6484779/99652d9e-d5d1-4483-9c12-0adae0fc3d5d)

**Comment by MatthiasWM** [comment]
1. yes, that is a bug
2. tl;dr: I will remove that button.

2., 3., and 4. yes, well, the dialog pops up when the user presses OK on the code dialog. So the users intention is to get rid of the code dialog in some way. If an error is detected, in the most likely scenario, the user will fix the bug. Second most likely, it's intentional, so "Ignore Error" will also close the code dialog. 

The idea of "Cancel Dialog" was the scenario where a user opens a Code dialog, edits around, changes his mind, gets the error, and then decides to dismiss the entire thing (close the error popup *and* the code editor. But I guess this reflects more my way of thinking than any actual use case. I will remove that button.

**Comment by MatthiasWM** [comment]
Item 1 should be fixed in 90d77372540d6747921f3d1b6c2e0eed465f4069

**Comment by MatthiasWM** [comment]
Item 2-4 fixed in aa2d058f101b4cd226afad397f9b27a8d0d7416a

**Comment by erco77** [comment]
Cool - thanks!
