### ISSUE TITLE
Cannot get fltk to work.

### ISSUE THREAD

**Issue by Dogeislove** [fltk/fltk#83]
i keep getting an error that is "unresolved eternal symbol. How do i fix this?

**Comment by fire-eggs** [comment]
You need to let us know what the unresolved symbol is. You also need to let us know if you are building under Linux or Windows.

Assuming the unresolved symbol starts with `Fl_`, this message occurs because you have failed to link against the necessary fltk libraries.

You might review the [FLTK Basics](https://www.fltk.org/doc-1.3/basics.html), specifically the section labelled `Compiling Programs with Standard Compilers`. E.g. under Linux you need to build your program like:
```
gcc your_program.c -L/usr/local/lib -lfltk -lXext -lX11 -lm
```

**Comment by erco77** [comment]
This isn't the right place for questions about how to solve build errors, this is for tracking specific bugs.
Please ask on fltk.general, so that others can see the problem/solutions.
Also include the operating system (mac,linux,windows,embedded hardware), build environment (Visual Studio, gcc, clang, mingw), version of FLTK you're trying to build/use, and in the case of errors, paste actual errors from the compiler/linker or if the error is when executing the program, errors/dialogs you're seeing (e.g. DLL errors)

**Comment by Dogeislove** [comment]
> us

im using wiindows

**Comment by Dogeislove** [comment]
i'm using windows

**Comment by Albrecht-S** [comment]
Sorry, this is the wrong place to ask user questions. Please ask your question in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Thanks.

Please provide the platform (Windows, Linux, macOS), the build system, compiler, and the error messages in text form (copy and paste preferred). TIA.
