### ISSUE TITLE
color values for Fl::arg()s need to be documented

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#842]
**Describe the bug**
The [Fl::arg()](https://www.fltk.org/doc-1.4/classFl.html#a1576b8c9ca3e900daaa5c36ca0e7ae48) command line flags that expect colors, such as `-bg <color>` and `-fg <color>`,  need to document the syntax for `<color>`.

I went down the docs rabbit hole looking for descriptions/examples, starting at Fl_Window::show(), e.g.

[Fl_Window::show(argc,argv)](https://www.fltk.org/doc-1.4/classFl__Window.html#a0d75dfcdc8fb797f9247482da1e0152b) -> [Fl::arg()](https://www.fltk.org/doc-1.4/classFl.html#a1576b8c9ca3e900daaa5c36ca0e7ae48) -> [Fl::background()](https://www.fltk.org/doc-1.4/classFl.html#a422da0dfc6aa51721e7c9a6ccf5b90ef)

..but nothing seemed definitive on the syntax of the `<color>` value.

Apparently `<color>` can be words like `green` and `black`, and after some experiments I found that values like `#f80` can work (for orange), but fltk's 32 bit values don't seem to be allowed (like `#ff800000`).

From what I can tell, on X11 `XParseColor()` is used to parse the colors, which would seem to make color values platform specific, but I'm not sure.

I'd expect color specifications would be cross-platform, the way `Fl_Color` is. For instance FLTK's own 32bit hex values, like `#ff800000`.. but this doesn't seem supported (I get the error `Unknown color: #ff880000` when `-bg #ff880000` is used)

Anyway, it would be good if color values were documented. I'd write it myself, but I don't understand how it's really supposed to work.

**Comment by MatthiasWM** [comment]
I activated the `#xxx` color interpretation for macOS as well, so it's the same on all platforms now. Your description is correct, but there are a few unexpected side effects:

- the order of fg, bg, and bg2 in the command line does not matter
- you can't set the selection color
- setting the bg2 color also changes the fg color to have sufficient contrast
- explicitly setting fg color overrides the bg2/contrast constraint
- setting the bg color will update the color lookup table for the gray ramp, so color indexes can stay the same for all apps, it's just mapped to different RGB values
- the calculation of the gray ramp is *only* based on the bg color, so there is no way to create an inverted (dark mode) ramp
- setting bg to black creates a an all-black ramp, setting a somewhat dark bg color creates a extremely dark ramp (exponential)
- setting the bg has no influence on bg2 or fg

So unless the user gives slight offsets in shade (make the background pastel instead of light gray), this is of limited use. There seems to be no good way of simulating dark mode. I assume we don't change any of this for 1.4.0, but we should consider allowing dark mode options and a customizable selection color.

**Comment by Albrecht-S** [comment]
> we should consider allowing dark mode options and a customizable selection color.

1. see Mike's branch `darkmode` and my mods in my own branch https://github.com/Albrecht-S/fltk/tree/darkmode which has some very, very experimental code.
2. customizable selection color would be good as well.

> I assume we don't change any of this for 1.4.0

I agree.

PS: I deassigned myself, please feel free to take over (for documentation etc.).

**Comment by erco77** [comment]
- I'd suggest even just the bare minimum documentation, e.g. for color names we support, and hex variations. Defer the detailed stuff until later when we can figure it out/nail it down.
- Should we (eventually) allow full 32bit FLTK color values (Fl_Color), e.g. `#rrggbbcc`?
  _I'm confused as to why that appears to not be supported currently. Seems like an easy thing, since it could go directly into Fl_Color values._

**Comment by Albrecht-S** [comment]
> [full FLTK Fl_Color values] I'm confused as to why that appears to not be supported currently.

@erco77 Off the top of my head: Parsing the color values was implemented (and documented in comments) to copy what XParseColor() would do. Adding the fourth component (which would be the FLTK color index) would make things even more complicated and it was perhaps not needed.
