### ISSUE TITLE
GTK error with Fl_Window

### ISSUE THREAD

**Issue by chad-cao** [fltk/fltk#848]
Dear all，
Now I am using FLTK with embed linux4.15 system on rk3568.
Now my fltk test program can works, but it does not normal. 
For the window, the icons of min, max and close are disappear. And when I move my cursor on the title bar, it will continually report the following errors:

(<unknown>:985): Gtk-CRITICAL **: 14:19:48.421: gtk_icon_info_load_symbolic_for_context: assertion 'icon_info != NULL' failed
(<unknown>:985): Gdk-CRITICAL **: 14:19:48.428: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(<unknown>:985): Gtk-CRITICAL **: 14:19:48.442: gtk_css_style_render_icon_surface: assertion 'surface != NULL' failed
(<unknown>:985): GLib-GObject-CRITICAL **: 14:19:48.454: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

I followed the problem, it should be because the theme is missing. And I'm not sure how to fix it now.
But if the icon is important, I think the window should create failed. If it is not important, it should not report it continually.
What do you think?
Thanks
Chad

**Comment by Albrecht-S** [comment]
@chad-cao Please tell us more about your system, is it (and are you) using Wayland? Since we don't know what "embed linux4.15 system on rk3568" is we can probably not help much.

We also need to know your configure/make or CMake commandline so we can help better.

What happens if you run your programs with environmentvariable "FLTK_BACKEND=x11", either by prepending it to your command or by setting it in your environment? Example:
```
$ FLTK_BACKEND=x11 bin/test/hello
```

Guessing: if you're using Wayland then this issue might be caused by the GTK plugin of libdecor (these are internals you don't really need to know more about). You can use another libdecor plugin - at least for testing - if you disable the GTK plugin with the CMake commandline option `-D OPTION_ALLOW_GTK_PLUGIN=OFF`. This will give your windows a black title bar but it might work w/o these warnings.

**Comment by chad-cao** [comment]
@Albrecht-S Thanks，your guessing is right. Now I can use clear_border to avoid the problem. And my program also do not need the border. I will remember the option you offered when I need in the future.
Thanks again.
Chad

**Comment by Albrecht-S** [comment]
@chad-cao Welcome, thanks for feedback, it's good to know that I could help.

However, your question was more like a user question which **should** be posted in fltk.general rather than here. I know from earlier correspondence that you may be able to access our Google groups, and if you can, please ask questions there. If you can't, please drop a note here, and we'll make an exception and try to answer your questions here. But please note as well that there are more regular users in fltk.general so you might get quicker answers. See also below:

Standard reply follows:

> This is the wrong place to ask questions about building or running programs with FLTK (user support). FLTK "issues" are reserved for bug reports and requests for enhancements, for further information please visit https://www.fltk.org/bugs.php.
>
>Please ask user questions in our user group [fltk.general](https://groups.google.com/forum/#!forum/fltkgeneral). Your question will have a wider audience and you will likely get more and quicker replies.
>
> Please include the system/platform (Windows, Linux, macOS), the build system (Visual Studio, CMake, Ninja), compiler (gcc, clang), compiler version, and build error messages in text form (copy and paste preferred). TIA.
