### ISSUE TITLE
Unnecessary commit to master by Visual Studio

### ISSUE THREAD

**Issue by MatthiasWM** [fltk/fltk#852]
https://github.com/fltk/fltk/commit/06e2bd7f0e295a34c28ddbb4fa7a03644540bb5c

I am speechless. VisualStudio screwed me over majorly again.Sorry about the noise once again.

**Comment by MatthiasWM** [comment]
@Albrecht-S hmm, so these are old changes reapplied?! I assume that VisualC did not do a rebase, so it recommitted my previous pull operation? As annoying as this is, does that need to be (can this be) fixed? The commit preview was fine, and in the logo the correct one was pushed first just fine. I have no idea why VisualC decided to push a second set. Sorry!

**Comment by MatthiasWM** [comment]
Ok, so I did a diff, and everything seems fine. Again, sorry about the noise.

**Comment by Albrecht-S** [comment]
@MatthiasWM I noticed the mess but it is as it is now. We can't "fix" anything that has been pushed to our fltk/fltk repo because it has been published. Although technically we **could** do it but it's not worth the effort and the trouble. Anybody who pulled already would get into trouble, including our GitLab mirror which pulls every hour or so. (Been there, had to fix that.)

What happened is that Git (i.e. Visual Studio) pulled from our Git repo and "merged" the upstream master branch into (onto) your local master branch. Finally your push uploaded **your version** to the server which makes it "look" as if everything had be committed again. I assume (but didn't check) that new Git hashes have been assigned to every commit.

**Conclusion:** we see that tools like Xcode and Visual Studio do _"whatever **they** think you want to do"_, but that is obviously not correct. My suggestion: don't use these tools for committing and pushing upstream - unless you know exactly what they are going to do. If you committed to your local `master` branch it's always good to run `git pull --rebase` from the commandline before you try to push anything. This should rebase your local `master` correctly on `origin/master`.

**Comment by MatthiasWM** [comment]
@Albrecht-S @ManoloFLTK thanks for your answers. I know, I know. IDEs can do evil things. At least for the Xcode side, Apple has improved their git support tremendously, and it now finally became really helpful. This particular commit was from Microsoft VisualStudio which loves to do unexpected things, especially in the still very experimental ARM64 version. But then again, using the command line under Windows is not so thrilling either. 

Anyway, I installed TortoiseGIT now and I hope this will fix things in the future. Alos, for larger patches, I will use pull requests again.
