### ISSUE TITLE
Redraw issues (with non_modal window) on Linux and bad Performance of Text_Display with wrap_mode (WRAP_AT_BOUNDS)

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#861]
Two bugs in one file.  I apologize for that.

1) A non modal window with an Fl_Tile, one Fl_Text_Display and one Fl_Text_Editor create redraw issues when resizing with custom code.  Maybe my code is bad.  I borrowed it from Ian MacArthur's code.
2) Fl_Text_Display and Fl_Text_Editor exhibit terrible performance with long texts with wrap_mode(WRAP_AT_BOUNDS).  It seems they consider ALL the text instead of just the visible text.

**To Reproduce**
[python_editor.zip](https://github.com/fltk/fltk/files/13588469/python_editor.zip)

1. See the README.md included in the .zip.

**Expected behavior**
1. Resizing should not cause redraw issues.
2. Wrap at bounds should consider only the visible lines to wrap them.

**Screenshots**
N/A

**FLTK Version**
1.4

**FLTK Configure / Build Options**
Default.

**Operating System / Platform:**
Maily Linux.

**Linux/Unix Runtime, if applicable:**
 - X11
 - did not test Wayland.

**Comment by MatthiasWM** [comment]
> 2. Fl_Text_Display and Fl_Text_Editor exhibit terrible performance with long texts with wrap_mode(WRAP_AT_BOUNDS).  It seems they consider ALL the text instead of just the visible text.

I answer 2 first, because it is easy to answer. Yes, your analysis is exactly right. It is a known issue, and I have been working on it. I'll give it the status "It's complicated". There are two workarounds. One is not to use wrap mode at all and manually line-break at some column. The other is to use the wrap mode WRAP_AT_COLUMN and if needed, update the column number when `Fl_Text_Editor::resize()` is called. This works especially well when using fixed fonts of the same size.

See #596.

> 1. A non modal window with an Fl_Tile, one Fl_Text_Display and one Fl_Text_Editor create redraw issues when resizing with custom code.  Maybe my code is bad.  I borrowed it from Ian MacArthur's code.

Fl_Tile relies that all children are precise to the pixel filling the tile and touching another. There must be no unused pixels inside a tile, and there must be no overlaps inside a tile:

I assume `Fl_Box  box` is meant to restrict resizing of the children of the tile? It must be invisible and the resizable to work. Otherwise it messes with the rest of the children. So we add 
```
  box.clear_visible();
  tile.resizable(box);
```

Next, the top above the tile moves around. This is easy to fix be calling 
`win.resizable(tile);`.

We need to adjust the top position of *output* to touch the top of the tile: 
`Fl_Text_Display output(tile.x(), tile.y(), tile.w(), tile.h() / 2);`

The *editor* must then fit just below the *output*:
`Fl_Text_Editor editor(tile.x(), tile.y()+output.h(), tile.w(), tile.h()-output.h());`

All the artifacts are no gone on my machine. Does that work for you, too?

**Comment by ggarra13** [comment]
Thanks for catching the Fl_Tile issues.  However my problem was not with Fl_Tile's themselves but with the window.
Here's the screencast on my Ubuntu 22.04.3 LTS box redraw issues when I resize the window (I made the Fl_Tile a tad smaller to make it easier to resize the window)

[Screencast from 06-12-23 18:22:21.webm](https://github.com/fltk/fltk/assets/6072843/1d7a87fc-62f8-41af-a785-55c80fd29274)

**Comment by MatthiasWM** [comment]
PS: since you do your won window resizing, you can reduce the artifacts by only calling `resize()` after the `PanelWindow::draw()` function, triggered by the previous resize, was called. You could add a flag, `consolidate_resize`, that you can set whenever your handle(FL_DRAG) methods calls resize(). Clear the flag in `PanelWindow::draw()`. Then make sure that handle(FL_DRAG) calls no more resize() until the flag is clear again. Call your final resize from handle(FL_RELEASE).

**Comment by ggarra13** [comment]
Ok.  I follow your explanation.  However, if I set the window to NOT be borderless (ie. not clear_border()) the redraw issues do not happen.

**Comment by ggarra13** [comment]
Ok.  I follow your explanation.  However, if I set the window to NOT be borderless (ie. not clear_border()) the redraw issues do not happen or at least happen less severely.

**Comment by MatthiasWM** [comment]
If the window has a border, the window manager will take over the entire resizing process. Not sure what else to say.

**Comment by ggarra13** [comment]
Oh, well.  I can live with the minor redraw issues.  I was just trying to be thorough as I plan to release v1.0.0 of my program January 1st, 2024.
