### ISSUE TITLE
Commit 0beab85 breaks rescaling of tile test program on X11, Wayland and macOS

### ISSUE THREAD

**Issue by ManoloFLTK** [fltk/fltk#863]
**Describe the bug**
Commit 0beab85 breaks the correct rescaling by ctrl+/ctrl- of the test program tile.

**To Reproduce**
Go to commit 0beab85 with
`git reset --hard 0beab85`
build and run `test/tile` under X11, Wayland, or macOS
Type ctrl-+ (cmd-+ under macOS)
the grey "child window" is broken.

Go to commit  b6be421 (the one just before): the same tests run OK.

Both commits are dated 23 nov '23.

**Expected behavior**
The "child window" redraws correctly

**Screenshots**
Incorrectly drawn child window after cmd-+ under macOS
<img width="496" alt="image" src="https://github.com/fltk/fltk/assets/41016272/46b5908b-70f5-4cb9-81a5-1e0405bd55a6">

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from:  Git
 - If from Git, branch:  master
 - If from Git, commit: 0beab85 is 1st bad and b6be421 is last good

**Operating System / Platform:**

 - OS:  Linux or macOS (Windows was not tested)

**Linux/Unix Runtime, if applicable:**
 - Wayland
 - X11
 Both show the bug

**Comment by MatthiasWM** [comment]
Ouch! Thanks for finding this.

**Comment by ManoloFLTK** [comment]
Thinking about this issue: apparently, the subwindow doesn't get resized: it just redraws at its previous size. That may be because rescaling with ctrl-+ creates a situation where the window size doesn't change when examined in FLTK units, although it does change if examined in drawing units.

**Comment by MatthiasWM** [comment]
Yes, that seems to be it. As soon as you touch the dividers, it jumps back to the correct size. Rhetorical dangers of minimizing redraws.

**Comment by ManoloFLTK** [comment]
@MatthiasWM Please, post here if you don't intend to take care of this issue. At this point, I assume you do intend.

**Comment by Albrecht-S** [comment]
@ManoloFLTK I believe I understand why Matt used `Fl_Widget::resize()` rather than `Fl_Group::resize()` in his commit: because `Fl_Tile` doesn't use the `resizable()` in the same way as `Fl_Group::resize()` would do. Thus, Fl_Group::resize() might have unwanted effects.

@MatthiasWM If `Fl_Group::resize()` is needed to produce correct results with subwindows (as Manolo said; I didn't check the details, I just tested it quickly), then it could be useful to call `init_sizes()` **before** calling `Fl_Group::resize()` as I did in the following patch which **_seems_** to work. But it's just an educated guess...
```
diff --git a/src/Fl_Tile.cxx b/src/Fl_Tile.cxx
index c37f2da89..db447de3c 100644
--- a/src/Fl_Tile.cxx
+++ b/src/Fl_Tile.cxx
@@ -573,8 +573,8 @@ void Fl_Tile::resize(int X,int Y,int W,int H) {
     }
     int tr = x() + w(), tb = y() + h();
     move_intersection(tr, tb, tr-dw, tb-dh);
-    Fl_Widget::resize(X,Y,W,H);
     init_sizes();
+    Fl_Group::resize(X,Y,W,H);
     return;
   }
 
```
I could also imagine to call `Fl_Widget::resize(),` then `init_sizes(),` and then `Fl_Group::resize()` which should ensure that `Fl_Group` doesn't mess with the children in unintended ways. Again, only guessing.

**Comment by MatthiasWM** [comment]
Sorry, I was busy IRL. Yes, the resize is ignored by my code because the size difference is 0. Using `Fl_Window::is_a_rescale()` to differentiate calls, or @Albrecht-S 's solution fix the initial bug. I will verify the best way and post the fix.

Unfortunately this revealed another bug. If scaling below 100%, calling resize() on the subwindow will not necessarily return the same coordinates, and Fl_Tile no longer works as expected. I assume that there is some rounding error due to the scale.

**Comment by ManoloFLTK** [comment]
I believe scaling below 100% was not considered to be useful and not checked in detail, so there can be several places where rounding can produce border effects. At this stage, FLTK properly supports scaling above 100%, while scaling below that is "undefined".

**Comment by MatthiasWM** [comment]
Thanks for the note on scaling less than 100%. Yes, it will break Fl_Window coordinates inside Fl_Tile, but it did that before my changes too, so there is no regression. And if behavior is undefined anyway, I will keep it at that for now. Would be nice to fix later in a general way.
