### ISSUE TITLE
Fl_Plugin_Manager::loadAll doesn't work correct

### ISSUE THREAD

**Issue by tanxn5** [fltk/fltk#876]
```
int Fl_Plugin_Manager::loadAll(const char *filepath, const char *pattern) {
  struct dirent **dir;
  int i, n = fl_filename_list(filepath, &dir);
  for (i=0; i<n; i++) {
    struct dirent *e = dir[i];
    if (pattern==0 || fl_filename_match(e->d_name, pattern)) {
      load(Fl_Preferences::Name("%s%s", filepath, e->d_name));   // <---------- load failed at this line
    }
    free(e);
  }
  free(dir);
  return 0;
}
```
reproduce:
I have a plugin ```/Users/t/test/plugins/foo.dylib``` then I try to load
```c++
Fl_Plugin_Manager::loadAll("/Users/t/test/plugins", "*.{so|dylib|dll}");
```
It just failed.  And ```Fl_Preferences::load``` accept incorrect file path: ```/Users/t/test/pluginsfoo.dylib```.  A ```/``` missing in filename.

**Operating System / Platform:**
 - OS: macOS
 - OS Version: 14.2.1

**Comment by ManoloFLTK** [comment]
The commit mentioned above should fix the problem. @tanxn5 Please, close issue if you confirm.

**Comment by ManoloFLTK** [comment]
@tanxn5 I see now the previous fix for this issue is OK under Unix and macOS but is wrong under Windows, because their directory separator character is not the same. A second commit (f59702e) fixes the issue in a cross-platform way. But it adds the constraint that the caller of `Fl_Plugin_Manager::loadAll()` must include the directory separator character in the `filepath` argument. This constraint is now documented.
