### ISSUE TITLE
Fl_Text_Editor prevents scrolling parent Fl_Scroll

### ISSUE THREAD

**Issue by erco77** [fltk/fltk#879]
**Describe the bug**
When an Fl_Text_Editor ends up under the mouse, it takes mousewheel events
for itself, freezing navigation of a parent Fl_Scroll.

**Even if Fl_Text_Editor doesn't have focus, or if there's nowhere to scroll to, it takes
mousewheel events for itself.**

Having Fl_Text_Editor widgets within an Fl_Scroll is common technique for making
database entry screens that have more than one screenfull of input fields, allowing
the user to scroll through them, e.g.

![image](https://github.com/fltk/fltk/assets/6484779/63a020df-669f-415a-878b-bf006465bfa8)

In this situation the user can scroll through the fields by using the mousewheel to navigate
the parent Fl_Scroll, and the mouse can be  be anywhere in the window /except/ when the mouse
ends up over an Fl_Text_Editor widget, then the parent scroll "freezes".

**To Reproduce**
Attached [mouse-roll-issue.cxx.txt](https://github.com/fltk/fltk/files/13822195/mouse-roll-issue.cxx.txt) test program demonstrates an Fl_Scroll containing child Fl_Multiline_Input widgets (blue) along the left, and Fl_Text_Editor widgets (green) along the right, with every 5 widgets containing more text than can fit in the widget:

![image](https://github.com/fltk/fltk/assets/6484779/121882fd-4b0d-4ccd-888a-b0bb337b1a1f)

The mousewheel can be used to scroll the parent Fl_Scroll /except/ when the mouse ends up over the green Fl_Text_Editor widgets; then the Fl_Scroll can no longer be navigated with the wheel unless the mouse is moved out of the green area.

1. Let mouse hover over **blue** areas or vertical gray areas and roll the mousewheel.. parent Fl_Scroll scrolls up+down
2. Let mouse hover over **green** areas and roll the mousewheel.. Fl_Scroll can not be navigated. **<- PROBLEM**

**Expected behavior**

I might be wrong, but I'd think unless the widget has focus (a cursor inside, e.g. click-to-focus), it shouldn't respond to mousewheel. If however FLTK widgets follow hover-focus for e.g. mousewheel, then at very least:

- If Fl_Text_Editor has no scrollbar (e.g. no content to scroll to), mousewheel should be ignored, allowing parent widgets to receive the events
- If Fl_Text_Editor _does_ have a scrollbar, if focus doesn't control event delivery, perhaps when the scroller reaches the top or bottom, it starts ignoring wheel events so the parent can be navigated.

Tested on Ubuntu 20/Linux and Windows (e.g. win10pro).

**Comment by Albrecht-S** [comment]
> I might be wrong, but I'd think unless the widget has focus (a cursor inside, e.g. click-to-focus), it shouldn't respond to mousewheel. ...

AFAICT: mousewheel events are always sent to the widget under the mouse (`Fl::belowmouse()`) first. This is intentional and works usually well. If the widget under the mouse doesn't consume the event it is sent further up the widget tree. This is the reason why it eventually reaches the scrollbars at all and I don't think that this behavior could (or should) be changed.

> If however FLTK widgets follow hover-focus for e.g. mousewheel, then at very least:
> (two points, see above)

I believe that these two points would be fine from a user's point of view. Indeed, while editing this comment if Firefox I tested the behavior in the browser, and it does seem to what these two points suggest. These two points can be summarized: if a widget (e.g. Fl_Text_Editor) that **would** use FL_MOUSEWHEEL events for internal scrolling receives a mousewheel event and decides NOT to use it because there is nothing to scroll in the given direction, then it should return 0 from its handle() method (not consumed) rather than 1 (consumed the event).

I think that such a behavior would be intuitive.

Disclaimer: I didn't test anything nor looked I at the concerned code. It might be more difficult to implement than anticipated.

**Comment by erco77** [comment]
I did some fishing around in current behaviors of wheel events:

In test/valuators app:

    a) Fl_Roller scrolls only when the mouse is over the widget. It has no sense of focus (e.g. click to focus)
    b) Fl_Scrollbar scrolls when mouse is over the widget or parent group. (seems correct for this special case where scrollbars don't take focus)
    c) Valuators that take input and therefore react to focus, e.g. Fl_Counter, Fl_Value_Input, Fl_Value_Output all respond to left-click-drag to change values, but not wheelmouse (maybe should?).
        **Also, I'm guessing left-click-drag to change Fl_Value_Output is a bug, as I'd think it'd be read-only to user input.**
    d) Fl_Spinner also takes input and takes focus, but doesn't seem to react to left-click-drags or wheelmouse (maybe should?)
    e) Fl_Value_Sliders seem to have a focus concept, and react to either left-click-drags or arrow-key-nav, but not wheelmouse (maybe should?)
    f) Fl_Dial has no concept of focus apparently, or wheelmouse reaction.. left-click-drag only

In test/input:

    f) Fl_Multiline_Input doesn't react to wheel events (maybe should?), one can only scroll doing left-click-drags or keyboard arrow-key-nav

**Comment by erco77** [comment]
>>  If however FLTK widgets follow hover-focus for e.g. mousewheel, then at very least: (two points, see above)

> I believe that these two points would be fine from a user's point of view.

Right -- I think that's an easy add; in Fl_Text_Display::handle(), it currently reads:

    case FL_MOUSEWHEEL:
      if (Fl::event_dy()) return mVScrollBar->handle(event);
      else return mHScrollBar->handle(event);

I would think ignoring events when there's no scrollbar would be an easy add (not tested):

    case FL_MOUSEWHEEL:
      if (Fl::event_dy()) {
        if ( mVScrollBar->visible()) return mVScrollBar->handle(event);  // vscroll visible? handle wheel event
        else return 0;  // not visible? ignore wheel event
      } else {
        if (mHScrollBar->visible()) return mHScrollBar->handle(event); // hscroll visible()? handle wheel event
        else return 0; // not visible? ignore wheel event
      }

Similarly, in the cases where the scrollbar is visible, a check if the scrollbar is at an extreme position (vscroll:top or bottom, hscroll:left or right), wheel events could return 0.

I can assign to self and try this out to see if it works predictably.

**Comment by Albrecht-S** [comment]
Only a few comments for now:
> Fl_Dial has no concept of focus apparently, or wheelmouse reaction.. left-click-drag only

I'm pretty sure I used Fl_Dial for touch screen (FL_ROTATE_GESTURE) events when I tested those. I'm not sure though how exactly this was implemented ... (looking at the code) ... and I see now that I handled FL_MOUSEWHEEL and **_experimental_** `FL_SCROLL_GESTURE` events in the same way. It was trivial, and FL_MOUSEWHEEL handling could be added easily. However, since touch gestures will be added in 1.5 anyway we should now keep it as-is and wait until 1.4.0 has been released and we switch to 1.5 (short after the release!).

> I can assign to self and try this out to see if it works predictably.

I don't think that this has priority, we could delay it and implement a better event handling even in 1.4.1 or any other patch release. For now I would prefer to concentrate on important issues (real bug fixes).

However, if you have some spare time and would try to fix this issue (Fl_Text_Editor event handling) I wouldn't mind...

My main point is that we don't create new bugs or inconsistencies short before the release.

**Comment by MatthiasWM** [comment]
I think that @erco77 's changes are compliant with how browsers and other UI's behave. If you have the time and no bugs on the list, please add that. If you like, I will check that this works for multiline Fl_Input as well.

**Comment by erco77** [comment]
Attaching this patch suggestion: [issue_879.patch.txt](https://github.com/fltk/fltk/files/13930001/issue_879.patch.txt)

This basically handles wheel events only if the scrollbar is visible, and events would actually move the scrollbar (e.g. scrollbar is not at the extreme position the wheel is being turned in).

Tested on linux. Should probably be tested on mac and with a trackpad, but I think all that should be consistent.

**Comment by erco77** [comment]
I also made a version 2 of the [mouse-roll-issue-v2.cxx.txt](https://github.com/fltk/fltk/files/13930017/mouse-roll-issue-v2.cxx.txt) test program to include (a) a really long line to see how a combo of vert+horizontal scrollbars are handled in the text widget, and (b) made the window resizable, so the window can be shrunk to cause the parent group's horiz scrollbar to appear, so as to make sure its behavior works with the text editor's horiz scroller when doing SHIFT-MOUSEWHEEL.

**Comment by erco77** [comment]
It was definitely an error to force events to the scrollbar if it wasn't visible.

The Fl_Scrollbar widget doesn't seem to guard against this, and probably shouldn't have to because a non-visible widget wouldn't normally get events in the first place. But Fl_Text_Editor seems to need to direct events to the scrollbars itself.

Note that I had to add FL_MOUSEWHEEL to the exclusion at the top of the handle() method in the diff. The reason for this is to prevent _vertical_ scrolling from stopping when the mouse happens to appear over the _horizontal_ scrollbar, causing wheel events to skip the new logic I added, causing scrolling to "freeze" as described in the OP.

**Comment by Albrecht-S** [comment]
@erco77 I would like to review and test your patch but I won't have enough time today. I'll try to do it tomorrow.

**Comment by erco77** [comment]
@Albrecht-S That's fine.
I moved to focusing on issue 844 which is tricky.

**Comment by erco77** [comment]
(Please note the above "Addresses issue #879' was really for #844, and has nothing to do with this issue)

**Comment by erco77** [comment]
Wondering if I should apply, or continue holding for review/test..

**Comment by Albrecht-S** [comment]
@erco77 Looking into it now...

**Comment by Albrecht-S** [comment]
> Wondering if I should apply, ...

I tested the new behavior with the given demo program and I reviewed the code. Code looks good, the app behaves as I expect (as discussed above like other apps like browsers do).

+1 :+1: Good to go from me, thanks for the patch.

**Comment by erco77** [comment]
Fixed in f254450, closing.
