### ISSUE TITLE
Setting an svg image as a window icon causes a segfault

### ISSUE THREAD

**Issue by MoAlyousef** [fltk/fltk#90]
Hello
I noticed that setting a window icon using Fl_SVG_Image causes a segfault. However using direct classes like Fl_PNG_Image or Fl_JPEG_Image to set the window icon works fine.
Here's a minimal reproducible example:
```c++
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_SVG_Image.H>

int main() {
  auto win = new Fl_Window(100, 100, 400, 300);
  auto svg1 = new Fl_SVG_Image("image.svg", nullptr);
  win->icon(svg1);
  win->end();
  win->show();
  return Fl::run();
}
```

The gdb backtrace of the segfault shows:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000008077769 in icons_to_property (icons=0x84f5ab0, count=1, property=0x7ffffffed328, len=0x7ffffffed330) at ../fltk/src/Fl_x.cxx:2861
2861              *data = (in[3]<<24) | (in[0]<<16) | (in[1]<<8) | in[2];
(gdb) bt
#0  0x0000000008077769 in icons_to_property (icons=0x84f5ab0, count=1, property=0x7ffffffed328, len=0x7ffffffed330)
    at ../fltk/src/Fl_x.cxx:2861
#1  0x00000000080778c2 in Fl_X11_Window_Driver::set_icons (this=0x84f5770) at ../fltk/src/Fl_x.cxx:2889
#2  0x0000000008076c4a in Fl_X::make_xid (win=0x84f4e90, visual=0x8514df0, colormap=32) at ../fltk/src/Fl_x.cxx:2690
#3  0x000000000806c203 in Fl_X11_Window_Driver::makeWindow (this=0x84f5770) at ../fltk/src/drivers/X11/Fl_X11_Window_Driver.cxx:686
#4  0x00000000080783d2 in Fl_X11_Window_Driver::show (this=0x84f5770) at ../fltk/src/Fl_x.cxx:3084
#5  0x0000000008053851 in Fl_Window::show (this=0x84f4e90) at ../fltk/src/Fl_Window.cxx:543
#6  0x000000000803b80f in main () at ../main.cpp:12
```
The issue occurs on both Windows and Linux.

**Comment by Albrecht-S** [comment]
Thanks for the report. Confirmed (on Linux so far).

I spent a fair amount of time with the debugger to find out what's going on. It has to do with `Fl_SVG_Image` not being _rasterized_ until it is drawn. The consequence is that the internal `data()` array is not yet filled with actual data at the time it's used to create the internal image used as icon (whatever system specific data this needs). You can't even force the image to be rendered in user space before calling `window->icon()` (I tried this first) because it's copied internally which would render your `data()` array useless. IIRC.

That said, I'm confident that this issue can be resolved. Maybe @ManoloFLTK has a quick idea or I can take another look later. @ManoloFLTK: IIRC `icons_to_property()` is the key where the `data()` array is used but its value(s) is (are) NULL.

For now I can offer a workaround. You can use a small function to render the SVG image to an `Fl_Image_Surface` and retrieve the image as a "normal" `Fl_RGB_Image` like this:
```
void set_icon(Fl_Window *win, Fl_Image *image, int size) {
  Fl_Image_Surface surf(size, size, 1);
  Fl_Surface_Device::push_current(&surf);
  fl_color(FL_WHITE);
  fl_rectf(0, 0, size, size);
  Fl_Image *img = image->copy(size, size);
  img->draw(0, 0);
  Fl_Surface_Device::pop_current();
  win->icon(surf.image());
  delete img;
}
```
There may be better ways though. The drawback I'm seeing with this approach is that you lose transparency (I used a white background) if the SVG image has transparent parts.This is yet to be resolved.
Note that this copies the image to the icon size selected by me. You could also use `image->scale()` or use the image as-is, YMMV. It's just a proof of concept. The code was partially copied from one of the demo programs, probably test/sudoku.cxx IIRC.

**Comment by ManoloFLTK** [comment]
Yes. Class Fl_SVG_Image is a bit special in that image->array is NULL until it's first drawn
(which allows to rasterize the SVG data to the exact resolution needed when drawing, think
HiRes displays) or until member function resize() is called. That's documented:
    https://fltk.gitlab.io/fltk/classFl__SVG__Image.html#details

The correct fix is therefore to call resize() when the SVG image is used as an icon.
That's what the attached patch does, for each platform.

A choice between 2 options has to be done.
1) consider that when the condition applied to an Fl_RGB_Image *rgb
   !rgb->array && !rgb->fail()
is true, rgb must be an Fl_SVG_Image, so cast it (Fl_SVG_Image*)rgb

2) add a new virtual member function to class Fl_RGB_Image
  virtual Fl_SVG_Image *as_svg_image()
which returns non-null only for Fl_SVG_Image objects.

The patch uses option 1), but option 2) is cleaner.

[svg_icon.patch.txt](https://github.com/fltk/fltk/files/4780682/svg_icon.patch.txt)

***** small test program *******
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_SVG_Image.H>

int main() {
  const char *svg_data = "<svg viewBox=\"0 0 200 200\" version = \"1.1\">\n"
  "<rect x=\"25\" y=\"50\" width=\"150\" height=\"100\" fill=\"black\" "
  "transform=\"rotate(45 100 100)\"> </svg>\n";
  Fl_Window* win = new Fl_Window(100, 100, 400, 300, "FLTK");
  Fl_SVG_Image* svg1 = new Fl_SVG_Image( 0, svg_data);
  win->icon(svg1);
  win->end();
  win->show();
  return Fl::run();
}

**Comment by ManoloFLTK** [comment]
I see svg_icon.patch does not work when the fltk_images library is kept separated from 
the main FLTK library. I will see how to handle that.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Which platform doesn't work, and why if 

> the fltk_images library is kept separated from the main FLTK library (?)

If it's Windows and you're using the DLL's built with Visual Studio built with CMake then this likely is going to fail...

OTOH I just built shared libs under Linux with your patch and your demo works.

**Comment by MoAlyousef** [comment]
Thanks for looking into this. Really appreciate it.

**Comment by ManoloFLTK** [comment]
The problem was to call Fl_SVG_Image::resize(), which is in libfltk_images, from a function
of libfltk. It's solved in this second patch :
[svg_icon.patch.txt](https://github.com/fltk/fltk/files/4781276/svg_icon.patch.txt)

**Comment by Albrecht-S** [comment]
OK, I see. Thanks for the explanation.

However, I'm not happy with the second patch, particularly not with this part:
```
+Fl_SVG_Image *Fl_SVG_Image::as_svg_image() {
+  if (!array) resize(w(), h());
+  return this;
+}
```
The usual behavior of `Fl_SVG_Image::as_svg_image()` should be to return the correct pointer or `NULL`, but in this patch it has a **massive side effect** by calling `resize(w(), h());`. This is unexpected and should be avoided. In general I'd expect this kind of method to be `'const'`, i.e. not to modify the object at all.

Is this patch a preliminary version and are you thinking about a better one?

**Comment by ManoloFLTK** [comment]
I expected this writing of Fl_SVG_Image::as_svg_image() to be shocking.

I believe it makes sense in that an Fl_RGB_Image object whose array value is null is 
somewhat bizarre.
This virtual member function allows to make sure an Fl_RGB_Image object is a standard
Fl_RGB_Image object, that is, with non-null array value, without knowing if the image
is an Fl_SVG_Image or a classical Fl_RGB_Image.

The "if (!array)" test ensures the rasterization operation is performed only once.
The virtual mechanism ensures the function costs nothing for non-SVG images.

An alternative could be to create another virtual member function
   virtual void Fl_RGB_Image::standardize() {}
re-implemented as
   virtual void Fl_SVG_Image::standardize() {
        if (!array) resize(w(), h());
   }

My idea was that this function could also be the usual as_svg_image() function
that's handy sometimes, since dynamic_cast is not authorized.
But I'm ready to opt for the alternative solution, if it's considered better.

**Comment by Albrecht-S** [comment]
I believe having both methods would be fine. One that does something (`standardize()` or a more specific name) and one that returns the type info. `as_svg_image()` should really only do what it is expected to do (return a pointer, be '`const`' otherwise), as all the other `as_something()` methods are doing.

Side note: I was recently thinking about adding the '`const`' qualifier to some or all of these `as_something()` methods anyway, but we need to decide this separately. Maybe also having both 'const' and 'non-const' versions (for other reasons, anyway) would be useful.

We should discuss this in fltk.coredev though, it's OT for this issue.

But thanks for your quick reply and patch proposal!

**Comment by ManoloFLTK** [comment]
The issue should now be fixed in the git repository.
@Albrecht-S : I have added both methods, as_svg_image() and normalize().
@MoAlyousef : please close if you confirm the fix.

**Comment by MoAlyousef** [comment]
Thank you. I have tried it with Fl_SVG_Image and it works. Trying it with Fl_Shared_Image for an svg image can still segfault however.

**Comment by ManoloFLTK** [comment]
The API does not support use of an Fl_Shared_Image object to set a window icon
because Fl_Window::icon(), Fl_Window::icons(), Fl_Window::default_icon(), and 
Fl_Window::default_icons() all expect Fl_RGB_Image arguments.

That other API
void Fl_Window::icon(const void *ic )
unfortunately accepts an Fl_Shared_Image object, but it's intended to accept
undocumented platform-dependent data, which is not of type Fl_Shared_Image*.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Thanks, commit looks good, but I'm not able to test it now. Will test later and report (only) if anything doesn't work.
