### ISSUE TITLE
FLTK 1.4 Mac Bug: Window scaling doesn't work correctly for subwindows

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#927]
**Describe the bug**
Note: This was already discussed in #917 but I figured I would submit an issue so that it does not get lost.

Applications that use subwindows do not behave correctly after the window has been scaled up or down, only on Mac.

This still behaves correctly on Linux/X11.

On Windows, it worked correctly during #917, but now the scaling shortcuts do not do anything on test/tiled.exe so I'm unable to verify if it still works correctly on Windows.

**To Reproduce**
1. Run test/tile (or test/tiled.exe on Windows)
2. See that resizing the tiles works as intended
3. Scale the window up or down (see that this step doesn't work on Windows)
4. See that resizing the tiles no longer works as expected on Mac

**Expected behavior**
The subwindow tile should continue to work correctly after the window has been scaled.

**Video**

https://github.com/fltk/fltk/assets/5231310/7a3b9fb5-a198-4165-8a73-c62871b83326

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: a0ff3f6

**FLTK Configure / Build Options**
 - `make`

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: macOS
 - OS Version: macOS 11.4
 - Processor if relevant: Intel

**Comment by ManoloFLTK** [comment]
After a first analysis, it seems the issue occurs when all these conditions are met together: macOS, scale factor below 100%, the window contains an Fl_Tile which contains an Fl_Window as child and the Fl_Tile's resizable part does not contain the child subwindow.

**Comment by Albrecht-S** [comment]
I also noticed this and I came to a similar conclusion. The effect can be seen easily and reliably when scaling once with `ctrl/-` to 90%. My suspicion is that the subwindow tile "loses contact" to the other tiles due to rounding errors when the subwindow is resized but I couldn't test this. HTH.

**Comment by MatthiasWM** [comment]
Yes, Fl_Tile in "size range" mode on macOS does not work with child windows in scales under 100%. This is exactly what Albrecht describes and is the result of losing precision when scaling down. I know this, and I am happy to fix this soon. When it was discovered, I just finished days of intense coding for the "size range" feature, and - as we Germans say - could not see the forest anymore because there were so many trees. With a little bit more distance to teh code, I will try again to fix this, and maybe even implement the rang maximum options.

**Comment by dannye** [comment]
Probably not too important, but I think the rounding errors are a little more unpredictable than that. I do still see (less severe) issues at 110% as well.

**Comment by ManoloFLTK** [comment]
@MatthiasWM The problem occurs also in the x direction : run test/tile, type cmd+'-', enlarge the window horizontally with the mouse somewhat swiftly.

**Comment by ManoloFLTK** [comment]
@MatthiasWM I would suggest the attached patch to fix this issue.
[issue927.patch](https://github.com/fltk/fltk/files/15051644/issue927.patch)

**Comment by MatthiasWM** [comment]
Thanks very much. I did not look at it in-depth yet, but it's promising. I'll try to make time tomorrow.

**Comment by MatthiasWM** [comment]
Ok, I hope that this commit fixes the issues. I could not get the Tile to disconnect at various scales and with extensive and vigorous dragging around of tile separators.

Converting Cocoa coordinates into FLTK coordinates should be avoided as much as possible because the conversion loses precision for scaling != 100%. I changed the code to stay within the FLTK system, at least for scaling for now. There may be more places that may benefit, but I don;t think that any of them cause serious bugs.
