### ISSUE TITLE
memory leak in Fl_X11_Screen_Driver.cxx

### ISSUE THREAD

**Issue by tanxn5** [fltk/fltk#934]
I think there is a memory leak at 
Fl_X11_Screen_Driver.cxx:1122 and Fl_X11_Screen_Driver.cxx:1127. After XCreateFontSet(), missing_list may lost without a XFreeStringList() call.

```
#if USE_XFT

#if defined(__GNUC__)
    // FIXME: warning XFT support here
#endif /*__GNUC__*/

    fnt = NULL; // fl_get_font_xfld(font, size);
    if (!fnt) {fnt = (char*)"-misc-fixed-*";must_free_fnt=false;}
    fs = XCreateFontSet(fl_display, fnt, &missing_list,
                        &missing_count, &def_string);
#else
    fnt = fl_get_font_xfld(font, size);
    if (!fnt) {fnt = (char*)"-misc-fixed-*";must_free_fnt=false;}
    fs = XCreateFontSet(fl_display, fnt, &missing_list,
                        &missing_count, &def_string);
#endif
 ```

**Comment by Albrecht-S** [comment]
Thanks for the report. I confirm it's a leak and I'm working on it.

**Comment by Albrecht-S** [comment]
Fixed in commit 29aba21b7885d436dba3db87c33d08378b57d23c.

**Comment by erco77** [comment]
Just a side comment;  this:
```
void Fl_X11_Screen_Driver::grab(Fl_Window* win)
{
  const char *p;
  static bool using_kde =
    ( p = getenv("XDG_CURRENT_DESKTOP") , (p && (strcmp(p, "KDE") == 0)) );
```
..I really had to squint to parse that; it's rare in C/C++ to use commas this way.
Might be a bit clearer to read if rewritten this way..?

```
void Fl_X11_Screen_Driver::grab(Fl_Window* win)
{
  const char *p = getenv("XDG_CURRENT_DESKTOP");
  static bool using_kde = (p && (strcmp(p, "KDE") == 0);
```

**Comment by Albrecht-S** [comment]
@erco77 Yes, I can confirm that it's hard to understand.

Please open a different issue before this starts a longer discussion here. This issue is closed and your comment is really OT here but obviously worth a discussion - please don't understand me wrong.

Regarding your suggestion: IIRC this would exececute getenv(..) every time this function is called which is bad but I don't know if this was @ManoloFLTK's reasoning (probably yes). Adding 'static' might help, but please see above...
