### ISSUE TITLE
Build test programs only on request

### ISSUE THREAD

**Issue by michaelbaeuerle** [fltk/fltk#940]
For packaging the FLTK library, it may be unwanted that the test programs are build automatically.
Building the tests only consumes ressources, if they are neither executed nor installed.

automake would use a separate rule "check" for this purpose:
https://www.gnu.org/software/automake/manual/automake.html#Standard-Targets

For pkgsrc I use this patch:
https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=blob;f=fltk14-devel/patches/patch-Makefile
and a notice, that the tests are not executed automatically:
https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=blob;f=fltk14-devel/patches/patch-test_Makefile

I propose the first patch for upstream merge.

**Comment by Albrecht-S** [comment]
@michaelbaeuerle Thanks for this request, I see your point.

Side note, for reference: We implemented a CMake option to disable building the test programs and we disabled building the tests automatically if FLTK is built as a subproject with CMake. Otherwise users can use the CMake option to disable building the tests themselves.

The patch you propose would not build the test programs by default and require the user (or FLTK developer) to run `make check` after `make` if they wanted to build the tests. To be consistent with other build options like `--enable-shared` or `--disable-wayland` I would suggest to add a configure option that disables building the test programs (opt-out) and let the default as-is because this is how FLTK was built all the time. As you, Michael, know, this option would apply only to 1.4.x because configure support will be dropped in 1.5.0 anyway.

That said, according to your link to automake, `make check` is not exactly what building the test and demo programs would do. "Run the test suite, if any" is not what our test and demo programs do. I read this as running an automated test suite that FLTK doesn't have (yet).

I would accept a configure option like `--disable-build-test` or `--disable-test[s]` but I'm not sure about a good name. Any suggestions?

**Comment by michaelbaeuerle** [comment]
> [...]
> I would accept a configure option like `--disable-build-test`
> or `--disable-test[s]` but I'm not sure about a good name.
> Any suggestions?

Because the subdirectory in the source tree is named "test", I would prefer "--disable-test".

Proposed patches:
[patch-configure.ac.txt](https://github.com/fltk/fltk/files/14667782/patch-configure.ac.txt)
[patch-makeinclude.in.txt](https://github.com/fltk/fltk/files/14667783/patch-makeinclude.in.txt)
[patch-Makefile.txt](https://github.com/fltk/fltk/files/14667784/patch-Makefile.txt)

**Comment by Albrecht-S** [comment]
Done in commit 2001132f4a1ab2ad02f31c4a7c4cf9a5d803ed54.

@michaelbaeuerle Thanks for the updated patch(es).
