### ISSUE TITLE
Fluid Replicable Crash When Using External Editor Vim in Konsole

### ISSUE THREAD

**Issue by Guitarmadillo** [fltk/fltk#945]
**Describe the bug**

I am on FLTK version 1.4 from March 8th 2024. 

1. In Fluid select Edit > Settings > External Editor > set it to "konsole -e vim"
2. Enable "Use for Code Nodes".
3. Create a code node inside of a class or an existing function. Open that code node in the external editor. 
4. Delete the default code printf("Hello World"); line and leave the code node completely empty. 
5. Close the code node then try to re access the empty code node. 

It should crash Fluid. It does not crash on an empty code node unless the external editor is enabled, and I did not try any other external editors. 

**Operating System / Platform:**

Debian 12 Bookworm latest stable kernel 6.1.0-18 (if I have the syntax correct) 

**Linux/Unix Runtime, if applicable:**

 X11

**Additional context**

Feature Request: One thing I was wondering is when editing these code nodes if it is possible to display the function or class name where the code node is inside of, that would be helpful when jumping between code nodes during sessions. I have only been using fluid for a few months and enjoy it very much, keep up the great work.

**Comment by Albrecht-S** [comment]
Looks like this is the culprit:
```
#2  0x0000555555624e03 in ExternalCodeEditor::open_editor (this=0x555555837af8, editor_cmd=0x5555557fc200 <G_external_editor_command> "konsole -e nano", 
    code=0x0) at /git/fltk/master/fluid/ExternalCodeEditor_UNIX.cxx:500
```

`code=0x0` seems to be the issue. Possible patch:
```diff
diff --git a/fluid/Fl_Function_Type.cxx b/fluid/Fl_Function_Type.cxx
index f7a7f30d8..6dc9fc927 100644
--- a/fluid/Fl_Function_Type.cxx
+++ b/fluid/Fl_Function_Type.cxx
@@ -611,6 +611,7 @@ void Fl_Code_Type::open() {
   if ( G_use_external_editor && G_external_editor_command[0] ) {
     const char *cmd = G_external_editor_command;
     const char *code = name();
+    if (!code) code = "";
     if ( editor_.open_editor(cmd, code) == 0 )
       return;   // return if editor opened ok, fall thru to built-in if not
   }
```

@Guitarmadillo You might want to test this patch but I'm leaving the final fix to @MatthiasWM.

**Comment by MatthiasWM** [comment]
Yes, that's pretty much it. Thanks for looking at this. Fixed in f779097c967f0224eac5bdd89df2a363c614fa91

**Comment by erco77** [comment]
Hmm, I was curious about this; this might be my fault: I think the real problem is the save_file() function (used by open_editor()) documents that 'code' can be NULL, but only ExternalCodeEditor_WIN32.cxx actually has code that supports this via:
```
static int save_file(const char *filename, 
                     const char *code,
                     FILETIME &file_mtime,        // return these since in win32 it's..
                     LARGE_INTEGER &file_size) {  // ..efficient to get while file open
  if ( code == 0 ) code = "";   // NULL? write an empty file    <<<<<<<<
[..]
```
The ExternalCodeEditor_UNIX.cxx does not have that line. If it did, the OP's crash probably wouldn't have happened.

I think the correct solution might be to reverse the change made, and apply the above fix line to the UNIX code.
If need be, I can do this.

**Comment by Albrecht-S** [comment]
@erco77 Formally the call in question is `ExternalCodeEditor::open_editor()`, and unless this one is also documented to allow `NULL` as the `code` parameter this should be fixed in one or the other way as well. I'm not going to check this because you are more familiar with the code and docs.

Reversing the previous fix is IMHO optional - but only if `open_editor()` explicitly allows NULL (see above). I wouldn't mind leaving it in place though but I'm open for removing it as well (it would save one `if` and one assignment - is it worth it?).

Thanks for checking this, BTW.

**Comment by MatthiasWM** [comment]
Or we make everything Fl_String now... .

**Comment by erco77** [comment]
OK, I'll leave the fix you guys have, and just also fix the comments for open_editor() to document code can be NULL, and implement the actual check in the UNIX file where it's needed. This way the docs and code are consistent.
