### ISSUE TITLE
Building OpenGL Examples on Windows with MSVC does not work

### ISSUE THREAD

**Issue by ggarra13** [fltk/fltk#959]
**Describe the bug**
Building OpenGL Examples with MSVC does not work.

**To Reproduce**

1. Have glew2.2.0 win64 downloaded from:

https://sourceforge.net/projects/glew/files/glew/2.2.0/glew-2.2.0-win32.zip/download

2. I unzipped it and the location of the x64 builds is in:

D:/code/lib/glew-2.2.0/bin/Release/x64
D:/code/lib/glew-2.2.0/lib/Release/x64

3. I moved the .lib and .dlls to the main directories (from the standard MSVC dirs):

```
cd D:/code/lib/glew-2.2.0/bin/Release/x64
mv *.dll ../..

cd D:/code/lib/glew-2.2.0/lib/Release/x64
mv *.lib ../..
```

4. I had to call cmake with all this (this needs work in the CMakeLists files):

`cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=D:/code/lib/glew-2.2.0 -DFLTK_BUILD_EXAMPLES=ON -DCMAKE_CXX_FLAGS=-ID:/code/lib/glew-2.2.0/include`

CMake does find glew32.
CMake compiles properly.

5. Error:
CMake does not link properly with the glew32.lib (DLL), getting errors like (maybe I am missing a preprocessor definition of the OpenGL3test is missing #include "windows.h"?

LINK: command "C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\link.exe /nologo examples\CMakeFiles\OpenGL3test.dir\OpenGL3test.cxx.obj /out:bin\examples\OpenGL3test.exe /implib:bin\examples\OpenGL3test.lib /pdb:bin\examples\OpenGL3test.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:windows -LIBPATH:D:\code\applications\mrv2\BUILD-Msys-amd64\Release\FLTK-prefix\src\FLTK\build\src\..\lib lib\fltk_gl.lib D:\code\lib\glew-2.2.0\lib\glew32.lib opengl32.lib glu32.lib lib\fltk.lib comctl32.lib ws2_32.lib gdiplus.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\examples\OpenGL3test.exe.manifest" failed (exit code 1120) with the following output:
OpenGL3test.cxx.obj : error LNK2019: símbolo externo __glewBindBuffer sin resolver al que se hace referencia en la función "public: virtual void __cdecl SimpleGL3Window::draw(void)" (?draw@SimpleGL3Window@@UEAAXXZ) 

**Workaround**

Linking against the static glew32 (ie. glew32s) works.

diff --git a/CMake/resources.cmake b/CMake/resources.cmake
index e5d6f8c9f..e755f89db 100644
--- a/CMake/resources.cmake
+++ b/CMake/resources.cmake
@@ -152,7 +152,7 @@ endif((NOT APPLE) OR FLTK_BACKEND_X11)
 find_library(LIB_freetype freetype)
 find_library(LIB_GL GL)
 find_library(LIB_MesaGL MesaGL)
-find_library(LIB_GLEW NAMES GLEW glew32)
+find_library(LIB_GLEW NAMES GLEW glew32s glew32)
 find_library(LIB_jpeg jpeg)
 find_library(LIB_png png)
 find_library(LIB_zlib z)

However this prefers static builds instead of shared builds which is contrary to the normal behavior.

find_package(GLEW)

seems to solve the issue (at least on Windows) by having different target variables for static or shared builds.

**Expected behavior**
FLTK should allow a variable to get passed to find the GLEW library.
It should use find_package(GLEW) to find glew as it is more solid.
It should work with either static or shared (DLL) builds.
It should print out the location where GLEW was found.

**FLTK Version**
 - Version: 1.4 
 - Downloaded and self-built from: Git
 - If from Git, branch: master

**FLTK Configure / Build Options**
See steps to reproduce.

**Operating System / Platform:**
 - OS: Windows
 - OS Version: 11

**Comment by Albrecht-S** [comment]
Commit bc63ea7629c8c3c4248a777d1c0325ae800556e0 fixes this issue. The GLEW library is now found and can be used on Windows with Visual Studio, MinGW (32-bit) and MSYS2 (64-bit). 

I tested it with the GLEW library downloaded from the link given above, using MinGW, Visual Studio 2019, and MSYS2. I could build and run the OpenGL3 demo programs, but none of them supports "OpenGL3" on my Windows 10 VM, although they can be executed and issue warnings like this (example):
```
Using GLEW 2.2.0
GL_VERSION=1.1.0

This platform does not support OpenGL V3 :
FLTK widgets will appear but the programmed rendering pipeline will not run.
```

Specific documentation on how to handle these libs is still to be done. Anyway:

I used the "full" download sucessfully **_w/o having to move any files_** within the glew-2.2 tree:
```
C:/git/glew-2.2.0-full/
├── LICENSE.txt
├── Makefile.txt
├── bin
│   └── Release
│       ├── Win32
│       │   ├── glew32.dll
│       │   ├── glewinfo.exe
│       │   ├── glewinfo.txt
│       │   └── visualinfo.exe
│       └── x64
│           ├── glew32.dll
│           ├── glewinfo.exe
│           └── visualinfo.exe
├── doc
│   ├── advanced.html
│   ├── ...
│   └── wglew.html
├── include
│   └── GL
│       ├── eglew.h
│       ├── glew.h
│       ├── glxew.h
│       └── wglew.h
└── lib
    └── Release
        ├── Win32
        │   ├── glew32.lib
        │   ├── glew32s.a                # <<< see note [1] below
        │   └── glew32s.lib
        └── x64
            ├── glew32.lib
            ├── glew32s.a                # <<< see note [1] below
            └── glew32s.lib
```
The CMake configure process finds the correct libs and builds (IMHO) correctly, no matter whether it's a 32-bit or 64-bit build.

To use this structure you need to point CMake at the root of this tree, either using `CMAKE_PREFIX_PATH` or the FLTK specific variable `FLTK_GLEW_DIR`. The latter is used internally to set up `CMAKE_PREFIX_PATH` for the search.

You don't need to set the include paths, this will be handled by CMake.

The CMake configure process prefers the static GLEW lib (glew32s) but can also handle the DLL. This is done by recognizing which one was found and setting the preprocessor macro `GLEW_STATIC` accordingly. The linker errors with the DLL reported by you were caused by setting `GLEW_STATIC` unconditionally in the source code. Thus linking with the shared library had to fail. This is fixed now as well.

If you **wanted** to link the shared GLEW DLL, then you could remove the static lib (glew32s) and it should still work, although you'd have to deploy the DLL together with your executable.

This is all I can do. I have no idea why my Windows 10 VM doesn't support OpenGL3 but that's OT and will not be dealt with here, in the context of this issue.

@ggarra13 Please confirm that the issue is fixed and close it. Thanks.

------
[1] `glew32s.a` is a **copy** of `glew32s.lib` which is needed when using CMake 3.28 or higher for **`MinGW`** builds (not MSVC) because `FindGLEW.cmake` was changed to find only static libs with the `'.a'` suffix when building for `MinGW`. I don't know if this will be kept or if it's a bug that will be fixed, but that's what I found out so far. It's still true in 3.29 as of today.

**Comment by ggarra13** [comment]
It worked for me, but it built a console application with MSVC 2022.  You probably need to change:

add_executable( OpenGL3test LIBRARIES ....)

to

add_executable( OpenGL3test  WIN32 LIBRARIES ... )

I think the WIN32 setting is just for MSVC, but you may know better about MingGW.

**Comment by ggarra13** [comment]
Ah... yes.  It was probably a debug build.  Closing the issue.
