### ISSUE TITLE
Adding /Xcode to .gitignore in FLTK

### ISSUE THREAD

**Issue by robbwheel** [fltk/fltk#980]
For users can be useful to generate FLTK also using Xcode inside a. /Xcode folder and not only in /build (already in .gitignore) , and not seeing it reported in diff at any fetch origin

FLTK version  1.4.0

Solution:
adding '/Xcode' in .gitignore for FLTK

an added bonus would be also adding '/Eclipse' and '/VisualStudio'

**Comment by ManoloFLTK** [comment]
Doesn't it make sense to place the Xcode folder inside the build folder?

**Comment by Albrecht-S** [comment]
Hi @robbwheel , thank you for your suggestion. However, I agree with Manolo.

Personally I have a build folder with several subdirectories for different builds like debug, release, mingw (cross-compiler 32-bit and 64-bit), `cmake-min` (build with minimal CMake version 3.15), and so on. On my Linux system I have currently 10 different build subdirectories. On macOS I have typically `debug`, `release`, `x11` (XQuartz), and `Xcode` subfolders (maybe more).

**_Conclusion:_** Although it's useful to have more than one build folder, adding one or more to `.gitignore` in pur repo is not useful because there would always be another one requested by users. Even the "build" folder itself is a compromise.

**_Solution:_** Git offers another way to add `excludes` to your local repo (checkout), see my own example below:
```
$ cat .git/info/exclude 
# git ls-files --others --exclude-from=.git/info/exclude
# Lines that start with '#' are comments.
# For a project mostly in C, the following would be a good set of
# exclude patterns (uncomment them if you want to use them):
# *.[oa]
# *~

cmake-examples/
private/
todo/
```

Note: The comments are "original" from git (init or clone), the other three lines are my own items. Feel free to use this git feature to hide local build folders.

This issue will be closed with label `wontfix`.
